### ISSUE TITLE
Link verification instructions on the website

### ISSUE THREAD

**Issue by xaur** [decred/dcrdex#1003]
dex.decred.org [downloads](https://dex.decred.org/#downloads) section links to three direct `dcrinstall` downloads and in the `How to Get Started` below it says

> Download, optionally verify, and run the installer, dcrinstall --dcrdex.

So it links to dcrinstall binaries and mentions their verification, but does not link to manifests/signatures or the steps to take.

I suggest to do both: add "manifest" and "signature" links below per-platform download links, and link to [Verifying Binaries](https://docs.decred.org/advanced/verifying-binaries/).

This adds friction for our "funnel" but we cannot cut corners here and need to promote this stuff because people trust their money to this software.

It could look like this (please pardon my HTML hacking):

![dcrdex-download-verify](https://user-images.githubusercontent.com/24484727/110187289-c0d92e80-7e0f-11eb-8769-9758e0fc63b5.png)

I guess [dexweb](https://github.com/decred/dexweb) is the proper repository but I think it is relevant for the dev team too, so posting in this tracker instead.

**Comment by chappjc** [comment]
Missed this, but should transfer to the [dexweb](https://github.com/decred/dexweb/) repo. @dajohi or @jholdstock able to transfer or just close this if it's resolved?

**Comment by jholdstock** [comment]
I dont have permissions to transfer this issue, but I think decred/dexweb#14 will close it when it is merged anyway.
