### ISSUE TITLE
client should store and check csum in preimage request

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1020]
Server should not be asking for preimages until the epoch is closed.  So client should be remembering the `CommitChecksum` field of `PreimageRequest` and verify that the order doesn't end up in an epoch's match proof with a different `csum`, which would indicate server is cheating (e.g. we handed over our preimage so the server could game the shuffle).

_Originally posted by @chappjc in https://github.com/decred/dcrdex/pull/1009#discussion_r597358893_

**Comment by buck54321** [comment]
Relevant spec section is https://github.com/decred/dcrdex/blob/master/spec/orders.mediawiki#Preimage_Reveal, as well as the `preimage` and `match_proof` requests.

1. Store the checksum in `handlePreimageRequest`, probably as a field in the `trackedTrade`.
2. After `ValidateMatchProof` in `handleMatchProofMsg`, check the stored checksum from part 1 against the `note.CSum`. If mismatch, then ...

Under normal circumstances, it would be almost impossible for a client to store the checksum, shut down, restart, and log in before the match_proof comes, so I don't see a compelling case for storing the checksum to the database and the upgrade it would involve.

**Comment by chappjc** [comment]
@LasTshaMAN is assigned.
