### ISSUE TITLE
client internationalization

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1022]
The browser pages and at least some of the text sent in notifications needs to have translations.

There are a few options for the html internationalization (i18n):

1. i18n templates of the gohtml templates like markets.tmpl.i18n and corresponding key-value files for each language that are combined via some substitution/evaluate command to generate the markets.tmpl for a specified locale.  The generation could also produce many files like markets_en-us.tmpl or instead subdirs like views/en-us, which would facilitate runtime selection.
2. Do all the i18n string substitution by the Go html template execution. With golang/x/text and a function in the template's `Funcs` map called say `"translate"`, this would not necessarily change the current variables passed to template execution.  In short, define dictionary files that translate keys to content in certain languages, load them into a type implementing `catalog.Dictionary` and set that to `message.DefaultCatalog`, define a template function called say `"translate"` and set it to `message.NewPrinter(lang).Sprintf`, where `lang` is a `language.Tag` determined from cookies and/or Accept-Language.  Template execution handles both the existing variables and internationalization via `{{ translate "some_text_key" }}`.
3. go-i18n, which is a package around the golang/x/text repos.  Perhaps easier, perhaps not, but a dep to avoid unless it's really good.
4. An npm/webpack import to convert certain html elements at build-time.  See https://github.com/decred/decrediton/tree/master/app/i18n

Option 2 is fairly straightforward, but it gets the Go bits very involved, much more so than simply switching between different generated template files.  Having the Go webserver aware and setup with translation machinery could also be helpful for internationalization of notification text.

**Comment by buck54321** [comment]
I tend to agree that 1 is best. Thanks for the footwork here, @chappjc.

I'm still looking at notifications.

**Comment by chappjc** [comment]
Shall I assign you?

**Comment by dcrlove2021** [comment]
Come on, man, you're great! 加油，伙计，你很棒
Greetings from Chinese Lovers!

**Comment by chappjc** [comment]
Alright, @dcrlove2021, we're on it.  Pls refrain from cheer-leading.  Thanks for your interest though!

**Comment by dcrlove2021** [comment]
ok

**Comment by xaur** [comment]
FYI Decrediton's experience has shown that i18n needs not only a technical framework but also due processes and _human_ coordination.

Strings change all the time and translated strings quickly get outdated. To make releases without outdated translations, we need

1) A person taking the role to deliver an updated translation and adhering to the chosen release schedule, one for each supported language. Ideally, there is a fallback person for each language too, to avoid any disruptions.
2) A window somewhere in the release cycle where translators have time to update their strings. e.g. 3 weeks before the release English strings are frozen, then 1-1.5 weeks for translations to catch up, and then ~1 "just in case" week for late fixes.
