### ISSUE TITLE
client/db/bolt: create archived orders bucket

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1039]
With large client databases, we have been seeing long startup times while it iterates through the orders bucket to find active orders.  Profiles indicate that the worst hotspots in these slow operations are all descending from a `bbolt.(*Bucket).ForEach` with most of the execution time on either `bbolt.(*Bucket).Bucket` (just looking up a sub-bucket), or `bbolt.(*Bucket).Get` (retrieving an entry from a bucket), both ultimately heating up `bbolt.(*Cursor).search`.  The `Get` is a much smaller and less frequent hot spot than `Bucket` though, so this indicates looking up a given order's *sub-bucket* is the low hanging fruit for improvement here.

Occasionally, a given machine will take extra long with a separate hot path on `bbolt.(*Cursor).Next` ... `bbolt.(*elemRef).isLeaf`.  It's not clear why this path only gets hot occasionally.

I believe we should move known completed orders into an archived orders bucket so there's no need to iterate over them on startup for eternity.  The order export function can read this bucket if needed.

**Comment by JoeGruffins** [comment]
I would like to take this on unless @buck54321 would rather do it?
