### ISSUE TITLE
client/core: Register should verify there is no account bucket for the DEX

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1049]
Although the register dialog bug that showed up when the connection to the dex was down on client startup was resolved in https://github.com/decred/dcrdex/pull/989 and the `Core.conns` map should now include all configure DEXs even if they are not reachable, we should add some additional sanity checks to `(*Core).Register`.  Namely, before attempting a `wallet.PayFee`, the client DB should be consulted for presence of an account for the given DEX.

**Comment by ukane-philemon** [comment]
@chappjc was this addressed in #1015 ?
