### ISSUE TITLE
display price in browser window title

### ISSUE THREAD

**Issue by sumiflow** [decred/dcrdex#1053]
Just a nice to have feature request.  It would be cool to show the price of whatever pair is selected in the browser title like Bittrex and some others do, instead of the current title.  This way I can see it without clicking the tab.
![image](https://user-images.githubusercontent.com/5420838/115075345-8cea3200-9ec0-11eb-8c90-e92e887ec834.png)

**Comment by amassarwi** [comment]
will do

**Comment by vctt94** [comment]
Working in it
