### ISSUE TITLE
Connect Wallets and Register

### ISSUE THREAD

**Issue by pilikan33** [decred/dcrdex#1059]
The instructions say to run  ./dex - WHERE IT IS LOCATED ??????

Connect Wallets and Register
Start the client. ./dexc
In your browser, navigate to localhost:5758

**Comment by JoeGruffins** [comment]
cd client/cmd/dexc
go build/install

**Comment by pilikan33** [comment]
go build
# decred.org/dcrdex/client/core
../../core/core.go:91:11: dt.Ticker.Reset undefined (type *time.Ticker has no field or method Reset)
note: module requires Go 1.15

**Comment by pilikan33** [comment]
i was install golang 1.15

**Comment by JoeGruffins** [comment]
Perhaps we can assist you better in live support? Hope thia link works:

https://matrix.to/#/!xUNvyzkFgiMjhvPbIi:decred.org?via=decred.org&via=matrix.org&via=planetdecred.org

**Comment by chappjc** [comment]
@pilikan33 Unless you are a developer, I suggest not to build from source, and instead use a released binary from https://github.com/decred/decred-binaries/releases/tag/v1.6.2 or from dcrinstall at https://github.com/decred/decred-release/releases/tag/v1.6.2.
If you want to build from source anyway, not that you should be building from the `release-0.1` branch if you want to use it in production.  But very soon 0.2 will be released and you will build from `release-v0.2`.
