### ISSUE TITLE
mouse wheel scrolls page AND zooms depth chart

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1063]
Just updated to Firefox 89 and on the depth chart the mousewheel doesn't just zoom, it now scrolls the whole window AND zooms.  This seems like a Firefox bug, but I'm not sure.

EDIT: It's just the long orders tables, which I think need to be limited in height and with their own scrolls.  Open to other solutions though.

**Comment by chappjc** [comment]
Ok, this is not just a FF issue.  Apparently I've only ever noticed it when one of the buy/sell orders tables is long enough to go down off the screen.  Perhaps the resolution should be to limit the height of these tables to the screen, with each table having their own scroll?

**Comment by chappjc** [comment]
Vid:

https://user-images.githubusercontent.com/9373513/116166520-d0644d80-a6c3-11eb-9ed6-77e859af3c85.mp4

**Comment by amassarwi** [comment]
will look into it
