### ISSUE TITLE
eth: uint64 too small to store balances

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1076]
Client assets use this to handle balances:
https://github.com/decred/dcrdex/blob/91d5a376592317ca60b76f488a194dca34c7ca2a/client/asset/interface.go#L185-L195

The max value for a uint64 (2^64) is ~1.8e19

The smallest unit of measure for eth is the [wei](https://ethdocs.org/en/latest/ether.html#denominations) and it takes 1e18 wei to make one eth. This means that using a uint64, the most a wallet can track is 18 eth.

We could do something complicated like bit shifting and using two uint64 which should give values up to 3.4e38 which I am guessing is safe.
We could have all balances as `*big.Int`.
We could round all eth values and store as 1e10 units?

Amounts are also stored in the db. I'm guessing we will need to make encoding asset specific. Maybe Balance itself can be made an interface and current coins can continue using `uint64` while eth uses `*big.Int`.

**Comment by chappjc** [comment]
Would we be getting into trouble using gwei?

**Comment by buck54321** [comment]
Using `*big.Int` is somewhat attractive, but it also seems like a pain to code. I've been leaning towards using *gwei**. We don't need to specify the unit or conversion factor used at the API level, it's just unique to an (asset ID, asset version).

For UI purposes, available conversion factors and unit labels could be provided by the backend, in the `WalletInfo` for the client and maybe a driver method for the server.

**Comment by JoeGruffins** [comment]
For now let's try out gwei (1e9 wei) and see if that causes any problems.
