### ISSUE TITLE
ui: settling booked order only says booked

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1084]
Partially filled booked orders that are settling used to say something like "booked/settling", but it now just says booked.  Observed the following on testnet:

![image](https://user-images.githubusercontent.com/9373513/117831787-89856480-b23a-11eb-9523-8c023529e641.png)

The last order 50% filled is the one matched with the first order in the list and still settling:

![image](https://user-images.githubusercontent.com/9373513/117831922-a9b52380-b23a-11eb-9a85-8bd0197c566d.png)

**Comment by chappjc** [comment]
Perhaps I am mistaken that it used to say booked/settling.  Maybe it was executed/settling only?

**Comment by JoeGruffins** [comment]
I think I remember booked/settling.
