### ISSUE TITLE
rate below the rate step causes divide-by-zero panic

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1085]
The recoverer middleware catches it.

![image](https://user-images.githubusercontent.com/6109680/117854523-2f42ce80-b24f-11eb-9ebb-32dc6f87cb7d.png)

![image](https://user-images.githubusercontent.com/6109680/117854593-41bd0800-b24f-11eb-884f-2578cdf23d60.png)

**Comment by JoeGruffins** [comment]
Will attempt to solve.

**Comment by JoeGruffins** [comment]
Perhaps a separate issue, but it seems small values, like `0.00001` can take an insane amount of cpu and time to calculate.
