### ISSUE TITLE
log a full signed refund txn when sending a swap

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1087]
https://github.com/decred/dcrdex/blob/3fa59cf4dad60a991346795da25666f9bd215af2/client/core/trade.go#L1399

At this point, I believe the bytes of the signed refund transaction should be logged for emergency use.  My suggestion is that the `client.Asset.Swap` method also return these bytes.

Related: https://github.com/decred/dcrdex/issues/952

**Comment by JoeGruffins** [comment]
I'll do this.

**Comment by chappjc** [comment]
Excellent!  One thing that occurred to me with some similar but unrelated work (pre-generating a fidelity bond refund txn) was that the output address of the txn may need to be an address from the same keys as used in the contract script's refund path to avoid wasting even more addresses.  By comparison, the current `(*ExchangeWallet).Refund` impls hit getnewaddress for the output.  We really don't want to do that in this pre-generation though when it's unlikely to be used.  So I'm thinking we use the same address as was used in the contract script.  Maybe you'll have other thoughts about this though.

**Comment by JoeGruffins** [comment]
As you say, this probably won't be used so probably fine to reuse addresses.

Won't the signed refund txs need to all be separate? So maybe map of coin ID to signed refund txn?
