### ISSUE TITLE
Create a vscroll for Buy/Sell Orders tables

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1091]
As mentioned in issue #945 :

In addition to the bins, the Buy/Sell Orders tables need to be limited in height with vscroll of their own. Otherwise the Your Orders tables that goes below them in narrower windows leaves the visible part of the screen. This only happens when one of the Buy/Sell Orders tables is so full that they extend down off the screen.

**Comment by martonp** [comment]
Will do

**Comment by peterzen** [comment]
This also causes the main vertical scrollbar to flicker in wide screen displays.
