### ISSUE TITLE
ui: buy side order size dialog issues

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1097]
The Buy mode of the Limit Order dialog seems to be broken with respect to (a) the preview of total order size in quote units and (b) Max Size.

Refresh the /markets page and do not click on Sell because that changes the behavior.

![image](https://user-images.githubusercontent.com/9373513/119576259-03ab0280-bd7e-11eb-97a1-b230da5a49ae.png)

The Max Buy isn't filled in, but the main issue I believe is the missing text that would read "Total: 0.1446 BTC" just below Quantity.  See the Sell dialog:

![image](https://user-images.githubusercontent.com/9373513/119576367-3c4adc00-bd7e-11eb-8a30-cf659a381b78.png)

The browser console has the following error with the Buy dialog:

![image](https://user-images.githubusercontent.com/9373513/119576137-cba3bf80-bd7d-11eb-8a08-bb762b3bdf9d.png)

**Comment by JoeGruffins** [comment]
I seem to be unable to reproduce. There is an issue with maxOrders that could be causing this, where calculating the max buy could take a very long time. Does #1086 fix it for you?

**Comment by JoeGruffins** [comment]
Was able to see `Uncaught TypeError: r.market.maxSell is null` in the console, but I dont see it manifesting in a ui bug.

**Comment by chappjc** [comment]
It happens all the time with 0.2 release.  I can't get guy estimates.  Always the `toString` error.

**Comment by chappjc** [comment]
The bug seems clear.  maxBuy.Lots is undefined becaues

```js
if (quoteWallet.balance.available < aLot) {
      this.setMaxOrder(0, 1e8 / rate)
      return
    }
    if (mkt.maxBuys[rate]) {
      this.setMaxOrder(mkt.maxBuys[rate].swap, 1e8 / rate)
      return
    }
```

**Comment by vctt94** [comment]
Does it still need a fix?

**Comment by chappjc** [comment]
The buggy code in question in my previous comment is still there.  To reproduce you just need to have a balance available < aLot.

**Comment by chappjc** [comment]
I'd guess that `setMaxOrder` needs to have `if (maxOrder.lots === 0) {` changed to `if (maxOrder === 0 || maxOrder.lots === 0) {` or similar.

**Comment by vctt94** [comment]
Looking into it
