### ISSUE TITLE
Use newly-exported txsizes

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#111]
The txsizes package in dcrwallet was previously internal, so we just copied a lot of the code for dcrdex.  We can use directly now.  https://github.com/decred/dcrwallet/pull/1573

**Comment by dnldd** [comment]
Would like to work on this if no one is already.

**Comment by chappjc** [comment]
This should also be done in dcrdata where txhelpers/txsizes.go is essentially copy/paste from dcrwallet's internal package.

**Comment by dnldd** [comment]
Looks like dcrdata doesn't have `txhelpers/txsizes.go`, not seeing any references to vars/funcs defined in txsizes either.
