### ISSUE TITLE
Buy order misses after little while

### ISSUE THREAD

**Issue by vctt94** [decred/dcrdex#1114]
When starting dexc into browser, it correctly shows the buy/sell form:

![image](https://user-images.githubusercontent.com/15069783/123468733-91ba1900-d5c8-11eb-8c52-b959766142f4.png)

But after a little while, it hides itself (no action needed)

![image](https://user-images.githubusercontent.com/15069783/123468664-77803b00-d5c8-11eb-91a5-7e4f0bb06776.png)

I think it might be happening because I do not have a btc wallet on it

**Comment by JoeGruffins** [comment]
I would think it shouldn't show the form if you don't have a wallet, and therefore can't trade.

**Comment by amassarwi** [comment]
@JoeGruffins Yep, makes sense, I can try improve that.

**Comment by buck54321** [comment]
> I would think it shouldn't show the form if you don't have a wallet, and therefore can't trade.

That is what is supposed to happen and what was happening. Must be a regression.
