### ISSUE TITLE
client: remove obsolete auto account disable

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1116]
There is a piece of legacy code in `client/Core` that disables the account in the local DB if the account was not found server-side, but this is now both obsolete and problematic. At one point I had my account toasted because of a postgresql connectivity glitch on the server that would have resolved itself had client not auto-disabled the account permanently in its db.  The resolution was to manually restore a dexc.db (client db) from backup, which I was fortunate to have.

https://github.com/decred/dcrdex/blob/fcd3926fe989d987d18e873ff604f4a754af4ce4/client/core/core.go#L2903-L2905

This logic isn't needed anymore because accounts can now be disabled manually by the client on the /settings page.  It was also a poor approach since it was not easily reversible by the client except by restoring a backup db file.

**Comment by amassarwi** [comment]
can do
