### ISSUE TITLE
db: server should save all match-related data

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#112]
Right now, the server is not storing the following match-related data.

1. 4 signatures = (1 'init' ack signature + 1 'redemption' ack signature) x 2 parties
2. The secret hash
3. The swap script
4. 4 coin IDs = (1 'init' + 1 'redeem') * 2 parties

All 10 are needed to reconstruct the signature messages for the match. Additionally, the coin IDs are needed for a [DB-based `TxMonitored` solution](https://github.com/decred/dcrdex/commit/0177702479128ef43ba7dec3cc93493865e68ef5#r36524884), which means the data can't be stored as, say, an encoded blob [as is done in \#99](https://github.com/decred/dcrdex/blob/c5b004a667b7f8d58ac5a7c2f094a339533d9984/client/db/bolt/db.go#L182). I could see a solution which stored all of this data in a separate table though, with its own archive policy.

**Comment by chappjc** [comment]
Will look into solutions when PR #81 is completed and merged.

**Comment by buck54321** [comment]
This is done except for #216. Can use that issue for coordination.
