### ISSUE TITLE
client/assets: Use internal or external address for refundAddr in swaps.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1123]
For coins where HD wallets are concerned, use the internal or external branch for refund addrs. These addresses aren't normally sent any funds, although they might if the user uses a refund txn from the linked pr. This has some relation to the gap limit, as I do not believe this addresses is seen as "used" by wallet logic and might be reused in a wallet restored from seed.

Discussion started here:

https://github.com/decred/dcrdex/pull/1110#discussion_r664867760

**Comment by martonp** [comment]
I'll work on this.

**Comment by chappjc** [comment]
I think this needs discussion to determine the "right" thing to do given the discrepancies, and identifying any consequences of one approach over another in the context of gap limits as well as privacy.

**Comment by martonp** [comment]
Seems to me like refund transactions should be going to the external chain. In BIP-44 it states:
`We scan just the external chains, because internal chains receive only coins that come from the associated external chains.`

If refund transactions go to the internal chain, they could be missed when reloading the wallet because the refund doesn't come directly from an address in the external chain.

**Comment by JoeGruffins** [comment]
I also think it should be external simply because it is not being sent funds right away. imo the internal branch is for change, which creates a utxo immediately upon confirmation of a tx. Funds will be sent later or not at all.

That is my interpretation of the internal/change branch anyway.

**Comment by chappjc** [comment]
I tend to agree that it's external, although I feel I could argue semantics of change in smart contracts (i.e. when "later" arrives, the funds in the contract _become_ change in that you've just paid to yourself).  Although, I don't yet see change addresses getting scanned less readily than external ones (except for usual gap limit issues).  Clearly the internal branch is scanned when restoring from seed or rescanning an HD wallet.  Also, I'm sure buck will want to comment as well.

**Comment by JoeGruffins** [comment]
Will make a pr to switch btc to external if there are no objections.
