### ISSUE TITLE
cannot reconfigure wallet even though it's the same wallet

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1136]
I've gotten the new error even when it's the same wallet:

2021-07-23 10:25:20.548 [ERR] WEB: reconfig error: new wallet cannot be used with current active trades: unable to change wallets **with active trades**. Trades with this wallet must match or be canceled in order to change settings

![image](https://user-images.githubusercontent.com/9373513/126804896-1fb3f4a1-891f-4520-bf52-fabb7d90e546.png)

This one was DCR, but the issue could be Core logic.

**Comment by JoeGruffins** [comment]
Were you able to update after trades finished? Didn't we make it so one couldn't change settings if they had trades and we couldn't say for certain if the new wallet was the same wallet. I think this was intentional but I'll check again...

**Comment by JoeGruffins** [comment]
https://github.com/decred/dcrdex/blob/26c149af45ed42ebf33c8a781925424d087413dd/client/core/core.go#L2058-L2064

So I think the to wallet but no script to look at and get a refund address yet from, so we don't know if that trade belongs to the new wallet.

I think an idea I shared somewhere is to give all wallets an id, like the zeroth address or whatever is good for that coin, then we can be sure if a new wallet is the same wallet. Or we could check if new wallet owns an address from old wallet and assume it's the same wallet. Could also have the private key imported in that case, but probably a good enough guess.

**Comment by chappjc** [comment]
> Or we could check if new wallet owns an address from old wallet and assume it's the same wallet. ... We have the old wallet's deposit address and must connect to the new one in ReconfigureWallet() anyhow.

I was sure (wrong though) that we were doing just this, using the deposit address to see if its the same wallet. But clearly I was just thinking about the checks in `Connect` to get a new deposit address if the previous one is no longer owned.

The swap and redeem address checks from https://github.com/decred/dcrdex/commit/3fa59cf4dad60a991346795da25666f9bd215af2 do make sense, but now I'm questioning if they are redundant with a deposit address check.

Regarding the contract not existing yet because we haven't done our swap tx yet, that says to me any wallet can handle the trade if it has the funds.  So a pre-swap broadcast wallet would check that it can spend order funding coins.  That is, either `t.metaData.ChangeCoin` or `t.Trade().Coins` if there's no change coin yet.  But I feel like doing this is really getting off into the weeds when a deposit address check would do it all.

Really for now I think we should just consider matches with no swap yet by the "from" wallet to be OK, only failing if `ownsAddr` can say for sure (nuke the `maybeDifferentWallet` bool).

**Comment by JoeGruffins** [comment]
I'm not sure why I made it so complicated the first time. The new wallet could also just have the key to one of the trade addresses, so it's no better that checking just the deposit address. Was there some reason for the complexity I've forgotten?

**Comment by chappjc** [comment]
> Was there some reason for the complexity I've forgotten?

I don't think so.  Been racking my brain as well, but as long as we can assume an HD wallet where imported keys were not being used for orders and trades, the deposit address being owned will imply all the other addresses are too.
