### ISSUE TITLE
ui: Errors can extend beyond module.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1145]
Some errors can be extra long and not fit in the intended space. It's not really a problem but does seem unintended, although I don't have a suggestion to fix it. For example:

![errtolong](https://user-images.githubusercontent.com/34998433/127988772-b888a10c-8629-456b-ba60-01275ea906ec.png)

**Comment by itswisdomagain** [comment]
This should work: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
