### ISSUE TITLE
ui: update to bootstrap 5

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1148]
For any brave UI devs, we need to update from bootstrap 4 -> 5

Besides needing to get on the current release, it's going to fix all the sass `slash-div` warnings. https://github.com/twbs/bootstrap/issues/34051

**Comment by chappjc** [comment]
For reference @thi4go just got done with dcrdata's Bootstrap upgrade https://github.com/decred/dcrdata/pull/1872
Wasn't terrible.  We still need to be more selective with the forms and helpers imports though because those are kind of meta imports with stuff that's not necessarily needed.  But that PR could be a good reference.

**Comment by bgptr** [comment]
I'd like to work on this.

**Comment by chappjc** [comment]
I think @thi4go was on this.  Is that right?

**Comment by thi4go** [comment]
Go for it @bgptr , let me know if you need a hand. Had to put this one on hold, sorry mate @chappjc should have warned prior.

**Comment by chappjc** [comment]
No problem.  For reference here's the bs 5 update pr for dcrdata https://github.com/decred/dcrdata/pull/1872
