### ISSUE TITLE
Reconsider reconnect handling in DCR backend

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#115]
[Previous discussion](https://github.com/decred/dcrdex/pull/17/files#r317306919)

Reconnect handling for the Decred server backend is shoddy. At the very least, we need to resend the height on the `rpcclient.Client`'s `OnClientConnected` notification, which I believe will still be sent even if auto-reconnect is used.

**Comment by JoeGruffins** [comment]
On reconnect, would sending any missed blocks to dcr.anyQ be the correct way to handle this?

**Comment by buck54321** [comment]
Closed by #241
