### ISSUE TITLE
eth: Add backend methods.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1154]
This issue is meant to track adding functionality to eth swaps. Currently there is a bare bones implementation. Anyone who would like to work on adding a method, please comment here first so work is not duplicated.

As the dex was originally designed with UTXO based coins in mind, some methods **may** require far reaching changes.

server
- [x] TxData(coinID []byte) ([]byte, error)
- [x] InitTxSize() uint32
- [x] InitTxSizeBase() uint32
- [x] Contract(coinID []byte, redeemScript []byte) (*asset.Contract, error)
- [x] ValidateSecret(secret, contract []byte) bool
- [x] Redemption(redemptionID, contractID []byte) (asset.Coin, error)

~- [ ] FundingCoin(ctx context.Context, coinID []byte, redeemScript []byte) (asset.FundingCoin, error)~
- [x] ValidateCoinID(coinID []byte) (string, error)
- [x] ValidateContract(contract []byte) error

~- [ ] VerifyUnspentCoin(ctx context.Context, coinID []byte)~
- [x] run(ctx context.Context) // fix TODOs and refactor
- [ ] ValidateSignature(addr string, pubkey, msg, sig []byte) error

client
- [x] Balance() (*asset.Balance, error) // fix TODO
- [x] MaxOrder(lotSize uint64, feeSuggestion uint64, nfo *dex.Asset) (*asset.SwapEstimate, error)
- [x] PreSwap(req *asset.PreSwapForm) (*asset.PreSwap, error)
- [x] PreRedeem(req *asset.PreRedeemForm) (*asset.PreRedeem, error)
- [x] FundOrder(ord *asset.Order) (asset.Coins, []dex.Bytes, error)
- [x] ReturnCoins(unspents asset.Coins) error
- [x] FundingCoins(ids []dex.Bytes) (asset.Coins, error)
- [x] Swap(swaps *asset.Swaps) ([]asset.Receipt, asset.Coin, uint64, error)
- [x] Redeem(form *asset.RedeemForm) ([]dex.Bytes, asset.Coin, uint64, error)
- [x] SignMessage(coin asset.Coin, msg dex.Bytes) (pubkeys, sigs []dex.Bytes, err error)
- [x] AuditContract(coinID, contract, txData dex.Bytes) (*asset.AuditInfo, error)
- [x] LocktimeExpired(contract dex.Bytes) (bool, time.Time, error)
- [x] FindRedemption(ctx context.Context, coinID dex.Bytes) (redemptionCoin, secret dex.Bytes, err error)
- [x] Refund(coinID, contract dex.Bytes) (dex.Bytes, error) // fix TODOs
- [ ] PayFee(address string, regFee uint64) (asset.Coin, error)
- [ ] Withdraw(addr string, value uint64) (asset.Coin, error) // fix TODOs

~- [ ] Confirmations(ctx context.Context, id dex.Bytes) (confs uint32, spent bool, err error)~
~- [ ] RefundAddress(contract dex.Bytes) (string, error)~
- [x] checkForNewBlocks() // Needs logic to check for redemptions.

<details closed>
<summary>changelog</summary>

```
2021
08/06 - issue created
09/02 - check server InitTxSize() uint32 and InitTxSizeBase() uint32
10/05 - check client MaxOrder, PreSwap, and PreRedeem
10/18 - check server Contract and client SignMessage, FundingCoins, ReturnCoins, and FundOrder
10/21 - check server ValidateSecret and Redemption
11/05 - check server ValidateCoinID
11/11 - FundingCoin and VerifyUnspentCoin removed from server list
11/24 - check server TxData and ValidateContract
12/02 - check client Swap and Balance, add fix TODOs to Withdrawal, RefundAddress removed by #1312
12/16 - check server run and client Redeem, AuditContract, LocktimeExpired, FindRedemption, and checkForNewBlocks
12/17 - check server Refund and remove Confirmations, it looks like that was divided into SwapConfs and RegFeeConfs and those are done, add ValidateSignature to server
```
</details>

**Comment by JoeGruffins** [comment]
Will work on the server's `TxData(coinID []byte) ([]byte, error)`

**Comment by JoeGruffins** [comment]
Included `InitTxSizeBase() uint32` in the same pr as `InitTxSize() uint32`

Will do `Contract(coinID []byte, redeemScript []byte) (*asset.Contract, error)`

**Comment by martonp** [comment]
I'll work on the client `MaxOrder(lotSize uint64, feeSuggestion uint64, nfo *dex.Asset) (*asset.SwapEstimate, error)`.

**Comment by martonp** [comment]
I'll do `PreSwap(req *asset.PreSwapForm) (*asset.PreSwap, error)` next.

**Comment by JoeGruffins** [comment]
Contract is in the pipeline so moving to server's `ValidateSecret(secret, contract []byte) bool`

**Comment by JoeGruffins** [comment]
#1089 will change/add some client methods

**Comment by JoeGruffins** [comment]
Will do `Redemption(redemptionID, contractID []byte) (asset.Coin, error)` for the server.

**Comment by JoeGruffins** [comment]
Also started on `FundingCoin(ctx context.Context, coinID []byte, redeemScript []byte) (asset.FundingCoin, error)` because Contract, Redemption, and FundingCoin all use the same asset.Coin interface to some extent.

**Comment by martonp** [comment]
I'll do `PreRedeem(req *asset.PreRedeemForm) (*asset.PreRedeem, error)` next.

**Comment by martonp** [comment]
I'll do `FundOrder(ord *asset.Order) (asset.Coins, []dex.Bytes, error)` next.

**Comment by martonp** [comment]
Will do `Swap(swaps *asset.Swaps) ([]asset.Receipt, asset.Coin, uint64, error)` next.

**Comment by martonp** [comment]
Will do `Redeem(form *asset.RedeemForm) ([]dex.Bytes, asset.Coin, uint64, error)`

**Comment by JoeGruffins** [comment]
Actually looks like `ValidateCoinID` was already done, doing `ValidateContract`

**Comment by buck54321** [comment]
I'll do `TxData`

**Comment by buck54321** [comment]
@JoeGruffins please remove the `FundingCoin` and `VerifyUnspentCoin` methods from the server list. We'll have to handle that a bit differently. I'll offer up something in a minute.

**Comment by JoeGruffins** [comment]
@buck54321  #1243 exists

**Comment by buck54321** [comment]
> @buck54321 #1243 exists

I'm really sorry about that, @JoeGruffins. I should have taken a wider look at this stuff earlier.

**Comment by JoeGruffins** [comment]
it's fine. I really didn't want to mess with the server as much as possible, but I'm confident your way is better. I was just going to shoehorn it in there.

**Comment by buck54321** [comment]
Here's what I'm looking at for required communications.

| `Message` | Required | Currently Sending | Recommended Action | Field assignments |
| -------------- | :--------- | ------------------------ | ----------------------------- | ------------------- |
| `Limit` / `Market` | account address | account address, amount, nonce | drop nonce. <sup>1</sup> | `Trade.Coins = []Coin{[]byte(contractAddr)}` |
| `Init` | txid, secret hash | txid, secret hash, contract address | drop contract address. <sup>2</sup> | txid = `CoinID`, secretHash = `Contract` |
| `Redeem` |   secret (maker) <sup>3</sup> | n / a | we'll send the secret | secret = `Secret` |

<sup>1</sup> Leave amount encoded for internal use, but only send address in the actual `Message`.

<sup>2</sup> I'm going to propose something different for contract address validation, but if we do want to validate the contract address, it'll need to be done earlier than this anyway, so let's not plan to send it here.

<sup>3</sup> We may want to record the redemption transaction IDs too, but it seems less important for eth.

There's also `Cancel`, but that' straightforward [once we get a signature algo figured out](https://github.com/decred/dcrdex/pull/1289#discussion_r749367628).

**Comment by JoeGruffins** [comment]
I'll look into the server `run` and what's up with eth reorgs. Not working in this area are you @buck54321 ?

**Comment by buck54321** [comment]
Go for it, @JoeGruffins. 

I'll claim `Confirmations` -> `SwapConfirmations` + `RegFeeConfirmations`

**Comment by chappjc** [comment]
@buck54321 If you're working on `SwapConfirmations`, please consider how we can apply the "redeemable" check in that.  If ETH's impl. calls `(*rpcclient).isRedeemable` in addition to the confirmation checks (perhaps just when >0 confs), the return from `SwapConfirmations` should reflect its findings.  Off the top of my head, a couple options are 1) a new return bool, which would likely just be true for utxo assets, or 2) force confs to 0 if `isRedeemable` says no.

Background: https://github.com/decred/dcrdex/pull/1274#discussion_r754401945

**Comment by chappjc** [comment]
Or, um, I guess `isRedeemable` can be used in `Redeem` just before actual broadcasting the secret key.

**Comment by martonp** [comment]
Regarding the CoinID to send during the `Init` request, I agree that we don't really need the Index field of the `TxCoinID` since we are also sending the secretHash in the `Contract` field, but I think it would be better to maintain a set of ETH coin IDs and actually use those when sending coin IDs. A coin ID should represent a specific amount of ETH, and without the Index field, the `TxCoinID` doesn't really do this. Even though it's a bit of extraneous information, it's still worth sending the entire coin ID over. Otherwise we'll have a set of coin ids, but the coin id that we are sending in a message doesn't deserialize to any of them, which is kind of confusing.

**Comment by martonp** [comment]
I'll do `AuditContract(coinID, contract, txData dex.Bytes) (*asset.AuditInfo, error)` next.

**Comment by martonp** [comment]
I'll do `Refund` next.

**Comment by JoeGruffins** [comment]
I guess I'll take a whack at the Withdrawal TODOs since they are still there and probably not related to other's work.

**Comment by buck54321** [comment]
I'm working on `(*Driver).Exists`

**Comment by buck54321** [comment]
I'll do `LocktimeExpired`

**Comment by buck54321** [comment]
I'll work on `FindRedemption`.

**Comment by JoeGruffins** [comment]
I guess I'll do `PayFee` for completion.

**Comment by JoeGruffins** [comment]
I guess I'll do the server's ValidateSignature.
