### ISSUE TITLE
server: implement lot size change

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1174]
Changing the lot size for a market currently involves the following:

1. suspend market and purge book
2. (almost certainly) allow all active swaps to finish negotiation
3. shutdown and edit markets.json and change lots size per-market
4. (**the bad part**) `UPDATE markets SET lot_size = <something in atoms/sats>`

Step #1 will always be needed since all orders on the book must be the same lot size.  This is quick and easy.

If the operator skips step #4, server panics on startup (it's a hard coded `panic`).  This should be changed:  At startup if lot size in `markets` postgresql table does not match the lot size in markets.json, check for booked orders and unbook any (ideally notifying clients) or refuse to start.  Then update the `markets` table with the new lot size and continue to start up everything.

Off hand I don't know what could go wrong if step #2 is skipped.  On startup, the Swapper tries to resume active swaps, and this might be fine but we need to evaluate for gotchas if the lot size is different.  It may be that there's an issue client-side where clients grab lot size from the current server config on reconnect, and their matches may reference this.

**Comment by JoeGruffins** [comment]
I would like to work on this if no one else is.

**Comment by chappjc** [comment]
Thanks, @JoeGruffins.  I had planned to do this but I decided to see about something else.

Regarding the resolution, I think if orders are unbooked on startup because of incorrect lot size, the clients cannot and don't need to be notified.  The server is in the process of starting up, so the comms aren't up yet and even if they were up earlier users are unlikely to connect super fast.  But when they do connect, they just do and order_status anyway to discover their orders are canceled.
