### ISSUE TITLE
client/webserver: need translations for orderReader

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1179]
Related #1022, #1051, #1127

The `orderReader` type in **client/webserver/types.go** has a handful of hard-coded strings and assumptions about number formats. These are used in historical data views at **/order{s}**.

**Comment by chappjc** [comment]
Also it seems that the OrderStatuses need translations as well for the /orders route.  `var allStatuses = map[uint8]string{` is english presently so the status filters in orders.tmpl (`{{range $status, $statusString := .Statuses}}`) have english strings.

**Comment by buck54321** [comment]
I think we should get rid of `orderReader` and `matchReader`, and refactor such that **everything** is handled with javascript on the **order** and **orders** view. I actually wanted to do that way back with #644. In the new architecture, **order.tmpl** and **orders.tmpl** would simply provide `data-tmpl` templates. Javascript would fetch and load the actual data. `orderReader` and `matchReader` are not trashed so much as translated to **orderutil.js**. There are already some mirrored methods there, like `StatusString`, `hasLiveMatches`, and `(*matchReader).StatusString`. Those methods exist because we update **some** displayed info live as we receive websocket notifications, so some of the machinery to create and update on-page elements is already in place.

**Comment by chappjc** [comment]
That seems fine.

However for the purposes of considering translations done for 0.3, I don't think we should bother with this.

**Comment by buck54321** [comment]
> However for the purposes of considering translations done for 0.3, I don't think we should bother with this.

Yeah, that'd be too much. I'm think it's fine to have a few untranslated strings in the historical order views for 0.3.

**Comment by vctt94** [comment]
I can work on that

**Comment by buck54321** [comment]
What are you planning to work on, exactly? Can you give me a rough game plan?

**Comment by vctt94** [comment]
I'm planning on getting rid of `orderReader` and `matchReader`, as you suggested, load this data from javascript and update them on their notifications. 

I believe `orderReader` will be a transtion simpler, so I am planning on start with it.

Do you have anything planned for that?
