### ISSUE TITLE
client: Add an LTC exchange wallet

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#118]
The BTC exchange wallet was designed to be re-used in much the same way as the BTC server backend was. That means the LTC exchange wallet can (hopefully) be implemented with very little effort. See the **server/asset/ltc** package for an example.

**Comment by JoeGruffins** [comment]
I can do this if noone is on it.

**Comment by JoeGruffins** [comment]
I assume we also want a test harness for this?

**Comment by chappjc** [comment]
Yup, simnet harness needed.
