### ISSUE TITLE
http API microservice

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#119]
The read-only HTTP (REST) API should be part of a standalone microservice.  The computational load for API requests need not burden the DEX server and potentially interfer with the critical operations of order and swap processing.  The data API service could connect to the same postgresql database server, or better to a replicated database to further isolate dcrdex from the API service.

**Comment by ukane-philemon** [comment]
@chappjc, this is closed by #796, right?

**Comment by chappjc** [comment]
No, we have a monolith presently, while this issue called for a microservice.  The work of serving a market data HTTP API is unrelated to the core functionalities of the dcrdex server (market and swap coordinator).  Another process needs to be created with the very narrow purpose of pulling data out of postgresql, analyze and reduce it, and served to consumers without bothering dcrdex.  The dcrdex can proxy requests or an upstream reverse proxy can route directly to it.

There are several reason.  When dcrdex starts up, data preparation and queries already delay launch by about 10 seconds _per market_, for a market that about 2 yrs old like the btc_dcr one on the dex testnet server.  Having the HTTP API request handlers built into dcrdex are also a attack vector we could do without.  Architecturally, the data collection business is too lightly knit into other code like the market and matcher, and eventually it's going to become hard to separate.

I think we can keep this issue on hold for now though.  But let me know if this makes sense to you.

**Comment by ukane-philemon** [comment]
> But let me know if this makes sense to you.

Uhm, you mean having the HTTP API request handlers separated into a microservice? Mostly, for read-only API requests?

**Comment by chappjc** [comment]
Yes, separate and entirely read-only.

**Comment by ukane-philemon** [comment]
Alright, would be glad to work on this when it is needed.
