### ISSUE TITLE
eth: calculate required gas instead of using hardcoded values

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1196]
The gas usage of various EVM operations may be changed, so functions that calculate the gas usage of initiating and redeeming swaps should be calculated instead of hardcoded.

**Comment by JoeGruffins** [comment]
Could use a small description.

Currently this looks difficult if actual funds are needed to query prices, but maybe that is not the case?

**Comment by martonp** [comment]
We will be doing hardcoded values instead. The gas estimation happens without any external calls, so any changes to the estimations would be caught by the harness test.
