### ISSUE TITLE
Update to btcd 0.22

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1209]
We are requiring btcd 0.20 presently, but there are two releases since then, most recently 0.22: https://github.com/btcsuite/btcd/releases/tag/v0.22.0-beta

In #1202 I will be updating btcutil to `v1.0.3-0.20210527170813-e2ba6805a890` to get the fixed hdkeychain, but unfortunately since btcd requires the same semantic version of btcutil (implicit v1), this forces v0.20 of btc to build with the new btcutil.  They should have bumped to btcutil/v2, but they didn't.  I don't see any clear issues, but we need to be careful.

As such, we should update our btcd require to v0.22.0-beta, which was already updated to use the "fixed" btcutil.

We only have to look out for changes to the following packages: `btcec`, `chaincfg`, `txscript`, `wire`,  `btcjson` (this one in particular), `chaincfg/chainhash`, and `blockchain`.

**Comment by ukane-philemon** [comment]
Now on v0.22.0-beta, closed?

**Comment by chappjc** [comment]
Yeah.  I've since moved on to getting upstream btcd's btcec/v2 broken free of it's circular require. Otherwise we're stuck at the current btcd revision because go-ethereum requires an older incompatible version.

Anyway, this issue is done
