### ISSUE TITLE
block-polling assets may erroneously detect a reorg

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#121]
With assets that require best block polling (vs. notifications), the cached best block may not be the previous block when the best block is retrieved.

e.g. 

`[INF] ASSET[btc]: Reorg from 00000000000016b77e1c1de8276574f3069f82e3d6b94f9e1e2fe0e19178367b (1657353) to 0000000000000e9e107dee915650dd2edaddfc11fc3685810ec3eca979debed4 (1657355) detected.`

1657354 and 1657355 were so close together that when the BTC backend with a current cached best block of 1657353 polled for a new block, it saw 1657355 and decided it was a reorg.  Fortunately it would find that 1657354 is mainchain and not delete anything from cache, but the logic may need to be adjusted so as not to mislead future code depending on accurate reorg detection, or at least accurate logging.

**Comment by chappjc** [comment]
For instance, https://github.com/decred/dcrdex/pull/81/commits/381a7724e08b74d3a2ab4b2ae484cb93d3e7a26a.  We'll need to be careful in these cases, but as it is written presently it works out fine except for missing some blocks in the cache.

**Comment by buck54321** [comment]
Is this issue resolved with the `BlockUpdate` struct added in #241, which has a `Reorg bool` field?

**Comment by chappjc** [comment]
I don't think so.  The `BlockUpdate.Reorg` field is set from the place where the problem was: https://github.com/decred/dcrdex/pull/241/files#diff-84bf0e0a1311bc0326902a31a49cc7a0R707-R715
but maybe the issue was fixed there in Run somehow (`iBlock.Confirmations > -1` perhaps?).  I would have to mine a few quick blocks to check.

**Comment by ukane-philemon** [comment]
> but maybe the issue was fixed there in Run somehow (iBlock.Confirmations > -1 perhaps?). I would have to mine a few quick blocks to check.

@chappjc, is this still a problem?
