### ISSUE TITLE
auth/admin: banning by admin API ineffective

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1214]
The admin API **/account/{accountID}/ban?rule=RULE** = `(*Server).apiBan` doesn't really work, because the `(*AuthManager).handleConnect` method will just [unban the user based on score](https://github.com/decred/dcrdex/blob/ad4321a869156c5340fb698fcdd828b751349117/server/auth/auth.go#L1193-L1196). Perhaps we need a new "violation" with a penalty of `math.MaxInt32` to re-enable administrative banning of users.

**Comment by chappjc** [comment]
That would be one resolution, which with I still tend to agree is needed at present despite the idea of an operator-initiated ban/suspend being incompatible in practice with mesh, and incompatible in theory with a bonded scheme (both future concepts).

The other option would be to nuke these endpoints (ban and unban) with the understanding that both a mesh configuration and a tiered/bonded user scheme would make (un)banning a specific user unilaterally less meaningful.

In any case, these two admin API endpoints have no effect any more and should be removed unless a synthetic violation is introduced that will max out ban score.
