### ISSUE TITLE
persistent order direction button selection

### ISSUE THREAD

**Issue by raedah** [decred/dcrdex#1229]
Order direction has two buttons for Buy and Sell. When using the Sell button and placing an order, the selected button reverts back to Buy after the order is placed. Expected behavior is for the Sell button to stay selected. Changing back to a Buy selection can cause a user to place successive orders and unintentionally Buy when they meant to Sell.

**Comment by martonp** [comment]
I'll do this.

**Comment by martonp** [comment]
This has already been fixed.

**Comment by chappjc** [comment]
I haven't seen this either
