### ISSUE TITLE
market history (candles) chart should default to 1h or 5m bin size

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1231]
And we should remember which bin size the user last selected and default to that if possible.

**Comment by buck54321** [comment]
This issue has evolved. We're now using a default of `5m` (#1825), but we actually **need** the `5m` candles until the 24-hour high/low values are served in the server's candles (also added in (#1825). Leaving this open until then, at which point we can start remembering the user's last choice.

**Comment by ukane-philemon** [comment]
@chappjc, can close?

**Comment by buck54321** [comment]
Resolved by #2284.
