### ISSUE TITLE
ui: ghost orders in depth chart

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1233]
Related #835.

![image](https://user-images.githubusercontent.com/6109680/137585084-e669866b-81eb-4095-83fb-f51a5b437099.png)

There's a ghost buy order there. It's not shown in the table below, but it's screwing up the depth chart gap position.

Register a simnet account and turn on the loadbot to repro.

**Comment by buck54321** [comment]
I actually thought we had resolved #835 at some point, but it's probably the same issue. I'm not seeing any zero-quantity orders in the tables.

**Comment by ukane-philemon** [comment]
fixed by #835?

**Comment by chappjc** [comment]
> fixed by #835?

Yes, although exact cause still unknown.
