### ISSUE TITLE
update geth to at least 1.10.11

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1252]
I noticed that abigen from go-ethereum 1.10.10 is now generating a contract.go with breaking changes.  The data has been reorganized, but it generates code for a version of the `abi/bind` package that apparently has breaking changes of its own.

A quick update of the require revealed other breaking changes.  The main one that broke the build is that a `node.Node` no longer has account manager backends by default, requiring them to be registered.  https://github.com/ethereum/go-ethereum/pull/23019
This seems to require changes like:

```diff
- ks := node.AccountManager().Backends(keystore.KeyStoreType)[0].(*keystore.KeyStore)
+ ks := keystore.NewKeyStore(node.KeyStoreDir(), keystore.LightScryptN, keystore.LightScryptP)
+ node.AccountManager().AddBackend(ks)
```

**Comment by JoeGruffins** [comment]
@martonp no problems! I'll always make an issue first. Didn't notice I needed to update though, will do now.
