### ISSUE TITLE
server: custom logo

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1256]
The server should provide a custom logo. 

1. Min size 32x32. 1:1 aspect ratio.
2. Served over HTTP
3. Logo is configurable, but we need a default icon. I can see two ways of dealing with this. a) have a default icon for the default server configuration. Probably just the dcrdex logo. Or b) have no default. If none is provided, client can fall back to letter coins. e.g. **/img/coins/a.png**

**Comment by ukane-philemon** [comment]
> b) have no default. If none is provided, client can fall back to letter coins. e.g. /img/coins/a.png

I think b is better. However, since the server logo is currently not on display anywhere, we would need to display the server logo somewhere on the markets page, dexsettings page, and settings page.

**Comment by chappjc** [comment]
I hope you haven't sunk much time into this.  When servers are in a network (mesh) it won't make sense.  I realize it's a long time out, but if we implement this it becomes something we have to remove.
I'm also not wild about bloating the `config` response with this data.

**Comment by ukane-philemon** [comment]
> I'm also not wild about bloating the config response with this data.

If we want the client to display this, we will eventually have to provide the logo data via the `config` response.
`unknown exchanges` can call the HTTP endpoint when they need to display a logo.

> When servers are in a network (mesh) it won't make sense. I realize it's a long time out, but if we implement this it becomes something we have to remove.

You can let me know if this isn't really applicable anymore.

**Comment by chappjc** [comment]
> If we want the client to display this, we will eventually have to provide the logo data via the `config` response.
> `unknown exchanges` can call the HTTP endpoint when they need to display a logo.

Why can't it just come from the HTTP endpoint for all cases?  The frontend could get it via XHR and the backend doesn't even need to know about the concept of a logo.

**Comment by ukane-philemon** [comment]
> The frontend could get it via XHR and the backend doesn't even need to know about the concept of a logo.

Request to servers(HTTPS) requires the server's cert which is not readily available to the frontend and also not on the `core.Exchange` struct.

**Comment by ukane-philemon** [comment]
@chappjc, can close?

**Comment by buck54321** [comment]
Won't implement. See #2004 for discussion.
