### ISSUE TITLE
Plugin-style asset backends

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#127]
The asset backends should eventually be implemented and loaded as plugins.

https://golang.org/pkg/plugin/
https://medium.com/learning-the-go-programming-language/writing-modular-go-programs-with-plugins-ec46381ee1a9

Among other things, this will require a module `decred.org/dcrdex/server/asset`.

**Comment by ukane-philemon** [comment]
uhm, @chappjc  is this still a thing?

**Comment by chappjc** [comment]
Nah.

Plugins turned out to be a no-go on account of cgo as well as poor platform support (no openbsd and others).

I think the markets.json system has proven more than adequate to define the supported assets.  New assets just need a rebuild and restart, which seems to be acceptable. If there turns out to be a need to have certain assets entirely omitted from the build, build tags are likely a better option.  It works for eth via the lgpl tag.
