### ISSUE TITLE
eth/client: Don't allow submitting a trade if not enough balance to redeem

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1275]
When buying ETH, the user needs to have some funds in their wallet. Otherwise, they will not be able to redeem the swap.

**Comment by martonp** [comment]
I'll work on this next.

**Comment by martonp** [comment]
Will wait for #1293 to be merged first.

**Comment by JoeGruffins** [comment]
I guess  #1314 will touch on this?

**Comment by JoeGruffins** [comment]
Fixed I think? @martonp can close?

**Comment by martonp** [comment]
Yes this was done by @buck54321 I think.
