### ISSUE TITLE
DCRDEX issue

### ISSUE THREAD

**Issue by fkcz91** [decred/dcrdex#1286]
Hi,

I have just installed DCRDEX and it is up and running in Decrediton (windows).

I tried to deposit funds to the DCR wallet to do a test trade. I started with 1. then did again 3. Every time I transfered DCR from my mixed wallet to the DEX wallet, I got two outputs in the transaction. One output is exactly the amount I wanted but there was always something extra added. Consequence is that I always deposited more than I wanted and really do not understand why.

Example: I wanted to transfer 3 DCR. 
the wallet input included: 0.67108864 DCR and 10.73741824 DCR (both from MIXED wallet)
the wallet output included: 8.40846498 DCR and 3.00000 DCR (both to DEX wallet)

The 3 DCR I wanted is there, but dont quite understand why 8.4 was transferred in addition.

Did this happen to anyone or does someone know what have caused?

Thanks!

**Comment by decencyunlaced** [comment]
Hello,

The issue you're having is fixed in the upcoming 1.7 release. I believe you're experiencing something like [this.](https://github.com/decred/decrediton/issues/3541)

**Comment by fkcz91** [comment]
yes, thank you!!!
