### ISSUE TITLE
contracts: Consider enforcing tx version.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1328]
While script versions are checked to be something we expect, transaction versions are not. For the same reasons script versions are checked, I believe we should also check tx versions, to ensure the tx structure is what we expect.

For btc, only version one is ever used afaict. Have not looked into ltc, but can assume nothing changes there. So enforcing one would be good.

For dcr, I believe we can possibly have 1-3. The dex functions fine on one, and that's probably all we have used so far. Two enables sequence locks, and I'm not sure, but if the tx is version 2 or greater, I think we need to check that the tx sequence is a disabled value. 3 enables treasury actions, so, enabling that would probably be fine. I think we can still spend from tgen created outputs fine even at one though, similar to other stake outputs, votes and revocations. However, any versions that don't exist yet should probably be enabled as they come, so that we can consider if we need to change tx validation and raise the allowed version one at a time.

related comment https://github.com/decred/dcrdex/pull/1308#discussion_r755743244

**Comment by JoeGruffins** [comment]
For bitcoin, I think sequence locks are enabled for version 1, so the sequence should also be checked for all tx.

https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki

**Comment by chappjc** [comment]
I think we can check if nSequence on ANY input is _less than_ 0xfffffe (MaxUint32-1), meaning RBF is enabled.  Conversely, not rbf if all inputs have sequence >= 0xfffffe.  But totally final (locktime disabled too), if sequence == 0xffffff.
https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/src/util/rbf.cpp#L9-L17
