### ISSUE TITLE
Withdrawals are not working

### ISSUE THREAD

**Issue by bogdyak** [decred/dcrdex#1329]
Dear team, trying to withdraw dcr from my dcr dex account. Gives me the following error
```
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.18.0 (Ubuntu)</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```
![bug](https://user-images.githubusercontent.com/33520852/144896538-3021350d-eba5-41b4-9a69-9e88b49c7cd4.png)

**Comment by chappjc** [comment]
You seem to have proxied the connection to your dexc process via nginx.  dexc is supposed to be listening on localhost and running on the same machine where you are using the browser.  Your browser is not communicating directly with dexc.

You will need to share more information about your setup.  Please use Matrix (see chat.decred.org) to get further support.
The team and community is happy to help with tech support, but I'm going to close this github issue as it does not appear to be an issue with the software itself.

**Comment by bogdyak** [comment]
> You seem to have proxied the connection to your dexc process via nginx. dexc is supposed to be listening on localhost and running on the same machine where you are using the browser. Your browser is not communicating directly with dexc.
> 
> You will need to share more information about your setup. Please use Matrix (see https://chat.decred.org/) to get further support. The team and community is happy to help with tech support, but I'm going to close this github issue as it does not appear to be an issue with the software itself.

Thank you
