### ISSUE TITLE
client/eth: Respect user's max fee rate.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1336]
eth should send transactions with a max fee chosen by the user. I really think this should just be changed to the chosen max fee as well: https://github.com/decred/dcrdex/blob/6bd4dc842fb5999c20c4c66d677dfa4cbc2fbaca/client/asset/eth/nodeclient.go#L471-L473
and there should be an error if the base fee plus miner tip would be over the chosen max fee. Maybe this is the only place that would need to change, besides recording the fee on construction of the `ExchangeWallet`.

**Comment by martonp** [comment]
Should we just not allow a nil `MaxFeeRate` to be passed into this function?

**Comment by JoeGruffins** [comment]
yes imo. If you do `maxFeeRate = new(big.Int).Mul(baseFee, big.NewInt(2))` Then that could really be anything depending on the network. There are some docs somewhere that says this specific 2x base is optimal for ensuring the tx gets included in the next six blocks. @buck54321 set this max so if he has thoughts about changing this...

**Comment by JoeGruffins** [comment]
Will attempt to solve this.

**Comment by JoeGruffins** [comment]
Related convo: https://github.com/decred/dcrdex/pull/1485#issuecomment-1049970496

The fee is being respected for initiations. It was never intended to block other transactions.
