### ISSUE TITLE
dcrdex: add option to delay market startup

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#134]
... I was thinking of specifying a delay duration instead of absolute time, that way a production server could set it and forget it, e.g. "markets re-open 10 minutes after the server starts".

_Originally posted by @buck54321 somewhere

**Comment by ukane-philemon** [comment]
@chappjc, is this feature still needed?

**Comment by chappjc** [comment]
I don't think so.  Only related option that might make sense it to start with the markets suspended.  Then the operator can use the admin interface to start them when things are ready.

**Comment by ukane-philemon** [comment]
> Only related option that might make sense is to start with the markets suspended.

Alright, since this feature is no longer needed can we close on this issue? And open another specifically for suspending markets on startup (if it's really what we want)?

**Comment by ukane-philemon** [comment]
> I don't think so. Only related option that might make sense is to start with the markets suspended. Then the operator can use the admin interface to start them when things are really ready.

@chappjc, I'd like to work on this. Any other thoughts?
