### ISSUE TITLE
eth/client/simnet_tests: testSendSignedTransaction failing.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1342]
Fails with `nodeclient_harness_test.go:446: pending in not showing`.

**Comment by JoeGruffins** [comment]
It looks like the balance ignores pending normal (not contract) receives altogether.

**Comment by chappjc** [comment]
I believe that's intentional as per https://github.com/decred/dcrdex/pull/1321
Maybe the test needs to be updated?

**Comment by chappjc** [comment]
Same intent server side: https://github.com/decred/dcrdex/pull/1293#discussion_r759834062

**Comment by JoeGruffins** [comment]
I wish it would take me to the comment. It should ignore pending incoming?

**Comment by chappjc** [comment]
Github will work one of these days I'm sure.

Client method: https://github.com/buck54321/dcrdex/blob/f0554f63331c97a5f9e21b7c24d2bfdc68a50c5b/client/asset/eth/contractor.go#L42-L46

Server code:  https://github.com/decred/dcrdex/blob/bd1d3b25c60a75179514e1e53e9225d36d1b0675/server/asset/eth/rpcclient.go#L141-L150

I thought the harness was updated in both those, so I'm not sure what the issues is.  Haven't looked into this `testSendSignedTransaction` fail yet.

**Comment by JoeGruffins** [comment]
Oh ok. So do not add untrusted funds. So, in the test there's a send to oneself, which would not usually happen, but could be trusted if it did. So, also ignore these receives or add a case for sends to oneself?

**Comment by buck54321** [comment]
Looks like it was removed in #1321 (merged Dec 6th), but added back in #1319 (merged Dec 9th). Probably a rebase error.

**Comment by JoeGruffins** [comment]
Removing the test.
