### ISSUE TITLE
Implement swap contract for erc20

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1345]

**Comment by martonp** [comment]
I'm working on this.

**Comment by chappjc** [comment]
Excellent @martonp, thanks!

Not that you need these resources, but some erc20 swap contracts I had bookmarked in case they are of any use to you:

- https://github.com/jchittoda/eth-atomic-swap/tree/master/contracts (or https://github.com/confio/eth-atomic-swap/tree/master/contracts)
- https://github.com/MarvinJanssen/stx-atomic-swap/blob/master/eth/contracts/Erc20Erc721HTLC.sol#L93

**Comment by martonp** [comment]
Thanks, I think they will be helpful.
