### ISSUE TITLE
ethereum token Wallet design (client)

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1348]
As smart contracts rather than regular externally-owned accounts, ERC-20 token control is tightly coupled with a regular account.

To receive tokens, the used address is the regular account address.  To transfer ERC-20 tokens, the user must have ETH in their regular account to call the `transfer` or `transferFrom` function.

As such, I believe the appropriate design for a `client/asset.Wallet` for an ERC-20 token involves the Ethereum `Wallet` being the **parent** for any token wallet instances.  One way this might work is to introduce a factory method:

```go
client/asset/eth.(*ExchangeWallet).NewTokenWallet(token TokenID, ...) Wallet
```

The token's backend would be tightly coupled with the ETH backend.  Namely, they would share a node, a block monitoring goroutine, account, etc.  The token `Wallet` would have direct access to the fund locking mechanisms for the purposes of reserving ETH for gas of the token txns, and it would have it's own token amount locking mechanisms.

The `Driver` system would still be used, and it can enforce that a regular ETH `Wallet` exist and be opened to power the requested token `Wallet`.

----

Alternatives?

**Comment by buck54321** [comment]
Thanks for starting the convo on this, @chappjc.

I have a lot of questions around asset IDs. Just a few different approaches and some of the consequences.

1. Tokens can be a new subdivision of an asset ID such that an asset is now defined as a tuple `(assetID, tokenID)`. A new field in `dex.Asset`, new database columns, interface and API changes to accommodate. 
2. We could cheat, and reserve a range of IDs for a particular asset's tokens, e.g. for ETH, we would reserve the range `[42000, 42999]` for tokens. Fewer interface and API changes, but it's almost too simple. The consumer actually **needs** to account for token degeneracy at some critical points like wallet creation (as you pointed out), and funding checks.
3. A blended approach, where we still use a reserved range, but we query tokenism at critical points. Backends would register token associations with with the **asset** packages, which would then provide methods for querying token dependencies. Consumers would then check if an asset is a token at critical points, e.g. funding checks, wallet creation.

**Comment by chappjc** [comment]
Good questions.  Clearly there are some factors to balance here.

Without regard to asset ID / token ID issues, when considering consumers outside of the client/asset packages, such as client/core, I do think we should strive to minimize special handling for tokens as much as possible.  This is why I propose a very tight coupling with the particular concrete `ExchangeWallet` of the base layer asset, where token wallet creation should be performed by a factory method of the base layer's ExchangeWallet, and all the operational concerns like funding should be coordinated behind the scenes, not involving client/core.

That said, just considering client/asset package operations, not client/core concerns, **distinct token IDs** sounds preferable to reserved special ranges.  Maybe something like this?

**client/asset/driver.go**

```go
// EXISTING
// Driver is the interface required of all exchange wallets.
type Driver interface {
	Open(*WalletConfig, dex.Logger, dex.Network) (Wallet, error)
	DecodeCoinID(coinID []byte) (string, error)
	Info() *WalletInfo
}

// ADD
type TokenDriver interface {
	OpenToken(tokenID uint32, baseWallet Wallet, ...) (Wallet, error)
}
```

**client/asset/eth/eth.go**

```go
// EXISTING
// Open opens the ETH exchange wallet. Start the wallet with its Run method.
func (d *Driver) Open(cfg *asset.WalletConfig, logger dex.Logger, network dex.Network) (asset.Wallet, error) {
	return NewWallet(cfg, logger, network)
}


// NEW

// Open opens the ETH exchange wallet. Start the wallet with its Run method.
func (d *Driver) OpenToken(tokenID uint32, baseWallet Wallet, /*, settings ...*/ ) (asset.Wallet, error) {
	eth, ok := baseWallet.(*ExchangeWallet)
	if !ok {
		return nil, errors.New("no good for ETH tokens")
	}
	return eth.NewTokenWallet(cfg, logger, network)
}

func (eth *ExchangeWallet) NewTokenWallet(tokenID uint32, ...) (asset.Wallet, error) {
	switch tokenID {
	case TokenUSDT:
		newTetherTokenWallet()
	default:
		return nil, fmt.Errorf("unrecognized ETH token %v", tokenID)
	}
}


func init() {
	asset.Register(BipID, &Driver{})
	asset.RegisterToken(TokenUSDT, &Driver{})
}
```

That's a little rough, just a sketch.
It does make the client/core-level consumer treat tokens a bit differently though, at least during setup and construction.

**Comment by buck54321** [comment]
> distinct token IDs sounds preferable to reserved special ranges

Unless I'm missing something, distinct token IDs binds us to the first option, with e.g.

- New fields in `dex.Asset`
- Schema changes for both DBs
- Changes to `order.Trade` to specify token IDs for both sides
- new main API protocols -> msgjson struct updates for token IDs

Not objecting. Just trying to understand the implications.

**Comment by chappjc** [comment]
Right, just exploring door #1 from the point of view of the client/asset packages.  It's a major changes for consumers, and that goes against my initially stated design goal of minimizing consumer awareness of tokens.

**Comment by chappjc** [comment]
> 2\. We could cheat, and reserve a range of IDs for a particular asset's tokens, e.g. for ETH, we would reserve the range `[42000, 42999]` for tokens. Fewer interface and API changes, but it's almost too simple. The consumer actually **needs** to account for token degeneracy at some critical points like wallet creation (as you pointed out), and funding checks

I think we could make this work.

We could get creative with "token dependency" information returned from asset backends that are in a position to know, and consumer like core could construct in an appropriate order.

**Comment by chappjc** [comment]
I think that was actually option 3 that you described. Haha.
But I still think that anything other than than wallet creation (and perhaps closing) should not require this dependency info.  Funding issues for instance I think is solvable entirely internally.

**Comment by martonp** [comment]
I actually started working on this a bit since I'm writing the contract for ERC20, and needed to write tests for it. I should've started a discussion on this earlier. 

What I was thinking to do was to have a singleton shared ETH node which is used by the ETH wallet and ERC20 wallets. There would be a shared `nodeclient` which provides all the functionality other than interacting with the swap contracts. Then, ERC20 and ETH wallets would both embed this shared `nodeclient` into their own `nodeclient`, and extend their own `nodeclient` with the specific functions needed to interact with the swap contracts. The locking code for ETH would be moved to the singleton `nodeclient` and the locking for individual tokens would just be in the token wallet.

In this way, core would not need to know anything about tokens. The reason that the ETH wallet and ERC20 wallets need to be tightly coupled is to share the node and the current state of locked ETH, but this can both be solved with a singleton `nodeclient`, and core would not need to be impacted at all.

I don't think core needs to be updated for wallet creation either. When passing a driver to `asset.Register` the Driver can just hold the assetID that would identify the token.

**Comment by chappjc** [comment]
> What I was thinking to do was to have a singleton shared ETH node which is used by the ETH wallet and ERC20 wallets. There would be a shared `nodeclient` which provides all the functionality other than interacting with the swap contracts. Then, ERC20 and ETH wallets would both embed this shared `nodeclient` into their own `nodeclient`, and extend their own `nodeclient` with the specific functions needed to interact with the swap contracts. The locking code for ETH would be moved to the singleton `nodeclient` and the locking for individual tokens would just be in the token wallet.

We agree that a shared node is a necessity.  A singleton isn't the only way to accomplish that, but it's probably simplest.  Having an ETH ExchangeWallet construct the token wallets accomplishes roughly the same thing but it wouldn't force a singleton.  The driver system can still hide the token distinction from core, but it would need tricks via WalletConfig to communicate which (globally-tracked) ETH wallet instance should be the parent.  But if we never need more than one ETH instance, a singleton would work and be simpler.

> In this way, core would not need to know anything about tokens. The reason that the ETH wallet and ERC20 wallets need to be tightly coupled is to share the node and the current state of locked ETH, but this can both be solved with a singleton `nodeclient`, and core would not need to be impacted at all.
> 
> I don't think core needs to be updated for wallet creation either. When passing a driver to `asset.Register` the Driver can just hold the assetID that identifies the token.

That's right, **if we make up unique asset IDs for the tokens**, because now recognized asset IDs are expected to be in https://github.com/satoshilabs/slips/blob/master/slip-0044.md, but they are not.  We can do as @buck54321 suggested and claim unused values and hope for no clashes in the future.

The asset ID is the main decision point, but I think the three of us agree it will be really messy and probably unnecessary to have separate token IDs.

**Comment by martonp** [comment]
> However, the child-parent nature of erc20s-eth does seem to be an issue for both wallet startup and shutdown. If core has configs for both USDT-erc20 and ETH, it must start ETH first and stop it last. How should we address that.

Why does there need to be a child-parent nature for erc20 and eth? I think they can both be considered users of the ETH node. The node can maintain a counter of its users and shutdown after all of them have disconnected.

**Comment by chappjc** [comment]
> Why does there need to be a child-parent nature for erc20 and eth? I think they can both be considered equal users of the ETH node.

Yeah, you're right.  For start up and shutdown that's alright.  This relationship exists only from a practical usability perspective because a realistic consumer is going to need the ETH wallet in order to deposit ETH to fund gas.
I see your point that it's possible to have just an ERC-20 wallet being the only consumer of an eth nodeclient, but you will need the ETH wallet to actually use your ERC-20 wallet.  I stand corrected that startup and shutdown order are not a concern though.

**Comment by martonp** [comment]
> Yeah, you're right. For start up and shutdown that's alright. This relationship exists only from a practical usability perspective because a realistic consumer is going to need the ETH wallet in order to deposit ETH to fund gas.

Maybe due to this core should have some understanding about tokens, if only just to be able to create the UI? Maybe it would be enough to just specify if another asset is used for network fees, and if so, which other asset it is.

**Comment by buck54321** [comment]
A singleton becomes problematic in testing.

With @chappjc's pattern, we leverage the child-parent relationship to make configuration easier, but at the cost of necessarily higher awareness of tokenism at higher levels. @martonp is likely right that the order of initialization can be worked around, but any pattern that will allow creating tokens before the underlying ETH wallet will have to ensure proper configuration across assets which could get messy for e.g. an RPC wallet implementation.

We will need **some** awareness of token-parent dependence at higher levels, but not much. It may be critical on the server for funding checks. On the client, we will want to display the ETH balance alongside the token balance. We could handle that with an asset-custom field for balance detail, but if we have other reasons to be token-aware in the front-end, we could handle that with custom handling for tokens too.

There are obviously trade-offs and some questions remain. My gut says that if we're certain we'll need token-awareness up to the UI level, we might as well use @chappjc's suggestion for architecture. But if we can get away without UI-level token awareness and figure out a singleton-free way to `Create` and `Open` wallets, we should try to conform to the current API.

**Comment by martonp** [comment]
> We will need **some** awareness of token-parent dependence at higher levels, but not much.

Yeah I agree, initially I was trying to make core completely unaware of tokens, but actually I guess there's no reason to do that.. tokens are a natural thing and it would make the design more awkward to completely ignore that.

If the node is not a singleton (belongs to the global state) and it belongs to something, the most natural is if it belongs to the ETH wallet, in which case the token wallets have to be aware of the ETH wallet. I can't really think of a way to make the token wallets aware of the ETH wallet if the reference is not passed through the  `Driver` methods.
