### ISSUE TITLE
dexcctl does not display prerelease and metadata build info

### ISSUE THREAD

**Issue by jrick** [decred/dcrdex#1378]
There appears to be no variables to change this using the linker either.

```
$ ./bin/openbsd-amd64/dexc -V    
dexc version 0.4.0-rc1+release (Go version go1.17.5 openbsd/amd64)
$ ./bin/openbsd-amd64/dexcctl -V 
dexcctl version 0.4.0 (Go version go1.17.5 openbsd/amd64)
```

**Comment by chappjc** [comment]
Do you want it the new way with a single version as in https://github.com/decred/dcrd/pull/2651 or will https://github.com/decred/dcrdex/pull/1379 suffice?
