### ISSUE TITLE
auth,storage: enforcing the cancellation threshold

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#138]
To penalize accounts that exceed the cancellation threshold, it is necessary to query the number of matched cancel orders created by a given account over N of their most recent orders.

The `AuthManager` handles account penalization, and there are two logical places where the `AuthManager` can be notified of executed cancellations:
1. Directly by `(*Market).processEpoch`, immediately after the Matcher unbooks the matched order from the book. Each `Market` has an `auth AuthManager` field that will facilitate this.
2. By `(*Swapper).Negotiate`, which is called by `(*Market).processEpoch` after all epoch matches are processed and coins are locked/unlocked.

I believe cancellation statistics should be updated as soon as possible after an order is removed from the books by a cancel order, hence (1) is my choice.  Further, processEpoch is a blocking call in the Market's epoch processing loop, so the penalization is more likely to into effect in a timely manner, although there are multiple markets.

Since cancellation statistics are DEX-wide (not per-market), the `AuthManager` must:
1. Keep a user's recent (last N=25) order history in memory (just the order type and ID), using a slice as a deque.  e.g. `map[account.AccountID]orderDeque` where `orderDeque` implements push/pop methods on an order slice.  Question: specifically what orders should be counted in this list? It should NOT include orders that "failed" in epoch processing because users could just create limit orders with TiF immediate and a rate that is certain not to match, thus easily padding their recent order history with non-cancel orders without having to preform any trades.  Hence only the `doneOK` output of `(*Matcher).Match` should be the orders to count in this list.
2. Querying the DB for recent order history when no in-memory history is available.

To directly communicate executed cancel orders to `AuthManager`, I suggest adding a `RecordCancel(user account.AccountID, oid order.OrderID)` method to the `AuthManager` (and the interface in the `market` package).  `(*AuthManager).RecordCancel` should update it's recent order deque for the user, and if the deque does not exist in the account map, query storage for the N latest relevant orders.

**Comment by buck54321** [comment]
> specifically what orders should be counted in this list?

I think the tally will be something like...

bad:  unbooked && remaining > 0
good: unbooked && remaining == 0
good: doneOK && (market || limit)

`AuthManager` will also need a `RecordSuccess` method. 

> Keep a user's recent (last N=25) order history in memory (just the order type and ID)

And the tally itself. One concern here is sorting. The tally can't be different if it's primed from the database vs built in memory over time. But what is the sort order for the last 25 orders. Based purely on timestamp? If so, will dealing with latency be a pain with a size-limited dequeue?

**Comment by chappjc** [comment]
> bad: unbooked && remaining > 0
> good: unbooked && remaining == 0
> good: doneOK && (market || limit)

I think we're looking at this a little differently.  The last one with doneOK is what I had in mind (although I implied market || limit), but I don't follow the the first two with unbooked.  The unbooked orders already counted as good when they originally went on the book.  An order becomes unbooked either through cancellation, in which case the cancel order itself would be bad in the list of N, or through being matched and filled, in which case the filled order was counted as good when it was booked.  Thus I don't think we need to "follow up" on booked orders to see how they made it off the book.

> One concern here is sorting.

Yah, that's a drag.  So much for a queue.  This'll take some care to do right and fairly.  But yes, the DB query that I had in mind would build the list in order by servertime.  The inherent possibility of a race in different Market's epoch queues also complicates this (if we count a cancel order from market A, tally and penalize, then 0.1 seconds later an order with an older server time comes in from market B with a slow/massive queue...).  Seems like processing will need to be done with a significant time lag to avoid that issue, which makes the list even more difficult to manage.  Gonna give this more though...
