### ISSUE TITLE
eth: Funding coin encoding.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1389]
Server wants the funding coin for account based wallets to be the utf-8 encoding of the address
https://github.com/decred/dcrdex/blob/986c765be89df6e45cae5ef538675b2700c7f7a9/dex/order/order.go#L483-L485

However the eth client still uses a funding coin which is the address bytes (not hex) and an amount
https://github.com/decred/dcrdex/blob/986c765be89df6e45cae5ef538675b2700c7f7a9/client/asset/eth/eth.go#L506

And it looks to currently need to have an amount encoded in order to unlock coins later.

I think there was discussion about this but I'm sure what resolution was decided. I don't think there is currently an issue or pr concerning this.

Maybe just send what the server expects?

**Comment by JoeGruffins** [comment]
The server also wants a signature of the entire funding message rather than just the coin id like it's getting. Which makes sense because it needs different data every time. One could reuse a signature of the address. I guess a few things need to change in this area.

**Comment by martonp** [comment]
I was about to post an issue regarding this as well. I was trying do a swap with ETH on the simnet and got an error due to this. The coin id stored in the db will have to be different than the coin id sent to the server. Are you working on a fix?

**Comment by JoeGruffins** [comment]
I was but wanted to make sure someone else wasn't and that we are sticking with the utf8 encoded address. I'll try to get something up today.

**Comment by martonp** [comment]
I think utf8 encoded address is fine, just needs to be converted in the `ValidateSignature` function.

**Comment by martonp** [comment]
https://github.com/decred/dcrdex/blob/986c765be89df6e45cae5ef538675b2700c7f7a9/client/core/core.go#L3950

Btw, the address over here won't be utf-8 encoded.

**Comment by martonp** [comment]
`AccountBalance` has the same issue.

**Comment by JoeGruffins** [comment]
Will build off of #1314 since that seems ready.

**Comment by JoeGruffins** [comment]
Well  #1392 but I think it would be better to leave the coins alone. Or let the server assets decode the coinid as you suggest (right?), but then we wouldn't need to make it a utf8 encoded address at all.

> Btw, the address over here won't be utf-8 encoded.

I think this is fine though, it's already a string. The funding address is the problem.

**Comment by JoeGruffins** [comment]
solved by #1392
