### ISSUE TITLE
testing: Init dexc from seed.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1393]
With external wallets we are able to send coins preemptively to simnet wallets that we later connect to and use during simnet testing.

The same can be done by using a predetermined seed with internal wallets. Specifically for eth, I propose we start the simnet testing app with a certain seed and send funds to whatever the wallet's address will be in the eth harness in order to always have funds for testing.

**Comment by JoeGruffins** [comment]
I should mention that I am talking about the `simnet-setup.sh` script.

**Comment by martonp** [comment]
I agree with this.
