### ISSUE TITLE
app: deposited funds often do not show up without refresh/reload

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1396]
In the setup and registration dialogs, it has been reported that when one sends funds to the displayed deposit address, the checkbox does not ever get checked even when the funding txn gets many confirms.

![image](https://user-images.githubusercontent.com/9373513/148611356-92e95712-6d08-47f9-9252-103295126677.png)

I have observed this myself, so there must be something off here.

**Comment by martonp** [comment]
I'll take a look.

**Comment by martonp** [comment]
Main issue is that this is <= instead of <
https://github.com/decred/dcrdex/blob/e05191aa482b92293b035ed1c3016b6b8bc8d1fd/client/webserver/site/src/js/forms.js#L656

There still seems to be a few other issues with this form I'm looking into though.

**Comment by martonp** [comment]
This should probably also check if there is enough for the tx fee as well.

**Comment by chappjc** [comment]
> This should probably also check if there is enough for the tx fee as well.

On that note, the form should suggest sending more, like the dex.decred.org landing page says:

>  Make a deposit to your Decred wallet of at least 0.1001 DCR to cover the current registration fee plus network transaction fees

the form could show something below the deposit address like "(send about 0.1001 DCR here to also cover network fees)"

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/1417.  Related work in https://github.com/decred/dcrdex/pull/1419
