### ISSUE TITLE
intl: deal with sellString

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1412]
https://github.com/decred/dcrdex/blob/e1218a26c8c91abe77ef9a6cf92f801db1399183/client/core/trade.go#L2544-L2549

When dealing with the `core` `sellString`, we should avoid using the string in translation subject templates that do `%sing` where "selling"/"buying" conjugations are needed because that's not workable for most languages.

https://github.com/decred/dcrdex/blob/17a96d1024895224dce835dc9db5e802f9ba1ba5/client/webserver/site/src/js/orderutil.js#L39

**Comment by buck54321** [comment]
Related: #1179
