### ISSUE TITLE
Lite book subscriptions

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#142]
From conversation on chat.decred.org

> ...it'd probably be good if there was a "read-only" order book feed too that didn't even include order IDs, at least not 64-character order IDs. No commitments, no match_proof notification. Bare minimum.

The vast majority of bandwidth for order book feeds will be eaten by order IDs, commitments, `match_proof` notification, and other information not necessary to simply watch the order book. As @chappjc pointed out in regards to client-side validation

> a client without an order in a given epoch is unlikely to care [about validating]

Lite subscribers could be differentiated from validating subscribers, and the order book router can send appropriate messaging for each.

**Comment by vctt94** [comment]
This still an issue?
