### ISSUE TITLE
eth lacks proper unitinfo

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1428]
If you have an eth configured, you get an error when clicking the exchange to add

https://github.com/decred/dcrdex/blob/e42db6eeebf4a462ff84f567cbe6315eed1f90aa/client/webserver/site/src/js/forms.js#L476

```
 Uncaught (in promise) TypeError: can't access property "conventional", e is null
    r forms.js:476
    o forms.js:487
    i forms.js:536
    value forms.js:517
    e register.js:53
    Ut entry.js:1
    a entry.js:1
    zt entry.js:1
    zt entry.js:1
    dexAddrForm register.js:49
    n forms.js:888
    wt entry.js:1
```

How did you get past this @JoeGruffins ?

Note that I created the wallets first, then went back to /register to click this

**Comment by chappjc** [comment]
Ahhh, this is when server reports eth, but client does not support it.  I think this is a general bug with client requiring support for every asset that server supports.

**Comment by buck54321** [comment]
I saw this too. It's confusing. Why isn't it falling back to the server's `UnitInfo`?

**Comment by buck54321** [comment]
I can take a look now if you aren't.

**Comment by chappjc** [comment]
Thank you for looking

**Comment by chappjc** [comment]
I think it would be a similar issue if server gave an LTC asset, but client wasn't compiled with LTC imported.
