### ISSUE TITLE
app: login spinner needs accompanying text

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1434]
This is not an error, but it can do this much longer now because it's starting up the built-in wallets.  Even though this isn't syncing the wallets, it can still take time to fire things up.

![image](https://user-images.githubusercontent.com/9373513/150548277-d574f4d3-4c76-4554-8f74-3c234aaebdf4.png)

Also if auth or some other network request times out, this can take a long time. Users may be tempted to kill dexc.

There should be some kind of information here to communicate what is going on at this point and to wait up to a minute or so if there are built-in wallets.

**Comment by buck54321** [comment]
If we're fairly certain that the vast majority of `Login` time is spend [here](https://github.com/decred/dcrdex/blob/8aaed770948b56c650380e73f6e2ba6328c9b873/client/core/core.go#L3288-L3308), 
then I'd say we do a constant message set by Javascript as an optional argument to `Application.loading`.

If, on the other hand, we think that the `resolveActiveTrades` and `initializeDEXConnections` steps are going to take significant times, then maybe we should add a new `core.Notification` called maybe `LoginStatusNote` and the status text can come from `Core`.

**Comment by chappjc** [comment]
Not too long ago I would have said it's definitely the wallet loop there, but I've noticed serious delays initializing dex connections since testing dex servers at .onion addresses.

I think some `LoginStatusNote`s would be very cool.  Just like when you fire up certain roku apps and it give some goofy status updates like
"Prepping rocket boosters..." <scrolls to next message>
"Calibrating subspace warp drive..."

(only not with the goofy stuff)

**Comment by ukane-philemon** [comment]
Since we could still spend time somewhere here https://github.com/decred/dcrdex/blob/master/client/core/core.go#L4290-#L4304 for first-time login, Are we opting for a `LoginStatusNote` or we just stick to a constant message?

**Comment by chappjc** [comment]
Shouldn't be too messy to have three notes prior to each of those operations in that branch.  I think it would improve UX a great deal to have some feedback at this stage

**Comment by ukane-philemon** [comment]
Alright, I will look into this.
