### ISSUE TITLE
need for constant node/wallet connectivity checks

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1435]
During wallet sync after connect (or rescan as planned), there is a wallet sync status goroutine, but during normal operation there is nothing to check:
- connectivity with the wallet (aside from the best block tickers), resulting in some kind of one-time ntfn
- connectivity of the node/wallet with the p2p network, such as checking number of peers in the ticker loop, also resulting in some kind of one-time ntfn

**Comment by martonp** [comment]
So maybe do this less frequently than the best block checks, once every 10 seconds, and then send notifications on changes to sync status? Would it be enough for the pre-order (#1436) check to only be done if the latest status from the wallet was "not connected", but if it was connected then just trust it? In this way it wouldn't matter if multiple orders are placed quickly.

**Comment by chappjc** [comment]
I'm looking at this now, but one thing about sync status is that it can't block anything on its own because there will often be moments where we're just one (or maybe two, or maybe several with ETH) blocks behind as new blocks is being processed.  In certain situations like connect and rescan, I think that we do want to get to 100%, but a wallet health indicator during normal operation should be more permissive.
