### ISSUE TITLE
similar to Rescan, need a way to Recreate a wallet for recovery

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1438]
There are a myriad of ways the native btcwallet and/or it's chain service files may become corrupted, necessitating one or more of the manual recovery steps described on https://github.com/decred/dcrdex/wiki/Native-BTC-Wallet-Recovery-and-Rescanning

I was able to corrupt neutrino and prevent it from ever starting again by killing dexc hard a few times.  In my case `neutrino.NewChainService` was returning an EOF error, which through debugging I traced from `newBlockManager` > `cfg.BlockHeaders.ChainTip()` > `(*blockHeaderStore).readHeader` > `h.readRaw(seekDistance)`.  Almost none of the errors from the neutrino constructors supplement the error with any details about what caused the error, so this is nearly impossible for an end user to debug even with the help of a developer.  In such cases, you just need to toast the neutrino data files (and wallet.db) with dexc stopped, start again, and resubmit the wallet config to force it to reinitialize.  We should smooth out this "recreate" process.

**Comment by martonp** [comment]
I'll do this one.
