### ISSUE TITLE
ui: remove or fix password prompt for app-unlocked users

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1441]
If the user has selected the option to "remember my password" (app-unlocked), when they attempt to unlock a wallet via the icon on the markets page balance widget, we don't need to display a button to click. We can just unlock. The only problem is that errors are displayed on the form, so for app-unlocked users, we'll need a new place to show errors. We could fall back to the notification icon, or only display the empty form with error message once an error is received. 

**A more immediate concern** though is that the form close button is not styled correctly, as per @jholdstock 

![image](https://user-images.githubusercontent.com/6109680/150678384-438685e5-c042-4f36-b319-d556409cd1a3.png)

**Comment by jholdstock** [comment]
I actually think keeping the extra prompt is a good idea.

1. It isn't totally obvious that clicking on the padlock will unlock the wallet, so informing the user and giving them a chance to cancel is fair.
2. Given that clicking on the unlocked padlock icon does not re-lock the wallet, a confirmation prompt before unlocking is reasonable.
3. Displaying errors in a single place is likely simpler to implement and maintain.

**Comment by ukane-philemon** [comment]
> A more immediate concern though is that the form close button is not styled correctly, as per @jholdstock

This has been fixed in [2fd8f3a](https://github.com/decred/dcrdex/pull/1487/commits/2fd8f3a11a28a22a448cdf2d99b23aaa2493a897)

Is this still an issue?
