### ISSUE TITLE
core,db: need methods to clean/delete old orders and matches, purging them from the db

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1448]
Perhaps optionally based on age.
Will likely need to be deleting keys/buckets in batches other wise the bolt txn will get too big and oom dex.

**Comment by JoeGruffins** [comment]
Is the reason for deleting the data just to keep database size small? Also I can do this.

**Comment by chappjc** [comment]
Yes, because the DB just grows and old order data may have no value to the user.  As such I would say this should be a Core method rather than automatic.  I can even see a cmd/purgedb app that lets you do this as an offline maintenance task.

**Comment by chappjc** [comment]
Something else to think about is archiving the data before it is purged from the active client DB.  The CSV export may or may not have sufficient detail (all the txn details for all matches), but some alternate format could work.  Another DB file of some kind that the user could "zip up" and move could also be alright but it's harder to read it later, needing a custom app to request human-readable data from it.
Open to ideas.

**Comment by chappjc** [comment]
I'm going to address server-side postgresql data archival.

**Comment by JoeGruffins** [comment]
Could it be a core method but accessible through rpc?

I would think the easiest solution to restoring old orders would be to just save the original db, which they could swap back later. If we don't want to make a UI component, this wouldn't be something for normal users I guess, so touching files should be ok for the intended power users?

**Comment by chappjc** [comment]
> Could it be a core method but accessible through rpc?

Sure.

> I would think the easiest solution to restoring old orders would be to just save the original db, which they could swap back later. If we don't want to make a UI component, this wouldn't be something for normal users I guess, so touching files should be ok for the intended power users?

"swap back" to dexc is a little to last resort, not the ideal approach to this.  I'm thinking no UI component, just an artifact that is accessible either as a basic format like CSV or a cli app to read a basic orders-matches.db.  Something along those lines.  It's just an archival, so whatever allows history to be inspected, fine.

**Comment by JoeGruffins** [comment]
So, perhaps optionally, save deleted order and matches to csv?

**Comment by chappjc** [comment]
A Core method that does just that for the full match/tx details would be sufficient.  The info would be readily available, and the active dexc.db could be reduced.
