### ISSUE TITLE
web: `e.zoomOutBttn is undefined` causing long hang.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1450]
As shown here, on master (ecc1f79), sometimes I get a long hang from this js error.

![image](https://user-images.githubusercontent.com/34998433/151095152-4f15f514-fbd3-4833-8b79-074f50238b5d.png)

```
Uncaught TypeError: e.zoomOutBttn is undefined
    value charts.js:492
    value charts.js:1020
    value charts.js:457
    value charts.js:88
    value charts.js:332
    value markets.js:884
    value markets.js:1077
    P markets.js:184
    pr ws.js:37
    onmessage ws.js:101
```

**Comment by chappjc** [comment]
👍 have seen it too

**Comment by JoeGruffins** [comment]
Will try to solve this as it happens to me a lot and is super annoying.

**Comment by chappjc** [comment]
Yes please
