### ISSUE TITLE
cannot run core test without lgpl

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1477]
core_test.go imports `dexeth "decred.org/dcrdex/dex/networks/eth"`, apparently just for `dexeth.InitGas`, although afaict this can just be some random but reasonable integer.  It's undesirable to have to specify `-tags lgpl` just to run the `core` unit tests.

Plus, I feel like core tests should ideally not require any of the networks or assets packages.  It requires some client/asset packages to get their drivers registered to power `coinIDString`, but the unit test can easily register fake drivers for this purpose, which we have done elsewhere even in core_test.go (see `tDriver` and calls to `asset.Register`).

**Comment by JoeGruffins** [comment]
Will solve this.
