### ISSUE TITLE
{dex/ws, server/market}: alternative send method for notifications

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1478]
The `func (*WSLink) Send(msg *msgjson.Message) error` method JSON-encodes the passed `Message`. For notifications, that's not great, because the same notification is being sent to possibly many users, such as in `(*BookRouter).sendNote`.

https://github.com/decred/dcrdex/blob/0c75bd4ef78a0cde38eb558dd20b1ffe2a655683/server/market/bookrouter.go#L708-L709

We should offer a `SendRaw([]byte) error` alternative to avoid repeated encoding.

**Comment by chappjc** [comment]
It's a great idea.

**Comment by JoeGruffins** [comment]
I would like to add `SendRaw([ ]byte) error`.
