### ISSUE TITLE
Make ui error messages more oriented towards users

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1488]
The error messages on the UI are just the error strings that are returned from functions in the code. These should be logged, but on the UI we should display just "Incorrect Password" instead of "error unlocking btc wallet: ReconfigureWallet password error: outer key deserialization error: incorrect password".

**Comment by chappjc** [comment]
Sometimes the innermost error is the most helpful, sometimes not.

As stated in this issue, the full error with context from every level of the call stack is too overwhelming.

So what's the solution?  No vague suggestions please.

**Comment by ukane-philemon** [comment]
Maybe it's time for [chappjc's initial suggestion](https://github.com/decred/dcrdex/pull/1511#issuecomment-1068562203)?

**Comment by chappjc** [comment]
Maybe something along these lines: https://github.com/decred/dcrdex/commit/4453e5d3cca8a0c2df46951f741126c62c6b38d3

Gives the api `standardResponse` some optional fields where the message can be broken down by the backend if necessary.
Tweaks the `dex.Error` type with a method to get the `string` field, which we'd use as the high level user-facing description.
Then we can still have the codes from core.Error, the innermost error with `core.UnwrapErr`, and the full error.  `writeAPIError` breaks them up if they are distinct.

The `dex.Error` type feels a little backwards in this use though.  It was originally intended to wrap a `dex.ErrorKind`, which provides the highest level description, with a details string for the um, details.  This uses it in the opposite way: the string provides the high level description for the user and the wrapped error contains the full error from the call stack.

**Comment by ukane-philemon** [comment]
> Maybe something along these lines: [4453e5d](https://github.com/decred/dcrdex/commit/4453e5d3cca8a0c2df46951f741126c62c6b38d3)
> 
> Gives the api `standardResponse` some optional fields where the message can be broken down by the backend if necessary. Frontend can recognize when the various fields are set, but `msg` is always there, just with `root` and `full` potentially containing the fully-unwrapped and entire errors, respectively. Tweaks the `dex.Error` type with a method to get the `string` field, which we'd use as the high level user-facing description. Then we can still have the codes from core.Error, the innermost error with `core.UnwrapErr`, and the full error. `writeAPIError` breaks them up if they are distinct.
> 
> The `dex.Error` type feels a little backwards in this use though. It was originally intended to wrap a `dex.ErrorKind`, which provides the highest level description, with a details string for the um, details. This uses it in the opposite way: the string provides the high level description for the user and the wrapped error contains the full error from the call stack.

Nice suggestion chappjc, maybe we can leave `full` error for the logs. We might only need the `msg` which is a high level error detail and the `root` error. This can make it possible to translate high level error detail(maybe in the frontend or in core).

We would end up with errors like: `high level error detail(if any, and might have a translation): root error(no translation)`, 
eg. `error unlocking btc wallet: incorrect password`, 
`seed phrase can't be decoded: invalid byte: U+006B 'k' `.

**Comment by chappjc** [comment]
Thinking about a `dex.FriendlyError` that is just like `dex.Error`, but a distinct type, so that a `FriendlyError` can be created with a "friendly message" at any level of the call stack.

At the api handler level, it can unwrap a _slice_ of friendly errors, which it can either join or choose to show incrementally upon, say, click for additional details from the user on the frontend.  Ultimately the full error with all the gory details could be shown if needed (no friendly errors or they click to get the full error).

For translations, these `FriendlyErrors` can be created with an `IntErrString` that indicates it should have a translation.  It's a slight burden to define these `IntErrString`s somewhere other than where you are writing code, but it would at least move toward solving both error translations as well as the general issue described in this thread.

**Comment by LasTshaMAN** [comment]
The solution outlined above looks nice!

I have a question/comment about `root`: what the use case for it ? It seems when  `FriendlyError` isn't enough to figure out what's wrong, one would go for full stack trace (because half the times just the root cause will probably not be sufficient)
