### ISSUE TITLE
client: all state, including locked funds, are lost upon reconfiguring wallet.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1492]
When our wallet is in control of tracking locked funds, they are lost on re-configuring the wallet. To reproduce, make an order selling eth or btc, then go to wallet options and save. The funds will be unlocked. Attempting to use the funds afterwards will result in an error from the server's coin locker.

Before:
![image](https://user-images.githubusercontent.com/34998433/155936173-4fa82dff-2856-4f26-b2c5-9b3188884ef6.png)

After:
![image](https://user-images.githubusercontent.com/34998433/155936260-6341b12b-f731-4f7b-8847-c561b220e965.png)

**Comment by chappjc** [comment]
I'm gonna prototype some methods as described in my last comment, but it would be great if this issue had proposed resolutions for multiple people, with reference to each of the wallet types (dcr full, dcr spv, btc full, btc spv, eth light)

**Comment by chappjc** [comment]
I wanted to get to this, but got swamped.  Fair game for all

**Comment by buck54321** [comment]
I'm gonna take a swing at this.

**Comment by chappjc** [comment]
Mostly resolved by `(*Core).reReserveFunding` added in https://github.com/decred/dcrdex/pull/1686.
Live reconfig support can be added for the other assets, but I think this issue is closed because it refers to the state loss that is resolved for all assets.
