### ISSUE TITLE
UI: Unable to click prices over 1,000.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1494]
Undoubtedly the comma again. Unable to select prices in the graph over 1000 and have the automatically inserted into the form. Price is set to zero.

All clicks in this red area insert 0.
![image](https://user-images.githubusercontent.com/34998433/155941571-81265b82-6f0e-4719-8d8e-80cfd91b66e8.png)

**Comment by bgptr** [comment]
On this
