### ISSUE TITLE
swap: tx wait expiration should be configurable

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#150]
txWaitExpiration is hard coded in swap.go:

// txWaitExpiration is the longest the Swapper will wait for a coin waiter.
// This could be thought of as the maximum allowable backend latency.

This needs to be an operator setting.  Discussion:
https://github.com/decred/dcrdex/pull/140/files#r370346846

**Comment by ukane-philemon** [comment]
@chappjc, is this still an issue? I can work on it.
