### ISSUE TITLE
btc wallet sync: inconsistent sync status

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrdex#1514]
Steps to reproduce: 
  1. start dexc with a new BTC SPV wallet.
  2. Assuming dcr wallet is all set and reg fee paid. Go markets page and attempt to sell dcr for btc, you get a `btc still syncing. progress=0.XX%` error e.g `0.72%`
  3. While on the wallets page, hover on sync status icon, you get `XX.x%` e.g `72.3%`.
  
  Hard to tell which is the correct sync status
![btcsyncing](https://user-images.githubusercontent.com/57448127/158154141-83e07e8d-da4c-4dec-88f5-00e11a4d608b.PNG)
.

**Comment by chappjc** [comment]
I think the one that is shown on the order form just needs to be multiplied by 100?

**Comment by ukane-philemon** [comment]
Thanks for your feedback.
