### ISSUE TITLE
Network-versioned server database names

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#152]
The DEX supports three named networks, **mainnet**, **testnet**, and **simnet**. The server has a configuration option, `pgdbname`, to indicate the name of the database to use. Unfortunately, that same name will be used regardless of network, so if the default name is used, all networks will use the same database. 

The dcrdata scheme has a small replacement tag, `{netname}`, that the operator can put into the database name and which will subsequently be replaced by a string specific to the network. In this scheme, a default value of **dcrdex_{netname}** is parsed as one of **dcrdex_mainnet**, **dcrdex_testnet**, or **dcrdex_simnet**. 

@chappjc may have other ideas here as well.

**Comment by chappjc** [comment]
I'm fine with doing the same in dcrdex.  I'll port it over.
