### ISSUE TITLE
ui: misshapen dex search text box

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1527]
![image](https://user-images.githubusercontent.com/9373513/158835736-aa395ae0-ed06-4ec9-a040-3ce2694329aa.png)

The search box is misshapen as you can see above.

_Originally posted by @chappjc in https://github.com/decred/dcrdex/issues/1522#issuecomment-1070987682_

**Comment by ukane-philemon** [comment]
@chappjc, have you seen this recently? I've never seen this happen.

**Comment by chappjc** [comment]
It's always that way, but only Firefox:

![image](https://user-images.githubusercontent.com/9373513/178056305-3286dc3c-3236-484e-a2ea-49196ecbb371.png)

Chromium:

![image](https://user-images.githubusercontent.com/9373513/178056335-8dd2fb45-a2f7-4f2e-983c-4e8fecc8302c.png)

**Comment by chappjc** [comment]
https://user-images.githubusercontent.com/9373513/178057092-0d0dbc52-fe44-47d3-b889-d9c9223c1002.mp4

**Comment by ukane-philemon** [comment]
Alright, I don't use firefox at the moment but will try to look into this.

**Comment by chappjc** [comment]
Here's an issue you can see in Chromium and Firefox:

https://user-images.githubusercontent.com/9373513/178064924-ef21bbc3-355d-46d5-ba7a-9a3f40bccf40.mp4

https://user-images.githubusercontent.com/9373513/178064926-1725ea16-0230-48db-ac02-a6b55dba4b8d.mp4

This issue is clearly related to the other - the `input` does not correctly fill out the parent `div`.

**Comment by ukane-philemon** [comment]
Just installed Firefox to investigate.
