### ISSUE TITLE
server/dcr: Preemptively check for --txindex.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1535]
Recently, I set up a testnet server and forgot to run dcrd with the `--txindex` flag. The server asset started up fine and there was no problem until a user tried to pay the registration fee. This caused the error: `[WRN] AUTH: Unexpected error checking fee coin confirmations: -32603: The transaction index must be enabled to query the blockchain (specify --txindex)`

If possible, it would be better to error at start-up when transaction indexing is not enabled to avoid problems after the server has already been started.

The `getinfo` rpc command does provide a way to check:
```
$ dcrctl getinfo
{
  "version": 1080000,
  "protocolversion": 8,
  "blocks": 889610,
  "timeoffset": -1,
  "connections": 8,
  "proxy": "",
  "difficulty": 31.33877036,
  "testnet": true,
  "relayfee": 0.0001,
  "errors": "",
  "addrindex": false,
  "txindex": true
}
```

**Comment by chappjc** [comment]
Similarly, bitcoind has `getindexinfo` we could use
