### ISSUE TITLE
client/eth: 12600000 > 0 redemption funds reserved error.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1539]
I apologize if this is already an issue. I feel like we have had several issues/pr about this, but when trading on simnet or testnet, I still see `[ERR] CORE: retiring order 0d52237b5b799d416c78d35543ce3ef05c4a7fa118be701f2cd4600d8c23cc4d with 12600000 > 0 redemption funds reserved` If this is expected, we should not log as error. If not expected should fix.

To reproduce make a 1lot trade for dcr/eth and watch it to the end.

**Comment by JoeGruffins** [comment]
Guess I will look into this, unless @martonp would like to?

**Comment by martonp** [comment]
I'm just wrapping up something else, I was going to check after that. If you have nothing else you'd rather do then go for it, otherwise I can do it.

**Comment by JoeGruffins** [comment]
I'll lightly look into it... If not a pr in the next few hours I gave up.
