### ISSUE TITLE
-100% rate change

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1540]
![image](https://user-images.githubusercontent.com/9373513/159499340-861d5c93-951c-4a04-881f-184da895fba5.png)

It's transient though.  A few minutes later:

![image](https://user-images.githubusercontent.com/9373513/159500063-34570648-0dde-40a1-9dca-8da930d441a3.png)

Because it's based on the 5 min cache?
https://github.com/decred/dcrdex/blob/24b2038b75158e224da3e0d3f7e1a4b0f7df47c9/server/apidata/apidata.go#L143

**Comment by JoeGruffins** [comment]
Also seen in #1604

**Comment by JoeGruffins** [comment]
Related to #1746 ?

**Comment by chappjc** [comment]
Resolved in https://github.com/decred/dcrdex/pull/1746, I believe.  I haven't seen this on 0.5
