### ISSUE TITLE
client/eth: attempting to unlock more than is reserved

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1544]
A random error testing on testnet. No idea currently what caused it. Full error is `2022-03-23 03:24:19.993 [ERR] CORE: attempting to unlock more than is reserved for order bea4ab86d2fb6d7585276cb1d10bbd04afdceb9e930c210d231b29b13c718fef. unlocking reserved amount instead: 0 reserved, unlocking 8600000`. Here are the client logs in that area. I can also provide server logs if needed.

https://pastebin.com/DCA6zSy3

**Comment by JoeGruffins** [comment]
Looking into it.

**Comment by JoeGruffins** [comment]
Can `t.findMakersRedemption` happen after a `t.processMakersRedemption`?

**Comment by JoeGruffins** [comment]
Working on top of #1556 I see in core logs:
```
2022-04-04 07:25:04.752 [ERR] CORE: attempting to unlock more than is reserved for order fe6721132602847d649a07db09cac62735540ebe73f106efe6144334100ffecf. unlocking reserved amount instead: 0 reserved, unlocking 8600000
```
BUT, pretty sure this to wallet is DCR. 
![image](https://user-images.githubusercontent.com/34998433/161529082-0878d024-a510-4e99-8449-30fb6832f0e0.png)

Not sure if the `t.accountRedeemer()` is sending a wrong signal somewhere. Still looks pretty random, as I have a trade directly after that looks the same but does not try to unlock coins here.

**Comment by chappjc** [comment]
There would be reserves for an ETH **refunds** when buying DCR with ETH, so this error is probably coming via `unlockRefundFraction`.

**Comment by chappjc** [comment]
One thing that looks suspect is in `(*trackedTrade).revoke` we have `t.unlockRefundFraction(t.Trade().Remaining(), t.Trade().Quantity)`.  But revoking the trade does not mean you don't still have to refund or even redeem active matches.

**Comment by JoeGruffins** [comment]
I think I've found where this is happening. Will hopefully have a pr up tomorrow.

**Comment by chappjc** [comment]
Reopening as per findings reported in https://github.com/decred/dcrdex/pull/1721#issuecomment-1191042640

If it can be hit with loadbot on `master` (the compound program, @JoeGruffins?), we should be able to get to the bottom of it, and I can clean up https://github.com/decred/dcrdex/pull/1653 to see if it will resolve the issue without making more.

**Comment by JoeGruffins** [comment]
> the compound program

Yes.
