### ISSUE TITLE
docs: How to get regXPub for btc.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1557]
In order for the server operator to accept fees in btc they need an xpub for the markets json. Howerver, it seems you cannot get an xpub for your wallet with bitcoind for a couple years? https://bitcoin.stackexchange.com/questions/90135/how-do-i-export-an-xpub-from-bitcoin-core-for-use-in-btcpayserver

What is the recommended method for getting an xpriv\xpub pair? Then what do do with it? It looks like you cannot import an xpriv into bitcoin core either.

I guess it's possible, and we could suggest using btcd? This info could be in the docs somewhere.

**Comment by chappjc** [comment]
Right bitcoin core can't and won't make that possible.  The options I've verified are Electrum and Exodus (maybe Samurai too, I forget), and a modification to btcwallet because btcwallet does not even have a `getmasterpubkey` like dcrwallet does.  https://github.com/decred/dcrdex/pull/1285

**Comment by JoeGruffins** [comment]
I guess this will no longer be needed with bonds.

**Comment by JoeGruffins** [comment]
I believe no longer needed with bonds.
