### ISSUE TITLE
Should we write a market maker bot?

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1560]
One reason people are hesitant to run markets is because there is no way to bootstrap liquidity. Should we offer a market maker bot? 

I'm not familiar with the setup or algorithms, but there's gotta be some expertise around here to draw on.

**Comment by chappjc** [comment]
Reasonable.  I think some concept code used in testing can be adapted easily.  Let's chat offline about timeline and if/how it fits in p3.

**Comment by martonp** [comment]
This might be one of the most crucial things to do.

**Comment by chappjc** [comment]
Issue superseded by https://github.com/decred/dcrdex/issues/1970
