### ISSUE TITLE
Fix races

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdex#157]
#156

**Comment by chappjc** [comment]
Numerous races are fixed in PR #145 .  Would you verify with that?

**Comment by chappjc** [comment]
Listing races to resolve:

- client/asset/dcr
  - decred.org/dcrdex/client/asset/dcr.(*ExchangeWallet).monitorBlocks()
      client/asset/dcr/dcr.go:1195 +0x61
  - decred.org/dcrdex/client/asset/dcr.tNewWallet()
      dcrdex/client/asset/dcr/dcr_test.go:112 +0x328
