### ISSUE TITLE
client,eth: need to babysit refund and redeem transactions

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1573]
@JoeGruffins has suggested previously (I cannot find the link) that we should babysit the ETH redeems and refunds until confirmation, which is not something we've felt the need to do with utxo coins (aside from categorizing these values as "immature" until they are mined).

The ability to completely squash one tx with another with the same nonce, and quite by accident, is all to easy.

May affect client/asset/eth and client/core.

**Comment by buck54321** [comment]
Related disucssion [here](https://matrix.to/#/!VzelzRZLBmoxbmvZWK:decred.org/$LlU_Z1Um9HHRg2EaEZTIc4OeUSpxg6exVzSEV-15pGo?via=decred.org).

My suggestion is 

1. Add a new status `MatchConfirmed = MatchComplete + 1`.
2. Add a new `asset.Wallet` method `ComfirmMatch(coinID []byte) bool` or similar, where the coinID in this case is the `out.ID()` for the `out Coin` return value from `(Wallet).Redeem`.
3. Plumb it through `db.MatchIsActive` and add logic around `tick`.
4. Probably a bunch of little stuff I'm missing, like a `DB` method or new coin ID encodings?

**Comment by martonp** [comment]
I'll work on this if no one else is.
