### ISSUE TITLE
client/core: fiat conversions

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1579]
It'd be nice to display fiat conversions next to values in some places.

- Next to their balance on the wallets page. 
- Order quantity on order confirmation form
- Withdraw form

Ideally, we'd have busy stablecoin markets and we could do this without oracles. But in the meantime, we could grab the prices through available public APIs. For Decred and Bitcoin, we can use [dcrdata](https://explorer.dcrdata.org/api/exchangerate), which already does a weighted average of markets. For others though, we'll need to find new endpoint.

#### Design considerations

Public APIs will have rate limits and API calls will incur significant delays. We'll need to keep cached values and only update the cache periodically. 

On the front-end, we'll need to be flexible, only showing fiat conversion when they're available.

~~We **could** implement through the `asset.Wallet`s as an optional `interface`~~ (nah, we should use **core**, see below), e.g.

```Go
type PriceFetcher interface {
    FetchPrice(ctx context.Context) (uint64, error)
}
```

We would have to define a canonical fiat unit, almost certainly USD, and wallets will return values in `USD/XYZ`. Or maybe `FetchPrice` should take a `fiat string` argument. 

I could also be a mostly **core**-level system, which makes more sense if we only rely on one or two APIs for the prices.

#### Where do we get data for other coins?

We **could** try to calculate it ourselves. For example, if we know the fiat exchange rate of BTC and DCR, then we can **kind of** know the exchange rate for any assets that share any markets with those, via a conversion using the mid-gap rate. For example, if we have a BTC-ETH market, then we can get an approximation for ETH by taking `ethPriceUSD = btcPriceUSD / midGap`. It won't be the best price, especially if the market is dead. And attempting to chain that logic by, say, figuring the `BCH` price from our `ETH-BCH` using the aforementioned ETH price would potentially chain and magnify the "error".

I've used [coinpaprika](https://api.coinpaprika.com/) before, and as long as you meter your requests, it seems pretty solid.
It looks like [messari.io](https://messari.io/api/docs) has a non-authenticated API that allows up to 20 requests per minute.

**Comment by ukane-philemon** [comment]
Interesting, would love to work on this.
> Order quantity on order confirmation form

won't this affect trading decision?

**Comment by buck54321** [comment]
> Where do we get data for other coins?

I linked two sources, coinpaprika and messari. Neither require api keys or authentication as long as the client request rates are sufficiently low. 

> > Order quantity on order confirmation form
> 
> won't this affect trading decision?

Can you explain what you mean when you say "affect trading decision"?

**Comment by buck54321** [comment]
If you want to work on this, please discuss here first.

**Comment by ukane-philemon** [comment]
> Can you explain what you mean when you say "affect trading decision"?

Coin value after conversion to Fiat would not be using the "real time price". 

A seller might want to sell x coin valued at $500 with cached conversion rate, while in real time it could be $400, does it in anyway affect if user makes that sale?

**Comment by ukane-philemon** [comment]
> If you want to work on this, please discuss here first. How would you implement this?

Yes, I would like to work on this. Implementing this would be straight forward as I would reference dcrdata's exchange bot.

> I linked two sources, coinpaprika and messari. Neither require api keys or authentication as long as the client request rates are sufficiently low.

You've mentioned two source, just want to be sure of which one we are using for other coins. Or both?

**Comment by buck54321** [comment]
I think this is going to be challenging. 

Just some things that are required for a complete solution.
1. ui: Conditionally display the rates, meaning if no rate is available, degrade gracefully
2. core: Handle multiple sources, probably by designing a flexible `type PriceSource interface` that `Core` can use and implementing one for each source, e.g. coinpaprika, messari, dcrdata.
3. ui: Let user select the sources to use from # 2. This is critical because if a source becomes outdated or otherwise corrupt, the user needs the option to disable that source.
4. core: If rate data is available from multiple sources, it should be integrated in some way so that we aren't over-reliant on a single source.
5. core: Rates need to be cached so that we stay under the request limit. Cache needs to expire so we don't report old data.
6. core and UI: Need to handle live updates. Core sends notifications and we update figures on the front end.
