### ISSUE TITLE
ui: Price change percent wrong sometimes.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1604]
Running on mainnet on 0.4.3-pre+dev

Here dexc has been running a few days. Just connecting via web browser will show this:
![image](https://user-images.githubusercontent.com/34998433/166851808-58c7031a-691e-4da7-9bf7-f147b5cf2890.png)

Change of -100.0%

After a few minutes it looks like a much more correct +0.34%:
![image](https://user-images.githubusercontent.com/34998433/166851901-1982af85-df45-48f5-adbc-9cb5f24bafbe.png)

I'm not sure what the time frame for the change is, but isn't -100% zero?

**Comment by chappjc** [comment]
Good report.  Adds to https://github.com/decred/dcrdex/issues/1540

**Comment by JoeGruffins** [comment]
Oh, didn't realize was already an issue open. Can close and link...

**Comment by JoeGruffins** [comment]
Closing because covered by #1540
