### ISSUE TITLE
btc: creating native wallet with too-low fee limit wrecks the wallet

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1609]
![image](https://user-images.githubusercontent.com/9373513/167321107-a1d9f427-657d-4592-b5df-f79d278495d9.png)

```
[INF] CORE: Initializing a built-in btc wallet
[TRC] CORE[btc]: Fallback fees set at 100 Sats/vbyte
[ERR] WEB: error creating btc wallet: error loading wallet for 0 -> btc: error opening wallet: fee rate limit is smaller than smallest unit: 2e-06
"POST http://127.0.0.3:5758/api/newwallet HTTP/1.1" from 127.0.0.1:58922 - 200 73B in 1.888988083s
```

Then when trying again with a higher limit:

![image](https://user-images.githubusercontent.com/9373513/167321139-37290869-6950-4540-9960-513cbe9350db.png)

`[ERR] WEB: error creating btc wallet: Error creating wallet: CreateNewWallet error: wallet already exists`

**Comment by chappjc** [comment]
Looks like anything less than 1 sat/B would result in this error: https://github.com/decred/dcrdex/blob/4548c2ba32c9706250efc8c38b9b3403aa41cf33/client/asset/btc/btc.go#L808-L810

I haven't worked through why it persists even though creation failed, and you cannot change it though

**Comment by vctt94** [comment]
I can work on this

**Comment by chappjc** [comment]
Thanks.  I'm pretty sure the same check that's hitting in `newUnconnectedWallet` needs to also be just before `createSPVWallet` otherwise we are creating a wallet that it won't let you open.
