### ISSUE TITLE
client: using an external API as a fee rate fallback

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1618]
I honestly wouldn't mind using an external API as a fallback.

https://explorer.dcrdata.org/insight/api/utils/estimatefee?nbBlocks=2

_Originally posted by @buck54321 in https://github.com/decred/dcrdex/pull/1498#discussion_r857720422_

**Comment by buck54321** [comment]
This should be implemented in the wallet packages behind the `FeeRate` method, I think.

**Comment by vctt94** [comment]
I can work on that

**Comment by buck54321** [comment]
Our Litecoin wallet doesn't assign `BTCCloneCFG.FeeEstimator`, so the wallet falls back to `(*baseWallet).feeRate`, which itself falls back to an external API with hard-coded endpoints. Does this mean that Litecoin can end up with a Bitcoin fee estimate?

**Comment by vctt94** [comment]
Okay, will do them next. Do you guys have any api's to recommend?

For bitcoin cash I was able to find: https://docs.bitcoincashnode.org/doc/json-rpc/estimatefee/
For zcash I am looking into: https://getblock.io/docs/available-nodes-methods/ZEC/JSON-RPC/estimatefee/

For litecoin and doge I still have not found a json-rpc api for them, with estimate smart fee, do you guys have any suggestions?

**Comment by chappjc** [comment]
For an external API, we'd need a service, not the node's JSON-RPC API, unless I'm misunderstanding those suggestions @vctt94.

An option is to use the bitcore API (was insight) that provides many alts including BCH, LTC, DOGE, and ETH:
- https://api.bitcore.io/api/BCH/mainnet/fee/1
- https://api.bitcore.io/api/LTC/mainnet/fee/1
- https://api.bitcore.io/api/DOGE/mainnet/fee/1
- https://api-eth.bitcore.io/api/ETH/mainnet/fee/1

I'll look for a ZEC oracle too.

**Comment by chappjc** [comment]
ZEC is interesting

https://github.com/zcash/zcash/issues/2942

`relayFee` from https://api.zcha.in/v2/mainnet/network:

```json
{
  "name": "mainnet",
  "accounts": 7236146,
  "transactions": 11589222,
  "blockHash": "0000000000ad94b0ae7b01b62ae9ced52f6fc16d959c6a449276e12a20fc1c97",
  "blockNumber": 1812084,
  "difficulty": 81371313.48398675,
  "hashrate": 10421641389,
  "meanBlockTime": 81.00833333333334,
  "peerCount": 8,
  "protocolVersion": 170100,
  "relayFee": 0.000001,
  "version": 5020050,
  "subVersion": "/MagicBean:5.2.0/",
  "totalAmount": 15285525,
  "sproutPool": 27065.27843336,
  "saplingPool": 834560.80050122
}
```

That value looks constant, possibly intentional according to the github issue.  Also it's not clear to me if that's a fee rate or an absolute fee.

**Comment by buck54321** [comment]
re Zcash: See also https://github.com/zcash/zcash/issues/2942. It appears to be in flux, to say the least.
