### ISSUE TITLE
trading: Self revoked trades may unlock coins that server does not (yet) preventing further trading.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1619]
As seen here https://github.com/decred/dcrdex/pull/1498#pullrequestreview-970381404

The client, as taker, revoked a trade because its locktime had passed, returning the coins locked for the order. The server however was still waiting for the taker to act and kept the coins locked because it did not know that the client had abandoned the trade. The client then tried to use those unlocked coins in a new trade and was prevented. This is temporary, and the coins are eventually released. I guess it's only a problem for taker, and the time is however long it takes for maker's swap to be confirmed plus the broadcast timeout. Then the server would also revoke and unlock the coins.

I'm not sure of the best answer, but maybe client should have a way to communicate that it would like to abandon the trade.

Leaving the logs so that they don't get lost, and for others to check if my sleuthing is wrong.
Server: 
[dcrdex.log](https://github.com/decred/dcrdex/files/8707847/dcrdex.log)
Client 1:
[out1.txt](https://github.com/decred/dcrdex/files/8707848/out1.txt)
Cient 2 (the self-revoker):
[out2.txt](https://github.com/decred/dcrdex/files/8707850/out2.txt)

**Comment by chappjc** [comment]
I think the answer here is that the server could revoke the trade early too.  We've added a number of checks (https://github.com/decred/dcrdex/pull/1541), but perhaps this one is another to add.

**Comment by JoeGruffins** [comment]
It looks like those checks should make this not happen if locktimes are the same for server and client.

I guess I had made the locktimes shorter for the client? The server will use it's hardcoded times in the config correct?

I think will close this in that case. We could have server and client communicate expected locktimes somewhere I guess. But maybe this isn't expected to be a problem in production.

Definitely logging the configured lock times for the client at startup would help.

**Comment by JoeGruffins** [comment]
I believe this happened because I set the client locktimes shorter than server, which is not expected to happen in production as the values are hard coded.
