### ISSUE TITLE
abigen --sol no longer works

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1625]
With abigen from go-ethereum 1.10.18, we can no longer do this:

https://github.com/decred/dcrdex/blob/b41da105df90e8d61f7371b330b53c8ef9e85d94/dex/networks/eth/contracts/updatecontract.sh#L38

https://github.com/ethereum/go-ethereum/pull/24936

**Comment by jeffprestes** [comment]
Meanwhile an alternative might be https://github.com/jeffprestes/abigen-golang 
I had to create it to avoid to break my project's scripts and might be useful here too. I hope it helps.

**Comment by chappjc** [comment]
Thanks.

I've found that using the `combined-json` switch on both abigen and solc is helpful as it combines everything rather than having to force you to deal with multiple files (e.g. .bin .bin-runtime .abi etc.). e.g.

```sh
solc --combined-json abi,bin --optimize --overwrite contract.sol -o .
abigen --combined-json combined.json --pkg contract --out contract.go
```

**Comment by chappjc** [comment]
Thanks.

I've found that using the `combined-json` switch on both abigen and solc is helpful as it combines everything rather than having to force you to deal with multiple files (e.g. .bin .bin-runtime .abi etc.). e.g.

```sh
solc --combined-json abi,bin --optimize --overwrite contract.sol -o .
abigen --combined-json combined.json --pkg contract --out contract.go
```
