### ISSUE TITLE
client/assets: Consider adding a way to add (and remove?) peers for internal wallets.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1636]
Especially for Ethereum where there is more of a server/served relationship and servers are limited, it may be necessary to point clients in the right direction, for instance towards a known good server. On testnet, at least, sometimes it is difficult to find "peers". I think this would be a useful tool to have IF it also becomes a problem on mainnet.

**Comment by ukane-philemon** [comment]
This would be nice  for Bitcoin spv wallets too. Somtimes my Bitcoin spv wallets takes long to start as a result of searching for a suitable peer.

**Comment by martonp** [comment]
I can do this.

**Comment by chappjc** [comment]
> I can do this.

All your.  Thanks!

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/1931
