### ISSUE TITLE
Need market overview API

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#165]
Right now, the only way to get information about an order book is to sync it. While #142 is intended to lighten the load on order book syncing, it'd be great if I could get an entire DEX overview with a single request (or subscription with updates). Minimally, I'd like to be able to query mid-gap rate for all markets. Bonus points for 24 hr. change too. 

Will require spec changes.

**Comment by chappjc** [comment]
Would you say this would be a subset of the public API (served by the microservice planned in https://github.com/decred/dcrdex/issues/119)?

**Comment by chappjc** [comment]
Also, did you have this in mind for some client work you were doing?  Just trying to gauge priority.

**Comment by buck54321** [comment]
Three months later...

Definitely could be part of #119. Not a priority yet, I don't think.

**Comment by buck54321** [comment]
I think this is largely superceded by https://github.com/decred/dcrdex/issues/941.

**Comment by vctt94** [comment]
Is this still an issue? I can work on this and #119 if no one is working on it.
