### ISSUE TITLE
client/webserver: TCore missing Markets method

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#166]
Resolved by PR https://github.com/decred/dcrdex/pull/153

**Comment by buck54321** [comment]
Looks like I grabbed it in #153.

https://github.com/decred/dcrdex/blob/dd82f40ae79402d68f6b2339c3d88d78e844b3fb/client/webserver/live_test.go#L56

**Comment by chappjc** [comment]
Nice, updating the description so it gets auto-closed when 153 goes in.

**Comment by chappjc** [comment]
resolved by https://github.com/decred/dcrdex/pull/153
