### ISSUE TITLE
site: look into go:embed for the site resources

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1664]

**Comment by vctt94** [comment]
I can work on that

**Comment by chappjc** [comment]
OK, please research the best approach.  I think an `embed.FS` (or multiple) should be used to abstract the use of the embedded files so that it code that uses it does not know it's embedded and it may actually be the files on disk.

To support development, if the files do exists at *runtime* they should be used instead of the embedded FS.

**Comment by chappjc** [comment]
Some resources to digest in planning:
- https://go.googlesource.com/proposal/+/master/design/draft-iofs.md
- https://go.dev/doc/go1.16#fs
- https://pkg.go.dev/io/fs#FS
- https://pkg.go.dev/os#DirFS
- https://pkg.go.dev/embed#FS
- https://pkg.go.dev/html/template#Template.ParseFS
