### ISSUE TITLE
TestTaperingQueue fails sometimes

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1671]
Failed during a CI run, but passes usually.

**Comment by chappjc** [comment]
Try to capture the CI log if it happens again.
I tried to reproduce but unable:
`parallel -P 4 -N0 --halt soon,fail=1 go test -race -count=1 -short -run TestTaperingQueue ./dex/wait  :::: <(seq 1 2000)`

**Comment by chappjc** [comment]
I think 5 ms is just too short for these CI VMs

**Comment by chappjc** [comment]
Hmm, I think the "little optimization if this waiter would fire immediately" that I suggested allows the waiters to be executed out of order given the right circumstances.  Maybe we remove that and just let it append even if it should fire immediately, just to keep the order stable.

**Comment by ukane-philemon** [comment]
https://github.com/decred/dcrdex/runs/7903466734?check_suite_focus=true fail log for #1766 
```
--- FAIL: TestTaperingQueue (0.01s)
    queue_test.go:123: wrong result order expected [+1 +3 +4 +2 +0], got [+1 +4 +3 +2 +0]
```

**Comment by chappjc** [comment]
Thx.  I triggered a re-run of those jobs for now.

**Comment by ukane-philemon** [comment]
Uhmm, I've hit a related fail here https://github.com/decred/dcrdex/actions/runs/3479377426/jobs/5817848849

**Comment by chappjc** [comment]
The link to that failed CI run will be dead before too long, so here's the failure for posterity:

```
 --- FAIL: TestTaper (0.04s)
    queue_test.go:58: first intervals are out of bound: 11.752457ms
FAIL
FAIL	decred.org/dcrdex/dex/wait	0.092s
```
