### ISSUE TITLE
move away from ini package reliance except for ini parsing

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1698]
I'm uncomfortable now when I see us using `Unmapify` and `map[string]string` because it no longer has to do with **ini** file processing.  It's quite unfortunate that `Unmapify(settings map[string]string, obj interface{})` uses the `ini` package (via `ParseInto`) at all.  The `config.Data` function is a cludge that should not exist (at least for `Unmapify`):

```go
func Data(settings map[string]string) []byte {
	var buffer bytes.Buffer
	for key, value := range settings {
		buffer.WriteString(fmt.Sprintf("%s=%s\n", key, value)) // to use `ini` for the dirty work
	}
	return buffer.Bytes()
}

func Unmapify(settings map[string]string, obj interface{}) error {
	cfgData := Data(settings)  // there has to be a better way to go from map[string]string -> struct
	return ParseInto(cfgData, obj)
}
```

Zooming out, the many "form" structs that have a `Config/Options map[string]string` field should probably be using `map[string]interface{}` for _[arbitrary data decoding](https://go.dev/blog/json#decoding-arbitrary-data)_ of [any JSON object](https://pkg.go.dev/encoding/json#Unmarshal), with a round trip through json.Marshal->json.Unmarshal and we wouldn't be abusing the ini package anymore.

https://go.dev/play/p/VYIOR61MYXH

On the frontend, I think we'd change the `map ()` function to return a JSON object instead of a `Record<string, string>`, then unmarshal the object into a `map[string]interface{}` as I've shown in the playground above.

The only place we should be using the ini package (and probably our dex/config package) is when parsing ini files or the contents of ini files.  But because of how we've done `Unmapify` we are unnecessarily reliant on the `ini` package, which is a black box we should avoid at all costs.

I haven't wanted to make a fuss about this before because we've been making progress, but I get the sense we're getting dug in on this ini stuff where it makes little sense.  Both the acrobatics and the dependency can be avoided in most of our use cases.

**Comment by buck54321** [comment]
> On the frontend, I think we'd change the map () function to return a JSON object instead of a Record<string, string>, then unmarshal the object into a map[string]interface{} as I've shown in the playground above.

One thing is that we would need to be aware of the expected data types. With INI, integers and strings of integers and booleans encode identically. 

https://github.com/decred/dcrdex/blob/6804b0d769aeb5620226f39af77f51ba1f07a5c0/client/webserver/site/src/js/forms.ts#L442

blows up with the JSON plan if we are expecting the `interface{}` to be anything but a string. So we would have to specify the type of every `ConfigOpt`.

**Comment by chappjc** [comment]
That's probably a major pain.

Maybe we can find a suitable way to code `Unmapify` for a `map[string]map` that does not use the ini package or worse, heaps of incomprehensible reflect code.

Or we keep going with the ini package, but it feels wrong to me in most of our use cases.

**Comment by buck54321** [comment]
We could write our own decoder.

**Comment by chappjc** [comment]
So reflect.  Ugh.
