### ISSUE TITLE
swap: db failures should not prevent active swaps, and should prevent penalization

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#171]
In the event of a DB failure (e.g. unexpected postgres process termination), the market and swap machinery needs to gracefully halt epoch processing and prevent new swaps while allowing active swaps (init already processed) to complete if possible.  Clients must not be penalized (inaction) when the swapper is shutting down due to such a failure.

The DEXArchivist already provides a LastErr method so that consumers can check DB health before beginning certain operations, and halt the subsystem if appropriate.  Other unexpected errors returned by DB operations must be handled appropriately, which means stopping the swapper and/or market while allowing active swaps to complete.

Some work has begin in https://github.com/decred/dcrdex/compare/master...chappjc:match-db-expanded?expand=1, but swap and market integration tests need to be created to ensure the server handles unexpected DB errors as described above.

**Comment by ukane-philemon** [comment]
@chappjc, did #177 fix this before now?
