### ISSUE TITLE
password error shouldn't go to notification bell

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1712]
![image](https://user-images.githubusercontent.com/6109680/179294113-d908a88a-1c6c-471f-9f99-a505b754d449.png)

**Comment by vctt94** [comment]
I can work on that

**Comment by buck54321** [comment]
It's yours. I think I saw that particular notification when I was changing wallet types, but you should look around. This is probably part of a bigger issue with forms. Anywhere an error is returned on a form submission, it should be displayed on the form only. Anywhere you see
```Javascript
app().checkResponse(res)
```
instead of 
```Javascript
app().checkResponse(res, true)
```
is probably wrong. I'm tempted to just get rid of the notification forwarding behavior of `Application.checkResponse` altogether, but I haven't looked closely at the implications of that.

**Comment by vctt94** [comment]
So I was looking into the code, and right now all check response which fails (and !skipnote), goes to the notification belt. From comments: 

```
  /*
   * checkResponse checks the response object as returned from the functions in
   * the http module. If the response indicates that the request failed, a
   * message will be displayed in the drop-down notifications and false will be
   * returned.
   */
```

If removing the forwarding behavior of checkresponse, should any of those notifications still be kept in the belt and moved to notification.go?

```

**Comment by buck54321** [comment]
> If removing the forwarding behavior of checkresponse, should any of those notifications still be kept in the belt and moved to notification.go?

You'd need to check it on a case-by-case basis, but my gut says that no API errors should go to the bell. Hopefully you can just remove the error forwarding of `checkResponse`. That'd be good.
