### ISSUE TITLE
Investigate need for response handler lifetime management

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#172]
Original comment thread at https://github.com/decred/dcrdex/pull/153#discussion_r375021298

Response handlers are now launched as a goroutine with no attempt at lifetime synchronization. Do we need it? 

Noting here that `wsConn` from **client/comms** does not satisfy `dex.Connector`. Should we rework `wsConn` for the new pattern?

**Comment by chappjc** [comment]
I believe this was resolved in PR #199 on lines https://github.com/decred/dcrdex/commit/9f6110fe56d2e8552440304d52ebb874489639eb#diff-f79fa92787fcd0b123b817c375ebac6cR263-R270
