### ISSUE TITLE
tokens/discussion: Need to check blacklisted addresses.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1725]
It's unfortunate, but token addresses can be blacklisted. This is part of the some token interfaces. It is separate from the [erc20 interface](https://ethereum.org/en/developers/docs/standards/tokens/erc-20/) which means tokens may not implement it, but its seems pretty common.

You can see them present in [USDC](https://etherscan.io/address/0x0882477e7895bdc5cea7cb1552ed914ab157fe56#code) and [Tether](https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code).

This issue is an attempt to get consensus on whether and how much we care if an address is blacklisted.

As far as I can tell, a blacklisted address would only be a problem for the one trying to use it for USDC. The initiator would not be able to initiate if they were using a blacklisted address. The redeemer would not be able to redeem.

In case of the redeemer, the initiator as maker could take both sides of the swap by later refunding. This seems to be the "worst" thing that can happen for users. So, if anything, clients could do a courtesy check with their own address before attempting to trade.

For Tether, it looks like a blacklisted address can still approve another address to spend its funds, but I'm probably misreading because that would be silly. It also looks like you can send to a blacklisted address, so redeemer could redeem but just not be able to send those tokens again.

So, maybe slightly different implementations for different tokens.

Also, I guess it's a possibility that the contract itself is blacklisted. If the blacklist would still allow approving and sending to the address, then maybe it's best that is also checked before trading.

**Comment by chappjc** [comment]
Thanks for following up.  Initially raised here with no resolution: https://github.com/decred/dcrdex/pull/1360#discussion_r771878739

Both USDC and Tether have an `isBlacklisted` method (spelling differences though).  I think it's reasonable for the users client to check their own address, as you suggested @JoeGruffins.

**Comment by buck54321** [comment]
Users attempting to use blacklisted addresses will quickly run into our reputation system.
