### ISSUE TITLE
client/db/bolt: tests running long

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1728]
`TestDeleteInactiveOrders` and `TestDeleteInactiveMatches` both take crazy long, like 13 seconds each for me.

**Comment by chappjc** [comment]
I've noticed this in the past as well, however it's only for a `-race` test.

No `-race`:

`--- PASS: TestDeleteInactiveMatches (0.80s)`

With `-race`

`--- PASS: TestDeleteInactiveMatches (11.62s)`

It's a much bigger slow down than normal, but it does appear to only be an issue when the race detector is enabled.  CI runs these tests fast too.

**Comment by chappjc** [comment]
Ohhh, but CI uses `-short` with go test so it skips these.  In any case, it does seem fast when not using `-race`.  Not sure we should identify the reason for the big 0.8 sec vs. 12 sec difference, but it is curious.

**Comment by JoeGruffins** [comment]
default:
--- PASS: TestDeleteInactiveMatches (1.19s)
--- PASS: TestDeleteInactiveOrders (1.83s)

race:
--- PASS: TestDeleteInactiveMatches (12.15s)
--- PASS: TestDeleteInactiveOrders (16.81s)

**Comment by buck54321** [comment]
Yeah, I'm much slower. Hmm.
