### ISSUE TITLE
server/swap/test: TestMalformedSwap test failure.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1730]
Random test failure on pr #1729 but probably unrelated to those changes. A second try by github passed and tests pass locally. Can be seen here: https://github.com/JoeGruffins/dcrdex/runs/7492614387?check_suite_focus=true

```
--- FAIL: TestMalformedSwap (0.01s)
    swap_test.go:1976: error sending maker swap transaction: maker swap rpc error. code: 64, msg: already received a swap contract, search in progress
```

**Comment by LasTshaMAN** [comment]
Looking into this, if nobody minds

**Comment by chappjc** [comment]
OK.

The fundamental issue is described here: https://github.com/decred/dcrdex/pull/1563#discussion_r899257787

The semaphore isn't toggled until after `processInit` sends it's response and returns to the `latencyQ` with `DontTryAgain` thus finally calling `endSwapSearch`.  In the original PR I had `endSwapSearch` called in `processInit` earlier but it wasn't half as clean of a solution.  I don't know if it's realistic outside of a unit test to have this be a race the client can win with a second init request, but this is how we would solve it.

Also, `ensureErr` needs a `t.Helper()` so we know where the error actually happened within

**Comment by chappjc** [comment]
Here's the alternate approach I am referring to: https://github.com/decred/dcrdex/commit/4d82ea4ba00b8f80e29e42451856bd97c54f1205#diff-6af7c56e40de4eb4dba203d67b1b07ccfc43ed88e99811b9697e9d754d01e21cR1469-R1473

**Comment by LasTshaMAN** [comment]
Thanks for additional context on this, 
- I'm unsure of what implementation of `Swapper` (current or the alternative you've suggested) is preferable for all intents and purposes, I think master version is good enough for now (and can be upgraded in the future), but can dig deeper into it if you think it's worth doing so
- and it's the flaky tests that needs improvements anyway, which I'm basically focusing on in the linked PR

**Comment by chappjc** [comment]
Thanks, I think working on the test is best for now.

If a client sends a second init request so fast, they are effectively hammering the server.  All they need to do is slow down for a microsecond for the semaphore to flip and they can submit again, assuming they haven't tripped the global or user request rate limiters.

BTW, the other reason for a "search in progress" response is if they had a previous request that timed out client side, but hadn't yet timed out server-side.  And again that is a try again scenario.

**Comment by buck54321** [comment]
Can close?

**Comment by JoeGruffins** [comment]
I hit again today, same?
```
2022-09-19 11:55:29.591 [DBG] TEST: Error going to user 224cbaaafa80bf3bd1ff731590bcbdda5a76f91e60a156994634e91c00000022, code: 25, msg: redemption error
2022-09-19 11:55:29.591 [DBG] TEST: handleInit: 'init' received from user 224cbaaafa80bf3bd1ff731590bcbdda5a76f91e60a156994634e91c00000022 for match 06314483d3227d5d0985ec799c1989851d2027e86e1f0ca252fa09bf724579c3, order 67d2d1b95e4fc0c115b71ade059215aa442e7f5227c3c753e5d936bc0e7bad9f
--- FAIL: TestTxWaiters (0.01s)
    swap_test.go:1610: error sending maker swap transaction: maker swap rpc error. code: 64, msg: already received a swap contract, search in progress
```
