### ISSUE TITLE
sever/auth/auth_test.go: TestHandleResponse test failure

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrdex#1734]
This is the first time I'm seeing this. 
https://github.com/decred/dcrdex/runs/7524088585?check_suite_focus=true
```
2022-07-26 15:56:14.652 [DBG] AUTH_TEST: (*AuthManager).handleResponse: unknown msg ID 26
--- FAIL: TestHandleResponse (0.02s)
    auth_test.go:1296: expected 0 response handlers, found 1
2022-07-26 15:56:14.677 [ERR] AUTH_TEST: AccountInfo error for ID e94e8d95338b67a417650538b5250d3939d5eb81c4497677f4263ef0d4e45885: general failure
```

**Comment by ukane-philemon** [comment]
```
client.logReq(newID, func(comms.Link, *msgjson.Message) {},
		0, func() { t.Log("expired (ok)") })
	time.Sleep(time.Millisecond) // expire Timer func run in goroutine
```
There's a `time.Sleep(time.Millisecond)` right above the fail line which should have ensured response handlers expire and are removed. Unfortunately, the whole clean-up process is done in a separate goroutine and maybe `time.Sleep(time.Millisecond)` is not always enough.

**Comment by LasTshaMAN** [comment]
Also saw this fail, attaching [full test output](https://pastebin.com/KJ6y68EC) just in case it will become useful during debugging.

Will try looking into it, if nobody has started on this yet.

**Comment by ukane-philemon** [comment]
> Unfortunately, the whole clean-up process is done in a separate goroutine and maybe time.Sleep(time.Millisecond) is not always enough.

Increasing `time.Sleep` a little more, maybe a few more Millisecond will allow enough time to ensure the clean-up is complete.
