### ISSUE TITLE
fuzzing

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1748]
Go version 1.18 added [native fuzzing support](https://go.dev/doc/fuzz/) to the standard toolchain, and we should use this capability.

We will need to start taking notes for the best candidates for fuzz tests, but I think the core bits of server comms systems and some of the most central algorithms like order matching, epoch shuffle, etc. are good ones.  Then there's some of the crypto helpers in the asset/networks packages.

Fuzzing is most effective with the most primitive methods and functions.  As such, this will take some careful targeting and potentially some very light refactoring here and there to get fuzzable functions.  This should also help us write better (more narrow and more exhaustive) unit tests.

An outcome of the initial work should be a readme or wiki page to guide dex devs on creating fuzz tests citing Go docs on best practices etc.

This was a minor part of the possible phase 3 development goals, but it should get a start.

**Comment by chappjc** [comment]
Something to consider @ukane-philemon

**Comment by davecgh** [comment]
I'm interested to see what you guys come up with here as well.  There was recently a PR to dcrd which adds ClusterFuzzLite which also seems like a reasonable option.

I personally think I'd rather use native Go fuzzing support in general, but I've not dug in enough to know how to handle the corpora and more long-term fuzzing efforts in terms of integration with GitHub actions.

**Comment by ukane-philemon** [comment]
@chappjc, can I work on this?

**Comment by chappjc** [comment]
Absolutely.  Feel it out with something small and low-level/primitive.
Part of what we need from this is research and then a knowledge transfer to the rest of the group.
