### ISSUE TITLE
ui: note feeder error

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1754]
On the Wallets page after creating a native DCR wallet.

![image](https://user-images.githubusercontent.com/9373513/182688790-e0df14e1-3905-4a7b-986b-7e8f581697a0.png)

**Comment by ukane-philemon** [comment]
Hmm, looked into this and it seems we received `balance` note while the page have not been updated with the `data-balance-target="42"` element. So the `balance` note tries to access element `data-balance-target="42"` which caused the error?

**Comment by JoeGruffins** [comment]
I can't seem to reproduce the error. Does it always happen or just once?

**Comment by ukane-philemon** [comment]
> 

I can. Launch dexc with another datadir, try creating dcr svp wallet. Once you hit on submit, balance notification will be sent while the page has not been refreshed. You'll see the noteFeeder error and other logs about a missing element in the dev console.

**Comment by JoeGruffins** [comment]
Actually, I don't see the notes at all in my dev console. I must be doing something wrong there.

**Comment by ukane-philemon** [comment]
Just reproduced.
<img width="1501" alt="Screenshot 2022-08-05 at 1 06 31 PM" src="https://user-images.githubusercontent.com/57448127/183074216-230ed9df-579e-4728-afea-5746d67066f5.png">
