### ISSUE TITLE
ui: Accelerate button pops up for wrong trade.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1760]
You can be looking at a completed order and when another order goes from epoch to maker cast, the `Accelerate` button will pop up where you are looking.

To reproduce:
Start the simnet harness and complete one trade on the dcr_btc market.
Make another trade and click on the executed order and wait a bit. The accelerate button will pop up. You can click it and accelerate some order.
Refreshing the page makes it go away.

![image](https://user-images.githubusercontent.com/34998433/182830474-b0fb4ea5-2698-4e82-abc8-9e8836c6dd84.png)

I often see some weird things happen on this screen. Maybe some investigation can get to the bottom of it all.

**Comment by martonp** [comment]
I think the reason is that the updates happen based on the match ID. And since both sides of the match are you, this causes issues.

**Comment by JoeGruffins** [comment]
Oh, could be... But this is a different match. I will try with separate dexc.

**Comment by JoeGruffins** [comment]
I have confirmed it happens even when using separate clients.

**Comment by martonp** [comment]
OK I'll take a look.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/1772
