### ISSUE TITLE
zec: Incorrect available/locked amounts.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1768]
Testing on testnet zec_btc because dcr testnet is down. Here trying to make a market sell (limit gives same error) and the error message is confusing. It looks like I should have 1.0119302 zec available, but the error message will tell me I only have 0.0019302 so exactly 1.01 less.

![image](https://user-images.githubusercontent.com/34998433/183612473-fe056162-08d9-4ca4-a6f6-bf479639ce77.png)

![image](https://user-images.githubusercontent.com/34998433/183611241-27bca0f3-c44a-477e-888a-a24723ba35f1.png)

Also, I have about 0.006 zec in sell orders already, so I think that should be showing up in `locked` but it is not.

**Comment by JoeGruffins** [comment]
It would make sense that that the 1.01 is two utxo. One from the testnet wallet and the other send from my other node. I guess it should be showing 1.01 locked is the real problem.

**Comment by chappjc** [comment]
https://github.com/decred/dcrdex/blob/50cf04fcf09919d96c801cae5c03ef4430eb1923/client/asset/btc/btc.go#L1393-L1416

For ZEC, it looks like we just don't set the `Locked` field at all.  @buck54321 Do you recall a reason why we don't also use `btc.lockedSats()` in this `zecStyleBalance` path?  Seems like a bug.

Also, I think we should look again at `(*baseWallet).lockedSats` and how it takes the result of `gettransaction` and does ` uint64(txOut.Value)`.  If it is negative (like it can be with `listtransactions`), we'll have an underflow.
