### ISSUE TITLE
UI: Orders screen shows refunding incorrectly sometimes.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1769]
When I first visited the page:
![image](https://user-images.githubusercontent.com/34998433/183633127-5175bd2f-2304-4796-82f4-a271c23a1227.png)

After some time, and I don't think it was a refresh:
![image](https://user-images.githubusercontent.com/34998433/183633681-77dda5ec-0616-4120-9a8d-a0327867a2d5.png)

**Comment by JoeGruffins** [comment]
The locktimes for the order are past which may be the reason. Unable to redeem because the output would be dust, which is human error I suppose.

**Comment by chappjc** [comment]
I have also seen it switch from "Revoked - X" to another status.

**Comment by chappjc** [comment]
Ok so `OrderUtil.matchStatusString` needs to match `(*matchReader).StatusString` is all I think.

**Comment by buck54321** [comment]
> Ok so `OrderUtil.matchStatusString` needs to match `(*matchReader).StatusString` is all I think.

related: https://github.com/decred/dcrdex/issues/1179#issuecomment-920056750
