### ISSUE TITLE
eth: handle block size max

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1771]
> I does seem limited, but considering that a regular tx is 21,000 gas, I think it's correct.

Back to the gas estimate issue, I think this means we should place a cap on the number of inits.

More broadly, it sounds like we need to place a cap on the number of lots otherwise there will be potentially unswappable orders, however huge they'd be.

_Originally posted by @chappjc in https://github.com/decred/dcrdex/issues/1622#issuecomment-1209423904_

___

Just spitballin'. Either...
1) Place a cap on number of lots in the dex protocol or at the server configuration level
2) Break up large swap internally to eth, which will carry a lot of complexity especially around errors.
3) Handle it in `*Core`, which may end up being the easiest, implementation-wise, but it's really just an ethereum thing.

**Comment by martonp** [comment]
I'll work on this. I think the third plan of handling it in `*Core` is the best. Each wallet can specify what their limit is and core can do the batching based on that.
