### ISSUE TITLE
simnet-trade-tests/dcrbtc: Some fail with dcr unlocking error if run together.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1783]
To run all the tests, I think, you do `./run dcrbtc -t success -t nomakerswap -t notakerswap -t nomakerredeem -t makerghost -t orderstatus -t resendpending` and this results in the error:
```
ERROR: test "notakerswap" failed: client1 place sell order error: dcr connectAndUnlock error: failed to unlock dcr wallet: dcr unlockWallet decryption error: expected 2 pushes. got 0
```
for a few of the tests.

They seem to be fine if run alone.

Also a command like `--all` to just run all the tests would be cool.

**Comment by JoeGruffins** [comment]
Will fix this. Also have a fix for the balance calculations that are making the tests fail recently.

**Comment by chappjc** [comment]
> Also have a fix for the balance calculations that are making the tests fail recently.

Nice! Thanks for getting to the bottom of that.

**Comment by JoeGruffins** [comment]
Will push early next week.
