### ISSUE TITLE
client: data backup

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#179]
1. Client data should be backed up. @chappjc suggested copying the entire database on shutdown, which I agree would be a reasonable first solution, though we should aim to have a backend-independent format eventually. 

2. A separate key dump method on `core.Core` is needed for users to save just account and signing keys on demand.

**Comment by dnldd** [comment]
@buck54321 for the key dump I'd like suggest a json file, like how pi dumps pki details currently. Is that agreeable?
