### ISSUE TITLE
UI: Orders page order is unintuitive.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1790]
This issue has two parts:

1. The order screen's swaps' order is not intuitive for taker. It will show your swap and redemption first, when in reality the other side sent first. The order it shows is 2, 1, 4, 3. Maker on the other hand will show the order 1, 2, 3.

Comments from @jholdstock on matrix:
```
future steps might be helpful as well actually, eg.

Step 1: BTC swap broadcast (them)
Step 2: DCR swap broadcast (you) (1/4 confs)
Step 3: DCR redeem (them) (pending)
Step 4 BTC redeem (you) (pending)

perhaps pending steps can be grayed or something
i think making the process a little more visible would help with user understanding and potentially reduce support questions
```

2. Refreshing will randomized the order of matches, which is disorienting. Should be oldest to newest, and if time the same alphabetical. This way the order will be the same every time you visit the page.

**Comment by JoeGruffins** [comment]
Some visuals:
![image](https://user-images.githubusercontent.com/34998433/184792530-05d10271-517b-401b-852b-5334214732b4.png)

After a refresh:
![image](https://user-images.githubusercontent.com/34998433/184792596-a840bde8-d3b5-4fdb-8eec-b30b57a74718.png)

**Comment by chappjc** [comment]
Have noticed all of these quirks.  And agree.

**Comment by martonp** [comment]
I can fix this.
