### ISSUE TITLE
disable wallet function

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1794]
When you start and login to dexc, it tries to connect to all previously configured wallets.  These might be external wallets like Bitcoin Core, Electrum-LTC, etc.  Or maybe you just don't want the native wallet for asset X getting online and establishing peers anymore.

You should be able to "disable" a wallet into Wallets page so that dexc will not attempt to connect or start the wallet until it is re-enabled.

**Comment by ukane-philemon** [comment]
I can work on this.
