### ISSUE TITLE
UI: Hide load from file for spv wallets.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1805]
There is the `load from file` button on the eth reconfigure wallet form which has no function currently. It is also there when looking at the btc and dcr SPV type wallets. Is it possible to hide it whenever one is looking at an spv/built-in wallet form?

![image](https://user-images.githubusercontent.com/34998433/185869764-9d2f1ef1-096d-4631-89ea-94d4c5aee16f.png)

**Comment by vctt94** [comment]
Working on this

**Comment by ukane-philemon** [comment]
@vctt94, still on this?

**Comment by vctt94** [comment]
Hey ukane, Yeah I am. Should have a PR open today. Sorry taking so long
