### ISSUE TITLE
site: change wallet type settings, close form on firefox

### ISSUE THREAD

**Issue by vctt94** [decred/dcrdex#1808]
If changing the form wallet type on firefox, the form closes and it is not possible to change the wallet type:

![image](https://user-images.githubusercontent.com/15069783/186033560-5330bb35-1e95-480e-9100-650cdd7b15cc.png)

It seems to happen only on firefox.

**Comment by chappjc** [comment]
I think a [Peek](https://github.com/phw/peek) repro vid is needed. I don't think I understand the exact issue, but I have changed wallet type on firefox myself without issue.

**Comment by vctt94** [comment]
Here is a video on 54f3db37efde4f8e6581e5e47a39e3c2dffaf436:

![Peek 22-08-2022 20-43](https://user-images.githubusercontent.com/15069783/186038557-314156b5-a409-407a-abfa-405fbe3cd6dd.gif)

firefox version: 103.0.2 (64-bits)

**Comment by chappjc** [comment]
Oh, snap!  I was testing on the 0.5 branch.

The video is very helpful
