### ISSUE TITLE
frontend reports same fees for both swap/redeem assets

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1814]
![image](https://user-images.githubusercontent.com/9373513/186174824-243221bb-66f5-49b7-b6d8-048f4f77799a.png)

The from/swap asset is correct, but the to/redeem asset's fees is just the other value.

**Comment by martonp** [comment]
The solution to this is very simple, but I also found the issue that there is a trade involving a token, the fees are shown using the token asset, even though they should be using ETH. I'm fixing both issues.
