### ISSUE TITLE
UI: Wallets page volume is off.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1834]
Just making a trade on the simnet puts the volume at an unrealistic level.

![image](https://user-images.githubusercontent.com/34998433/187613976-fceeeaea-9ca5-4a62-933e-d108f5b9fa2f.png)

![image](https://user-images.githubusercontent.com/34998433/187614054-e2b6c0aa-d372-4a7f-b621-0c0b4e5914ed.png)

**Comment by martonp** [comment]
I'll fix this.
