### ISSUE TITLE
ui: external fee estimate option needs a default value

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1858]
No settings should be shown by default for native wallets.
![image](https://user-images.githubusercontent.com/6109680/191768609-ec6a5e3a-e83b-45f7-914b-3b4271a2b8a0.png)

**Comment by chappjc** [comment]
> No settings should be shown by default for native wallets

On principle?  Seem appropriate to show the setting, although why don't we just mark it optional so it's hidden by default?

**Comment by buck54321** [comment]
Why does it feel appropriate to show this particular setting? The user doesn't need to see this during wallet creation. The point is to make it a one-button, one-click experience whenever possible.

**Comment by chappjc** [comment]
> Why does it feel appropriate to show this particular setting? The user doesn't need to see this during wallet creation. The point is to make it a one-button, one-click experience whenever possible.

Sorry, not this particular setting I guess.  It's not something that absolutely requires choosing.  Can be default true.

I was just not certain that in all cases that there would be no required settings, even for native wallets.

Not a concern that needed to be raised.  My bad.

**Comment by buck54321** [comment]
Any existing policy is only convention established by previous work, but I think the simplest form of a policy here would be something like *any configuration that can be given a reasonable default value should be*. I typically notice this at the UI, and that is my primary interest, but it's a good policy regardless.

**Comment by vctt94** [comment]
I can fix this

**Comment by vctt94** [comment]
I believe this is not an issue anymore
