### ISSUE TITLE
ui,core: order placement could be partly async

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1862]
Especially when using a split tx, in which the funding output must propagate to the server node while we wait, the ordering sequence could be broken into an synchronous "funding" part and an asynchronous "comms" part. The benefit being that from the client's perspective, the ordering would appear to happen quickly, and the part most likely to error is the `FundOrder` part anyway.

The flow would be something like this.

1. **frontend**: User initiates order via `(*WebServer).apiTrade`.
2. **core** :Run `FundOrder` and other order preparation up to but not including sending the order.
3.  **core**: Generate a temporary ID for the order (since we don't have a server timestamp yet).
4. **core**: Start sending the order asynchronously.
5. **core**: Return the temporary ID to the caller waiting on `apiTrade`
6. **frontend**: Receive temporary ID. Close forms. Show order in "my orders" table, with pending indicator.
7. **core**: When ordering is complete, send result to client via core notification, including both temporary ID and newly finalized order ID
8. **frontend**: Receive result, updating order ID on succes. On failure, error goes to notification bell but also show some kind of modal error dialog too.

**Comment by ukane-philemon** [comment]
Thanks for the flow. I can look into this.

**Comment by chappjc** [comment]
Whatever the resolution, we must retain the synchronous `Trade(pw []byte, form *TradeForm) (*Order, error)` part of the `Core` API.  New methods can of course be added however.
