### ISSUE TITLE
litecoin electrum rpc issue with walletpath when using multiple wallets

### ISSUE THREAD

**Issue by karamble** [decred/dcrdex#1867]
i have created a 2nd litecoin wallet in my electrum wallet gui.
from that moment on i am not able to connect my wallet trough the dexc gui, always giving me:
'wallet not loaded' errors.

Research shows, that the rpc query needs to specify the walletpath, see:
https://pythontechworld.com/issue/spesmilo/electrum/7391

I am not able to enter a wallet name in the 
Electrum-Ltc (external) - tab when adding a new litecoin wallet, therefore i think we need to add the form field for wallet name and add it to the rpc query. see:
https://github.com/decred/dcrdex/search?q=default_wallet

**Comment by chappjc** [comment]
It's documented that it must be named default_wallet.
https://github.com/decred/dcrdex/wiki/Client-Installation-and-Configuration#sync-blockchains
We will eventually support multiple like you indicated, but not at present.

**Comment by chappjc** [comment]
It's a legit issue, to be clear.

It's just an irritating rpc design because it requires the full path to the wallet, not just it's name.  Plus it's in every request payload rather than in the endpoint.

**Comment by chappjc** [comment]
Solution brewing.  Not too bad, just annoying API.
