### ISSUE TITLE
rpc: Unable to do togglewalletstatus.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1869]
```
$ ./dexcctl -pabc --simnet togglewalletstatus 42
arguments: unable to parse arguments: wanted 2 but got 1
```
```
$ ./dexcctl -pabc --simnet togglewalletstatus 42 true
password arguments: unable to parse arguments: wanted 0 but got 1
```

**Comment by ukane-philemon** [comment]
What's `-pabc`? Your password?

**Comment by JoeGruffins** [comment]
yes

**Comment by vctt94** [comment]
Are you working on this @ukane-philemon ?

**Comment by ukane-philemon** [comment]
> Are you working on this @ukane-philemon ?

Yeah, I will look into it. The `togglewalletstatus` route do not accept an optional password parameter atm.

**Comment by JoeGruffins** [comment]
It looks like we just need to remove the dexcctl requirement of a password. Web does not require a password. Did this change at some point?

**Comment by JoeGruffins** [comment]
I think it is correct to just remove this line https://github.com/decred/dcrdex/blob/a0ee93952cb9c1df6de7adf9b5986bbdbe7a697e/client/cmd/dexcctl/main.go#L61

**Comment by ukane-philemon** [comment]
Sorry of the late reply, I think you meant to do this instead 

```
$ ./dexcctl -p abc --simnet togglewalletstatus 42 true
password arguments: unable to parse arguments: wanted 0 but got 1
```

**Comment by ukane-philemon** [comment]
> I think it is correct to just remove this line and it works correctly
> 
> https://github.com/decred/dcrdex/blob/a0ee93952cb9c1df6de7adf9b5986bbdbe7a697e/client/cmd/dexcctl/main.go#L61

The UI no longer require a password,  it is correct to remove that line but that was not the issue.

**Comment by JoeGruffins** [comment]
> no space between the -p flag and the value.

It works without the space.. for me

**Comment by chappjc** [comment]
I think we need to look into why there's a misleading error in the first place `wanted 0 but got 1` and why that's not more clear that it has something to do with an unwanted pass arg
