### ISSUE TITLE
ui: send should always be possible even when /txfee fails

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1878]
> It seems I cannot send funds from the wallet with the error `wallet does not support fee estimation`. I am running this rebased on master if that matters.

You should always be able to send without fee estimation. @ukane-philemon We cannot block sending because /txfee doesn't work.  The form with all the nice fee estimates is absolutely not required to actually attempt a send.  If /txfee fails, we still have to show a confirm form just without all the estimates and things that are purely informative, not needed.

_Originally posted by @chappjc in https://github.com/decred/dcrdex/issues/1870#issuecomment-1263606206_

We have a special case for a certain zec error because zec doesn't support subtraction, but no error should actually prevent the submission of an `/api/send` request, although we could catch certain expected errors for the purposes of having fewer error messages on the ui.

**Comment by ukane-philemon** [comment]
> You should always be able to send without fee estimation.

Alright.

**Comment by chappjc** [comment]
Might be as simple as this, not sure: https://github.com/decred/dcrdex/pull/1870/commits/fe20a0cf609870a6d6fc5a49da481110dfb64bd2
It's working anyway.
We should be checking `traitTxFeeEstimator` one way or another.

**Comment by ukane-philemon** [comment]
> We should be checking traitTxFeeEstimator one way or another.

Okay, I think it will save us some resources too.

**Comment by ukane-philemon** [comment]
@chappjc, closed by #1840
