### ISSUE TITLE
client: allow adding a dexConnection with no dexAccount

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1882]
The current flow to "Add a DEX" is tied to registering an account on that DEX, however, this flow could go differently:
- You do Add a DEX, specify the host name, click OK
- Without registering, it adds the DEX host, and takes you **straight to the Markets page** where you see the depth chart, order book, etc. just like you do now if you are registered
- Instead of the order submission form, there is a Create Account button and some simple text explaining that to trade you need to create an identity with the server.
- The markets list on the left will allow you to explorer the markets for all servers regardless of registration.
- Clicking the Create Account button will take you to the form we have now that shows what assets that server accepts for the fee. When register and then you come back to the markets page, it would show the confirmation countdown and eventually the actual order form.

This should be fairly straightforward in `client.Core` with perhaps a little extra logic and fields on the `dexConnection` and methods that process the `Core.conns` map to allow servers with no accounts to be handled without issue.  Namely, don't attempt `authDEX`, block orders, etc.

This would require a new `Core` method to add a dex without registering (yet).  The existing register method would need to learn to work with both new/unknown dex hosts as well as an accountless dex already in the `hosts` map.

Somewhat related, but I don't see the bandwidth as an issue anymore: https://github.com/decred/dcrdex/issues/142  Solving the present issue would be straightforward if "accountless" "dexConnections" behaved the same way on backend and frontend w.r.t. order book subscriptions and all other notifications.

On a related note, there could be an "Add a DEX" on the left on the Markets page:

![image](https://user-images.githubusercontent.com/9373513/193475702-17003eeb-6a1b-4802-8b86-bd480b43bd13.png)
(that looks terrible, but for illustration...)

**Comment by chappjc** [comment]
Potentially a duplicate of https://github.com/decred/dcrdex/issues/726

**Comment by vctt94** [comment]
I'd like to take this one

**Comment by buck54321** [comment]
@vctt94 Let's skip this one for now. It's a big undertaking and we need to work out the details ahead of time.

**Comment by ukane-philemon** [comment]
Related? #726

**Comment by chappjc** [comment]
Yeah, maybe even a duplicate.  Noted that here: https://github.com/decred/dcrdex/issues/1882#issuecomment-1264728846
