### ISSUE TITLE
restyled markets page bug roundup

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1886]
- [x] order note JS error on login ([vid](https://user-images.githubusercontent.com/9373513/193926592-da59501c-f13e-4301-85e9-41e08133cd54.mp4)), with active orders?

    ![image](https://user-images.githubusercontent.com/9373513/193926420-898a8c1b-d7ef-4930-b607-71002e974361.png)

- [x] `recentMatchesTable` selector warning, with an empty table, I think

    ![image](https://user-images.githubusercontent.com/9373513/193926914-b1c01cf1-b163-42d4-ae4b-b97302a7bfa8.png)
    ![image](https://user-images.githubusercontent.com/9373513/193927023-7f425576-40c4-4185-bc42-7b484c620c3f.png)

- [x] finicky click sensitivity on "hide" arrow box above markets list ([vid](https://user-images.githubusercontent.com/9373513/193928679-2887dc0e-853f-4a24-9c3b-1a6fbdfc6fe0.mp4)) It's hard to tell from the vid, but I'm clicking a lot inside the box and on the arrow, but it doesn't contract/hide.  There seems to be a magic touch.
Related: When I contracted it, I couldn't figure out  how to get it back.  Normally for these actions there would be a small arrow pointing back "out" somewhere near where the list was.  I think the intent is to click on market name header at the top/center?  You can also click on the DEX logo, but that reloads the entire page.

- [x] misaligned market search box text.  The font style is also quite chunky. Perhaps too high in the box as well.  The magnifying glass also stays there with text as long as you click away, but it should not be there with text.

    ![image](https://user-images.githubusercontent.com/9373513/193929572-ab990550-f738-4a5f-abc8-c0c146818f0a.png)

- [x] market search box is case Sensitive.  This is doubly confusing because the font does not seem to have different shapes between case, only size.

   ![image](https://user-images.githubusercontent.com/9373513/193930102-5e81a234-7767-4e13-b613-9a7b5b160417.png)

    ![image](https://user-images.githubusercontent.com/9373513/193930170-d5caf682-adb1-4a45-a65e-ba5eff3efb80.png)

<s>- [ ] cancelling multiple orders is more cumbersome (not necessarily a bug) ([vid](https://user-images.githubusercontent.com/9373513/193927290-e71bbc5c-18a8-4097-b21f-75af14f6726d.mp4)) </s>

- [x] selectable box missing from deposit address in reg process. Not on the markets page, but I think it's a side-effect of style changes.

    ![image](https://user-images.githubusercontent.com/9373513/193927484-b4b9298e-5d86-4fa8-be78-abb9e5b2b770.png)

**Comment by chappjc** [comment]
When the server is down, it shows an error message, as before, but when it reconnects, has a JS error.  Previously it did a page reload, which was fairly fool proof.

![image](https://user-images.githubusercontent.com/9373513/193953633-a99e82cb-f4a7-4f07-93dd-aa243795de63.png)

```
2022-10-04 19:18:36.153 [INF] CORE[wss://127.0.0.1:17273/ws]: Attempting to reconnect to wss://127.0.0.1:17273/ws...
2022-10-04 19:18:36.159 [DBG] CORE: notify: |POKE| (conn) Server connected - 127.0.0.1:17273 is connected
2022-10-04 19:18:36.159 [INF] CORE[wss://127.0.0.1:17273/ws]: Successfully reconnected.
2022-10-04 19:18:36.160 [DBG] CORE: Server 127.0.0.1:17273 broadcast timeout 1m0s. Tick interval 7.5s
2022-10-04 19:18:36.160 [INF] CORE: DEX 127.0.0.1:17273 with market dcr_btc restored for trade 92c1c7873d2d9cbe96245c963d1f4fdc5555423ad6a0c97600bb743449343e54
2022-10-04 19:18:36.163 [DBG] CORE: Authenticated connection to 127.0.0.1:17273, acct d8600824df88f23b8069cff62e15d21a5c9bf27f3706363bf01d24153da311b7, 1 active orders, 0 active matches, score -2 (suspended = false)
2022-10-04 19:18:36.163 [TRC] CORE: Status reconciliation not required for order 92c1c7873d2d9cbe96245c963d1f4fdc5555423ad6a0c97600bb743449343e54, status "booked", server-reported status "booked"
```

**Comment by chappjc** [comment]
Stopping and starting the server while dexc is running to trigger dex conn notes triggers js errors:

![image](https://user-images.githubusercontent.com/9373513/193954141-3982430f-f863-41a5-a15a-b90ee9b5f4b5.png)

![image](https://user-images.githubusercontent.com/9373513/193954172-657749f4-f415-47bf-abb4-507365ff6e60.png)

**Comment by chappjc** [comment]
There is no link to the Orders page that lists all orders, including historical:

![image](https://user-images.githubusercontent.com/9373513/193956460-ad7dd175-0f64-442e-904d-4a343bc0c617.png)

**Comment by martonp** [comment]
I't a little confusing to have this down arrow when the sidebar is open and clicking it doesn't do anything.
<img width="312" alt="Screen Shot 2022-10-09 at 1 37 18 PM" src="https://user-images.githubusercontent.com/6186350/194754854-8d2c0d11-6fd1-4e31-8bce-ba3f2838b957.png">

**Comment by martonp** [comment]
When you search for a market and there are no results, the entire screen readjusts. It would be better if the market sidebar had a fixed width and this didn't happen.
