### ISSUE TITLE
Binaries mentioned in releases are missing

### ISSUE THREAD

**Issue by xaur** [decred/dcrdex#1905]
[dcrdex v0.5.0](https://github.com/decred/dcrdex/releases/tag/v0.5.0) release page says:

> Binaries are attached at the bottom of this release. Just download the one for your system...

But I only see 2 Assets with the source code.

![dcrdex_v0 5 0](https://user-images.githubusercontent.com/24484727/196046548-6521daa4-f259-4e59-9905-790013291496.png)

[dcrdex v0.5.3](https://github.com/decred/dcrdex/releases/tag/v0.5.3) release says:

> Either download the file for your distribution below, or wait for the signed distributions to be created at https://github.com/decred/release/tags.

and

> NOTE: This release includes an experimental downloadable executable for Windows

But again only 2 assets below

![dcrdex_v0 5 3](https://user-images.githubusercontent.com/24484727/196046554-227c9c4d-48b7-4c18-8a64-519de34a3408.png)

Now that they are all replaced with v0.5.4 I guess few people will have any problem with that, but to avoid confusion the text can be tweaked a bit I think.

**Comment by chappjc** [comment]
Done.  Thank you for pointing this out.

**Comment by chappjc** [comment]
That's pretty funny, but that seems to just be a github display issue when listing all releases. If I click into v0.5.0, the entire notes show.

**Comment by xaur** [comment]
Oh so it is only truncated on the [all releases](https://github.com/decred/dcrdex/releases) page but I can see it in full via the [direct link](https://github.com/decred/dcrdex/releases/tag/v0.5.0). I don't remember GitHub to truncate releases before.

Anyways, the issue is fixed. Thanks.
