### ISSUE TITLE
UI: inaccurate Price warning (when placing limit order)

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#1908]
The warning on screenshot below (it only appears if I'm hovering over Price field that needs to be filled) seems to suggest that price should be an integer number.

On the other hand, when I was trying to set price at `0.0000099` BTC per DCR I was able to click on `Place order to buy DCR` button and it silently cut this price off to `0.000009` and let me successfully place an order (I didn't even notice that price was rounded down until later; it might be just sub-optimal UX when buying DCR, it is even worse when selling DCR because rounding down means I'm selling for less than I intended to if I don't double-check).

Instead I think it would be better if UI didn't allow me to enter a Price value that doesn't satisfy `Rate Step` in the first place (possibly highlighting `Rate Step` value in red  when I try to, so that I can see why it doesn't).

<img width="365" alt="image" src="https://user-images.githubusercontent.com/112318969/196187668-3ef3c6dc-6e7f-4a93-9aa1-0d81f0b045ff.png">

I'm running latest `master` of this repo on testnet.

**Comment by chappjc** [comment]
Instead of js validation when you change focus, we should look at using the `step` attribute. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#step

**Comment by norwnd** [comment]
Thanks for the hint, lets see if I can fix/improve this in a PR of my own.

**Comment by chappjc** [comment]
I tried the `step` attribute manually shortly after suggesting to check it out, and it didn't seem to actually enforce anything, although it did change the message that was displayed on hover.

I'm not sure what changes silently though.  As soon as the price field looses focus, it applies the rate step.  When you click "Place order..." the confirmation screen shows the rate with any rate step interval applied.  How can we make the price field more responsive?

**Comment by ukane-philemon** [comment]
> I tried the step attribute manually shortly after suggesting to check it out, and it didn't seem to actually enforce anything,

> Note: When the data entered by the user doesn't adhere to the stepping configuration, the [user agent](https://developer.mozilla.org/en-US/docs/Glossary/User_agent) may round to the nearest valid value, preferring numbers in the positive direction when there are two equally close options.

**Comment by norwnd** [comment]
I've been fiddling with this for last couple of days, will have something to show soon.

**Comment by norwnd** [comment]
Same thing with rounding to integer number is present for Market Buy Order as well (`mktBuyField` field), 

<img width="374" alt="image" src="https://user-images.githubusercontent.com/112318969/197753409-52b880b6-db0e-45c4-a6ff-472a4be054b7.png">

but let's discuss it in a separate issue (since I have a couple other questions related to Market orders I've outlined there) - https://github.com/decred/dcrdex/issues/1920

**Comment by JoeGruffins** [comment]
Looks really cool! Noticing a couple things while testing:

Can you also prevent negative values?

![image](https://user-images.githubusercontent.com/34998433/199151159-bb01f91f-d336-4727-a0ec-3de8cc6323c1.png)

Is the max order calculation correct? I don't have this much btc to sell.

![image](https://user-images.githubusercontent.com/34998433/199151344-6816922b-3a1a-4ff9-81c1-7b410dabe01a.png)

**Comment by buck54321** [comment]
I think this is resolved now?
