### ISSUE TITLE
ui: form to archive orders

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1911]
The `(c *Core) DeleteArchivedRecords(olderThan *time.Time, matchesFile, ordersFile string)` method could use an http api endpoint and a form accessible from the /orders page.  Three inputs: (1) time before which to purge data, (2) optional, purged matches csv file name, (3) optional, purged orders csv file name

**Comment by ukane-philemon** [comment]
@chappjc, I'd like to work on this.

**Comment by ukane-philemon** [comment]
`olderThan` sounds incorrect? correct me if am wrong. We mean to delete records `before` `olderThan`. maybe something like `endDate` instead. And the comment for `DeleteInactiveOrders` and `DeleteInactiveMatches` is incorrect too. Will fix it in a PR.

**Comment by chappjc** [comment]
> `olderThan` sounds incorrect? correct me if am wrong. We mean to delete records `before` `olderThan`. maybe something like `endDate` instead.

The variable name makes sense to me.  The function will delete records older than X.  `endDate` is more confusing.  

> And the comment for `DeleteInactiveOrders` and `DeleteInactiveMatches` is incorrect too. Will fix it in a PR.

The comments on the `interface` are strange yes.
