### ISSUE TITLE
For Market Buy/Sell DCR, Rate shows 0 (in Your Orders and Order History sections)

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#1919]
I've noticed that `Rate` has `0.000` value when looking at the orders inside of `Your Orders` (active orders) section: 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/112318969/197706937-b2967412-7e6d-4df5-bd6f-7ea0e6ff4cda.png">

while if I open an order page to see the details, rate value seems to be fine: 

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/112318969/197709843-9a92379d-3afb-45f7-9e85-390b876c2af0.png">

When I open Order History (`/orders` page) I see same 0 value for `Rate`: 

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/112318969/197709354-23cb7da7-66db-4bc8-8116-fab59a01cd0f.png">

Happens for both Market Buys and Market Sells.
I don't know whether this is limited to UI but might wanna investigate this myself later.

**Comment by buck54321** [comment]
market orders don't have a rate
