### ISSUE TITLE
redeems do not require confs if match revoked

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1924]
Taker will skip confirming the redemption if they do not have server's ack of their redeem request, as stated here:
https://github.com/decred/dcrdex/blob/1619a9ccfefe12c15ffa8e0b788013d6432431b8/client/db/types.go#L336-L337

I think the logic should be changed to check all redemptions.

_Originally posted by @JoeGruffins in https://github.com/decred/dcrdex/issues/1909#issuecomment-1282496285_

This really refers to **revoked** matches skipping the redeem confirm requirement.

This might be a simple fix to the logic, but it needs to be considered carefully when we change the canonical definition of match "activeness".  Will likely require updates to `(*trackedTrade).matchIsActive` to consider the requires confirms bool

**Comment by JoeGruffins** [comment]
I'll look into this.
