### ISSUE TITLE
client: litecoind send settxfee error

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1925]
On v0.5.4, trying to send LTC from the wallets page, using litecoind (Litecoin Core), I hit:

> [TRC] CORE[ltc]: feeRateWithFallback using caller's suggestion for fee rate, 1.
> [ERR] WEB: send/withdraw error: SendToAddress error: error setting transaction fee: rawrequest (settxfee) error: -8: txfee cannot be less than wallet min fee (0.00010000 LTC/kvB)

I never had that problem before, so not sure why now.  But I checked `litecoind --help` and there's this:

>   -mintxfee=<amt>
>        Fees (in LTC/kB) smaller than this are considered zero fee for
>        transaction creation (default: 0.0001)

Which is strange since the min relay fee is smaller
 
>   -minrelaytxfee=<amt>
>        Fees (in LTC/kB) smaller than this are considered zero fee for relaying,
>        mining and transaction creation (default: 0.00001)

I don't know how this wasn't hit before, but 1 litoshi/Byte (0.00001 LTC/kB) transactions relay just fine and make up the majority of the block transactions.  So should user's just set `mintxfee=0.00001`?

Even `estimatesmartfee` says to use something very low:

```
$  litecoin-cli estimatesmartfee 1
{
  "feerate": 0.00000994,
  "blocks": 2
}
```

That makes no sense to me since it's less than 1 lit/B, but whatever.

FWIW, our simnet harness says this:

```
$  ./alpha estimatesmartfee 1
{
  "feerate": 0.00010000,
  "blocks": 2
}
```

**Comment by vctt94** [comment]
Can take a look at it

**Comment by chappjc** [comment]
We can't use `settxfee` to fix the user's setting.

```
$  ./litecoin-cli -testnet settxfee 0.00001
error code: -8
error message:
txfee cannot be less than wallet min fee (0.00010000 LTC/kvB)
```

Any other idea of how to handle this?

If there's an RPC to see what the current `mintxfee` is set to, we can use that to clamp what we give to `sendtoaddress`...

**Comment by ukane-philemon** [comment]
> I'll just document in the release notes that litecoind should be run with mintxfee=0.00001

Since we know what the default is and we can't use `settxfee` when our feeRate is less, I think we can stick with this, at least for now.

**Comment by chappjc** [comment]
No longer an issue since we don't use settxfee any more.
