### ISSUE TITLE
Missing signatures for release binaries

### ISSUE THREAD

**Issue by xaur** [decred/dcrdex#1942]
[v0.5.4](https://github.com/decred/dcrdex/releases/tag/v0.5.4) and [v0.5.5](https://github.com/decred/dcrdex/releases/tag/v0.5.5) have the binaries and the manifests with hashes. Decred [releases](https://github.com/decred/decred-binaries) have "spoiled" me to also want signatures for the manifests. It would be nice to have those too, to know a malicious actor didn't replace both the binaries and their hashes.

**Comment by chappjc** [comment]
I can only sign with my own pgp keys.  If you want signatures, you'll have to wait for binaries to appear on the https://github.com/decred/decred-binaries repo.  How to improve this?  When there is a critical fix, I will post patches immediately.

**Comment by xaur** [comment]
To be clear, I made this issue because I think releases with signed builds are nice for security and just look pro. But as long as decred-binaries post new dcrdex builds once in a while, there is no big problem and it is fair to redirect there. And it saves dcrdex team from the pita of dealing with PGP.

Re what can be improved, I think there are not too many options. C0 is rolling releases at their own schedule based on core software development. At the same time, it is good for dcrdex to have own release binaries to issue patches quickly. So we have two "releasers" here who can naturally have two release keys. And so the simplest improvement I imagine is to sign with your own key, if that is feasible.

Also, if I understand the [release](https://github.com/decred/release) tool correctly, it can be used to let different people build identical binaries, which can complement (or even be a soft alternative to) signing. For example, I could find messages from 2-3 developers that they obtained same hashes and that would be an improvement over hashes from a single source.

**Comment by xaur** [comment]
[v0.5.7](https://github.com/decred/dcrdex/releases/tag/v0.5.7) has the sigs so this is mostly resolved!

A smaller issue now, I had to obtain the right key by first learning its fingerprint and then finding a working homeserver for it. One good practice I've seen to ease the gpg pains was to just commit the pubkey into the repo (e.g. [Electrum](https://github.com/spesmilo/electrum/tree/master/pubkeys)), or at least pin the correct fingerprints in the repo (e.g. [Bitcoin](https://github.com/bitcoin/bitcoin/tree/master/contrib/builder-keys)).

**Comment by xaur** [comment]
[v0.6.2](https://github.com/decred/dcrdex/releases/tag/v0.6.2) and [v0.6.3](https://github.com/decred/dcrdex/releases/tag/v0.6.3) don't have sigs again.

**Comment by xaur** [comment]
I guess this is considered completed via having the signatures here: https://github.com/decred/decred-binaries/releases/tag/v1.8.1
