### ISSUE TITLE
UI: Order status discrepancy between different views

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#1945]
Out of 3 different forms that show order status I can see:
- `executed` on 2 of them

<img width="350" alt="image" src="https://user-images.githubusercontent.com/112318969/200587784-9b453340-8a11-4eca-84c2-39535476b4ae.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/112318969/200587902-e01d1208-47fa-4bfc-b189-a7aa56843c4e.png">

- `settling` on this one

<img width="350" alt="image" src="https://user-images.githubusercontent.com/112318969/200588090-50684388-29ad-4d9d-8eec-017d4c5ef059.png">

On current `master`, I created 2 limit orders that matched (trading with myself basically), and it seems corresponding ETH Maker Swap didn't get mined in time, DEX server revoked it:
```
2022-11-08 12:35:38.391 [ERR] CORE: notify: |ERROR| (order) Swap reporting error - Error notifying DEX of swap for match dbfb6b3b5f295319a890c6967ecb70e28b20b56baee9e3a636caa3c475591016: error sending 'init' message: rpc error: error code 24: failed to find contract coin 0x2ef2c3bab324b45da3a2be2fba46890f68ac91318250f5eddfe2e0b74118fbbf - Order: dd9386a5ed4cefadce933cfa4315285fb2d888f12b4d6ad5dfc44028b8457577

...

2022-11-08 12:39:15.848 [WRN] CORE: Match dbfb6b3b5f295319a890c6967ecb70e28b20b56baee9e3a636caa3c475591016 revoked in status MakerSwapCast for order dd9386a5ed4cefadce933cfa4315285fb2d888f12b4d6ad5dfc44028b8457577
```

(according to Etherscan txn is still pending several hours after; it's probably because 32 Gwei is much lower than current base-fee):

<img width="350" alt="image" src="https://user-images.githubusercontent.com/112318969/200590703-178b9056-7e2e-4b2a-a260-0fb30687463d.png">

I think `settling` status is the correct one, because this Maker Swap txn could still be mined, and if that happens `dexc` should probably perform refund afterwards.

--------------------------------------------------------------------------------

**Another thing** (seems to me) could be off is that Ethereum wallet didn't show corresponding funds in ETH (both ? Maker Swap txn amount + reserved ETH for refund) being locked - shouldn't it lock some ETH to be able to perform that refund later (if Maker Swap txn did get mined, and [it was mined actually](https://goerli.etherscan.io/tx/0x2ef2c3bab324b45da3a2be2fba46890f68ac91318250f5eddfe2e0b74118fbbf)) ?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/112318969/200595982-ab3b6aa4-8aa8-49f8-b685-105cd4fc767e.png">

While that [Maker Swap txn](https://goerli.etherscan.io/tx/0x2ef2c3bab324b45da3a2be2fba46890f68ac91318250f5eddfe2e0b74118fbbf) was hanging in mempool, I sent all the funds out of Ethereum wallet just to see what happens:
```
2022-11-08 14:42:38.912 [TRC] CORE[eth][ETH][RPC]: Sending signed tx via "goerli.infura.io"
2022-11-08 14:42:39.117 [INF] CORE: notify: |SUCCESS| (send) Send Successful - Sending 0.096933917 eth to 0xdcFF22f9Ea62eefC797550B007FaB5b3b103a5f9 has completed successfully. Coin ID = 0xdf39cd55c67640262cce68e515dd5dd9cc975341831202a2a79c94d66ea52191
2022-11-08 14:42:39.322 [TRC] CORE: notify: |DATA| (balance) balance updated
2022/11/08 17:42:39 "POST http://127.0.0.1:5758/api/send HTTP/1.1" from 127.0.0.1:63202 - 200 88B in 1.319308499s
```
That send ^ was successful, and I got another txn in mempool with gas price = ~ 80 Gwei. It didn't get mined for 10-20 minutes though, just was sitting in mempool (with base fee being ~60 Gwei). In about 20 minutes Maker Swap txn got mined (like I mentioned above), and my 2nd send-txn [got dropped ?](https://goerli.etherscan.io/tx/0xdf39cd55c67640262cce68e515dd5dd9cc975341831202a2a79c94d66ea52191), maybe it was using same nonce (but I couldn't find nonce on Etherscan to compare, and 2nd txn had gas price set at ~80 Gwei ... I would expect it to be mined first if it had same nonce ... but that's probabilistic, so can't count on that).

So, now I have to refund my Maker Swap txn, but Ethereum wallet still doesn't show any ETH being locked:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/112318969/200610458-91986b8a-3910-4942-9a99-cc774ab4c17a.png">

I tried to send it all out once again, this time [it worked](https://goerli.etherscan.io/tx/0x1e4cafbbd8bbb017ecc6652a2ab2c92c708f80c3fc95b12772a5f0a03947a407)):

<img width="350" alt="image" src="https://user-images.githubusercontent.com/112318969/200614277-15659f0e-1235-4162-8c30-5e816e48790a.png">

and now I probably don't have enough ETH to perform that refund I'll be needing.

**Comment by chappjc** [comment]
Thanks for raising the issue about order statuses.  They should all be settling, not executed, while waiting on a revoked match to wrap up.  I've been irked by this in the past too, but have not made an issue.

About ETH, we got majorly set back when the light client was bricked and we had to switch to RPC providers.  Reserves have been a headache for a long time though, but it looks to have failed badly in this case.  Regarding the nonces, we've seen that with the RPC providers, we have more difficulty with nonces, and @JoeGruffins has started a resolution in https://github.com/decred/dcrdex/pull/1733 (see `lastNonce` field and the helper methods).  Thanks for looking at these ETH issues as well, we have bugs to address with the big overhaul to an RPC provider instead of our own native light (les) client.

**Comment by chappjc** [comment]
> (according to Etherscan txn is still pending several hours after; it's probably because 32 Gwei is much lower than current base-fee):

Oh about this, I assume you set up your own dcrdex testnet server to do this, so what you need to do in the future is set maxFeeRate for eth to be higher than any foreseeable base fee.  Say 30 gwei/gas.

**Comment by JoeGruffins** [comment]
Thank you @norwnd testing eth! Please continue!

Is the order status thing just eth or all coins?

I had not noticed the reserves are not working currently. Will look into it.

As @chappjc mentioned we recently, and rather unexpectedly, switched from light nodes to rpc, so we have less information. No info on mempool really. Which is mostly ok, as we cannot trust the mempool anyway.

About low fee, hopefully the resolution of #1932 will fix this.

I still need to study up on what happens with replaced transactions now with the recent eth change from bidding for fees to a hard coded fee based on number of recently mined transactions. I guess we need to get acceleration transactions going for eth like we have for btc.

**Comment by norwnd** [comment]
> Is the order status thing just eth or all coins?

Same happens for DCR:

<img width="100" alt="image" src="https://user-images.githubusercontent.com/112318969/200758955-ce0c6fde-7544-4925-996e-f0a000c417d3.png">

<img width="100" alt="image" src="https://user-images.githubusercontent.com/112318969/200758997-db523c9f-129e-4fac-a259-43d447383ebd.png">

<img width="100" alt="image" src="https://user-images.githubusercontent.com/112318969/200759060-b2ada73a-21c0-410d-9fbc-47417fe1b0ec.png">

> I guess we need to get acceleration transactions going for eth like we have for btc.

Eth gas prices are very spiky indeed, probably it is even more important to have acceleration for ETH than any other coins because having huge default fee (of, say, 300 Gwei per gas unit) is a lot for "simple retail user" to swallow, many would rather wait and accelerate (than pay hundreds of $).
I think I've seen something like [2 * baseFee being used as default](https://github.com/norwnd/dcrdex/blob/2e00ff37698d0340595d61b1ee5b9164aea8e973/client/asset/eth/eth.go#L1883-L1910), if server-provided `maxFeeRate` is lower than current `baseFee` (I might have untangled that code incorrectly though); maybe `2 * baseFee` value there is a bit too much, why not use just `baseFee` (or maybe `1.2 * baseFee`), that will increase the need for acceleration though ?

**Comment by JoeGruffins** [comment]
>  having huge default fee (of, say, 300 Gwei per gas unit)

That default is not all used. It is the max we are willing to pay per unit gas. Eth will decide what is paid based on how populated recent blocks have been. The gas price will be whatever this says at the time https://ycharts.com/indicators/ethereum_average_gas_price The price will likely be under 60 gwei per gas.

With eth we no longer bid for gas. This is a a recent change with eip 1559 which was included in the London hard fork https://ycharts.com/indicators/ethereum_average_gas_price

**Comment by chappjc** [comment]
> Ethereum gas prices are very spiky indeed, probably it is even more important to have acceleration for ETH than any other coins because having huge default fee (of, say, 300 Gwei per gas unit) is a lot for "simple retail user" to swallow, many would rather wait and accelerate (than pay hundreds of $). I think I've seen something like [2 * baseFee being used as default](https://github.com/norwnd/dcrdex/blob/2e00ff37698d0340595d61b1ee5b9164aea8e973/client/asset/eth/eth.go#L1883-L1910), if server-provided `maxFeeRate` is lower than current `baseFee` (I might have untangled that code incorrectly though); maybe `2 * baseFee` value there is a bit too much, why not use just `baseFee` (or maybe `1.2 * baseFee`), that will increase the need for acceleration though ?
> 
> Also it looks a bit weird to me that [server configuration value (hardcoded) is used](https://github.com/norwnd/dcrdex/blob/2e00ff37698d0340595d61b1ee5b9164aea8e973/client/asset/eth/eth.go#L1883-L1885) instead of just current `baseFee` that `dexc` can itself estimate.

Seems like you are thinking in terms of the old fee structure.  You can set your max fee cap to 10000 and it will only pay the current block's baseFee (set by network consensus), plus a tip, which is set separately.

What this means is it's actually far **less** important to implement accelerations for ETH, even pointless I would argue, because eip1559 makes the transactions *dynamic* with respect to fees in the first place.  The only reason not to use a crazy high maxFeeRate is to prevent reserving too much eth.

**Comment by chappjc** [comment]
Oh, about the refund reserves, in https://github.com/decred/dcrdex/pull/1866/files/9efdb3091f6188f5fbdbdf1e609c0ab3ab86e5fb#diff-13a4a6b12c1ae844ef90151638f194427cfdc545fceb58d52c0f6f33b81d859bR5335 I discovered a bug where we neglected to store the refund reserves to the client DB.  This might be the source of the problem you noticed, but I think there are still many remaining issues with reserves we will have to squash.

**Comment by norwnd** [comment]
> Seems like you are thinking in terms of the old fee structure. You can set your max fee cap to 10000 and it will only pay the current block's baseFee (set by network consensus), plus a tip, which is set separately.

You are right, thanks for clarification.

> The only reason not to use a crazy high maxFeeRate is to prevent reserving too much eth.

Or something like [this](https://decrypt.co/99219/otherside-nft-mint-burned-more-157m-ethereum) as well.

**Comment by chappjc** [comment]
> Or something like [this](https://decrypt.co/99219/otherside-nft-mint-burned-more-157m-ethereum) as well.

That's entirely up to the users.  We have a max fee rate limit in the eth wallet settings for this.  https://github.com/decred/dcrdex/blob/367ea22354f1b55cf5929f7a71c30a2ca75ec6c7/client/asset/eth/eth.go#L90-L98

**Comment by JoeGruffins** [comment]
> What this means is it's actually far less important to implement accelerations for ETH, even pointless I would argue

It looks like norwnd's txn got stuck though. If you set the max too low... do you need to set it higher?

Setting something super high at the beginning is probably the best play though.

**Comment by chappjc** [comment]
> It looks like norwnd's txn got stuck though. If you set the max too low... do you need to set it higher?

Right be cause maxFeeRate on server was too low.  Your https://github.com/decred/dcrdex/issues/1932 will fix this.

There's no way to accelerate above maxFeeRate because that goes beyond order reserves.  We can drastically modify the meaning of accelerate to attempt to check for available balance beyond reserves, but I think 1932 is the fix.
