### ISSUE TITLE
UI: Maker Swap - display expected Refund time

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#1947]
When this happens:

![image](https://user-images.githubusercontent.com/112318969/200620148-5e18cd04-3f8e-4987-880a-a9cff375fde5.png)

user might get uneasy, starting at this message for hours (might even contact support asking for help):
```
Refund (eth, you)
<Pending>
```

The info about **when refund will happen** would be useful to show:

```
Refund (eth, you) will happen after: ~%s
<Pending>
```

I guess `%s` should reflect the value that can be seen in this log:
```
2022-11-08 12:17:01.277 [INF] CORE: Contract coin 0x2ef2c3bab324b45da3a2be2fba46890f68ac91318250f5eddfe2e0b74118fbbf (eth), value = 4000, refundable at 2022-11-09 11:16:57 +0300 MSK (receipt = { tx hash: 0x2ef2c3bab324b45da3a2be2fba46890f68ac91318250f5eddfe2e0b74118fbbf, contract address: 0xa483b6166dA8Da6748B29Af35f96C4F9388c456C, secret hash: ac4587cb9eb12f99f0ce0b5ae8c7b969c64aa680da4f03d85ffb1297dae5355c }), match = dbfb6b3b5f295319a890c6967ecb70e28b20b56baee9e3a636caa3c475591016
```

Could similar happen to `taker` ? when he also needs to refund.

**Comment by norwnd** [comment]
Maybe there is no need to use exact `receipt.Expiration()` value (that will require adding it to `Match`, webserver API, and storing it in DB probably) and just take `Match.stamp` + `20h` as rough estimate ? Even if this `20h` value changes in the future on the back-end, and we forget to adjust it in UI - that won't be a big deal I think.

**Comment by chappjc** [comment]
> Maybe there is no need to use exact `receipt.Expiration()` value (that will require adding it to `Match`, webserver API, and storing it in DB probably) and just take `Match.stamp` + `20h` as rough estimate ? Even if this `20h` value changes in the future on the back-end, and we forget to adjust it in UI - that won't be a big deal I think.

Yeah, the 8hr taker / 20hr maker lock times are compile-time constants, used across all assets.  No need to store anything new, I think.  `Core` decides the lock time when making new contracts like `matchTracker.matchTime().Add(trackedTrade.lockTime{M,T}aker)`, and similar when auditing the counterparty contract.  I think it's fair to skip adding the lock time values to the `core.Match` struct, which is sent via http to the ui, and instead have the same 8/20hr constants in the JavaScript somewhere.

**Comment by chappjc** [comment]
One thing to keep in mind is that when lock time is passed, it is not necessarily refundable at that moment.  It varies with asset, but in DCR and BTC (and probably all BTC clones), the median of the last 11 blocks must be after lock time.  So we need to have messaging for that relatively brief state where we can't give any ETA.  When in this state, the logs are phrased as "expired %v ago, but additional blocks are required by the %s network".  Frontend would probably not mention blocks, just hint that the refund is imminent.

**Comment by norwnd** [comment]
Looking into it.
