### ISSUE TITLE
ui: markets view not working for unsupported asset

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1949]
Use **client/webserver/live_test.go**, `go test -tags lgpl,live -timeout 60m`, and MONA-KMD market for testing.

![image](https://user-images.githubusercontent.com/6109680/200818929-fa08d878-9918-46da-a04b-f873491f2358.png)

![image](https://user-images.githubusercontent.com/6109680/200819043-d4670d60-13e2-4bec-b937-2c23eef2cc78.png)

**Comment by ukane-philemon** [comment]
I'd like to look into this.
