### ISSUE TITLE
server/market: insufficient balance error on DCR/ETH market

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#1950]
On `testnet` (using `dex-test.ssgen.io:7232` DEX server) on `master` I've set up DEX account from scratch, sent some ETH and DCR funds to it (see screenshots below), 

when trying to create limit-order I'm encountering `error code 36: insufficient balance` error:

<img width="150" alt="image" src="https://user-images.githubusercontent.com/112318969/200833710-c50ee744-93b1-4e2c-8f4b-8ae5a8d83bea.png"> <img width="150" alt="image" src="https://user-images.githubusercontent.com/112318969/200833865-a9814187-8096-4296-ab71-a5182dfbee2a.png">

even though I have quite a lot of [ETH](https://goerli.etherscan.io/address/0x9eEd1b4A72B4Bf7768A852c48715531b1Ee4a26c) and [DCR](https://testnet.dcrdata.org/address/Tsdoz9KLXVP8RigFKM5z2VxCPgmPadd4Wzp?chart=balance&zoom=l9bppls0-laj6crk0&bin=month) in those wallets ^ (I've also topped up ETH wallet to have `0.3` ETH there just in case, and waited a bit, that didn't help). Previously I could trade roughly with similar limit orders on `dex-test.ssgen.io:7232`.

Happens both for `buy` and `sell` DCR/ETH limit orders, and there is this in `dexc` logs:
```
2022-11-09 12:42:52.556 [ERR] WEB: error placing order: new order request with DEX server dex-test.ssgen.io:7232 market dcr_eth failed: rpc error: error code 36: insufficient balance
```

- could be something with `dex-test.ssgen.io:7232` configuration, or a bug (maybe you can check the logs to fetch more details ?)
- and I think `insufficient balance` error message is not ideal here; user can see plenty of non-locked funds in his wallets, and limit form even shows that he can buy 22 lots! Should probably be more specific: `DEX server sees your ETH balance to be %s, order requires: %s`

Probably related to funds-locking issues I've observed in https://github.com/decred/dcrdex/issues/1945; I was able to successfully place DCR/BTC orders with that same setup.

**Comment by norwnd** [comment]
@JoeGruffins I can leave that setup "as is" for several days, in case you have a fix for it I can test against,

or maybe try to spin up dex server locally and see whether I can add more details to logs and reproduce it.

**Comment by chappjc** [comment]
The ETH node on dex-test.ssgen.io:7232 has been down for several days.  Don't use it or nothing will swap.  Sorry I didn't announce.  This also explains why the server doesn't see the latest balance.

**Comment by chappjc** [comment]
eth on dex-test will be back again shortly, about an hour.  Will ping on matrix when it is synced again.

But having considered the issue, I think it is confusing that server just says `insufficient balance` instead of `network node not synchronized`.  We can look at the server code to see how to improve that.
