### ISSUE TITLE
client/eth: Add jwt secret config option.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1956]
This may be a recent change, but geth now requires a secret to be communicated to use over http. It looks like a random 32 byte hex is fine, as that is what prysm and geth will use for authentication. We need to it to be a new config option and need to add one to the simnet harness and startup script.

https://github.com/ethereum/go-ethereum/blob/master/node/jwt_handler.go

Let me know if I am missing something, I don't think this was mentioned when the providers were added. Maybe it's just new to geth. A full node should work fine as a provider correct?

**Comment by JoeGruffins** [comment]
I can add this.

**Comment by chappjc** [comment]
Thanks @JoeGruffins.  This will be good on server too so geth doesn't need to run on the same machine.

I think http has always required a token, but we've used IPC.

**Comment by JoeGruffins** [comment]
Oh, that's right, we can point the clients to the IPC file. I suppose this may be more useful for the server then.
