### ISSUE TITLE
shutdown of core should guarantee all subsystems are done

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1960]
Got this in Decrediton testing.  This happened because after Core is shutdown (according to waitgroup), Decrediton's adapter closed the logger and nil'd the log rotator, however, it seems that one of the `asset.Wallet`s still hit the `TipChange` callback.  Need to see if there is a simple way for Core shutdown to do a bit better cleanup.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f8e719c7f07]

goroutine 240533 [running]:
github.com/jrick/logrotate/rotator.(*Rotator).Write(0x0, {0xc009a68480, 0x76, 0x2?})
	/home/jon/go/pkg/mod/github.com/jrick/logrotate@v1.0.0/rotator/rotator.go:133 +0x27
main.logWriter.Write({}, {0xc009a68480, 0x76, 0x78})
	/home/jon/github/decred/decrediton/modules/dex/libdexc/log.go:25 +0x56
github.com/decred/slog.(*Backend).printf(0xc00023d880, {0x7f8e721f330c, 0x3}, {0x7f8e721f3b88, 0x4}, {0x7f8e7222ddad, 0x29}, {0xc003e1e060, 0x2, 0x2})
	/home/jon/go/pkg/mod/github.com/decred/slog@v1.2.0/log.go:340 +0x342
github.com/decred/slog.(*slog).Errorf(0x0?, {0x7f8e7222ddad?, 0x7f8e7184e9a7?}, {0xc003e1e060?, 0x7f8e72b5db20?, 0x7f8e00000001?})
	/home/jon/go/pkg/mod/github.com/decred/slog@v1.2.0/log.go:466 +0x5f
decred.org/dcrdex/client/core.(*Core).tipChange(0xc0001f4000, 0x58acfd0?, {0x7f8e72cfa5a0, 0xc0037dfd60})
	/home/jon/go/pkg/mod/decred.org/dcrdex@v0.5.6/client/core/core.go:7147 +0x274
created by decred.org/dcrdex/client/core.(*Core).loadWallet.func1
	/home/jon/go/pkg/mod/decred.org/dcrdex@v0.5.6/client/core/core.go:2027 +0xaa
/home/jon/github/decred/decrediton/node_modules/electron/dist/electron exited with signal SIGABRT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ukane-philemon** [comment]
>  Need to see if there is a simple way for Core shutdown to do a bit better cleanup.

Anything specific in mind?

**Comment by chappjc** [comment]
> > Need to see if there is a simple way for Core shutdown to do a bit better cleanup.
> 
> Anything specific in mind?

What I was thinking about was probably that `(*Core).tipChange` needs to be launched using `Core`'s `WaitGroup` so the app doesn't shutdown while it's still running.  Where the closure is defined in `loadWallet`:

```go
	tipChange := func(err error) {
		// ...
		c.wg.Add(1)
		go func() {
			defer c.wg.Done()
			c.tipChange(assetID, err)
		}()
	}
```

That still leaves a little race with perfectly timed shutdowns since that closure can be called regardless of the lifetime of `Core`.  We could try to address that by adding  a `context.Context` arg to `client/asset.WalletConfig.TipChange func(error)`, which in btc's case would be passed in from `(*intermediaryWallet).watchBlocks` and `reportNewTip`.  Then `Core` can be sure that the waitgroup is incremented before the context is canceled, meaning shutdown will wait for that goroutine.

That last bit feels a bit janky though.  Maybe we should have used a channel to signal to a receiver loop goroutine started from `(*Core).Run`, which would pertain directly to `Core`'s lifetime.   Probably not worth refactoring it though.

**Comment by ukane-philemon** [comment]
I will implement the first part of your suggestion for `tipChange`.
