### ISSUE TITLE
utxo assets need redeemed swaps monitored through confirmation too

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1962]
Although less critical than ETH where txns get clobbered very easily by nonce replacement, Bitcoin's mempool can get so full that transactions are purged (and never mined).  In the last couple days, this threshold has been as high as 11 sat/vB.  With no redeem rebroadcasting for UTXO assets, that was nearly a problem with client configs with very high redeem confirmation targets, like 6.

In addition to txns being evicted from mempool prior to being mined, broadcasting can fail with errors like `error sending redeem transaction: rawrequest (sendtransaction) error: -26: mempool fee not met, 143 < 1924`.  While an error like that from a full-node wallet like bitcoind is good because it will keep trying to rebroadcast, the light clients more readily declare success if peers decide not to respond in error, or we simply move on assuming the publish succeeded.  In this light client case, the neutrino broadcaster should continually rebroadcast, eventually succeeding when network conditions permit, but this could be too late.  It would be best to have logic to change the fee and try a new redeem.

**Comment by JoeGruffins** [comment]
I can work on this.

Do we also worry about refunds? Eth doesn't worry about refunds yet, right? Perhaps it should as a separate issue?
