### ISSUE TITLE
ui: verify order view is clipped at the top

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#1976]
Verify order form is clipped at the top by to page header.
This also hides some essential information about order when scaling is used in browser: 1st screenshot = 100%, 2nd screenshot = 120%.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/112318969/204100606-42720f5c-4d4e-45d8-8281-d8b60979dc62.png">

<img width="250" alt="image" src="https://user-images.githubusercontent.com/112318969/204100598-084307d7-cebe-4828-9094-5c51c3e1a69a.png">

Even at 100% scaling that cut-off looks kinda bad to me,

I tried couple of things but couldn't really make it work, I'll defer to someone more experienced with html/css to figure this out.

**Comment by ukane-philemon** [comment]
You should be able to scroll if the form is too long.

**Comment by norwnd** [comment]
The things is 
- I can scroll down easily
- I'm able to scroll up, but not all the way - it hits some limit after which strong gravity kicks in (and it is pretty hard to fight this gravity with 120% scaling to be able to read DEX-server address that's up there)

**Comment by JoeGruffins** [comment]
I can scroll up just fine on Firefox. What browser is this?

**Comment by norwnd** [comment]
> I can scroll up just fine on Firefox. What browser is this?

Firefox it was, I observed it in Chrome/Brave as well when scaling but can't seem to reproduce it now on master ...

actually I introduced it in https://github.com/decred/dcrdex/pull/1977 (which still  needs further work), so I'll make sure to fix it there.
