### ISSUE TITLE
ui: send verification total send value seems wrong

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1982]
Shouldn't `value` be `totalSend` on the third line?

https://github.com/decred/dcrdex/blob/4685064b998de6e5a7dea26e89f8c1ffb258d10e/client/webserver/site/src/js/wallets.ts#L289-L291

**Comment by ukane-philemon** [comment]
Nice catch. You're correct, fiat value is incorrectly displayed for `value` instead of `totalSend`.
