### ISSUE TITLE
ui: user should be able to acknowledge order disclaimer

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1985]
![image](https://user-images.githubusercontent.com/6109680/205622695-b6f2f5d0-2d57-41da-abf6-f50c21193156.png)

Should be able to hide that message somehow.

**Comment by ukane-philemon** [comment]
I could be a pita for some users to always check a  checkbox for every order. I think it makes sense to acknowledge order disclaimer once?

**Comment by buck54321** [comment]
> I think it makes sense to acknowledge order disclaimer once?

That's what I meant. I'm not suggesting they need to acknowledge it before ordering or every single order. .They should be able to hide the message once (acknowledge) and it stays hidden, maybe with a short placeholder message that they can click to re-expand or something. Probably just use `State.store/fetch` to remember the state.

**Comment by ukane-philemon** [comment]
> I'm not suggesting they need to acknowledge it before ordering or every single order.

I know. This acknowledgement would be validated  on the client server and trade rejected if no acknowledgement, I think.

**Comment by buck54321** [comment]
> > I'm not suggesting they need to acknowledge it before ordering or every single order.
> 
> I know. This acknowledgement would be validated on the client server and trade rejected if no acknowledgement, I think.

No no no. This has nothing to do with the user's ability to order. We are just hiding the message.

**Comment by buck54321** [comment]
This change should not touch **core** or **webserver**.

**Comment by buck54321** [comment]
I'm just going to assign myself here.

**Comment by ukane-philemon** [comment]
I was thinking acknowledgement of order disclaimer is becoming a minor requirement to place an order. But I see you only intend to hide the message.

**Comment by chappjc** [comment]
Yeah, no more hoops to place and order, just cleaning up the UI if you've seen the message before.   :wink:
