### ISSUE TITLE
Switch client browser frontend to postbond instead of legacy fee register

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1991]
With all the foundational piece in place for bonds, this is one of the next steps https://github.com/orgs/decred/projects/2

For the UI, what we do depends on if we intend to support both the legacy fee and bonds in the next release. I don't think we should give the choice, only bonds.

So, while we transition in development, I think we should start by showing two options at /register - one that uses the legacy fee and one that uses a bond. But since it's only for developers to use either as needed, I don't think we should make it a single polished form with a selector. In fact, two separate forms shown simultaneously where you just use one of the forms might make the most sense. Otherwise if we make a nice selector on a single form, we're going to have to change that when the legacy fee is dropped. If there are two separate forms shown side-by-side, we just remove one when it's time to drop the fee for the next release.

**Comment by itswisdomagain** [comment]
I suppose we'd only want to use legacy registration if we're having some issues with bonds, otherwise, we would want to focus on using and testing bonds. If so, how about UI shows only bonds while we continue to support legacy registration via dexcctl for now.

In any case, I'd like to take this up. Sounds like it would benefit from #1990 but doesn't depend on it?

**Comment by chappjc** [comment]
Thanks.

But until bond rotation is in, with settings for tier maintenance, I don't think we want to use bonds even in dev just yet.  It'll be super annoying to go to dexcctl to postbond every few minutes on simnet

**Comment by chappjc** [comment]
I take back my last comment.  I agree with you.  We need to take the plunge to get this into production asap.
Let's do it.  Thanks for taking this on, @itswisdomagain.
