### ISSUE TITLE
App password change isn't synched with Native wallets

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2007]
When I use **Remember my password** on login, and then change App password to a different one Native wallets seem to be not aware of the change (while other parts of the app are aware: e.g. when asking to show seed new password works fine):

[password-change-issues.webm](https://user-images.githubusercontent.com/112318969/209271544-1f77c1c3-0da5-4638-bd7f-68d2a177273d.webm)

Note:
- the error ^ is different when I'm changing password for the 2nd time (from 8 symbols to 2). Or maybe it's just a different flavor of the same issue
- restarting **dexc** seems to be resolving the issue (logout probably too, I don't use it very often, didn't check)
- the issue doesn't seem to appear when **Remember my password** on login isn't checked

**Comment by JoeGruffins** [comment]
Can confirm this behavior after changing the app password. After the second change, the error is different and looks something like `Error opening wallet: cached encrypted password not found for auth token: 16812e05f28b5070f2b4014e8ba5151f1c4e986829676d3fc67c4b925d6da4bf`

**Comment by JoeGruffins** [comment]
I will look into this if @norwnd is not already.

**Comment by norwnd** [comment]
> if @norwnd is not already.

I'm not, go ahead!

**Comment by JoeGruffins** [comment]
Does #2015 fix it?

**Comment by norwnd** [comment]
Doesn't seem to solve it for me, still getting same error after changing password for the first time:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/112318969/210069932-6e7849a8-d1f8-41c4-b48a-c545bd38fb86.png">

and after changing 2nd time:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/112318969/210070183-63b07fc1-262d-491e-a7d5-38080e2587ba.png">
