### ISSUE TITLE
client does not recognize manually broadcast refund

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2009]
This is a rare scenario, but I think might be worth looking into in case there is more to it.

I was testing manual refunds [as per these discussions](https://github.com/decred/dcrdex/issues/952), on `testnet` I've done this:
- created DCR-USDC order
- took/matched against it with another **dexc** instance (**Taker** on screenshot below), here is [the relevant DCR swap contract](https://testnet.dcrdata.org/tx/f403a9b58ad27a1d00df7c801263548a63f2842f0349898c1af186a69564678f/out/0)
- shut down my **dexc** instances to trigger refunding scenarios
- manually broadcasted **Taker** [refund transaction](https://testnet.dcrdata.org/tx/a0d0adf9f7132672067b7497cc49df377e9801de38b8fb9c0de3788f994baeee/out/0) I pulled out from logs, it got mined after lock-time expired
- restarted my **Taker dexc** instance, and it discovered [this non-existent transaction](https://testnet.dcrdata.org/tx/4639d4dc9bef6977d59c20681f10dcec5f754387a47bb875bafc6ac9a73e5a76) as my refund, see **Refund (dcr, you)** below

<img width="400" alt="image" src="https://user-images.githubusercontent.com/112318969/209617022-411e7376-edf1-49c7-9773-540057b4ec98.png">

**Comment by norwnd** [comment]
In the logs I don't see any mentions of [non-existent transaction](https://testnet.dcrdata.org/tx/4639d4dc9bef6977d59c20681f10dcec5f754387a47bb875bafc6ac9a73e5a76), or the correct [manually broadcasted transaction](https://testnet.dcrdata.org/tx/4639d4dc9bef6977d59c20681f10dcec5f754387a47bb875bafc6ac9a73e5a76). The most relevant bits about refunding this match seem to be:
```
2022-12-27 05:13:38.321 [DBG] CORE: Refundable match 8038a42b394ff7250fce0317ce421ac9701b6bb569b0e94ebc1c5b593cf806f9 for order 5bba41c5e2f61fc6793193eace7bc56308c6a3eddbdf693a48d63f33a53c8d84 (Taker)
2022-12-27 05:13:38.321 [INF] CORE: Refunding dcr contract f403a9b58ad27a1d00df7c801263548a63f2842f0349898c1af186a69564678f:0 for match 8038a42b394ff7250fce0317ce421ac9701b6bb569b0e94ebc1c5b593cf806f9 (no valid redemption received from Maker)
2022-12-27 05:13:38.321 [ERR] CORE[dcr]: feeRate error: fee rate estimation unavailable and external API is disabled
2022-12-27 05:13:38.866 [TRC] CORE[dcr]: Output f403a9b58ad27a1d00df7c801263548a63f2842f0349898c1af186a69564678f:0 was not reported as unspent by SPV wallet. Spend status UNKNOWN.
2022-12-27 05:13:39.026 [WRN] CORE: notify: |WARNING| (order) Matches Refunded - Refunded 2.00000000 DCR on order 5bba41c5 - Order: 5bba41c5e2f61fc6793193eace7bc56308c6a3eddbdf693a48d63f33a53c8d84
```

**Comment by JoeGruffins** [comment]
This makes sense. It could check to see if the output is spent first. But, in the case the refund tx was used we expect dexc to have blown up and be unusable. We expect the user to let dex do the refunding, as pointed out in the text surrounding the refund tx `They should NOT be used if dexc is operable.` https://github.com/decred/dcrdex/blob/436e82e21028d987e876c5dae4f73ab467aff2fa/client/core/trade.go#L2394-L2399

Would storing the wrong/fake refund tx have any really adverse consequences? Misinformation to the user at least.

I don't think we do or plan to do any refund watching like we do with redeems. It looks like we just store the refund coin id.

**Comment by chappjc** [comment]
> From briefly looking at the relevant area in the code [here](https://github.com/decred/dcrdex/blob/21862fd8882f408b517b52f69dadc319106afb88/client/core/trade.go#L3059-L3084) and further down [here](https://github.com/norwnd/dcrdex/blob/21862fd8882f408b517b52f69dadc319106afb88/client/asset/dcr/dcr.go#L3038-L3051) it seems DCR `ExchangeWallet` is creating its own refund-transaction and trying to send it, without being aware of the fact that it might have been refunded already.

BTC respects this "CRITICAL" comment:

https://github.com/decred/dcrdex/blob/21862fd8882f408b517b52f69dadc319106afb88/client/core/trade.go#L3059-L3064

but DCR's `Refund` impl does not.

However, even if that's resolved, the logic is that spent without a recorded refund means that it was redeemed by the counter party (if taker) and we start `t.findMakersRedemption`.  If maker, it would simple retry Refund forever.  As @JoeGruffins  said, the user has meddled and disregarded the warning in the logs.

Can this be improved?  Yes.  Is this something a user can get into in normal operation? No.

**Comment by chappjc** [comment]
Related: https://github.com/decred/dcrdex/issues/1962

**Comment by norwnd** [comment]
> Can this be improved? Yes. Is this something a user can get into in normal operation? No.

Makes sense.

Maybe instead it is worth looking into / addressing [refund data redundancy](https://github.com/decred/dcrdex/issues/952#issuecomment-1365657079), since that could potentially change the way manual refunds are done (currently by fetching refund-txn from logs and publishing it).

I wonder whether it is possible to automate the whole "manual" part out of it, maybe it could look like this:
- suppose user lost his **dexc db** and **logs**
- he installs fresh **dexc** instance and imports **seed** there
- then he creates wallets he previously used (I wonder whether any auto-discovery for wallets user already used with this particular seed is possible, that would be nice, but certainly out of scope and not mandatory for this process)
- after wallets are synced, **dexc** runs some kind of "unfinished swaps" check  and if it finds any it tries to handle [possible failure scenarios](https://github.com/decred/dcrdex/issues/952#issuecomment-1365657079) (for DCR it could check whether wallet has any recent swap transactions that can be refunded; for ETH-based assets it could also check if there are any recent `inits` that haven't been `redeemed` and pulling out **secretHash** it can refund those; maybe there is a way to handle that Maker-redeem case as well, maybe with server's help)

I totally get that's probably not high priority any time soon, just thinking whether it could be addressed eventually.

**Comment by chappjc** [comment]
> * after wallets are synced, **dexc** runs some kind of "unfinished swaps" check  and if it finds any ...

This is the real problem.  Consider the UTXO assets: a swap contract contains data provided by the counterparty, and random data.  Part of the contract is the counter party's pubkey, and if you are the taker, the secret hash comes from the counterparty.  The secret keys are also randomly generated, not deterministic, even if you are the maker who knows the secret.

We have briefly spitballed ideas about having extra outputs on the swap contract transactions that could facilitate discovery, but it's not straightforward by any means.

**Comment by norwnd** [comment]
> Consider the UTXO assets: a swap contract contains data provided by the counterparty, and random data. Part of the contract is the counter party's pubkey, and if you are the taker, the secret hash comes from the counterparty. The secret keys are also randomly generated, not deterministic, even if you are the maker who knows the secret.

That wasn't very obvious to me when I was going through the code / testing, appreciate clarification!

Could simple blockchain-agnostic solution be something like: instead of client trying to identify/find/reconstruct it's data from scratch it could store the most critical bits with the server (in encrypted form) so that it doesn't have to reconstruct everything based on what it could find in blockchain (when seeding new **dexc** instance) and instead just request it from server; server would store this data, having reasonable limits in size and time (FIFO cache). I'm not sure how well that would fit into server-mesh you are working on, or whether server can be held accountable for not storing this data (that can probably be addressed in the same manner it already is for other data server stores/relays on client's behalf).

**Comment by JoeGruffins** [comment]
That is a lot of work for the server that is really the client's responsibility to keep up with. The best solution is for the user to keep backups. imo. Plus I don't think it will work with mesh, which I arguably do not know how will work yet.
