### ISSUE TITLE
eth/server: Problem getting balances.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2016]
Seeing the error `2022-12-30 17:20:21.193 [ERR] MKT: (*DEXBalancer).CheckBalance: error getting account balance for %q: %v 0x946dfaB1AD7caCFeF77dE70ea68819a30acD4577 accountBalance error: contentFrom error: the method txpool_contentFrom does not exist/is not available` on master. Probably due to a recent geth version change. I do not think I noticed this in the pr, however.

**Comment by JoeGruffins** [comment]
This is with the simnet harness. Maybe it does need some arguments for what api's are enabled on start up. Looking into it.

**Comment by JoeGruffins** [comment]
I do not see it on testnet.

**Comment by JoeGruffins** [comment]
I must be going crazy, I really though this was working before, but it looks like we don't have access to "txpool" methods?

There has been some talk of allowing even paid services for server. In that case there would be no access to the transaction pool I believe. Perhaps we can dumb down this? https://github.com/decred/dcrdex/blob/92239afd4cfa11b893f1178fede0639cb9003fe3/server/asset/eth/rpcclient.go#L183-L225

And not worry about the txpool. Using "eth_getBalance" instead which is provided by `ethclient`.

**Comment by chappjc** [comment]
When I attach via IPC:

```
instance: Geth/v1.11.0-unstable-a9dfac03-20221207/linux-amd64/go1.19.4
at block: 8229507 (Fri Dec 30 2022 23:44:00 GMT+0000 (UTC))
 datadir: /opt/geth/data
 modules: admin:1.0 clique:1.0 debug:1.0 engine:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
```

On the `authrpc` interface, perhaps not all modules (namely txpool) are available as we thought.

Unfortunately `geth attach` does not seem to be able to attach with a JWT to the authrpc interface.

How can we list the modules available after connecting to the endpoint?

Anyway, I think server's eth backend needs to support connecting on the unauthenticated http or ws interfaces.

**Comment by JoeGruffins** [comment]
We have `modules: engine:1.0 eth:1.0 rpc:1.0` over authrpc by default. I guess we can't turn on more...

**Comment by chappjc** [comment]
> We have `modules: engine:1.0 eth:1.0 rpc:1.0` over authrpc by default. I guess we can't turn on more...

That's unfortunate.  We'll need to revert all the jwt stuff that targets the `authrpc` interface, and support the older unauthenticated `http`/`ws` interfaces instead. Auth (and transport encryption) are user/operator tasks.

**Comment by JoeGruffins** [comment]
Are those three not enough?

**Comment by chappjc** [comment]
> Are those three not enough? I think if we simplify the server balance we will be fine. Client tests are passing over jwt.

- What is gained from using the `authrpc` interface with fewer available modules?  This interface was added almost exclusively for `engine` API for the consensus client.  Possibly we shouldn't be using it.  (this entire thread: https://github.com/decred/dcrdex/pull/1963#discussion_r1047636561 )
- Is it worth limiting to these three modules when we don't have to?
- Will the authrpc interface suddenly drop or add modules?  Are there guarantees?

I don't know a compelling reason for JWT-authenticated RPC *from DEX*.  It provides no encryption and thus does not prevent an attacker from sniffing the traffic or performing replay attacks (see the [engine api auth spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md)).  The authenticated interface is designed to prevent internet exposed services from being used without permission, a newish issue with a separate consensus client that may live on a distant machine.  And it creates [complications for the dex settings dialogs](https://github.com/decred/dcrdex/pull/1963#issuecomment-1356214203).

I think a geth user should power dex with `--http`/`--ws` (and relevant settings pertaining to cors, vhosts, etc.) and if run remotely they should apply transport encryption with solutions like a vpn or ssh tunnel.

**Comment by JoeGruffins** [comment]
> What is gained from using the authrpc interface with fewer available modules?

An easy way to connect to a remote geth node that the go-ethereum devs will be updating. IF we are allowing things like infura, I don't know why more modules are necessary. I don't think that server needs to be using too many resources on mempool investigation either. 

>  Possibly we shouldn't be using it. 

Could be true. Maybe this is why they did not add that commit in a release yet.

> Is it worth limiting to these three modules when we don't have to?

Again I don't think we gain much by meddling with the mempool. As you know transactions could be replaced rather easily, erasing earlier mempool transactions. And if we will be using outside services, we are already "limited".

> Will the authrpc interface suddenly drop or add modules? Are there guarantees?

I guess not. Your issue will clear this up about how/if we should use it. Obviously that's what I should have done first. I hope it gets a reply...

Can revert in the meantime.
