### ISSUE TITLE
eth: add plain http/ws support

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2026]
With https://github.com/decred/dcrdex/pull/2023 reverting the authrpc changes that allowed server to use an alternative to IPC, we will need to add in support for http/ws RPC for server.

I believe client is fine with it's "multirpc" to use geth's http/ws interfaces without changes.  Only server needs updates.
Is that correct @JoeGruffins?

**Comment by JoeGruffins** [comment]
I believe so.
