### ISSUE TITLE
eth/testing: personal namespace is deprecated.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2033]
In the eth harness at `/dex/testing/eth` we use personal namespace to send funds and deploy contracts. Documentation suggests this is deprecated https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-personal-deprecation

There they suggest using clef which, when I looked into implementing in the harness, requires input to a secure shell that we cannot easily automate.

I think this has been deprecated for a year at least, so maybe no hurry.

**Comment by chappjc** [comment]
Piotr indicated they'd make a clef guide to help people transition.  They made the decision much more recently: https://github.com/ethereum/go-ethereum/issues/25948

However, for dev network / simnet work, I figure to just replace `personal.sendTransaction` (and `unlockAccount`), we'd write a tiny cli app, say `geth-personal`, that:
- connects to geth with `ethclient`
- reads keys from a json file
- creates, signs, and publishes a basic transaction based on cli args (a `KeyStore`, `PendingNonceAt`, `Sign`, `SendTransaction`, etc)

We could even try to use one of our dex wallet types, but that would be extreme overkill and more complicated.

**Comment by chappjc** [comment]
However, when and if we make it back to our les-powered `nodeClient` at some point, I think we have to change how we store and manage the keys because I have a feeling `node.AccountManager()` will go away too, although they've not said this to my knowledge.  I had asked about this but didn't get a response: https://twitter.com/chappjc/status/1537840700582133760

**Comment by buck54321** [comment]
We made some progress towards geth-less key handling in #1832. Should be a breeze.

**Comment by JoeGruffins** [comment]
> EDIT: when it https://github.com/ethereum/go-ethereum/pull/26390, it will still be available with --rpc.enablepersonal

If this is the case, maybe testing can keep using it?

**Comment by chappjc** [comment]
> > EDIT: when it [ethereum/go-ethereum#26390](https://github.com/ethereum/go-ethereum/pull/26390), it will still be available with --rpc.enablepersonal
> 
> If this is the case, maybe testing can keep using it?

For a while anyway.  Eventually they'll remove it and we'll needs our own signing+send tool.

**Comment by JoeGruffins** [comment]
Mentioned in #2135
