### ISSUE TITLE
erc20: token fee estimates on ui are wild

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2041]
![image](https://user-images.githubusercontent.com/9373513/211854990-36e5c53c-d0fa-4791-9cff-63ef80a83e58.png)

Noted in https://github.com/decred/dcrdex/pull/1733#pullrequestreview-1218454607 when buying DCR with USDC (testnet)

**Comment by martonp** [comment]
The fees for this shouldn't even be in USDC, they should be in ETH.

**Comment by JoeGruffins** [comment]
Its likely it is using the unit info for usdc (1e6) on eth gwei (1e9) values.
