### ISSUE TITLE
server/auth: UserSettlingLimit can overflow and return negative.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2048]
While testing on testnet, I have had this function return negative after testing a bit:
https://github.com/decred/dcrdex/blob/cc224f86abd0101de095810defd591b5be33f609/server/auth/auth.go#L798

Values when it overflows look like:
```
current lot size 10000000
base is 400000000
sa is
(*auth.SwapAmounts)(0xc0034bc7c0)({
 Swapped: (int64) 40000000,
 StuckLong: (int64) 120000000,
 StuckShort: (int64) 0,
 Spoofed: (int64) 0
})
limit is -80000000
```

**Comment by chappjc** [comment]
Do you know what `AbsTakerLotLimit` was set to?  That one line you linked to doesn't look like an overflow to me, but the line `limit = auth.absTakerLotLimit * currentLotSize` could be if the limit was set in atoms instead of lots.

**Comment by chappjc** [comment]
Oh, `stuckLongWeight` is `-5`.  So this looks correct to me.

**Comment by JoeGruffins** [comment]
Oh... I can trade on all my markets except doge where the lot size is higher.

Sorry, this is normal then? I get the error message on the ui:
```
In-Flight order with ID 1 failed: new order request with DEX server 127.0.0.1:17273 market doge_dcr failed: rpc error: error code 53: order quantity exceeds user limit: Order quantity 10000000 too large. Current likely-taker order limit: -80000000 (you have 0 settling already and 0 in epoch taker orders)
```

Which seemed odd.

**Comment by JoeGruffins** [comment]
Yeah, sorry that is * -5. hmmm. I'm banned from one market... Will close because it is not overflow. Sorry about that.

How do I get the score back up if unable to trade at all.

**Comment by JoeGruffins** [comment]
Not overflow

**Comment by chappjc** [comment]
> How do I get the score back up if unable to trade at all.

That is a good question.  Place an order that is not "likely taker" I suppose is the only resolution at present.

All of this is up for change though: https://github.com/decred/dcrdex/blob/cc224f86abd0101de095810defd591b5be33f609/server/market/market.go#L1839-L1845

Plus with tier that is planned to scale user limits (https://github.com/orgs/decred/projects/2?pane=issue&itemId=2420755), this will be changing soon anyway.

**Comment by chappjc** [comment]
We could also change `UserSettlingLimit` to only go to <=0 if there are actively settling orders, and to allow at least one lot in a likely-taker order if there is nothing settling (meaning it's swap history that's blocking you, not active swaps).
