### ISSUE TITLE
ui/markets: active orders section could use some work

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2068]
1. Resolved orders should either disappear or there should be an option to clean it up. I'm imagining a little broom icon or something.
2. I wonder if the dropdown section could be displayed automatically on hover instead. Not inline, but as an absolutely positioned element with high z-index. This could potentially be troublesome on mobile though. Not sure.

![image](https://user-images.githubusercontent.com/6109680/214273337-a6a8cc86-32ee-4ed8-a507-b31061603d54.png)

**Comment by norwnd** [comment]
Another minor thing we might wanna look into is how to arrange elements such that they don't push into each other, for example, here seems like **Age** column could be moved to the right slightly (**Rate** and **Filled** are also getting mixed up in undesirable way, but could be slightly alleviated by https://github.com/decred/dcrdex/issues/2174):

<img width="200" alt="image" src="https://user-images.githubusercontent.com/112318969/221482801-919a5102-7216-4a4e-aef0-813d6ae7561d.png">

Maybe, for all practical purposes, this ^ could be solved by simply adjusting padding/margins a bit (as opposed to significantly reworking table structure such that it becomes adaptive to its contents).

**Comment by buck54321** [comment]
> Another minor thing we might wanna look into is how to arrange elements such that they don't push into each other, for example, here seems like **Age** column could be moved to the right slightly (**Rate** and **Filled** are also getting mixed up in undesirable way, but could be slightly alleviated by #2174):
> 
> <img alt="image" width="200" src="https://user-images.githubusercontent.com/112318969/221482801-919a5102-7216-4a4e-aef0-813d6ae7561d.png">
> 
> Maybe, for all practical purposes, this ^ could be solved by simply adjusting padding/margins a bit (as opposed to significantly reworking table structure such that it becomes fully adaptive to its contents).

I'm using `display: grid`, so I added `column-gap: 5px`.

**Comment by buck54321** [comment]
> One other related feature-request I can think of is making `cancel order` and `order details` buttons a bit more prominent (in a similar spirit to #2117)

Added some x padding and margin.
