### ISSUE TITLE
server/auth: something seems wrong with this AuthManager method

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2072]
https://github.com/decred/dcrdex/blob/8d99975b34e4ed372953ee39f5fbc659b2302918/server/auth/auth.go#L965-L967

I think maybe that first line is supposed to be 

```Go
violation := misstep.Violation()
```

**Comment by chappjc** [comment]
Agree.  Error introduced with https://github.com/decred/dcrdex/commit/ff71878be2eca619f2619b56dd35149abbad9279#diff-db497632f7ebb518251e95d0f5e3e66e4527e986708df27c05ce409cbe00d55fR966
Fortunately not in production.
