### ISSUE TITLE
ui: registration, better messaging when almost synced

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2080]
On `/register` page, when progress gets to 100% (it can stay like this for minutes, in my experience) I can see 99.9% on `/wallets` page (which is more accurate, because showing it as 100% might screw with user expectations about his balance - see more on this below, so it should probably be 99.9% on `/register` page also):

<img width="250" alt="image" src="https://user-images.githubusercontent.com/112318969/215254332-1a940311-51a1-43ad-98fd-1c18e26265e8.png"><img width="250" alt="image" src="https://user-images.githubusercontent.com/112318969/215254354-1b381641-c2cb-4ee8-b81a-367f7910d80a.png">

**Additionally**, note that it shows `> 1 day remaining` estimate even with 100% sync progress. This is probably inaccurate even if sync progress is changed to display 99.9%, and might be a **separate issue entirely**.

The address (shown on registration form) has been funded ~14 mins ago (so it should probably show balance of 40 DCR, not 0 DCR if wallet indeed is 100% synced):
<img width="250" alt="image" src="https://user-images.githubusercontent.com/112318969/215254191-1e28259f-8fc3-49ea-8a77-520dac4056e3.png"><img width="250" alt="image" src="https://user-images.githubusercontent.com/112318969/215254143-0c174e4c-4869-43f5-aad5-332ad36996d8.png">

Not sure whether it is a dcr/spv specific issue, or more of a UI display problem.

**Comment by chappjc** [comment]
> On `/register` page, when progress gets to 100% (it can stay like this for minutes, in my experience) I can see 99.9% on `/wallets` page (which is more accurate, because showing it as 100% might screw with user expectations about his balance - see more on this below, so it should probably be 99.9% on `/register` page also):

Yeah this is just UI rounding it I think.  We've ensured 99.9% and not 100% if the synced flag is false:

https://github.com/itswisdomagain/dcrdex/blob/73816f5d4ed5d20374a462e0e89f9b0af23b2bfd/client/asset/dcr/spv.go#L784-L785

If you follow the issues that are linked with that you'll see we have limited visibility to what dcrwallet (or btcwallet) is doing in this phase, and there's literally no way to discern how long it's going to need to get done.

**Comment by chappjc** [comment]
> The address (shown on registration form) has been funded ~14 mins ago (so it should probably show balance of 40 DCR, not 0 DCR if wallet indeed is 100% synced):

In this case, it's not synced yet, so why would you expect to see the balance updated?  I realize it says 100%, but the synced check box is not checked.  This is just the 100% UI issue again.

**Comment by norwnd** [comment]
> In this case, it's not synced yet, so why would you expect to see the balance updated? I realize it says 100%, but the synced check box is not checked. This is just the 100% UI issue again.

ah, so it is a checkbox ... I kinda thought it is just a list item and didn't expect it to be checked upon sync completion, rather I simply saw 100% and assumed it must be fully synced then (I realize the possibility of some uncertainty regarding the latest block(s), but txn with 6 confirmations shouldn't have been missed if 100% progress  is reported). So yes, basically 100% seems a bit misleading, and I think that 99.9% trick would be desirable to have here as well.

**Comment by chappjc** [comment]
> > In this case, it's not synced yet, so why would you expect to see the balance updated? I realize it says 100%, but the synced check box is not checked. This is just the 100% UI issue again.
> 
> ah, so it is a checkbox ... I kinda thought it is just a list item and didn't expect it to be checked upon sync completion, rather I simply saw 100% and assumed it must be fully synced then (I realize the possibility of some uncertainty regarding the latest block(s), but txn with 6 confirmations shouldn't have been missed if 100% progress is reported). So yes, basically 100% seems a bit misleading, and I think that 99.9% trick would be desirable to have here as well.

Thank makes sense.  Fair enough.  Perhaps there needs to be some red/orange text in the "Fund the Registration Fee" text saying if it's not synced yet so balance is not yet accurate?

> but txn with 6 confirmations shouldn't have been missed if 100% progress is reported

Also a logical conclusion.  Please see https://github.com/decred/dcrdex/issues/1816
This is an issue with the wallet packages saying 100% synced when they've done 100% of fetching and connecting blocks, but there's a second stage of discovering address use and and scanning through blocks that is not part of that sync progress unfortinately.  For that all we could do is check a flag, done in https://github.com/decred/dcrdex/pull/1955

If we can find a way to get more info that would be great, but we seemed to be limited in what we can report at this stage.

**Comment by norwnd** [comment]
I would like to take a look at this, if nobody else already.
