### ISSUE TITLE
Direct token wallet creation busted

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2085]
When creating a token wallet without first creating the parent, the configuration form is supposed to show the config options for the parent wallet too. That's not happening anymore.

![image](https://user-images.githubusercontent.com/6109680/215480894-6a7ccf3a-6c18-4401-85b6-23457bf308ef.png)

☝️That should be showing the input for PRC provider

**Comment by martonp** [comment]
I'll fix.
