### ISSUE TITLE
eth and token orders not resolving redemption fees

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2088]
Fresh simnet harness. Place and settle dcr-dextt or dex-eth order. Mine as many eth blocks as you want. Will still have active orders. Seemed like it did eventually resolve for me one time, but way way later.

**Comment by chappjc** [comment]
No idea, but I think we should merge https://github.com/decred/dcrdex/pull/2062, which is directly related

**Comment by JoeGruffins** [comment]
I have been testing on simnet a lot recently, especially eth, and have not seen this. I guess it is waiting on eth redemptions, and for some reason is not seeing the confirmations. It needs 10 confirms currently I believe.

**Comment by buck54321** [comment]
I just checked and I'm not seeing it now either. I'll leave open for a minute, but perhaps the issue was resolved/non-existent.
