### ISSUE TITLE
ui: swap fee summary followup

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2095]
#2057 solves some big issues with fee summaries for tokens. There were a couple of more things I think could use some tweaking.

1) We changed the fee range from percent to absolute values
![image](https://user-images.githubusercontent.com/6109680/215782608-8fa04836-3ada-4922-8b14-6b4ea4165158.png)
which isn't as informative, imo. Can we still display percents for non-tokens? We could even go back to percents for tokens, **IF** we have a fiat rate source for the necessary assets.

2) When a fee rate rounds to 0.0 (< 0.05) %, we should show "< 0.1%"
![image](https://user-images.githubusercontent.com/6109680/215783731-5f762767-8e0a-4105-84c7-79f51ae90903.png)

**Comment by martonp** [comment]
Good ideas. I'll update.
