### ISSUE TITLE
ui: switching markets does not change the tab/window title

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2115]
![image](https://user-images.githubusercontent.com/9373513/217301235-cb246fac-ea90-418b-a01c-ede2b35a51f5.png)

Here I've switched to the DCR-ETH market, but the window title (on the browser tab) didn't change.

**Comment by ukane-philemon** [comment]
Is this issue on the current master? I checked but can't seem to reproduce the issue. The window title on the browser tab didn't change when I switched to different markets multiple times.
<img width="245" alt="Screenshot 2023-02-15 at 12 59 07 PM" src="https://user-images.githubusercontent.com/57448127/219021540-1a1460af-84de-4935-89e2-4b3c3cb09e04.png">
