### ISSUE TITLE
ui: show reason estimate is unavailable

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2120]
When an order estimate is unavailable for some reason, we're showing a generic message and hiding the actual reason behind a tooltip.
![image](https://user-images.githubusercontent.com/6109680/217602475-fbba1e27-7e7f-4ac8-8478-34a0619c9885.png)
We may have done this on purpose, since we're using an error message not necessarily intended for display and not translated. But for some errors, such as when the order is for more than maxbuy/maxsell, we could definitely display more helpful messaging.

**Comment by JoeGruffins** [comment]
I'm still confused why I get this on our simnet server with eth but not on testnet.

**Comment by JoeGruffins** [comment]
Just throwing in prints, although trying to buy a one lot order, it does `maxOrder` which does `estimateSwap` with 1187 lots. Is it necessary to get max order for an order who's amount is already decided?

**Comment by JoeGruffins** [comment]
This is unrelated to this issue, but it seems the highest amount of swaps or n we can use in `w.estimateInitGas(w.ctx, n, ver)` is around 45 on simnet. Have we ever looked into this before? What is the limit on the number of inits at once and could it be the same? Will make an issue and do some more investigation tomorrow if someone else does not.

**Comment by JoeGruffins** [comment]
Made #2123 which I believe is the reason behind this particular error on simnet.
