### ISSUE TITLE
server/eth: server needs to support startup with failing providers in the list

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2122]
The server supports multiple providers, but at startup they all have to be working (connect as well as not old best header).
This means that if a provider gets their issue resolved later, you have to restart the server to start using it again.
With multiple providers in the eth.conf, it would make more sense to allow failed providers as long as there is at least one "working".  The failing providers can be rechecked periodically, or when rotating through providers.  Perhaps as long as the provider can connect at startup we can allow it with an old best header, just disregard that providers results until it is up-to-date?

**Comment by martonp** [comment]
I'll fix.

**Comment by JoeGruffins** [comment]
Small thing that is loosely related, the simet harness continually appends to the file at $ETH_CONFIG_PATH in the dcrdex harness. If it could just write a new file every time that would be good.
