### ISSUE TITLE
eth: Consider block gas limit.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2123]
If you try to get a swap estimate on our simnet with over 40ish swaps, you git an error `gas required exceeds allowance (n).` This n is the simnet harness's block gas limit. That value starts as `12,487,783` in our simnet genesis file. On mainnet it is currently `30,000,000` so pretty close.

I think ultimitely `MaxOrder` needs to consider the current block gas limit and either restrict based on some percent of the max, or the orders need to be broken up into multiple txn.

It seems like the mainnet block gas limit is just set to 30 million at the moment? I'm also not sure what percent of of one block's gas we can expect to use comfortably.

We might also need to check that too many redeems would not be called in the same transaction.

I remember seeing some code in our repo about the block gas limit, but I cannot remember where it was now. I don't think the client is currently handling this properly however.

Also, as an aside, for `EstimateGas`, although the limit ends up being the block gas limit, there is also a configurable rpc limit, with the default being `50,000,000`. If some providers adjust this it may unexpectedly fail. This gas limit appears to affect all rpc calls.

**Comment by chappjc** [comment]
We did that for the actual transactions in https://github.com/decred/dcrdex/commit/a00b5bc2cb1acbe2a0f2fd92d38c808b37e4586b
Sounds like we just need to make the estimate code aware too.

**Comment by JoeGruffins** [comment]
Thank you. That's the code I remember. I guess just the estimation needs to be aware, as you say.

**Comment by JoeGruffins** [comment]
Would like to tackle this if that`s alright.

**Comment by chappjc** [comment]
Absolutely!  All yours.
