### ISSUE TITLE
TestRegister occasionally fails

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#2128]
--- FAIL: TestRegister (1.35s)
    core_test.go:2256: timed out waiting for feepayment or balance notification

**Comment by norwnd** [comment]
Seen this fail recently on CI: https://github.com/norwnd/dcrdex/actions/runs/4335400908/jobs/7569956377
```
--- FAIL: TestRegister (2.64s)
    core_test.go:2286: timed out waiting for feepayment or balance notification
```
