### ISSUE TITLE
ui: pick server screen improvements

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2141]
Leaving it here to maybe address in distant future (not sure whether it will still be relevant with server mesh),

I find server-choice-screen a bit awkward, as suggested by `Pick a server` I would expect a click on server-row I chose to put me on the next screen (basically doing `Submit` button click for me, don't even need to show `Submit` button), instead I have  to click on `Submit` button to proceed on the next screen:

<img width="150" alt="image" src="https://user-images.githubusercontent.com/112318969/219643551-b6ad024d-9c22-43c3-bf19-97c3403b7c1a.png">

**Comment by buck54321** [comment]
Good point. Can I assign you?

**Comment by norwnd** [comment]
> Can I assign you?

Yeah, sure!

**Comment by JoeGruffins** [comment]
nit: title `sever` -> `server`

**Comment by ukane-philemon** [comment]
@norwnd are you still on this?

**Comment by norwnd** [comment]
Haven't got to this one yet, go ahead and take it if you want.
