### ISSUE TITLE
gaps in candlesticks

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2168]
This is not a new issue for 0.6, just reporting now.

![image](https://user-images.githubusercontent.com/9373513/221195307-76b0cd28-9f5d-4e54-818e-08402930e47d.png)

![image](https://user-images.githubusercontent.com/9373513/221195322-d863107f-9174-4f19-bca1-5e964c9200a0.png)

Usually this happens after you go away for a while and come back.  When you switch to the chart it looks alright for a couple seconds except that it's out of date, and then it redraws, but you are missing candles.

Refreshing the browser does not help, suggesting something is wrong on the backend.  I wonder if there's a gap in subscribe -> unsubscribe -> resubscribe, where it fails to get the data it missed while unsubscribed?

**Comment by JoeGruffins** [comment]
I noticed this on mainnet the other day. I'm on 88692db99c7a4b11fe08efd587c4283368a09ad6

**Comment by chappjc** [comment]
This has been a symptom since as long as I can remember having candlesticks.

**Comment by JoeGruffins** [comment]
It seems I can reproduce this. Log in and view mainnet as normal and wait a bit. Then log in with a private tab. The candles are deleted from where you first logged in with the first terminal up until present, even for the first terminal.

**Comment by ukane-philemon** [comment]
> It seems I can reproduce this. Log in and view mainnet as normal and wait a bit. Then log in with a private tab. The candles are deleted from where you first logged in with the first terminal up until present, even for the first terminal.

Yeah, I see it too and was able to reproduce it by just running mainnet for some minutes while on another tab.

**Comment by chappjc** [comment]
I didn't know about the other private tab trick.  It also just happens on its own with a single tab logged in.

**Comment by chappjc** [comment]
Because candlesticks are show by default, this is much harder to ignore:

![image](https://user-images.githubusercontent.com/9373513/221729817-39aeaca8-42d7-4abf-9d51-4fecb388a803.png)

I'm planning to look into this, but I think we should consider this high priority.
