### ISSUE TITLE
canceled orders showing as canceled/settling on markets page

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2173]
Not one of the legacy historical orders.

/markets page:

![image](https://user-images.githubusercontent.com/9373513/221465922-0479f544-e6a0-4e03-b94a-c3337a736647.png)

That's the issue, although it didn't start or stay that way.  It starts as "cancelling", then changes to "canceled", but as soon as you submit a new trade order, this one changes to "canceled/settling", presumably when it refreshes the table for the new order you just booked.  Then the moment backend retires the order (`[INF] CORE: Retiring inactive order xxx in status canceled`), it changes to "canceled".
Perhaps the active matches loop is considering a cancel match as active?

**Comment by norwnd** [comment]
Observing **possibly related behavior** with recently placed orders, in `booked` status, at some point "Your Orders" table starts to display `booked/settling` status (presumably during matches executing against those orders, which is expected) but doesn't eventually update `booked/settling` -> `booked` automatically (only does after I manually refresh the page) like it does on `/order/{id}` page.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/112318969/221480110-ca3cd7af-994d-4b44-b9ad-08a24f307b7b.png">

I can dig into it if nobody is already.

**Comment by chappjc** [comment]
Please do look.
I think the ".../settling" appears when the table is refreshed when a new order is inserted, regardless of whether that order has any fills.
