### ISSUE TITLE
ui: trim Rate precision to Market rate step

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2174]
There are multiple UI elements displaying Rate/Price with higher digit precision than Market actually supports (seemingly for no good reason, and at the expense of UI bloat), for example:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/112318969/221483676-037c4f3c-5c17-4ae5-8764-bc2a928505aa.png"><img width="150" alt="image" src="https://user-images.githubusercontent.com/112318969/221483766-78cab170-cb9b-4580-896e-9ce961a75ad5.png"><img width="150" alt="image" src="https://user-images.githubusercontent.com/112318969/221483828-677a2ddd-fa67-4806-9ffa-09d191577d5b.png">

Among Markets I tested (DCR-ETH, DCR-USDC, DCR-BTC) it seems to only affect DCR-ETH one.

**Comment by chappjc** [comment]
Yeah, this is ugly.  Tagging this for 0.6.  Hopefully it's straightforward and we can fix without breaking other things.

**Comment by chappjc** [comment]
> Among Markets I tested (DCR-ETH, DCR-USDC, DCR-BTC) it seems to only affect DCR-ETH one.

Seeing it on DCR-BTC on testnet now too:

![image](https://user-images.githubusercontent.com/9373513/221716469-3154072e-15f4-42e0-b8b2-98f114f15a86.png)

**Comment by martonp** [comment]
I'll fix.
