### ISSUE TITLE
ui: funding coin on order details page

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2175]
While I typically do appreciate all the extra info I can get (about order execution process and whatnot), a typical DEX user won't probably know or care about `Funding Coins` section on order details page:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/112318969/221493093-33b31134-2840-484e-bd8b-78052f932a71.png">

personally, fiddling with DEX for ~ half a year now I didn't use this `Funding Coins` data in UI even once (and it is available in logs for debugging purposes, for interested users anyway), but it does add cognitive load (and minor bloat) when digesting order details page, so I would suggest to remove it altogether from UI.

On the off chance I just haven't encountered a use-case for it (while some exist), then instead of removing, it is probably worth to
- make it a clickable link (similar to how transactions on Match cards are leading to blockchain explorers)
- maybe supply a tooltip that explains to the user what `Funding Coins` are and when he might need those

**Comment by jholdstock** [comment]
I'm in favour of removing funding coins from the UI so long as it remains available in logs. Despite running into various issues and corner cases with erroneously locked outputs, I have never found that value in the UI useful. Agree its just bloat for 99% of users.

**Comment by chappjc** [comment]
Darn, I personally use it quite often.

> On the off chance I just haven't encountered a use-case for it (while some exist), then instead of removing, it is probably worth to
> 
> * make it a clickable link (similar to how transactions on Match cards are leading to blockchain explorers)

They used to be!  This is a recent regression.

> * maybe supply a tooltip that explains to the user what `Funding Coins` are and when he might need those

OK, "the coins that are used to fund this order"?

**Comment by chappjc** [comment]
Tagging this issue for 0.6, for at least making the links clickable again, possibly to somehow hide the funding coins section with "show funding coins" thing if we want to hide this text by default.

**Comment by JoeGruffins** [comment]
I would rather not have the funding coins removed. I'll look at the pr though...
