### ISSUE TITLE
ui: consider saving user-entered values on order form

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2176]
Consider tracking/saving user-entered values on order form (maybe in browser local storage). We are already keeping track of these when user changes between **Buy**<->**Sell** and **Limit Order**<->**Market Order**, so it seems this feature would be just a natural extension.

I can think of couple use-cases for this:
- I have started filling in order form, lets say I decided on Price and filled it in, but then I switched to another Market (clicking on it on left doc) to maybe compare something from it with the Market I was gonna trade on (maybe I haven't decided whether I want to buy BTC or DCR, but already started to fill in the price and/or quantity); when I switch back to the Market where I started I have to fill in order form from scratch
- (might be a browser quirk, haven't look too deep into it, but might be a problem for users who can't change browser behavior for some reason) when I'm using Firefox occasionally it will auto-refresh page for me, it's pretty annoying when happens while I'm filling in my order form because I have to do 1) notice that happened 2) do it from scratch

Notes:
- those values ^ are Market-specific (so, we shouldn't be using values user filled in when fiddling with DCR-ETH order form once he switches to DCR-USDC market). We had [somewhat relevant discussions in the past on default rate/quantity values](https://github.com/decred/dcrdex/pull/1921#issuecomment-1354056430), linking here for historical reference
- I don't see a reason to keep tracking/saving those values between `dexc` restarts, and it might even confuse user (suppose he didn't log into `dexc` for a while, and now he did and those values are there, and they probably are out of date anyway)

**Comment by chappjc** [comment]
> * (might be a browser quirk, haven't look too deep into it, but might be a problem for users who can't change browser behavior for some reason) when I'm using Firefox occasionally it will auto-refresh page for me, it's pretty annoying when happens while I'm filling in my order form because I have to do 1) notice that happened 2) do it from scratch

When the backend reconnects to the DEX host, the frontend reloads everything since there was a break in notifications so you have to refresh most things.  This could be avoided perhaps.  It's certainly not needed if the host that reconnected is not the market you currently have displayed.  I use multiple dex servers at once so I notice this and it's irritating.

No real opinion on use of browser storage to persist filled values.
