### ISSUE TITLE
core: need a general purpose client notification system

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#218]
When errors (or successes) are encountered during automatically triggered actions, e.g. a tip change or a request from a DEX, the messages are not making it to the UI. They also aren't stored, so old notifications cannot be viewed after restarting. I'd like to explore the idea of a general purpose notification system in the client. 

### Proposed design

- Feeder would request a `<-chan core.Notification` notification feed. From then on the feed must be monitored if the `Core` is running. More than one notification feed could be requested and all would receive every notification. `core.Notification` is an interface for any type of notification, minimally 

```
type Notification interface {
  fmt.Stringer
}
```

I could also see a method for "notification level", e.g. warning, error, success.

- **client/core** would have **exported** notification types that satisfy `Notification`. Feeders can choose to employ a type-switch block to examine notifications closer and perform dependent actions.

- Internally, `Core` would route all notifications through a single channel, apply timestamps, and store in the database. 

- `Core` will provide a getter for notifications. A minimal method might provide `N` notifications sorted by descending time. 

- `RPCServer` can provide a route for printing recent notifications. `WebServer` will request recent notifications on startup and request a channel to monitor for websocket clients.

### Alternative

Client histories could be reconstructed and time-ordered by careful examination of stored order and match data. Good indexing could prevent extraneous DB load. Would need to store errors too.

**Comment by buck54321** [comment]
I'm choosing to view silence as complicity here. I'm going to start on this.

**Comment by chappjc** [comment]
Nice proposed design.  Go for it!
