### ISSUE TITLE
client/dex: candles race

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2188]
Continuing race crusade:
```
WARNING: DATA RACE
Write at 0x00c00ae1c508 by goroutine 41:
  decred.org/dcrdex/dex/candles.(*Cache).combineCandles()
      /Users/norwnd/dcrdex/dex/candles/candles.go:174 +0x679
  decred.org/dcrdex/dex/candles.(*Cache).Add()
      /Users/norwnd/dcrdex/dex/candles/candles.go:62 +0x249
  decred.org/dcrdex/client/core.(*candleCache).addCandle()
      /Users/norwnd/dcrdex/client/core/bookie.go:101 +0xee
  decred.org/dcrdex/client/core.(*bookie).logEpochReport()
      /Users/norwnd/dcrdex/client/core/bookie.go:204 +0x484
  decred.org/dcrdex/client/core.handleEpochReportMsg()
      /Users/norwnd/dcrdex/client/core/bookie.go:1068 +0x152
  decred.org/dcrdex/client/core.(*Core).listen.func1()
      /Users/norwnd/dcrdex/client/core/core.go:8240 +0x156
  decred.org/dcrdex/client/core.(*Core).listen.func2()
      /Users/norwnd/dcrdex/client/core/core.go:8254 +0xcc

Previous read at 0x00c00ae1c508 by goroutine 13681:
  reflect.Value.Uint()
      /usr/local/go/src/reflect/value.go:2662 +0x169
  encoding/json.uintEncoder()
      /usr/local/go/src/encoding/json/encode.go:561 +0x45
  encoding/json.structEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:759 +0x2ba
  encoding/json.structEncoder.encode-fm()
      <autogenerated>:1 +0xdb
  encoding/json.ptrEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:943 +0x382
  encoding/json.ptrEncoder.encode-fm()
      <autogenerated>:1 +0x90
  encoding/json.structEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:759 +0x2ba
  encoding/json.structEncoder.encode-fm()
      <autogenerated>:1 +0xdb
  encoding/json.(*encodeState).reflectValue()
      /usr/local/go/src/encoding/json/encode.go:358 +0x88
  encoding/json.interfaceEncoder()
      /usr/local/go/src/encoding/json/encode.go:714 +0x17b
  encoding/json.structEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:759 +0x2ba
  encoding/json.structEncoder.encode-fm()
      <autogenerated>:1 +0xdb
  encoding/json.ptrEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:943 +0x382
  encoding/json.ptrEncoder.encode-fm()
      <autogenerated>:1 +0x90
  encoding/json.(*encodeState).reflectValue()
      /usr/local/go/src/encoding/json/encode.go:358 +0x88
  encoding/json.(*encodeState).marshal()
      /usr/local/go/src/encoding/json/encode.go:330 +0x224
  encoding/json.Marshal()
      /usr/local/go/src/encoding/json/encode.go:161 +0xf9
  decred.org/dcrdex/dex/msgjson.NewNotification()
      /Users/norwnd/dcrdex/dex/msgjson/types.go:421 +0x6a
  decred.org/dcrdex/client/websocket.(*marketSyncer).Run()
      /Users/norwnd/dcrdex/client/websocket/websocket.go:265 +0x16b
  decred.org/dcrdex/dex.(*StartStopWaiter).Start.func1()
      /Users/norwnd/dcrdex/dex/runner.go:65 +0x81
```

I think the reason for this race is that passing a **pointer** over Go `chan` isn't fully protecting us from accessing the data being pointed to in a racy way; They say: [Don't communicate by sharing memory, share memory by communicating.](https://go-proverbs.github.io/), and that's probably the best fix I could suggest here. It seems best to avoid channels communicating objects with pointers, this leads to false sense of security and this is a good example.

Here is that [channel-culprit](https://github.com/decred/dcrdex/blob/master/client/core/bookie.go#L43-L43), so:
- might be worth investigating whether it can easily be refactored towards that proverb ^
- if not, a paper over type of fix (the only **obvious** place I can see) would be to make  a copy of `msgjson.Candle` [here](https://github.com/decred/dcrdex/blob/master/client/core/bookie.go#L216-L216); I didn't check all the possible `Payload` types, only the one when it contains `CandleUpdate`, other types of payload need to be checked also if we are to go this route; 

Could be the root cause for https://github.com/decred/dcrdex/issues/2168.

**Comment by chappjc** [comment]
Please go ahead and and push a commit trying with a copy of the `msgjson.Candle`.  The race detector output certainly supports that as a resolution, or making a copy in `addCandle`.

**Comment by chappjc** [comment]
But I don't think the design problem is `b.send(&BookUpdate{` where we're sending a pointer to a `BookUpdate`, because obviously the ownership of that `BookUpdate` is entirely handed off to the receiver.  This is just as good as a copy (by value).  The problem is that the `Payload` is incorrectly a pointer in cases.  You've pointed this all out.   But I don't think it's a violation of that proverb the way we are using the channel with a pointer since the pointer is not retained by the sender.  We can certainly send a value, but that won't solve the problem if the by-value struct contains a pointer itself.

You are correct we need to look at all the payloads.

**Comment by chappjc** [comment]
This also looks like a problem for the same reasons you identified:

https://github.com/decred/dcrdex/blob/80b0531a64a806ac8901d812b1e322418118cac1/client/orderbook/orderbook.go#L654

`newMatches` is returned and becomes the payload, but the backing array is now also used by `ob.matchesSummary`.  A copy is needed.

**Comment by norwnd** [comment]
> We can certainly send a value, but that won't solve the problem if the by-value struct contains a pointer itself.

That's true, and that's the danger I'm concerned about when using channels.

**Comment by chappjc** [comment]
Just to echo an idea from Matrix chat, a possibly less error prone design to investigate in the futre might be to make the Payload into something that does not have this pitfall, such as a `json.RawMessage` or `msgjson.Message` (since the receiver just constructs a notification and relays it on).

```go
type BookUpdate struct {
	Action   string      `json:"action"`
	Host     string      `json:"host"`
	MarketID string      `json:"marketID"`
	Payload  msgjson.Message `json:"payload"`
}
```

**Comment by norwnd** [comment]
If it isn't very urgent, I'd like to work on this in ~2 weeks.

**Comment by chappjc** [comment]
It's fine. The most obvious race is fixed, and Joe found gap cause.

**Comment by buck54321** [comment]
> This also looks like a problem for the same reasons you identified:
> 
> https://github.com/decred/dcrdex/blob/80b0531a64a806ac8901d812b1e322418118cac1/client/orderbook/orderbook.go#L654
> 
> `newMatches` is returned and becomes the payload, but the backing array is now also used by `ob.matchesSummary`. A copy is needed.
> 
> EDIT: Also with `(ob *OrderBook) RecentMatches()` as that's in the payload for `FreshBookAction`.

I think `ob.matchesSummary` is effectively append-only. Should be okay, right? Or am I missing the problem?

**Comment by chappjc** [comment]
> I think `ob.matchesSummary` is effectively append-only. Should be okay, right? Or am I missing the problem?

I suppose the elements of the shared backing array aren't modified, so looks alright now that you mention it.  Slice headers are independent.  Didn't did deeper, or look at the other race outputs.
