### ISSUE TITLE
Wallets screen doesn't update after reconfiguring wallet type

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#2190]
1. Create fresh simnet dexc
2. Create BTC SPV wallet
3. Reconfigure to RPC Wallet
4. The screen still shows the 0 balance, and clicking the settings button still reveals the SPV settings. After refresh, the correct things are displayed.

**Comment by buck54321** [comment]
Unable to reproduce.

**Comment by ukane-philemon** [comment]
@martonp, do you still notice this?

**Comment by martonp** [comment]
Seems fine now.
