### ISSUE TITLE
wallet birthday at creation assumes GMT (just UI or backend too?)

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2192]
It's 6:02pm CST on Feb 28 at the time of this, which is just past midnight GMT:

![image](https://user-images.githubusercontent.com/9373513/222010972-45b91476-b9c5-4730-905c-f6665a66ad64.png)

Seems like the future.  In fact, I'm not sure it's even handled correctly on the backend.

**Comment by ukane-philemon** [comment]
> Seems like the future. In fact, I'm not sure it's even handled correctly on the backend.

The backend uses the default location for time values including wallet birthdays (i.e UTC), are you suggesting we change that to use the local timezone?

**Comment by chappjc** [comment]
Looks to just be UI.  Docs for `toISOString` state "The timezone is always zero UTC offset, as denoted by the suffix Z.".  Fixing so we get the locale date.

**Comment by chappjc** [comment]
This is way stranger than I thought.  Assigning to an input's value (or valueAsNumber or valueAsDate) and trying to get it back is even not so straightforward.
https://stackoverflow.com/questions/53032953/what-is-the-correct-way-to-set-and-get-htmlinputelement-valueasdate-using-local
https://stackoverflow.com/questions/16825363/how-do-you-parse-a-date-from-an-html5-date-input?answertab=scoredesc#tab-top
I might move on from this.
