### ISSUE TITLE
candle chart doesn't remember last bin size selection or show current selection

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2198]
When navigating away from and back to the markets view, the candles are always the 5-minute candles.

There is a reason that the default is 5 minutes. The `High24` and `Low24` fields of the `msgjson.Spot` were only added in #1825, so we get the values from the 5 minute candles until servers are up-to-date. I don't know if it makes sense to fix this before then or not.

Also, there is no indication of the currently selected bin size. It can be inferred by looking at the x-axis, but we also be more explicit, highlighting a button or even just displaying it somewhere.

**Comment by ukane-philemon** [comment]
>Also, there is no indication of the currently selected bin size.

There is an indicator atm which is a green border unless you are considering a more pronounced indicator. <img width="65" alt="Screenshot 2023-04-02 at 1 19 58 AM" src="https://user-images.githubusercontent.com/57448127/229323891-2975eaae-1aac-483e-8bdc-efa968951fd3.png">

> When navigating away from and back to the markets view, the candles are always the 5-minute candles.

yup, we could save the user's last selection to local storage and use that if it is still a valid duration.

**Comment by norwnd** [comment]
> There is an indicator atm which is a green border unless you are considering a more pronounced indicator

I would say it is barely visible in dark mode, and close to invisible in light mode.

**Comment by norwnd** [comment]
> what do you guys think would be a good fit? red?

I'd probably use some color that isn't already present on the chart itself (that rules out red and green at least) but is still compatible with colors on `/markets` page, maybe violet (from dcrdex brand icon); but same color also might look different depending on light/dark background - so this needs some experiments I guess. 

I would also consider coloring `5m` text itself along with item border to increase visibility, or do something equivalent.

**Comment by chappjc** [comment]
The candles before may 15?  No there was just a collection bug so those candles are now poisoned forever server-side.
