### ISSUE TITLE
Decred pre-size tooltip is empty

### ISSUE THREAD

**Issue by vctt94** [decred/dcrdex#2213]
When hovering on the info icon at decred pre size option, it shows an empty box, as we can see here:

![image](https://user-images.githubusercontent.com/15069783/224114426-650d842a-3d1d-451e-8bd9-447b1b35235d.png)

**Comment by buck54321** [comment]
I'm more interested in how you got here, exactly. That error comes from

```Go
noSplitEst, _, noSplitLocked, err := dcr.estimateSwap(req.Lots, req.LotSize,
	req.FeeSuggestion, req.MaxFeeRate, utxos, false, bump)
if err != nil {
	dcr.log.Errorf("estimateSwap (no split) error: %v", err)
	opt.Boolean.Reason = fmt.Sprintf("estimate without a split failed with \"%v\"", err)
	return opt // utility and overlock report unavailable, but show the option
}
```
but wouldn't that mean we should have failed earlier in `PreSwap` at `dcr.maxOrder`?

**Comment by vctt94** [comment]
Can not reproduce this on latest master.
