### ISSUE TITLE
Redesign markets page for smaller screens

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#2215]
Currently, when looking at the markets page on small screens, you have to keep scrolling to see the charts and the sides of the order book are stacked on top of each other. I think a better design would be what is on Binance, where you have buttons to switch between charts and the orderbook, and the sides of the orderbook are next to each other.
![Screenshot 2023-03-10 at 12 49 22 PM](https://user-images.githubusercontent.com/6186350/224387771-1b99af0b-7639-4de1-96a9-b1d5de560ac3.png)
![Screenshot 2023-03-10 at 12 49 17 PM](https://user-images.githubusercontent.com/6186350/224387774-df3ebcba-7687-41ca-8ae6-70672f44e033.png)

**Comment by norwnd** [comment]
> where you have buttons to switch between charts and the orderbook

I also think having just 1 of (candle chart, depth chart) on your screen at a time makes it easier to see what's going on, and navigate UI overall. Plus many users don't even use depth chart (or even know about it), so hiding it behind button click to swap candle chart (shown by default) is very reasonable UX-wise.

**Comment by ukane-philemon** [comment]
@buck54321, can I work on this?
