### ISSUE TITLE
client/dcr: Cannot change from spv wallet to rpc.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2240]
On simnet create an spv wallet then attempt to reconfigure to rpc:

![image](https://user-images.githubusercontent.com/34998433/226809093-1ded95e7-1aa6-4309-8aef-eeaf7e87ad47.png)

**Comment by JoeGruffins** [comment]
The password is there in the field. It does require it I believe.

**Comment by chappjc** [comment]
OK.  The reason I'm asking is because you have the _wallet_ password field collapsed, which will not send it to wallet creation:

![image](https://user-images.githubusercontent.com/9373513/226915119-7b33f4ee-db96-4ec6-8d89-b7dc7513a1c0.png)

**Comment by JoeGruffins** [comment]
Oh wait, you are right, thats the rpc password. I need to also set a new password. Ah. I guess this in a non-issue.

**Comment by JoeGruffins** [comment]
I just tried and that does work. Was password always in a separate box? I got confused.

**Comment by chappjc** [comment]
I think I've made the same mistake, which suggests the UI needs something changed.  I don't know what.  Perhaps if the change wallet type is expanded, it includes some text like "Do you need to set a password for the new wallet?" or something.

**Comment by JoeGruffins** [comment]
Wait, I can make a new wallet without the password...

**Comment by JoeGruffins** [comment]
Oh, no, that is the wallet password field there for a new wallet.

**Comment by JoeGruffins** [comment]
Issue was user error.
