### ISSUE TITLE
ui: display error message when unable to connect wallet

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2241]
Observed with ETH wallet but could affect others too, 
- I had single Ethereum Provider configured 
- upon `dexc` start it wasn't able to connect (I mocked up this failure to test something else), hence wallet is shown in "Off" state which is all good so far
- but then clicking on **connect** button results into something weird, some frames change but no errors are displayed:

[connect-wallet-no-error-shown.webm](https://user-images.githubusercontent.com/112318969/226813312-52d6cd02-4598-491d-97c2-0379f69bc2df.webm)

<br>

while in the logs the error is:
```
2023-03-22 05:41:08.044 [ERR] WEB: error connecting to eth wallet: connectWallet: failed to connect eth wallet: connect failure: failed to connect
```
so the user should see something similar ^ in UI.

As a sidenote, I'm not even sure why this `connect` button is there in the first place , wouldn't it be **better to try re-connect wallet automatically every 30s or something** ?

**Comment by norwnd** [comment]
Somewhat related issue: clicking on `connect` button doesn't change anything until I refresh page even though according to logs wallet does get reconnected (so from user perspective, he'll continue clicking on `connect` button when what he actually is to refresh browser page).

**Comment by norwnd** [comment]
> Somewhat related issue: clicking on connect button doesn't change anything until I refresh page even though according to logs wallet does get reconnected (so from user perspective, he'll continue clicking on connect button when what he actually is to refresh browser page).

This behavior is likely the result of me running 2 different **dexc** instances, accessing both from same browser, actually.

**Comment by ukane-philemon** [comment]
@chappjc, is this still an issue?

**Comment by chappjc** [comment]
I think you solved this one.
