### ISSUE TITLE
ui: simplify enable/disable wallet for token/parent wallets 

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2242]
Potential UX improvement to consider is to permit the following (if there aren't any fundamental limitations to doing this):
- disable all token wallets when parent wallet gets disabled
- enable parent wallet when token wallet gets enabled

or maybe **even simpler way to handle it** would be to remove this enable/disable functionality from token wallets and just let parent wallet fully manage it,

currently user needs to handle this manually:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/112318969/226815886-a178b280-5e11-42ff-9018-c74de45c8a84.png"><img width="200" alt="image" src="https://user-images.githubusercontent.com/112318969/226815953-b7cfcddd-ab62-4e31-826d-6ec6411da6f1.png">

**Comment by chappjc** [comment]
> * disable all token wallets when parent wallet gets disabled
> * enable parent wallet when token wallet gets enabled

Both seem reasonable to me.

I don't think we should prohibit disabling a token wallet though.  When you first create an ETH wallet, you have no token wallets unless you explicitly enable them.  I think that's the right way to handle it.  Respecting user-choices aside, each token adds to the RPC provider utilization.
