### ISSUE TITLE
client/testing/simnet-trade-tests: "notakerswap" on dcreth fails with client 2 as maker.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2243]
These tests have a history of being flakey, but `notakerswap` is consistently failing for dcr_eth only when client 2 is maker.
```
ERROR: test "notakerswap" failed with client 2 as maker: eth balance change not in expected range 0.005591700 - 0.006180300, got 0.000518972
```

**Comment by JoeGruffins** [comment]
Looking into this briefly in case it's something easily fixable within the test, which is usually the case.

**Comment by JoeGruffins** [comment]
Oh yeah, those extra funds seem to be in immature according to logs:
```
2023-03-22 16:18:01.191 [INF] T[2]: Client 2 eth balance: available 83.988250031, immature 0.006000000, locked 0.000000000.
```
I guess mine a block or consider immature.

**Comment by JoeGruffins** [comment]
Mining doesn't seem to move the funds to available. I guess related to changed in #2211

**Comment by JoeGruffins** [comment]
The test passes on commit 2822708fd4b49e64899048970947ef318a86c620 right before those changes.

**Comment by chappjc** [comment]
@buck54321 Unclear how severe the issue is.  Might just be added delays the harness tests aren't accounting for.
