### ISSUE TITLE
ui: eth/token wallet setup hints

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2245]
Embed the link to wiki page from https://github.com/decred/dcrdex/pull/2233 somewhere in UI (somewhere visible, like on create and reconfigure ETH/Token wallet forms highlighted with red) so that user is prompted to read Ethereum tutorial. 

Expecting users to find it on their own is probably a set up for countless help-requests in decred support channels.

I think overall approach of hint-on-need-to-basis is more practical than having a separate wiki and expecting users to read it before using DEX.

**Comment by buck54321** [comment]
Can add a field for a link to the `WalletDefinition` and display the link on the create/reconfig form (or hide link element if field is empty). Can I assign you, @norwnd?

**Comment by norwnd** [comment]
Yep!
