### ISSUE TITLE
client/asset/eth: fallback providers of last resort

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2246]
Ignoring Ethereum recommendations listed in https://github.com/decred/dcrdex/blob/master/docs/wiki/Ethereum.md could result in failure to redeem (if all user-specified providers fail while user is trying to redeem),

one solution that doesn't degrade UX would be to allow user to configure just 1 provider (like we currently do), but have 2 or more hardcoded fallback providers (e.g. https://rpc.ankr.com/eth) that will not affect current flow in any way except that these will be used as a measure of last resort when none of user-configured providers are available.

For additional context/concerns see [this discussion](https://github.com/decred/dcrdex/pull/2233#discussion_r1144288254).

**Comment by norwnd** [comment]
Would like to work on this, if this is a desirable feature.

**Comment by norwnd** [comment]
> Lock times are long for a reason. User has plenty of time to fix the problem if their provider is really tanked for 8 hours.

Time isn't the main issue here (but even 8h might not be enough, can't user set up some trades and go afk for a while ? or have additional network issues to deal with on top), 

not providing a fallback here is basically equivalent to stating "**users who don't understand and remember the following**: 1) ETH provider can fall out of sync for whatever reason 2) that means your wallet falls out of sync 3) that in turn means trades might fail to complete (you likely loose funds) **shouldn't use DEX**"
- DEX doesn't target those users who don't understand this chain of events ?
- they might still use DEX and encounter this "issue" on their own, dumb as they are, and go in flames on media about DEX being unreliable; and quite rightfully so  because this could've been prevented quite easily
- even if I do understand this chain of events, I might not want to keep these low level details in my head when trading or doing something else

**Comment by chappjc** [comment]
Well the least we can do is:
- have two provider text boxes already, so it's obvious that's suggested
- have a link to the wiki page where they can see a list of providers and learn what they are picking

On the philosophical points, yes, I think DEX users need to be more aware than the average user.  At least a little.  Sorry.  Further, MetaMask users:
- have blindly been unaware and as a consequence they have seen downtime when Infura experiences [downtime](https://decrypt.co/47846/ethereum-backbone-infura-suffers-major-damage), [repeatedly], [...](https://decrypt.co/98457/metamask-ethereum-apps-down-infura-outage)(https://coinmarketcap.com/alexandria/article/ethereums-infura-iating-outage-revives-decentralization-concerns).
- had unfavorable ToS forced upon them by a developer chosen provider: https://decrypt.co/115486/infura-collect-metamask-users-ip-ethereum-addresses-after-privacy-policy-update, https://vpnoverview.com/news/metamasks-infura-tool-to-collect-users-ip-and-wallet-addresses/, https://yro.slashdot.org/story/22/11/25/0459224/infura-collecting-metamask-users-ip-ethereum-addresses-after-privacy-policy-update, https://chainwitcher.com/metamask-users-ip/

Users will "go in flames" on social media if we make the same mistakes.

**Comment by norwnd** [comment]
Okay then, accidentally violating user privacy (which could happen with fallback providers) also isn't ideal,

> have a link to the wiki page where they can see a list of providers and learn what they are picking

we have a [separate issue for this](https://github.com/decred/dcrdex/issues/2245), I believe

> have two provider text boxes already, so it's obvious that's suggested
> possibly nag the user to use more. Showing two inputs by default is fine too.

I guess the last question to answer is whether we want to force min required providers to be 2, or just display 2 fields to fill in and allow for 1. I'd vote for 2+ being mandatory.

**Comment by chappjc** [comment]
> I guess the last question to answer is whether we want to force min required providers to be 2, or just display 2 fields to fill in and allow for 1. I'd vote for 2+ being mandatory.

No, this was something I raised in [the discussion that preceded](https://github.com/decred/dcrdex/pull/2233#discussion_r1144761493) this issue.  1 is allowed.

This issue seems so simple to me.  Change nothing about the requirements or the UI except have it look like the user already  hit the "+" once when they get there.

**Comment by norwnd** [comment]
Looks like this one can be closed now.
