### ISSUE TITLE
dexc: no warning or error if dex url lacks entry in certs.json

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#225]
If ~/.dexc/certs.json lacks and entry for the dex specified on the web interface, it has an error that does not indicate the missing entry in certs.json:

> [ERR] WEB: preregister error: Error initalizing websocket connection: x509: certificate signed by unknown authority

![image](https://user-images.githubusercontent.com/9373513/77578566-c2337480-6ea6-11ea-9faf-cd6638a81987.png)

Ideally `dexc` would indicate that the dex url didn't have a cert specified.

**Comment by itswisdomagain** [comment]
`certs.json` was dropped in #254, but this error message still displays when no cert file is uploaded, and a more descriptive error message can be displayed.

I can have a quick PR up for this if desired.

**Comment by chappjc** [comment]
Perhaps worth addressing at the same time as reworking the dex address handling so the preferred method is to omit the scheme, but perhaps allow it (just stripping it off) for backward compat.  This pertains to our discussion on `net.SplitHostPort` and `url.Parse` in https://github.com/decred/dcrdex/pull/328#discussion_r425218790

**Comment by itswisdomagain** [comment]
Coolio. I'll take this up.

**Comment by itswisdomagain** [comment]
> Perhaps worth addressing at the same time as reworking the dex address handling so the preferred method is to omit the scheme, but perhaps allow it (just stripping it off) for backward compat.

I see #374 is created to track that, and @JoeGruffins has opted to work on that, so I'll just fix the error message for no cert provided cases.
