### ISSUE TITLE
ui: display rate for the collapsed view of orders in the 'your orders' section

### ISSUE THREAD

**Issue by artikozel** [decred/dcrdex#2254]
In v0.6-beta as it is currently the rate at which orders are placed are not displayed in the collapsed view of the order menu. I believe there is enough real estate there to display it alongside the order size either as a simple "@ rate" or in any way the devs see fit, because the only visual confirmation available at first glance are the little arrow pointers in the depth chart and this information is just as critical to trading as order size.
However, if said real estate was left empty for a reason, then perhaps indicating to the user where their orders sit in the orderbook with a simple dot icon next to the order in the orderbook view would suffice.
![image](https://user-images.githubusercontent.com/44892068/227707598-5a22f4e5-3f30-447b-9793-b42eeb86f314.png)

**Comment by chappjc** [comment]
I agree with this too.  Would you object to rate here @buck54321?

**Comment by buck54321** [comment]
Will it fit?

**Comment by chappjc** [comment]
There seems to be amble blank space there.

![image](https://user-images.githubusercontent.com/9373513/228897924-c632d780-fc91-4ba6-855c-df588ef3f896.png)

**Comment by buck54321** [comment]
Looks good to me

**Comment by norwnd** [comment]
I can do it.

**Comment by chappjc** [comment]
Go for it.  Tightly scoped diff please, since we might backport.
