### ISSUE TITLE
client: markets won't load after old-seed import

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2256]
I'm not quite sure how it is supposed to work with bonds, but now (on latest master, testnet) after I've imported dex seed got redirected to `/markets` page:
- not a single market would load
- there is no suggestions to "create wallet" or "register with server"; or any error message that would signal that imported seed isn't compatible with bond-oriented **dexc** because it was registered with a particular server with the old one-time payment method (if that's the intended behavior here)

[markets-wont-load-after-seed-import.webm](https://user-images.githubusercontent.com/112318969/227760874-5a243713-dd45-44a1-90d5-2f3ff067ffbd.webm)

<br>

In logs I only see this line that could be somewhat relevant:
```
2023-03-26 06:39:46.820 [ERR] CORE: dcr wallet not available for bonds: no configured wallet found for DCR (42)
```
the full log: 
[markets-wont-load-after-seed-import.txt](https://github.com/decred/dcrdex/files/11070987/markets-wont-load-after-seed-import.txt)

**Comment by norwnd** [comment]
And for some reason this doesn't reproduce for me either, markets page opens just fine after seed import (server recognises same account).

**Comment by norwnd** [comment]
Closing since [this is the most likely cause](https://github.com/decred/dcrdex/issues/2257#issuecomment-1484099408).

**Comment by norwnd** [comment]
One other similar case I see with Brave occasionally (not sure whether it is Brave-specific issue): after **login** UI can't connect WS and keeps running that ws-reconnect loop I mentioned above. It does look very similar to what I recorded above when importing seed, but
- the seed-case had some WS connections established successfully (as was logged by **dexc**), while here `WebSocket connection to 'ws://127.0.0.1:5758/ws' failed: WebSocket is closed before the connection is established.` and there is nothing about WS from dexc perspective in logs:

[brave-ws-failure-to-connect-after-login.webm](https://user-images.githubusercontent.com/112318969/227789478-6910b184-bd37-4418-84f7-f6ca095d99e9.webm)

<br>

log for this run: [brave-ws-failure-to-connect-after-login.txt](https://github.com/decred/dcrdex/files/11072199/brave-ws-failure-to-connect-after-login.txt)

According to that stack-trace browser shows - [here is](https://github.com/norwnd/dcrdex/blob/master/client/webserver/site/src/js/ws.ts#L102-102) where we close connection before it was established, but retry seemingly does pretty much same thing, and page refresh doesn't help either.

So, isn't 500ms timeout a bit restrictive ? However I doubt higher value will resolve anything because retries should have helped if that was the case ...

**Comment by chappjc** [comment]
See also https://github.com/decred/dcrdex/issues/583#issuecomment-687626125
The main trouble with that was leaving the window open for a bit after dex was shutdown, and the browser's reconnect behavior starts to choke it.  Then when you login, it hangs.  I found this even affected different tabs.

**Comment by chappjc** [comment]
If you debug more, use `enableLogger('ws', true)` and see the discussions about logging readystate in the linked issues and PRs.

**Comment by norwnd** [comment]
> The main trouble with that was leaving the window open for a bit after dex was shutdown, and the browser's reconnect behavior starts to choke it. Then when you login, it hangs. I found this even affected different tabs.

Thanks, it does look like browser issue indeed. I went through the relevant code and [sketched out a PR](https://github.com/decred/dcrdex/pull/2260) that might help with this unfortunate behavior.
