### ISSUE TITLE
ui: refresh page right after wallet creation

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2257]
In demo from https://github.com/decred/dcrdex/issues/2256#issue-1640799959 you can see that after wallet was successfully created UI doesn't update accordingly (effectively prompting user to create wallet 2nd, 3rd and so on time), we probably need to issue a page refresh or something to make this behavior smoother.

**Comment by norwnd** [comment]
Actually I can't reproduce this after **dexc** restart, it might have something to do with
- me running 2 **dexc** instances and accessing both from same Brave browser; however besides having to re-login all is typically working fine with such a setup
- or maybe some incorrect handling of `async/await`s that [relinquish control flow](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#control_flow_effects_of_await) while some concurrent event changes `NewWalletForm.current` from under it (or something like that); getting stuck on `Synchronizing Ethereum` view while setting up USDC wallet (without prior ETH wallet setup) is what gave me these vibes (see `runParentSync` func for details):

[stuck-on-eth-sync-page.webm](https://user-images.githubusercontent.com/112318969/227768467-2e2b291b-1d4c-420c-a735-79e6e03c7388.webm)

**Comment by chappjc** [comment]
> * me running 2 **dexc** instances and accessing both from same Brave browser; however besides having to re-login (because cookies ignore the port part of the domain and hence are shared for 127.0.0.1 unlike localstorage which differentiates by port) all is typically working fine with such a setup

This is why we have the different networks use different loop back addresses rather than changing the port.
Did you have the two on the same address but different ports?

**Comment by norwnd** [comment]
> Did you have the two on the same address but different ports?

Same 127.0.0.1 interface for both, different ports.

**Comment by chappjc** [comment]
OK, let's close these issues then.  What you describe for all three is just the kind of thing you experience in this case.

https://superuser.com/questions/458875/how-do-you-get-loopback-addresses-other-than-127-0-0-1-to-work-on-os-x

**Comment by norwnd** [comment]
> OK, let's close these issues then. What you describe for all three is just the kind of thing you experience in this case.

Okay, hope this is it!

**Comment by chappjc** [comment]
Issues can be reopened if it happens again, no worries.  The cookie constraints in https://www.rfc-editor.org/rfc/rfc6265#section-1 were something we had do deal with a long time ago because of how everything breaks when doing this.
