### ISSUE TITLE
client/dcr: Add ticket purchasing.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2264]
Part of proposal https://proposals.decred.org/record/ca6b749

Proposed interface:
```
type TicketBuyer interface {
	TicketPrice() (uint64, error)
	SetVSP(string) error // For SPV only, RPC wallets must set on wallet start same as mixing
	PurchaseTickets(n int) error
	Tickets() ([]*Ticket, error)
        VotingPreferences()([]*Agenda, []*TspendPolicy, []*TreasuryPolicy, error)
	SetVotingPreferences(choices map[string]uint8, tspendPolicy map[string]string, treasuryPolicy map[string]string) error
}
```

As I understand it we are not currently interested in the dcrwallet's automatic ticket buyer functionality. Only manual ticket purchasing.

<details closed>
<summary>change log</summary>
23/03/29 - Condense Policy getters
</details>

**Comment by JoeGruffins** [comment]
@buck54321 added methods from Treasury related policies. I guess we want those from the beginning.

Should we allow purchasing tickets without a vsp? I would think no? Related but I can't find an rpc method to check on VSP set in config.

I believe the wallet will pay the vsp fee for us. If for some reason the fee payment tx falls through, I'm not sure if it tracks that or tries to pay again automatically.

I guess we also need `processUnmanagedTicket(txhash) error` in case of wallet being restored?

I doesn't look like we need grpc support.

Also please assign me.

**Comment by JoeGruffins** [comment]
Should `TicketPrice() (uint64, error)` include VSP fee or that be a separate return?

**Comment by JoeGruffins** [comment]
@jholdstock tells me on matrix we don't need to worry about the VSP fee, wallet will continue to retry.

**Comment by buck54321** [comment]
> @buck54321 added methods for Treasury related policies. I guess we want those from the beginning.

Probably? We didn't commit to anything tspend stuff in the prop, but it is core functionality. I'm not well versed on the details though. What's the difference between "treasury policy" and "tspend policy".

Can `Agendas`, `TspendPolicy`, and `TreasuryPolicy` be combined into a single state getter?

 > Should we allow purchasing tickets without a vsp?

Definitely not now. Maybe never. 

> Related but I can't find an rpc method to check on VSP set in config.

That's unfortunate. We may need to open some PRs for dcrwallet. Also want the `ticketbuyer.balancetomaintainabsolute` setting for RPC wallets. For native wallets, we can work around this stuff if needed.

> I doesn't look like we need grpc support.

🎉

**Comment by chappjc** [comment]
- Are we looking at manual ticket purchases only as Joe suggests, or the auto ticker buyer?  The `ticketbuyer.balancetomaintainabsolute` setting is relevant to ticket buyer obviously, so it sounds like the latter.
- Mixed ticket purchases are only achieved by the auto ticket buyer via a collaborative split tx such as [this](https://dcrdata.decred.org/tx/588f508a3edd1774f33a09756609b6663f80e8b7c7e3c744cd4f7e4dbec653b3/out/15), so I don't think we want manual purchases.
- Do we intend to handle native and RPC wallets the same?  In terms of functionality offered to the user.
- What about RPC dcrwallet instances that are controlled by Decrediton. These will have all the ticker buyer as well as voting policies configured, so do we have competing settings they might change in DEX?  How do we prevent conflict?

**Comment by chappjc** [comment]
> What's the difference between "treasury policy" and "tspend policy".

You can set a vote policy per politeia key (that controls the treasury) or per tspend (tx in mempool).

**Comment by buck54321** [comment]
> Are we looking at manual ticket purchases only as Joe suggests, or the auto ticker buyer? The ticketbuyer.balancetomaintainabsolute setting is relevant to ticket buyer obviously, so it sounds like the latter.

For the native wallet, we're only doing manual ticket purchases for now. We'll integrate auto-ticket buying and mixing later. For RPC wallets, we'll at least want to be able to view our current staking stats. I have no problem enabling manual purchases too, but I understand the conflicts that raises with e.g. Decrediton. For RPC, we would want to know whether the auto-buyer is running and the balancetomaintainabsolute I think, to avoid problems with order funding. 

Here's what I suggest, @JoeGruffins. Enable manual ticket purchases over RPC, but allow disabling via configuration. This makes it possible for Decrediton and others to claim staking privileges.

> Mixed ticket purchases are only achieved by the auto ticket buyer via a collaborative split tx such as [this](https://dcrdata.decred.org/tx/588f508a3edd1774f33a09756609b6663f80e8b7c7e3c744cd4f7e4dbec653b3/out/15), so I don't think we want manual purchases.

Is it? I never run auto-ticket buyer and my manually purchased tickets are mixed. Is the auto-ticket buyer used in the background somehow?

Either way, we can't integrate with mixing yet because we don't have it implemented. We'll cross that bridge when we get there.

> Do we intend to handle native and RPC wallets the same? In terms of functionality offered to the user.

Hopefully answered above, but yes. As much as is possible.

**Comment by buck54321** [comment]
> I never run auto-ticket buyer and my manually purchased tickets are mixed. Is the auto-ticket buyer used in the background somehow?

To be clear, I know that when I purchase a ticket, there is a new mixed output created at the appropriate size. I was just unaware that the auto-ticket buying functionality was involved.

**Comment by chappjc** [comment]
Oh, I stand corrected about manual `purchaseticket` RPC when mixing is enabled but not `enableticketbuyer`.  I thought it just barfed out a regular split and a ticket purchase immediately, but the RPC actually hangs while it dials the CSPPServer, only returning when it has completed a mix in the collaborative split tx.

For example, testnet with `purchaseticket mixed 1234` on a mixing wallet ticket buyer OFF:

```
2023-03-28 10:36:31.910 [INF] WLLT: Returning address (account=1 branch=1 child=137)
2023-03-28 10:36:31.910 [INF] WLLT: selected input b3c5007fb02c5247f0fac7663523727d6b8f1b16a79c5a6510d3e931aafcc7b6:6 (0.01048576 DCR) for ticket purchase split transaction
2023-03-28 10:36:31.910 [INF] WLLT: selected input 5d67944b6c3a964920c13d324a6646a4a404c5f1bf3c2b0b8347348811b852d2:4 (0.04194304 DCR) for ticket purchase split transaction
... <lots more inputs>
2023-03-28 10:36:31.981 [INF] WLLT: Dialed CSPPServer 10.20.0.3:56966 -> 155.138.223.168:15760

2023-03-28 10:38:02.220 [INF] WLLT: Returning address (account=0 branch=1 child=1)
2023-03-28 10:38:04.794 [INF] WLLT: Completed CoinShuffle++ mix of ticket split transaction f2e9c19d4e042a1b59cb226e3f5d51de92d49a13b39ec73b730eb375cc1fb6e2
2023-03-28 10:38:04.795 [INF] WLLT: Inserting unconfirmed transaction f2e9c19d4e042a1b59cb226e3f5d51de92d49a13b39ec73b730eb375cc1fb6e2
2023-03-28 10:38:04.804 [INF] WLLT: Split output is f2e9c19d4e042a1b59cb226e3f5d51de92d49a13b39ec73b730eb375cc1fb6e2:3
2023-03-28 10:38:04.805 [INF] WLLT: Returning address (account=0 branch=1 child=2)
2023-03-28 10:38:04.806 [INF] WLLT: Returning address (account=1 branch=1 child=138)
2023-03-28 10:38:04.806 [INF] WLLT: Inserting unconfirmed transaction a7cacddfb2df123626dc8b84657427525ecb3e6c08c1a94fc3bbbdd72a9c9594
2023-03-28 10:38:04.809 [INF] WLLT: Published ticket purchase a7cacddfb2df123626dc8b84657427525ecb3e6c08c1a94fc3bbbdd72a9c9594
```

So that is going to be interesting since the RPC will take minutes, possibly quite long on mainnet.

**Comment by JoeGruffins** [comment]
Same as the vsp, it only looks to see if the server is set in the config https://github.com/decred/dcrwallet/blob/c6e7b5f9af7711f5ea2476faac95094d4003c043/internal/rpc/jsonrpc/methods.go#L3402-L3424

**Comment by JoeGruffins** [comment]
> What about RPC dcrwallet instances that are controlled by Decrediton. These will have all the ticker buyer as well as voting policies configured, so do we have competing settings they might change in DEX? How do we prevent conflict?

and

> Here's what I suggest, @JoeGruffins. Enable manual ticket purchases over RPC, but allow disabling via configuration. This makes it possible for Decrediton and others to claim staking privileges.

We don't have a way to change the rpcwallet's config anyway, and I think we can keep it that way. If we add a way to get the config values we can adjust accordingly. So, if ticketbuyer is running, don't allow purchasing at all and respect the `balancetomaintain` when trading. If VSP is not set, don't allow purchasing. Otherwise allow manual purchasing. Always show current tickets and allow changing vote preferences. Show current VSP but it cannot be modified.

Unrelated but do we check rpc wallets are not watching only? Probably they error somewhere in setup?

**Comment by buck54321** [comment]
> Hmm, it looks like the fee payment logic is inside `internal` so we may have to write our own fee payment logic for internal wallets... https://github.com/decred/dcrwallet/blob/master/internal/vsp/feepayment.go

I wonder if @jrick will let us get away with something like this.
```Go
type VSPClient interface {
	Process(ctx context.Context, ticketHash *chainhash.Hash, feeTx *wire.MsgTx) error
	FeePercentage(ctx context.Context) (float64, error)
}

func (w *Wallet) NewVSPClient(vspHost, vspPubKey string, feeAcct, changeAcct uint32,
	maxFee dcrutil.Amount, dialer DialFunc) (VSPClient, error) {

	return loader.VSP(vsp.Config{
		URL:    vspHost,
		PubKey: vspPubKey,
		Dialer: dialer,
		Wallet: w,
		Policy: vsp.Policy{
			MaxFee:     maxFee,
			FeeAcct:    feeAcct,
			ChangeAcct: changeAcct,
		},
	})
}
```

**Comment by buck54321** [comment]
Actually, that won't work. Hmm.

**Comment by JoeGruffins** [comment]
Looking into it. Will just make an ugly copy-pasta for now.

**Comment by JoeGruffins** [comment]
From matrix it looks like a no on getting those config values and a maybe on exposing the fee payment code. @jrick seems to think the maintain balance is bugged and should be removed.

So, can we let rpc wallet users fend for themselves? We let them buy manual tickets but we won't know if they are using a VSP or currently running the ticketbuyer, and we don't worry about balance to maintain. For now at least... @buck54321 I'm not sure I understood what you meant by `but allow disabling via configuration`, do you mean in our config? That is certainly possible.

**Comment by buck54321** [comment]
> I'm not sure I understood what you meant by `but allow disabling via configuration`, do you mean in our config? That is certainly possible.

A `ConfigOption` to disable manual ticket purchasing would be a simple approach. Decrediton could set the option. When the option is used, our UI would degrade to a read-only mode that simply displays current staking stats.

**Comment by JoeGruffins** [comment]
Attempting to export logic from wallet https://github.com/decred/dcrwallet/pull/2224

**Comment by JoeGruffins** [comment]
Backend is solidified. I'm going to clean up the rpc server pr #2316 

If anyone wants to start on the web side please show intent here! Otherwise I will start on it after the rpc pr looks good enough.

**Comment by buck54321** [comment]
If you could, please do the **webserver** and **core** parts in a similar pass-through fashion to #2317, with **core** doing nothing but accessing wallet methods. Where 2317 had `(*Core).shieldedWallet`, you could similarly do something like

```Go
func (c *Core) ticketBuyer(assetID uint32, forFundTransfer ...bool) (asset.TicketBuyer, error) {
	w, found := c.wallet(assetID)
	if !found {
		return nil, fmt.Errorf("no %s wallet", unbip(assetID))
	}

	tb, is := w.Wallet.(asset.TicketBuyer)
	if !is {
		return nil, fmt.Errorf("%s wallet is not a TicketBuyer wallet", unbip(assetID))
	}

	// Check if this wallet can send funds at the moment.
	if len(forFundTransfer) > 0 && forFundTransfer[0] {
		if err := w.checkPeersAndSyncStatus(); err != nil {
			return nil, err
		}
	}

	return tb, nil
}
```

**Comment by JoeGruffins** [comment]
@buck54321 ok. I think that's what I'm doing? Does #2316 look incorrect? For purchasing core will need to unlock the wallet and check the balance after buying.

**Comment by JoeGruffins** [comment]
I was testing out on simnet, and noticed the returned fees from StakeStatus don't look right for the rpc wallet `Fees: (uint64) 18446744073709548636`. They look sane for the internal wallet though. Block height is 0 as well.

**Comment by JoeGruffins** [comment]
ah, ofc
```
$ ./alpha gettransaction 417c1e1c649d312c4a340450c985517afa0b1bc706437afe7bd4ccc159a0ecfe
{
  "amount": -0.0000298,
  "fee": -0.0000298,
  "confirmations": 63,
  "blockhash": "6a3072798f069f3d725c3886a5957362d22b7a3293830151bc75acbb64b360ef",
  "blockindex": 0,
  "blocktime": 1691477807,
  "txid": "417c1e1c649d312c4a340450c985517afa0b1bc706437afe7bd4ccc159a0ecfe",
  "walletconflicts": [],
  "time": 1691477776,
  "timereceived": 1691477776,
```

**Comment by buck54321** [comment]
> @buck54321 ok. I think that's what I'm doing? Does #2316 look incorrect? For purchasing core will need to unlock the wallet and check the balance after buying.

That looks roughly right. Ready for review?

**Comment by buck54321** [comment]
Handled expertly by @JoeGruffins
