### ISSUE TITLE
ltc native wallet and cfilters scanning with litecoind broken

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2267]
https://github.com/ltcsuite/ltcd/pull/25#issuecomment-1487816291
https://litecointalk.io/t/ltcd-wire-deserialization-bug-fixes/57872?u=chappjc

They didn't update after btcd fixed the bugs in Fall 2022.

If they don't merge that PR, we will have to use the [dcrlabs ltcd fork](https://github.com/dcrlabs/ltcd/tree/wire-witness-fixes), and because we cannot release with `replace` statements, we will have to also fork ltcwallet, and update a large amount of imports.  I am hoping that losh will merge that PR, but it has been up for over a month with no comment.  I have asked on litecointalk.io.  If there are any other known developer channels, please consider this urgent and reach out.

**Comment by chappjc** [comment]
For testing, `replace github.com/ltcsuite/ltcd => github.com/dcrlabs/ltcd v0.0.0-20230329011723-6a36409e58b0`
I am able to use the native LTC wallet with that.  That also is needed to fix cfilters scan even with RPC litecoind.

**Comment by losh11** [comment]
Fix has been merged.

**Comment by chappjc** [comment]
Thanks!

**Comment by chappjc** [comment]
Almost there.  Just need https://github.com/ltcsuite/ltcd/pull/29 to resolve a build error introduced by https://github.com/ltcsuite/ltcd/pull/23.
