### ISSUE TITLE
eth: domain helper is misused, and does not handle IP addresses

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2271]
https://github.com/decred/dcrdex/blob/ff852e67bed8961a5dd8f13e5906ef6cb15049f3/client/asset/eth/multirpc.go#L663-L666

The `domain` helper function is only intended for use with a host name (e.g. `provider.host`), but recently it was applied to the full endpoint address, which could be a URL.  To use `domain` for compliant provider matching, we would need to parse the URL first, as we did in `connectProviders`, which used to precede this check.  @JoeGruffins 

A different issue is that `domain` does not work as expected with IP addresses like "127.0.0.1" where it says the domain is "0.1".

Lastly, `func failedProviders(succeeded []*provider, tried []string) string` also misused `domain` since the `tried` slice is the full endpoints, not the hosts.

**Comment by JoeGruffins** [comment]
Will attempt to fix.
