### ISSUE TITLE
dexc web: order preview should show quote amount too

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#228]
When creating an limit order, the base lots and rate are specified.  When rate or amount are changed, there should be a preview of how much of the quote amount will be spent (buy order) or received (sell order).

![image](https://user-images.githubusercontent.com/9373513/77581661-1c830400-6eac-11ea-95bb-e287bfa39ee9.png)

Although a dialog shows the amount after clicking:

![image](https://user-images.githubusercontent.com/9373513/77581906-869ba900-6eac-11ea-8cda-ab7ae4a65528.png)

It would still be desirable to see the amount without clicking.

**Comment by song50119** [comment]
@chappjc, Can I pick this up?
