### ISSUE TITLE
Market maker testing framework

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#2303]
Loadbot can be expanded with new program types that simulate various market conditions. Then, various bot configurations could be tested to see how they fare in those conditions.

**Comment by JoeGruffins** [comment]
I will work on this.

Some possible new programs for the bots: 
- sideways - This would oscillate randomly between a range. 
- trending or increasing/decreasing price - I guess going up or down forever? Can go back the other way once it hits a point?
- volatile - All over the place?

Does this need to test arbitrage in some way? I guess it would be possible to set up mock exchanges although that may be involved.

Should the market maker clients also be automated?

**Comment by JoeGruffins** [comment]
So yes to also testing arbitrage? Using actual exchange rates does make sense. The testing framework is only for simnet though right?

**Comment by martonp** [comment]
Yes for arbitrage, and yes only simnet. I think it can be two separate PRs though.
