### ISSUE TITLE
server: concurrent data api loading

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2315]
converting https://github.com/decred/dcrdex/pull/2151 to issue

**Comment by ukane-philemon** [comment]
I'd be looking into this.

**Comment by buck54321** [comment]
Just do 1) for now. I'm not sure about 2). What do we do client side if a market is open but historical data is not available?

**Comment by chappjc** [comment]
> Just do 1) for now. I'm not sure about 2)

Do 1, but that's a relatively small issue .  Load speed is poor even for markets that are just months old.  The big issue is when you have many defined markets, and the history data loads sequentially, not in parallel.

> What do we do client side if a market is open but historical data is not available?

For 2, you can at least load the data for markets in parallel.  It's not IO limited, so we can take advantage of as many CPU cores and are available.  Doing so does not mean that you have to start a market before it's historical data is ready.  Just ready them in parallel.

Going one step further, start the markets as their data becomes ready instead of waiting for all.

However, to answer your question, you don't need historically data to start the market, only book.  In fact, server admin can turn it off.  It's entirely auxiliary to the functioning of a market.  I think you have have some assumptions in client about the availability of the data, mainly in frontend.

**Comment by buck54321** [comment]
The best solution would be to store day and hour data in the DB for quick loading, and then we only need to construct the last candle from the epoch table.

**Comment by buck54321** [comment]
> However, I think we do have have some assumptions in client about the availability of the data, mainly in frontend.

I guess this was my concern. We're probably making some assumptions client-side about data availability, and nothing to handle delayed loading.

**Comment by chappjc** [comment]
> The best solution would be to store day and hour data in the DB for quick loading, and then we only need to construct the last candle from the epoch table.

Agree

**Comment by buck54321** [comment]
I'm taking a look at the DB option.
