### ISSUE TITLE
client/asset: import p2sh script to wallets

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#234]
`importscript` command for dcrwallet, and `importaddress` command for bitcoind can be used before broadcasting the swap transaction to force the wallets to watch for and index the vins/vouts. It's not actually necessary to watch for those addresses in order to perform swaps, and the client won't actually make use of the newly stored transactions, but it's helpful for auditing purposes.

**Comment by chappjc** [comment]
I noticed this during out first testnet swap in dcrwallet's logs (where DCR was being sold as the Maker):

```
[INF] WLLT: Inserting unconfirmed transaction 4a14a2d79c1374d286ebd68d2c104343bcf8be44ed54045b5963fbf73667cecc
[DBG] WLLT: failed to find redeemscript for address TchUiUNfb96ji35N767BNesdKTe88KP35nf in address manager: item does not exist: no address with id 6d4bc656b3287a0e6b0d38802db6400f70531117
[DBG] WLLT: Marked address TsnuLiVxWBPMdNd2fG7kWhMQTj8FXSWJ9ab used
...
[DBG] WLLT: Marking unconfirmed transaction 4a14a2d79c1374d286ebd68d2c104343bcf8be44ed54045b5963fbf73667cecc mined in block 396615
[DBG] WLLT: failed to find redeemscript for address TchUiUNfb96ji35N767BNesdKTe88KP35nf in address manager: item does not exist: no address with id 6d4bc656b3287a0e6b0d38802db6400f70531117
[DBG] WLLT: Marked address TsnuLiVxWBPMdNd2fG7kWhMQTj8FXSWJ9ab used
[DBG] WLLT: Updating processed txs block marker to 00000065b1ca3c495de63fe61eea70c277d656958f3d949042db0fc3680bdb98
[INF] SYNC: Connected block 00000065b1ca3c495de63fe61eea70c277d656958f3d949042db0fc3680bdb98, height 396615, 1 wallet transaction(s)
```

TchUiUNfb96ji35N767BNesdKTe88KP35nf is the contract's P2SH address, which was created by this user, so it is reasonable for dexc to import the redeem script for the contract prior broadcasting the txn.  When the contract is redeemed by the taker, the redeem script is revealed publicly, but if things go sideways, it would be best to have dcrwallet already aware if the redeem script if revocation without dexc help.

**Comment by chappjc** [comment]
Pretty sure we've decided for a different solution for SPV using cfilters, not importscript.  Please close if that's correct.

**Comment by chappjc** [comment]
Bump on the suggestion to close this

**Comment by buck54321** [comment]
It doesn't look like we'll be using `importscript`. Feel free to close.
