### ISSUE TITLE
core: wrong password error is unrecoverable 

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#235]
If you enter the wrong password during wallet creation, you get an error message, but attempting to enter the correct password results in a "wallet already exists" error and there's no way to get things right. 

The wallet password should be checked before the wallet is stored.

**Comment by buck54321** [comment]
I've started work on this.

**Comment by chappjc** [comment]
I haven't confirmed, but based on convo with ay-p, it seems like any of the settings such as account/wallet cannot be fixed either.  Will review PR #240 today. Maybe that covers it too.
