### ISSUE TITLE
client: search for bond priv key for unknown bonds reported by server

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2371]
If a user restores from seed but does not then import and bond data from a previous instance, any active bonds reported by the server are considered "unknown".

https://github.com/decred/dcrdex/blob/f081ef2efab52e951ea3f3e5831e674a32fbd0fc/client/core/core.go#L6553-L6570

This "EXPERIMENT" code creates a db.Bond from the data from the connect result, but we don't try to figure out the KeyIndex, which would let us actually refund it (assuming it's real and the server didn't report garbage to us).  To do this:
- use the coin ID to pull the transaction, which should be simple for the wallet if it was the wallet that created the bond (if it's not then we won't have the keys anyway)
- construct the bond redeem script from the bond commitment output (second output), the missing `bond.Data`
- iterate `KeyIndex` from zero to find a private key that can spend the bond output i.e. matches the pubkey hash data push
- store the correct `KeyIndex` in the `db.Bond` and **store** that in the client DB

This is only a partial solution to the bond data restoration issue because server isn't going to report expired bonds, which may still be unspent.

**Comment by JoeGruffins** [comment]
I was updating the `simnet-setup.sh` to work with bonds and `discoveracct` does not seem to work anymore. Is this the same issue?

**Comment by chappjc** [comment]
No, different issue. Discover works through GUI, so sounds like rpc issue.

**Comment by JoeGruffins** [comment]
Apologies, trying again today seems to be working as expected. Looks ok actually.

**Comment by JoeGruffins** [comment]
I understand what this pr is asking now and would like to work on this.

**Comment by JoeGruffins** [comment]
Correct me if I am wrong. 

We could add the bond key index and the account index to the current nulldata output which would make recreating the redemption script much more straightforward. Unsure if this is a security risk, I assume not.

If we added one more nulldata script with something belonging to the user's wallet, for instance the account ID, but minus the unknown locktime, I think we could pull out all of a users active bonds with a cfilters scan. This would make finding expired bonds at seed restoration possible without any data from the server/servers.

**Comment by JoeGruffins** [comment]
For the current issue, I will attempt to solve the problem as chapp suggested for v0 bonds, and only for bonds the server reports that we don't know about. I think the problem can be solved better entirely with a new bond version that includes an output we can search for as stated above, so leaving the second part of this issue for now.
