### ISSUE TITLE
ui: depth chart marker for own orders reluctantly appears

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2373]
The triangle marker on the depth chart that identifies the location of your own orders does not appear until you hover your mouse over the order in the "Your Orders" list below the order form.

![image](https://github.com/decred/dcrdex/assets/9373513/7339f2b2-ea7f-43b0-b884-7c2383c15a76)

Note that hovering does make it get big, and then it gets smaller, as expected, but neither size marker is there until you do that.

**Comment by ukane-philemon** [comment]
> but neither size market is there until you do that.

@chappjc, please can you expatiate on this?

**Comment by chappjc** [comment]
I meant to say marke**r**, not marke**t**.  Issue edited.

**Comment by ukane-philemon** [comment]
> The triangle marker on the depth chart that identifies the location of your own orders does not appear until you hover your mouse over the order in the "Your Orders" list below the order form.

do you mean the own order chart marker should always show if there are active others not only when the "Your Orders" section receives a hover mouse action?

**Comment by buck54321** [comment]
> do you mean the own order chart marker should always show if there are active others not only when the "Your Orders" section receives a hover mouse action?

Yes

**Comment by ukane-philemon** [comment]
> > do you mean the own order chart marker should always show if there are active others not only when the "Your Orders" section receives a hover mouse action?
> 
> Yes

It seems @chappjc discovered a hidden feature?

These code lines, I think control this behaviour.
https://github.com/decred/dcrdex/blob/master/client/webserver/site/src/js/markets.ts#L1491-L1494
https://github.com/decred/dcrdex/blob/master/client/webserver/site/src/js/markets.ts#L445-L448

We can display this always but there are some UX considerations.
1. Some users don't know what those markers are.
2. Displaying them always(without user intervention) might seem counter-intuitive. 

> 1. Indicators on the depth chart for the user's orders. When the mouse hovers near
  the indicator, the order is highlighted in the "Your Orders" table. Conversely, when
  the mouse hovers over a row in the "Your Orders" table, the indicator is highlighted
  on the chart. From https://github.com/decred/dcrdex/pull/837

**Comment by chappjc** [comment]
> We can display this always but there are some UX considerations.
> 
> 1. Some users don't know what those markers are.
> 2. Displaying them always(without user interaction) might seem counter-intuitive.

Strongly disagree.  They are not confusing.  Also, the user interaction is creating the orders, so it's not happening without any queue.

> > 1. Indicators on the depth chart for the user's orders. When the mouse hovers near
> >    the indicator, the order is highlighted in the "Your Orders" table. Conversely, when
> >    the mouse hovers over a row in the "Your Orders" table, the indicator is highlighted
> >    on the chart. From [ui: more chart interactivity #837](https://github.com/decred/dcrdex/pull/837)

The above is describing the **highlighting** of the market, not the appearance or disappearance.

This really is a simple issue.  The market needs to be created when the point on the depth chart is created.

**Comment by ukane-philemon** [comment]
> Furthermore, they always stay after they appear -- the intent is for them to always be there!

Okay. I might have been confused about what "highlighting" meant in that context.

**Comment by chappjc** [comment]
> > Furthermore, they always stay after they appear -- the intent is for them to always be there!
> 
> Okay. I might have been confused about what "highlighting" meant in that context.

Fair enough.  I should have demonstrated with a vid.

https://github.com/decred/dcrdex/assets/9373513/3cecb217-8976-4eb4-8100-5517c27317cc

In the above video:
- I created that order and it appeared on the depth chart, but without a marker.
- I hover on the You Orders entry and it appears.  It is initially also "highlighted" (a bit bigger) because I'm also hovering.
- I move the mouse away from the entry and it "unhighlights" (gets smaller), but it stays.
- At about 0:10, I reload the page and the marker draws on the fresh depth chart automatically.  You can also navigate away and back to the market to see that these markers are supposed to be there always.
