### ISSUE TITLE
Volume display changing frequently to impossible numbers

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#2376]
Running on mainnet I saw the volume numbers jumping around:

<img width="384" alt="Screenshot 2023-06-03 at 10 20 03 AM" src="https://github.com/decred/dcrdex/assets/6186350/690c5325-407d-4955-b83a-eae62e7d2872">
<img width="384" alt="Screenshot 2023-06-03 at 10 19 57 AM" src="https://github.com/decred/dcrdex/assets/6186350/bbf64465-3c3e-483f-acdb-2f37db4f3f66">
<img width="384" alt="Screenshot 2023-06-03 at 10 19 41 AM" src="https://github.com/decred/dcrdex/assets/6186350/ea86ca11-de7e-4c2a-be6b-8d0f4e5ed130">

Few minutes later I restarted and the number was still at 1680. There are some orders exactly 1 day ago, so perhaps that is related.

**Comment by JoeGruffins** [comment]
Impossible because they are not divisible by the lot size or they are too high? This is the dcr_btc market?

**Comment by martonp** [comment]
Yes, I said it was impossible because they are not divisible by the lot size.
