### ISSUE TITLE
spec: update community conduct

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#238]
One thing that became apparent with #206 is that the rules of community conduct need some revision. 

1. The language needs to be more precise and to disambiguate between orders and matches. 
2. The full algorithm for cancellation ratio should be agreed upon and documented. Must include description of the rolling average calculation for low counts.
3. There has been good support for adding temporary penalties. 
4. Procedures for petitioning account recovery should be agreed upon and documented.

**Comment by chappjc** [comment]
I'm in a position to draft the algorithm for cancellation ratio computation.

Failure to act in an active swap is a more severe violation than canceling a booked order, I think we can agree, but I think immediate account closure is harsh.  Revision to this could involve temporary penalties (as mentioned in 3. of this issue) and/or affecting a user's "conduct score", which does not exist presently, more heavily than order cancellation would.  Thus, another possible revision to community conduct rules could merge rules 2 (settlement/inaction) and 3 (cancellation ratio), with a common scoring mechanism.  e.g. cancelling an order is 1 strike, inaction or invalid responses during swap is 3 strikes.

I gave some though to account re-opening, and while I'm certain it's going to be a common thing early on, I'm not sure what mechanism would allow this without spamming the operator incessantly.  @JoeGruffins BTW, this was one of the next things I was thinking for dcrdex's admin interface -- `/account/{accountID}/reopen` or something similar.

**Comment by xaur** [comment]
Cancellation ratio sounds like a policy local go a given server. I imagine that some server admins may be okay with more cancellations.

**Comment by buck54321** [comment]
@xaur: The cancellation ratio is a variable set by the operator. Looking forward to decentralized markets though, there will probably need to be agreement on a lot of these policy variables in order for markets to be compatible.

**Comment by buck54321** [comment]
> Revision to this could involve temporary penalties (as mentioned in 3. of this issue) and/or affecting a user's "conduct score", which does not exist presently, 

There has been some previous discussion of something named **reputation**, and I'm guessing your concept of **conduct score** would fit the bill.  **cancellation ratio** will only be one variable in a larger equation. 

I think it's okay to work in the direction of a scoring system right away.

**Comment by xaur** [comment]
Reputation needs to be attached to something, which brings us to the problem of how we model the identity system, esp. if we want to make it compatible with decentralized markets in the future. Also, decentralized environment will raise the question of what source of reputation to trust, which is the web of trust area.

It will obviously have something to do with cryptographic keys and bring all the challenges of PKI, e.g. how to deal with revocations.

**Comment by xaur** [comment]
Speaking of language, is there any reason this thing is called "community conduct" and not simply "server rules"? The former is popular these days in a very different context as you might know.

**Comment by buck54321** [comment]
I'm more than open to changing the name. Always taking suggestions, but I'm not crazy about "server rules". Maybe something like "trading rules"? I dunno.

**Comment by buck54321** [comment]
**A starting point for discussion of a score system, tentatively called the trade score.**

***S*** = trade score
***N*** = count of most recent **matches** up to 100
***c*** = cancellations of the last 50 placed **orders**
***r*** = at-fault revocations

![image](https://user-images.githubusercontent.com/6109680/88242166-0dda0d00-cc52-11ea-80ec-e340e3520718.png)

There are two score minima. The soft minimum (***m<sub>soft</sub>***) is 0.9. The hard minimum (***m<sub>hard</sub>***) is 0.8. For clients with 0.8 <= ***S*** < 0.9, the client is metered at a maximum of 1 active order until they get their score back up. If the client's score drops below 0.8, their account is suspended and they can no longer order, though they can still `connect` and complete active matches. They may petition the DEX operator for reinstatement.

Trade score is uncalculated for first two matches. Matches are not counted until completed or revoked. Orders are not counted until executed, revoked, or cancelled. 

For clients with 3 <= ***N*** < 100 matches, the hard and soft minima are adjusted by a factor, ***a(N)***

![image](https://user-images.githubusercontent.com/6109680/88241683-758f5880-cc50-11ea-8b87-2ca52231e0b7.png)
![image](https://user-images.githubusercontent.com/6109680/88241708-893abf00-cc50-11ea-9c74-ef1cd3425c8a.png)
![image](https://user-images.githubusercontent.com/6109680/88241729-948dea80-cc50-11ea-9971-9785c0c2b472.png)

These factors are chosen so that a user could have 1 at-fault revocation in their first 3 matches and still recover.

Of course, all of these parameters are adjustable and the scoring formulas should be scrutinized, but I'm hoping this captures the most basic requirements of a score system.

**Comment by chappjc** [comment]
Fully in support of a unified scoring system that incorporates both cancels and match failure/revocations.  This allows a simplified single score and does not necessarily penalize a user for their first revocation.
