### ISSUE TITLE
Post Bond Page - Improving UX

### ISSUE THREAD

**Issue by exitus1** [decred/dcrdex#2381]
As discussed on matrix, there should be some relevant info as to what a fidelity bond is on the initial post bond page, and information telling the user when they can expect to unlock their bond funds.

When you select an asset to create the bond, there is some nice, succinct info, perhaps this can be duplicated so it's on both pages?:

![image](https://github.com/decred/dcrdex/assets/46197055/08857b82-574e-42b7-9d1a-86164296a18b)

There was also discussion on changing the wording from "Post Bond" to something less foreign sounding, like "Create your bond"  Or "lock funds in your bond".

**Comment by chappjc** [comment]
Resolved in https://github.com/decred/dcrdex/pull/2395 and shipped with [v0.6.2](https://github.com/decred/dcrdex/releases/tag/v0.6.2). Decrediton update pending in https://github.com/decred/decrediton/pull/3882
