### ISSUE TITLE
server/dex: should allow network-versioned configuration files or settings

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#239]
Switching between networks requires changing the `regfeexpub`, but the exported key is network-specific. I could see a couple of approaches to fixing this.

1. Before checking *~/.dcrdex* for the config file, check *~/.dcrdex/[netname]* for a file first.

2. Create separate config entries for `xfeeregfeexpub_simnet` and `regfeexpub_testnet`. This might be the easiest, but if there are any other settings that might need network versioning, this solution quickly gets ugly.

**Comment by chappjc** [comment]
I just run `dcrdex` with `--whatevernew --regfeexpub={network specific value}` on the command line, so it hasn't bothered me much.  Another approach a user might take is to specify a config file when changing networks, e.g. `dcrdex -C ~/.dcrdex/dcrdex-mainnet.conf`.

**Comment by ukane-philemon** [comment]
@chappjc, is this still an issue?
Looks like your comment would need to be somewhere in the docs for easier reference?
> I just run dcrdex with --whatevernet --regfeexpub={network specific value} on the command line, so it hasn't bothered me much. Another approach a user might take is to specify a config file when changing networks, e.g. dcrdex -C ~/.dcrdex/dcrdex-mainnet.conf.

**Comment by chappjc** [comment]
I don't know.  I don't think it's an issue personally.  In practice, operators aren't going to have multiple networks running, and the config file approach seems fine to me.
I don't want to rename `regfeexpub` to `regfeexpub_{network}`

**Comment by ukane-philemon** [comment]
@buck54321 what do you think? We can find somewhere in the docs to put @chappjc's comment.

**Comment by xaur** [comment]
> Another approach a user might take is to specify a config file when changing networks, e.g. `dcrdex -C ~/.dcrdex/dcrdex-mainnet.conf`

This is the best. I use this for dcrwallet configs. Switching all options with a single arg is very convenient. Conf files can be easily diffed and synced. Even better if the app has `--appdata` to switch all state (including the .conf file) with a single arg. It is already mentioned in `Server-Installation.md`.
