### ISSUE TITLE
ui: misleading bond message

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2408]
When starting up after being shut down for a while.

![image](https://github.com/decred/dcrdex/assets/6109680/2feb5c25-3536-4d12-9d84-a972de94c329)

(Note also the typo `You` instead of `Your`)

The logic in **markets.ts** goes like...

```Typescript
if (market.dex.tier >= 1) {
  ...
} else if (this.hasPendingBonds()) {
  ...
} else {
  ...
  Doc.show(page.bondRequired)
}
```

But there must be a non-insignificant delay between startup and broadcast of new bonds, because the message persists for enough time to cause confusion. I think we need to check target tier instead of pending bond count or something.

**Comment by chappjc** [comment]
> But there must be a non-insignificant delay between startup and broadcast of new bonds, because the message persists for enough time to cause confusion.

Correct.  `rotateBonds` has is on a 20 second ticker, I believe.

> I think we need to check target tier instead of pending bond count or something.

That sounds more appropriate.  Or if (target tier < current tier) && (pending bond count == 0) then say something else like bonds will post shortly, balance permitting.

**Comment by JoeGruffins** [comment]
Will try to solve this.
