### ISSUE TITLE
[Decrediton] Connect DRC Wallet: Failed to retrieve user information

### ISSUE THREAD

**Issue by pacu** [decred/dcrdex#2430]
I'm not being able to connect my newly created wallet with DEX.

Steps:

1. open Decrediton 1.8.0
2. Create a new wallet
3. follow backup procedure 
4. use SPV 
5. wait until wallet is synced
6. go to DEX tab
7. follow instructions to create DEX seed and passphrase
8. Click "Connect DCR Wallet Button"
9. input both passphrases

**expected:** 
DCR wallet is connected to DEX

**result:** 
Error notification toast message shown at the bottom of the screen reads
"Failed to retrieve user information: Error: User error: response buffer too short (need [REDACTED_AMOUNT] bytes)"

MacOS: 13.4.1 (22F82)

**Comment by chappjc** [comment]
Decrediton issue resolved in https://github.com/decred/decrediton/pull/3882
I suggest using the standing dex application instead
