### ISSUE TITLE
dexc-desktop/linux: target="_blank" links do nothing

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2453]
May be able to write some C to handle it. See https://github.com/webview/webview/issues/113

**Comment by dev-warrior777** [comment]
So you would provide a "tailor made" webview library for dex with an extra C++ closure or C callback worked in?

(C++ as the `webview.h` code has changed quite a bit since the link above from 2018)

`g_signal_connect` `g_signal_connect_data` macros are still available though so can use mostly C.

**Comment by buck54321** [comment]
> May I know more about the specific issue for dex, pls.

External links need to open in the user's web browser. Right now clicking external links does nothing. I mean `target="_blank"` links. 

I see we're using `window.open` a couple of places. Might need a solution there too. Haven't looked yet.

**Comment by dev-warrior777** [comment]
![image](https://github.com/decred/dcrdex/assets/126670673/8adce140-c2d5-4239-a139-809bb89ec3ef)


Quick answer is:
loading into the same browser window 

- javascript: window.open(url, '_parent'); 
- javascript: window.open(url, '_self'); 
- javascript: window.open(url, '_top');

..all work (linux)

none of the others above do.

I have looked at a few old (many years ago) gtk patches where the signal `"create-web-view"` was used to create a new webview and load the new url into it. None of those seem to exist now.

Will see if gdb can help find out if _any event code_ is called on execution of any of the above JS. Then I think I have spent too much time on this for now.

**Comment by dev-warrior777** [comment]
![image](https://github.com/decred/dcrdex/assets/126670673/604828d9-0532-4173-885f-643b9d35ebf8)

- It does not really work!

Above I can create a new `webview` with a `"create"` signal and callback from webkit2 .. but I have to cheat and fire the signal myself synchronously. This is because no signal seems to be fired from a javascript: `window.open(url, '_blank');` execution embedded in the first window **win_test** above.

Maybe we can connect to a DOM event .. not sure .. I did not look at that.

**Comment by dev-warrior777** [comment]
So I forgot about doing this the way described in the 2018 link and looked at what is available in webview functions today. 

![image](https://github.com/decred/dcrdex/assets/126670673/e905d8bc-429f-404b-913c-d521f07dc621)

This is an adaptation from the [examples](https://github.com/webview/webview/tree/master/examples) -- bind.go. Actually I did all this in C first which is easy enough.

[bind_open_blank.zip](https://github.com/decred/dcrdex/files/12336598/bind_open_blank.zip)

**Comment by dev-warrior777** [comment]
Only tested on linux since I do not have other laptops here .. but the way the *webview* library is structured I would not expect errors from mac (cocoa) or windows (edge)

**Comment by ukane-philemon** [comment]
> Only tested on linux since I do not have other laptops here .. but the way the _webview_ library is structured I would not expect errors from mac (cocoa) or windows (edge)

Thanks for investigating the issue @dev-warrior777, dexc-desktop for MacOS is using the MacOS Native APIs directly so I think it's not affected.

I'm also a bit limited to my MacOS machine but will find time someday to dual-boot and dog-feed on Windows.
