### ISSUE TITLE
Token Address should be displayed

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#2467]
ETH/Polygon token addresses should be displayed on the screen so the user can be sure which token they are using.

**Comment by ukane-philemon** [comment]
@martonp please can you add more flesh to this? What address exactly? deployment or wallet?

**Comment by martonp** [comment]
The address of the ERC20 contract for the token. https://github.com/decred/dcrdex/blob/3c1aeb49479309f15c39823b5842af4b08a02492/dex/networks/eth/tokens.go#L162C1-L162C1

**Comment by buck54321** [comment]
Assigning @peterzen

**Comment by peterzen** [comment]
> ETH/Polygon token addresses should be displayed on the screen so the user can be sure which token they are using.

Where in the UI would you like to see this displayed?
