### ISSUE TITLE
Reset password option via seed (when password forgotten)

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2475]
If the user forgot his password he can't reset it in DEX UI on his login page (he could go to settings and try to reset it there, but it will ask the user for his current password - which he doesn't remember):

<img width="400" alt="image" src="https://github.com/decred/dcrdex/assets/112318969/35083913-6c13-428d-a9b4-74a9765e2aea">

the only way to reset password currently in this situation is to re-import DEX seed. But you can't re-import seed without manually deleting DEX database (so it's pretty much  "advanced user only" option, and somebody came asking about it in support channel recently).

I see 2 options on how to address this:
- "change password" section in settings might accommodate additional option for resetting with DEX seed (instead of with current password)
- but this ^ is still somewhat complex to use this flow, so we should probably have a clickable button/link on login page along the lines of "I forgot password" which will open resetting with DEX seed dialogue for user

**Comment by ukane-philemon** [comment]
Thanks for your input on the support channel. I'd like to work on this if you are not already on it.

**Comment by norwnd** [comment]
> I'd like to work on this if you are not already on it.

Sure, go ahead.

**Comment by JoeGruffins** [comment]
In my opinion it is the user's responsibility to remember their password. I don't think this is an issue. They have the seed to create a new dex with no lost funds, besides possibly bonds that are not refunded... Which would be a real issue.
