### ISSUE TITLE
ui: Block buy/sell button when balance is 0

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#2527]
When trying to buy DCR on the DCR/DEX.TT market and the DEX.TT balance is 0, I get the confusing error message: 'error estimating swap gas: error calculating swap gas: execution reverted: transfer from failed'. 

If one of the asset balances is 0, then the button to trade from that asset should not be sensitive, and there should be a tooltip saying "Cannot {buy/sell} because balance is 0. If both balances are 0, then the order form should be hidden.

**Comment by peterzen** [comment]
I can tackle this one if no one else is working on it.

**Comment by peterzen** [comment]
Hiding the order form altogether is confusing UX - it would take away the ability to discover the UI.  With the buttons disabled the order form can't be submitted.  Maybe we could consider greying out the form and adding a label across along the lines of "Deposit funds to trade".
