### ISSUE TITLE
ui: DEX server edit screen doesn't have a close/back button

### ISSUE THREAD

**Issue by peterzen** [decred/dcrdex#2545]
The update DEX server dialog can not be closed the same way as other dialogs, the only way to get back to the Settings UI is to use the browser's back button.

![image](https://github.com/decred/dcrdex/assets/5878500/3414e804-67da-48e7-99ba-45795e8e810f)

**Comment by ukane-philemon** [comment]
I think this is a page not a dialog. Click menu btn -> click settings btn should be an easy flow, no?

**Comment by peterzen** [comment]
It is indeed a page.  However, from a user flow perspective, there should be a way to go back one level - consistently with the rest of the GUI.

**Comment by ukane-philemon** [comment]
> However, from a user flow perspective, there should be a way to go back one level - consistently with the rest of the GUI.

Yh, just have to find a way to squeeze it into the UI :). If it were a dialog, we could use the x closer as it aligns with our current UI.
