### ISSUE TITLE
JS errors when running live webserver

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrdex#2549]
The first error log was generated on the `wallets` page and the second on the `markets` page.

<img width="1677" alt="Screenshot 2023-09-29 at 8 40 03 PM" src="https://github.com/decred/dcrdex/assets/57448127/0e05e68d-4b98-4f02-84af-79755f2b914c">

**Comment by peterzen** [comment]
Are there any particular steps to reproduce this?

**Comment by ukane-philemon** [comment]
npm run build and run the live web server test.

**Comment by peterzen** [comment]
I'm unable to reproduce this on the current tip.  I do see other errors such as the one related to #2532 and this other one below but not the one you're encountering.
![image](https://github.com/decred/dcrdex/assets/5878500/0b8a3a91-fd7f-4c6c-a246-79277ac0be72)

**Comment by buck54321** [comment]
I think this is outdated. Can reopen if needed.

**Comment by ukane-philemon** [comment]
> I think this is outdated. Can reopen if needed.

Yh, master is error-free.
