### ISSUE TITLE
server/comms: TestClientRequests fails randomly with "clientCount != 0"

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#255]
![image](https://user-images.githubusercontent.com/34998433/79058550-7bb58680-7caa-11ea-9156-0ed7acc1b2a4.png)

I have been unable to reproduce this failure locally, but have hit it twice while submitting pr's. 

This is a temporary example, but you can see in #221 between the commits 47e23bd and be3ccde where only a comment was changed indicating that this failure will happen radomly.

**Comment by buck54321** [comment]
This was likely resolved by #435
