### ISSUE TITLE
ui: wallet forms not showing correctly on markets view

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2574]
When 1 wallet is not created yet, we used to show the other wallet and a button to create the missing wallet. None of that is displayed anymore.

![image](https://github.com/decred/dcrdex/assets/6109680/f9ff3d24-94bb-433a-af89-82beb8ad48b7)

**Comment by ukane-philemon** [comment]
Surprising. I'll investigate and suggest a fix.
