### ISSUE TITLE
ui: Background colors and depth effects

### ISSUE THREAD

**Issue by peterzen** [decred/dcrdex#2578]
At present, all UI elements on the screen are visually on the same level, mostly using the same background color.  This makes it difficult for the eye to distinguish between elements (tabs, dialogs, stuff that provides information vs controls expecting interaction, etc).   (See also #2075) 

This could be improved by introducing a few additional hues of the current blue, and applying a touch of 3D effects.

![image](https://github.com/decred/dcrdex/assets/5878500/9efeb9aa-a8af-44fb-b9f7-bf1a34a5be3e)
![image](https://github.com/decred/dcrdex/assets/5878500/c73c6693-14a0-4f4d-9bfb-084cf019766f)

![image](https://github.com/decred/dcrdex/assets/5878500/53f360a7-da58-4d9c-8a23-173d2d634a7e)
![image](https://github.com/decred/dcrdex/assets/5878500/da5479db-b9bf-4d3f-920e-3506b95cf9cc)
![image](https://github.com/decred/dcrdex/assets/5878500/04915f6b-7acb-4969-9afe-94e26362cac8)

The light mode is especially hard on the eye in this regard.

![image](https://github.com/decred/dcrdex/assets/5878500/7cb8131c-b315-450c-933b-624366c22962)

![image](https://github.com/decred/dcrdex/assets/5878500/bb9ddfec-a1c8-4b23-9bcb-38648e084572)
![image](https://github.com/decred/dcrdex/assets/5878500/e00d8e0a-99ff-4304-ac9d-ae41bd4b905b)

**Comment by buck54321** [comment]
I think this looks really good for the dialogs, though I might go a little more subtle shade difference in light mode. The first picture is the shade I'd use for dark-mode dialogs. Looks like `#102332`. The second image's shade is too bright. 

Can I see it with a drop shadow that's maybe 1px smaller and not offset?

I'm less excited for the market panes. What's that look like in dark mode?

You can just open a PR.

**Comment by ukane-philemon** [comment]
@buck54321, I think this was resolved by https://github.com/decred/dcrdex/pull/2601?  If there are targeted UI changes we can open issues for them.
