### ISSUE TITLE
client/{dcr,btc}: maxOrder loop needs to be a binary search

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2589]
With the new trade limits implementation, lot sizes can be thousands of times smaller than what we're used to dealing with. Our current `maxOrder` implementation does some rough estimation, and then zones in on the exact max order by looping with a `lots--` until it finds the value. This is a bad idea if lot sizes are really small. Instead, we should do a binary search.

https://github.com/decred/dcrdex/blob/6a12553d2e0034f6d141345bb0ecd413cfc2650b/client/asset/btc/btc.go#L1874-L1885

**Comment by thanhnp2k** [comment]
I'll solve this issue
