### ISSUE TITLE
ui: Optimize notification dropdown layout/legibility

### ISSUE THREAD

**Issue by peterzen** [decred/dcrdex#2591]
The notification feed dropdown feels rather crowded at present, both in terms of the number and formatting of notes.  Also, the content of the messages could be reworded slightly to be less techy and resemble those on other trading platforms (i.e. appear more familiar to the normie trader).

#### Notifications tab

 * show shortened hashes and maybe make them clickable (if so,  display details in a modal panel so that the user doesn't have to navigate away from the Markets view)
 * Redemption Confirmed messages say the same information as the *Redeemed...* in the Activity tab, consider hiding these

<table border="0">

 <tr>
    <td style="vertical-align: top;">
<img src="https://github.com/decred/dcrdex/assets/5878500/71b71b6c-cd70-47d4-a7e4-174be9f44dc9">
</td>
    <td style="vertical-align: top;text-align:top;" valign="top"><img src="https://github.com/decred/dcrdex/assets/5878500/8ecf0608-ce73-4aea-9016-623258099721" style="vertical-align:top;display:inline-block;"></td>
 </tr>
</table>

#### Recent activity tab
 * change message formatting to be similar to the Notifications
 * consider hiding intermediate status messages (e.g. swaps initiated) - under normal circumstances the user doesn't need to know about these (they can still be displayed in bubbles but don't really have to take up space in the feed).  Show instead a message if something goes wrong under the hood.

<table border="0">

 <tr>
    <td style="vertical-align: top;">
<img src="https://github.com/decred/dcrdex/assets/5878500/06e21825-9e6c-4a1f-855f-ad5ea42c443b">
</td>
    <td style="vertical-align: top;text-align:top;" valign="top"><img src="https://github.com/decred/dcrdex/assets/5878500/bfb3f38c-de21-46e7-915f-7feea09fc582" style="vertical-align:top;display:inline-block;"></td>
 </tr>
</table>

**Comment by thanhnp2k** [comment]
I will resolve this issue

**Comment by buck54321** [comment]
> I will resolve this issue

Not this one, @thanhnp2k. Do some smaller work first please.

**Comment by buck54321** [comment]
@peterzen, I agree with this take. I've thought about links before, and I think it's possible. We just need a custom bit of markup that includes the asset id. Something like `{{{42|Tsd9nXSRYyxoLafFJnbkPTs9fRHSUuKSQgu}}}`. The front end can figure out what to do based on the asset and the length of the second bit, e.g. address, transaction ID, or transactionID + vout. I think. Probably have to do some work on the `CoinExplorers` functions.

**Comment by peterzen** [comment]
Should the explorer view open in a modal?

**Comment by buck54321** [comment]
I don't think so.
