### ISSUE TITLE
ui: Checkbox label jerkiness

### ISSUE THREAD

**Issue by peterzen** [decred/dcrdex#2605]
Labels change font weight on hover - is this a feature or a bug?

![ezgif-1-fdffd6b5f6](https://github.com/decred/dcrdex/assets/5878500/885377e4-2311-4819-b6d5-49b09789ccdf)

**Comment by thanhnp2k** [comment]
> Labels change font weight on hover - is this a feature or a bug?
> 
> ![ezgif-1-fdffd6b5f6](https://user-images.githubusercontent.com/5878500/282918533-885377e4-2311-4819-b6d5-49b09789ccdf.png)

I will resolve this issue

**Comment by thanhnp2k** [comment]
I will resolve this issue

**Comment by buck54321** [comment]
It's a feature from the `form-check-label ` class, and it's actually a nice effect on Chrome, at least on Linux, but on other systems it looks pretty bad.

**Comment by thanhnp2k** [comment]
Oh. So it's a feature, right? I understand, and I will choose other issues accordingly

**Comment by buck54321** [comment]
I mean, if it looks bad, we should either get rid of it, or figure out how to make it look good. The big difference is that on Chrome, it doesn't change the text size, but on others it does. My guess is that it's some difference with the text rendering system that we can't do anything about. 

@peterzen Think we should rid of it?

**Comment by peterzen** [comment]
It's the `font-weight` that changes on hover, the exact rendering does indeed vary on browser/font settings.  It looks a bit like a bug TBH, I think we should get rid of the hover effect.
