### ISSUE TITLE
app: add ability to sign out

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#261]
Maybe just a little icon to click to open a small menu with an option to sign out. 

<img src="https://user-images.githubusercontent.com/6109680/79223884-cdcbe880-7e1f-11ea-8baa-44ab8c577530.png" height="96" width="352">

If there are active trades, signing out should only sign out of the app (by deleting the auth cookie), not close the actual core accounts and wallets. 

Here's the SVG for the profile icon: [profile.svg.zip](https://github.com/decred/dcrdex/files/4475199/profile.svg.zip)

**Comment by chappjc** [comment]
@song50119 is gonna pick this up.

**Comment by JoeGruffins** [comment]
@chappjc can close?

**Comment by buck54321** [comment]
Resolved by #347
