### ISSUE TITLE
Cant connect to DEX server - bad handshake

### ISSUE THREAD

**Issue by pagoda0** [decred/dcrdex#2654]
Hello, 

im running dcrdex via decrediton. When i try to login to a DEX server (dex.decred.org:7232) i get these errors: 

```
2024-01-04 11:46:29.828 [ERR] DEXC[wss://dex.decred.org:7232/ws]: Initial connection failed, starting reconnect loop: websocket: bad handshake
2024-01-04 11:46:29.828 [ERR] SRVR: websocket: bad handshake
```
I already used dcrdex before and did some swaps so im surprised its not working anymore. Im using the latest decrediton 1.8.1

**Comment by peterzen** [comment]
> I already used dcrdex before and did some swaps so im surprised its not working anymore. Im using the latest decrediton 1.8.1

Hey, it's an issue on the server right now, it will be back soon.
