### ISSUE TITLE
beeep doesn't show logo for notifications on Mac

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2674]
Is there a Mac-native solution that avoids beeep?

**Comment by peterzen** [comment]
Beeep on Windows also doesn't display the application name.  Filing it here instead of opening a separate issue as this is related to beeep as well.

![image](https://github.com/decred/dcrdex/assets/5878500/822086e4-2b87-438a-bb5b-2d356ad47fff)

**Comment by ukane-philemon** [comment]
> Is there a Mac-native solution that avoids beeep?

Yes, there is.

**Comment by ukane-philemon** [comment]
> > Is there a Mac-native solution that avoids beeep?
> 
> Yes, there is.

I'll be looking into this in the coming week.
