### ISSUE TITLE
Flatpak/Flathub

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdex#2716]
Echoing my Decrediton issue (https://github.com/decred/decrediton/issues/3939) here as I think that after DCRDEX has its rebrand finalized it should be distributed via Flathub for maximum visibility on Linux.

**Comment by peterzen** [comment]
https://github.com/decred/dcrdex/issues/2581

**Comment by peterzen** [comment]
> Echoing my Decrediton issue ([decred/decrediton#3939](https://github.com/decred/decrediton/issues/3939)) here as I think that after DCRDEX has its rebrand finalized it should be distributed via Flathub for maximum visibility on Linux.

https://github.com/decred/dcrdex/issues/2581

**Comment by jzbz** [comment]
Forgot you had taken this on @peterzen. Appreciate it.
