### ISSUE TITLE
tatanka: Add fiat oracles.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2727]
Similar to fee rates, we need oracles so that tatanka can provide clients with fiat rates. Because this is a server, I think that the operator may also choose to use services that are paid and/or require an api key, so maybe it could have a settable component. This should also use redundancy where possible.

@ukane-philemon has shown interest in doing this and has some ideas
related to #2565

**Comment by ukane-philemon** [comment]
I'll work on this an submit a PR soonest.
