### ISSUE TITLE
UX Suggestion: Reduce Fidelity Bond amount

### ISSUE THREAD

**Issue by exitus1** [decred/dcrdex#2728]
Currently, new accounts are required to submit and lock 4 DCR (~$100) before they can access the DEX. While I understand this is to encourage good behavior like not backing out of trades, I think it's acting as a roadblock for getting new users on the DEX. We need to be cognizant that atomic-swap trading is still new and foreign to most, and that putting up any sort of barrier, like a $100 fee to enter is probably doing more harm than good. Most people don't know what a fidelity bond is, and it's not something encountered on other DEXs. 

My suggestion: Reduce fidelity bond amount significantly, maybe even to 0.2 DCR (0.1 + 0.1 for overlap period)

**More users = more liquidity** and a better trading experience for all.

I hope i'm not ruffling any feathers here, just want to see DEX get as many users as possible!

<img width="1280" alt="2024-04-02 21_15_53-Greenshot" src="https://github.com/decred/dcrdex/assets/46197055/0692042a-d8fb-4a4a-a3e0-821c8845847f">

**Comment by exitus1** [comment]
> We have to also remember Americans don't even have a simple way of getting DCR... Except dcrdex... By requiring them to have DCR before they can get DCR we kinda shoot ourselves in the foot. But at least lower it so that if someone says to me hey I wanna use dcrdex I can send them 0.1 dcr or whatever so they can start

You can pay the fee with BTC and soon ETH and I think (?) LTC - but the issue still stands it's a tall amount. At 0.1 dcr we could start paying for others registration which would be nice.

**Comment by jzbz** [comment]
I remember seeing a regulatory filing Coinbase had done where they stated the average buy they were seeing from customers was around $500. Posting a $100 bond to buy $500 of coins if  you're just dipping your toes in the water seems kind of steep.

I realize the bond is an absolute necessity for the mesh work. My personal preference would have been that we rolled with a zero registration fee and now zero bond (if that's technically feasible) to have the lowest friction experience possible until we start to see people screw around (abusing free optionality) and create the need for enabling the bond to align incentives.

**Comment by PhoenixGreen** [comment]
Yeah, I agree with this. Personally, I’m of the same opinion as JZ, if possible start from zero and then move it up gradually as needed. The 0.1 DCR registration fee always seemed very reasonable to me.

**Comment by buck54321** [comment]
We're going to do something to onboard users. Low bond sizes are part of the equation. Pre-paid bonds have been discussed. Special bond types are on the table too. Thanks for reminding me.
