### ISSUE TITLE
some early (pre-trade) server message should be signed

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#273]
If the server's signing key has changed, but dexc remembers the old one, you will get messages like the following when placing an order:

[ERR] CORE: Abandoning order. preimage: 55106abaeecf8fe62a4b70f8607825526410a79a60b19c87568c38f532ed4cc2, server time: 1587067806540: signature error. order abandoned

It would be nice if another response would be signed so the server's sig can be verified earlier.

**Comment by buck54321** [comment]
The signature could be included with the `config` response, but I'm not looking to serialize that entire structure, so we can hopefully find something else to sign.
