### ISSUE TITLE
app: simple interface option

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#277]
Per @jzbz on matrix **DCR DEX** room

> Whoever gets to a DEX experience that resembles the old Shapeshift flow will capture the huge non-nerd component of the market.

An interface for people just looking for super simple conversion would be great. Should probably use limit orders with time-in-force immediate underneath to limit slippage losses while avoiding standing orders.

**Comment by ukane-philemon** [comment]
> Should probably use limit orders with time-in-force immediate underneath to limit slippage losses while avoiding standing orders.

@chappjc, I think this is already in place, Or is there more to this issue?

**Comment by ukane-philemon** [comment]
@buck54321, if you don't mind I'd appreciate your feedback here.
