### ISSUE TITLE
spec: update trade suspension message.

### ISSUE THREAD

**Issue by dnldd** [decred/dcrdex#280]
The trade suspension message is currently outdated from @buck54321 comments in #269. This is to discuss the changes to be made to the message type and proceed with implementing the suspension handler. 

update suggestions from buck: 

> The spec for suspension is still based off of a simpler time when we had a single epoch duration for the entire DEX. That was changed a while back. The suspension route can no longer send the epoch. It should probably be changed to either a timestamp, or a mapping of market->epoch or market->timestamp.

Which suggestion here is preferred? Thoughts @chappjc?

**Comment by chappjc** [comment]
As I indicated in https://github.com/decred/dcrdex/pull/269#pullrequestreview-396505403, my vote would be for a market->epoch map.  I have a trade suspension branch going for the server's suspend/resume capability, which needs to be fleshed so we know where to hook up and outgoing message code.

**Comment by chappjc** [comment]
For reference, the implementation issue: https://github.com/decred/dcrdex/issues/281

**Comment by itswisdomagain** [comment]
Related: #354
