### ISSUE TITLE
Privacy Mixing Transactions labeled "Send" - Scary UX

### ISSUE THREAD

**Issue by exitus1** [decred/dcrdex#2824]
![image](https://github.com/decred/dcrdex/assets/46197055/8a423419-8286-43ad-88ae-5292dec68d87)

Novice users might think their wallet is being drained with all the "Send" Txs and red "amount".

Suggestion: Change "Send" to "Mix" or "Privacy" to avoid scares.

Change the red numbers in the Amount section to a different color like yellow.

**Comment by jzbz** [comment]
Yep good ideas, also maybe adding `(Sent to self after mixing)` or similar to make it explicit would avoid panic.
