### ISSUE TITLE
Lots per Level Increments

### ISSUE THREAD

**Issue by pubpete** [decred/dcrdex#2829]
When creating a bot (DCR-USDC) I use the up arrows to increase the lots per level and it goes from 1 to 66, instead of 1,2,3... 
And goes up by 66 DCR increments. 

<img width="634" alt="Screenshot 2024-06-19 at 11 26 09 PM" src="https://github.com/decred/dcrdex/assets/32755460/282c64b7-4acc-495d-94c5-27b509b594c3">

<img width="634" alt="Screenshot 2024-06-19 at 11 26 18 PM" src="https://github.com/decred/dcrdex/assets/32755460/86e4f9ed-37a7-4492-9dfd-78cbb64dc0d3">

**Comment by buck54321** [comment]
That's by design. Lot sizes can be < $1 USD. The increment targets about $100 per click.

**Comment by buck54321** [comment]
Looks like yours went up 500 though, so I'll take a look and make sure it's working as expected.
