### ISSUE TITLE
ltc: pre-size funds always give error on testnet.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2887]
Trading on rc-1 on testnet on the dcr/ltc market. When buying dcr and clicking the pre-size option the buy always fails with:

`In-Flight order with ID 8 failed: new order request with DEX server bison.exchange:17232 market dcr_ltc failed: rpc error: error code 36: failed funding validation`

**Comment by buck54321** [comment]
This was fixed in #2880 I just hadn't updated the testnet server yet.

**Comment by JoeGruffins** [comment]
Ok.
