### ISSUE TITLE
Custom RPC Provider warning showing in Decred Wallet during initial sync

### ISSUE THREAD

**Issue by bochinchero** [decred/dcrdex#2900]
Seen on v1.0.0-RC2, built from source on linux.

![image](https://github.com/user-attachments/assets/d63cc899-8268-43c9-8558-fc8d1d94cb9c)

**Comment by buck54321** [comment]
Unable to reproduce.

**Comment by ukane-philemon** [comment]
I think I reported this a while back and was supposedly fixed.
