### ISSUE TITLE
Notifications dropdown cropped out on smaller screens

### ISSUE THREAD

**Issue by bochinchero** [decred/dcrdex#2906]
Seen on v1.0.0-RC2, built from source on linux.

Opening the web interface from mobile, the notifications dropdown is not resizing and a good portion of it is off screen.

**Comment by ukane-philemon** [comment]
Do you have a screenshot?

**Comment by bochinchero** [comment]
![image](https://github.com/user-attachments/assets/b254fc96-8b04-4291-ac2f-1ee9fcd9382f)
