### ISSUE TITLE
mm: manual placements on one side causing mm settings ui hangup

### ISSUE THREAD

**Issue by bochinchero** [decred/dcrdex#2916]
Seen on v1.0.0-rc3, linux, built from source.

Had this happen on two different pairs, since the settings screen doesn't load, I can't change the configuration or delete the bot.

1. Go to market maker screen.
2. Create new bot.
3. Select a pair.
4. Select basic market maker.
5. Configure placements manually.
6. Set placements on only one side (e.g. buy side only).
7.  Create bot.
8. From the market maker screen, the new bot settings never finish loading.

![image](https://github.com/user-attachments/assets/f7e65107-0aa6-4def-96a0-48169d64bb15)

**Comment by martonp** [comment]
I am unable to reproduce this. I put a placement on one side only and the UI works fine. If you are able to reproduce again, could you post the console logs please?

**Comment by bochinchero** [comment]
These are the setttings I'm using to reproduce:
![image](https://github.com/user-attachments/assets/05fe3873-ae39-4dbe-9291-b6395a596e8c)

Browser console has this error, dexc.log has no relevant messages.
![image](https://github.com/user-attachments/assets/aa73c915-582b-4348-9206-5b0589460273)

I have managed to remove the errored out bots by going through the "Create New Bot" dialog for the same market.

**Comment by martonp** [comment]
Thanks @bochinchero
