### ISSUE TITLE
core: need a way to disable dex server accounts without deleting

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2943]
Currently "disable account" for a server bascially deletes the account. But it won't let you do that with active bonds. We need a way to disable the account without actually deleting it and while still monitoring bonds to refund, in a similar fashion to how we can disable individual wallets.

**Comment by ukane-philemon** [comment]
I'd like to look into this.

**Comment by dajohi** [comment]
`func (*core).DisableExchange(disable bool) error {}`
and
`type Exchange struct` gets a `Disabled bool`

then core doesn't auto connect to any exchange with Disabled = true

**Comment by sysfu** [comment]
Funny because I'm trying to figure out how to permanently unregister, remove, or delete the bison.exchange dex, and I can only seem to disable it using Bison 1.0.4.
