### ISSUE TITLE
app: markets view layout issues

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#296]
The layout on the markets page has some issues. 

1. Resizing results in unexpected behavior such as sections getting progressively larger and overflowing their containers.

2. When window height is small, scroll bars are shown as desired, but the order table heights are not right.

Based on @chappjc comment https://github.com/decred/dcrdex/pull/278#pullrequestreview-400983272

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/560
