### ISSUE TITLE
app: improve user orders table on markets view

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#297]
There are a number of ways that the orders table on /markets can be improved.

1. Orders should be sorted newest first
2. Old orders should either be removed, be removable, or have their own table. 
3. It should say whether they are market or limit orders.
4. The **filled** column indicates how much of the order has matched, but we also need to know how much has settled, so maybe a **settled** column, also with % units.
5. Clicking on an order should display information about it's matches. The match data could be shown in a modal dialog, or in the table itself by inserting the info to display as a row below the order's row.
6. Right now, only orders for the currently displayed market are shown. A client might want to view all active orders, regardless of market. Should it be an option?

**Comment by chappjc** [comment]
Assigned to @kevinstl, although not with github since he's not in the decred org and it won't let me.

**Comment by chappjc** [comment]
Related, an order details page is probably needed to do things like investigate the various swaps (transactions, etc.), get the full order IDs and match IDs for support purposes, etc.
