### ISSUE TITLE
core: wallet connect and unlock should be attempted in Core.Trade if not already done

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#298]
To place an order after signing in, you must unlock individual wallets first, which is a little silly because it's the same password needed to submit the order. Instead, if the wallets are not connected or unlocked when the order is placed via `(*Core).Trade`, a connect/unlock should be attempted and an error returned if unsuccessful.

**Comment by JoeGruffins** [comment]
I'll take this one, if that's ok.

**Comment by buck54321** [comment]
I'm not sure if it's worth it or not, but you may be able to reuse something from `loadDBTrades`. https://github.com/decred/dcrdex/blob/c176cbc6cd0fe01ba2a6eca2c28f044d65555b31/client/core/core.go#L1792-L1817
