### ISSUE TITLE
app/core: check out cancellation bugs

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#299]
Based on @chappjc comment https://github.com/decred/dcrdex/pull/278#issuecomment-620032798

1. There are error messages but the cancellation appears to succeed. 
2. There is maybe an issue with the message parameters when a second order is cancelled. Fixed by a page refresh, so look at JS first.

**Comment by JoeGruffins** [comment]
Would like to investigate this if someone isn't on it.

**Comment by JoeGruffins** [comment]
Maybe this got fixed somehwere?

**Comment by chappjc** [comment]
I think this was resolved by removing event listeners on the frontend.  Let's consider it resolved.  Thanks for checking.
