### ISSUE TITLE
ui: (wallet, transaction history) formatting issue for Amount

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2994]
Running 1.0.0, there is a formatting issue under **Polygon Transaction History** section of **Wallet** tab, namely **Amount** is showing 0.001 of what it should be (CurrentShownAmount=CorrectAmount*0.001),

same issue with incorrect amount is seen if I double-click into particular transaction record to see more details.

I should note, this is what I observe for USDT/USDC (which have 6 decimal points I believe), not sure whether other currencies are affected.

No screenshots for this one for privacy reasons.

**Comment by dev-warrior777** [comment]
6 decimal points for USDT confirmed .. it is configurable with most tokens using 18 I believe

**Comment by norwnd** [comment]
Additional data point: seems send/receive wallet transactions with DCR and MATIC show the correct amount.

**Comment by martonp** [comment]
Fixing.
