### ISSUE TITLE
ui: negative confirmations (-1/2) on DCR swap

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2999]
I've noticed DCR swap can show negative confirmations number (namely -1/2):

<img width="300" alt="image" src="https://github.com/user-attachments/assets/1710a206-fad4-4305-9747-277755a37b07">

if there is some meaning behind it - probably better to show 0 instead of -1, it isn't obvious what it is and looks like a bug to uninitiated.

**Comment by dev-warrior777** [comment]
This was mentioned on the stream with https://x.com/DecredSociety/status/1840456294064660697 in a live demo - a fix is great

**Comment by norwnd** [comment]
Hey @buck54321 @martonp I've just ran into this again (with Bison wallet version that includes https://github.com/decred/dcrdex/pull/3009):

<img width="400" alt="image" src="https://github.com/user-attachments/assets/6d3ac72c-8a1e-4ca3-ace0-1d3b722ab287" />
