### ISSUE TITLE
DCR Backend

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#3]
We need a backend for DCR. For this work, it is assumed that the DEX operator has access to a full node with `txindex`, and that queries will be performed using the blockchain node software's standard RPC. 

Part of this work will involve creating some common DEX interfaces. I anticipate there will be an interface for the asset backend itself, one for UTXOs, and probably some for transactions and blocks. These interfaces will necessarily need to be defined in a separate module. This work should also be coordinated with the analogous BTC backend development (#4), so that the interface can be accommodating for both. The DCR and BTC backends will be baked-in, but the interfaces defined during this work will also be used for plugins. 

The asset backend will need to have at least the following functionality.

- [x] Retrieve UTXOs
- [x] Broadcast notifications for new blocks and mempool transactions
- [x] Validate signatures
- [x] Calculate script sizes (some script sizes might be constants)

**Comment by buck54321** [comment]
I'd like to take this one.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/17
