### ISSUE TITLE
dcrdex config should set a default epoch duration

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#300]
Fair enough, will check for 0 there.  Also seems reasonable to replace 0/-1/omitted with a the specd default.

_Originally posted by @chappjc in https://github.com/decred/dcrdex/pull/283_

**Comment by ukane-philemon** [comment]
@chappjc, what do you think is a sensible default for epoch duration? Looks like we are already handling the situation where poch index is not set but not for epoch duration.
