### ISSUE TITLE
core: trigger FindRedemption attempts when maker goes dark

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#301]
If 1) the client is the taker on a match, 2) the match status is `TakerSwapCast`, and 3) it's been `BroadcastTimeout` since `SwapConf` confirmations on the swap tx, then the client should begin running `FindRedemption` every tip change until the the client is able to either find the maker's redemption or issue a `Refund`.

**Comment by itswisdomagain** [comment]
I want to start work on this.
