### ISSUE TITLE
Market Maker Bot Gap Issue

### ISSUE THREAD

**Issue by ovvnyou** [decred/dcrdex#3019]
Unable to set up laddered buy/sell orders, using market maker bot.
Goal:
Buy below market @ $11, $10, $9, $8, $7, etc.
Sell above market @ $14, $15, $16, $17, $18, etc...

Irrespective of Gap Strategy and rate, bot sets all orders very close to current market price. (Unable to break the $12-$13 range.)

(P.S. I've been following Decred since the beginning. Your hard work will pay off. This is the beginning of greatness.)

**Comment by martonp** [comment]
Try the "Absolute" Gap Strategy.

> (P.S. I've been following Decred since the beginning. Your hard work will pay off. This is the beginning of greatness.)

Thanks for the encouragement :)

**Comment by ovvnyou** [comment]
Looks like it was user error.
Thank you
