### ISSUE TITLE
Partial Fill Orders on DCR-USDT in DCRDEX Causing Arbitrage Order Cancellations on Binance

### ISSUE THREAD

**Issue by alexandrapicho95** [decred/dcrdex#3020]
A bug has been identified where partial fill orders for the DCR-USDT pair on DCRDEX are causing arbitrage orders on Binance to be cancelled without properly executing the trade. This issue requires attention and resolution to ensure smooth trading operations.

Steps to Reproduce:

    Place a partial fill order for DCR-USDT on DCRDEX.
    Observe the arbitrage order on Binance being cancelled without executing the trade.

Expected Behavior:

Arbitrage orders on Binance should execute properly even when partial fill orders are placed on DCRDEX.

Actual Behavior:

Arbitrage orders on Binance are being cancelled without executing the trade when partial fill orders are placed on DCRDEX.

Request:

Please investigate and resolve this issue to ensure proper execution of arbitrage orders on Binance.

**Comment by dev-warrior777** [comment]
Hi, do you have any logs for this please?

**Comment by martonp** [comment]
How long after placing the trading was the Binance order cancelled? There is an "Order Persistance" setting that specifies how many epochs to wait before cancelling unfilled CEX orders.

**Comment by alexandrapicho95** [comment]
@dev-warrior777 If I encounter the issue again after adjusting the settings, I will provide the relevant logs for further investigation.

@martonp The Binance order cancellation appears to occur immediately. I will adjust the 'Order Persistance' setting to the maximum value and monitor the behavior. 

If the issue persists, I will reopen the issue.
