### ISSUE TITLE
app: show better messaging when waiting for fee confirmations

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#306]
When the user is waiting on confirmations for their registration fee, there are a couple pain points. 

1. There is a success notification that says that core is waiting on confirmations, but so far nobody seems to take it seriously. Better wording might help?
2. If the user attempts to place an order anyway, they will get an error notification about an "unauthorized connection", which is not incorrect but not very helpful. We should probably just not display the order form at all until registration is complete.

**Comment by itswisdomagain** [comment]
Related... Don't know if this has been considered/discussed:
From [the spec](https://github.com/decred/dcrdex/blob/master/spec/accounts.mediawiki#step-2-fee-notification):
> The client pays the fee on-chain and notifies the DEX of the transaction detail. The fee is paid with a standard P2PKH output to the address received in step 1. Once the transaction is mined and has the requisite number of confirmations (swapconf), the client should send their fee notification to complete the registration process.

Is it not more efficient for the server to track transactions for `swapconf` once notified of payment since the server is connected to the backends of the regfee asset? Done that way, the server can send something like a "welcome message" to the client once the transaction gets `swapconf` confirms.

**Comment by itswisdomagain** [comment]
I want to take this up as part of an ongoing effort to improve the client app setup (pre-register and register) flow.

**Comment by itswisdomagain** [comment]
> From [the spec](https://github.com/decred/dcrdex/blob/master/spec/accounts.mediawiki#step-2-fee-notification):
> 
> > The client pays the fee on-chain and notifies the DEX of the transaction detail. The fee is paid with a standard P2PKH output to the address received in step 1. Once the transaction is mined and has the requisite number of confirmations (swapconf), the client should send their fee notification to complete the registration process.

It appears from the client registration code that the DEX is only notified after the transaction receives `swapconf` confirms. Is this intended? Might need to reword the specs wiki which suggests that there are 2 notifications sent - when the fee is paid to notify the dex of the tx and when the tx gets `swapconf` confirms.

**Comment by ukane-philemon** [comment]
> If the user attempts to place an order anyway, they will get an error notification about an "unauthorized connection", which is not incorrect but not very helpful. We should probably just not display the order form at all until registration is complete.

Currently, users can't trade until registration is complete. @buck54321 are there any other pain points regarding this?
