### ISSUE TITLE
Simnet Utilities

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#31]
It'd be handy to be able to quickly initialize the state of a set of simnets with > coinbase maturity blocks, the block reward being directed to a set of wallets that the CLI client can access. We'll also need the ability to trigger reorgs. 

@chappjc has previously done much of this using shell scripts and tmux, and maybe that's the right approach here, but we'll need to add the wallet functionality. ~~I could also see doing this in go.~~

Seems like shell script is the way to go. Really just need to bring together the script from @davecgh 

https://gist.github.com/davecgh/3da3c48bd9ab1914ff134c0b26b8661c

and the reorg scripts from dcrdata

https://github.com/decred/dcrdata/tree/master/dev

**Comment by chappjc** [comment]
Mostly resolved by https://github.com/decred/dcrdex/pull/34, I believe, but there will need to be more simnet scripts to facilitate demoing swaps and driving client tests.

**Comment by buck54321** [comment]
With the simnet tests in **client/core** and **dex/testing/loadbot**, I think we've covered the goals of this issue. Any additional needs can be addressed separately.
