### ISSUE TITLE
orderrouter: handle market orders when the book is empty

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#312]
See `TODO:` at https://github.com/decred/dcrdex/blob/c176cbc6cd0fe01ba2a6eca2c28f044d65555b31/server/market/orderrouter.go#L292-L294

When there is an empty book, the mid-gap price is 0, so the epoch queue is at risk of being flooded with low value market orders. 

1. Is rejecting market orders placed against an empty book okay? It's verifiable, if that helps.
2. One security measure we've danced around is to limit the number of orders a client can place in a single epoch. Seems like a common sense policy to me, Would require a spec change.

**Comment by vctt94** [comment]
I believe this can be closed?
