### ISSUE TITLE
app: hide order forms when registration is incomplete

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#337]
This work should accompany or follow #336. When registration is incomplete, the order forms on the **markets** view should be hidden and instead there should be a message indicating how many confirmation are remaining until registration is complete.

**Comment by fernandoabolafio** [comment]
@buck54321  I wonder how would be the best way to track the payment state in the frontend. I know that the endpoint `/api/user` returns the `feePending` which we can use to check that at the moment the app inits. However, if there is still a fee pending, the only way to check for that would be by waiting for a specific notification and checking it again or just polling that api route, right?

**Comment by buck54321** [comment]
In #343, you are adding `Data`-severity notifications [here](https://github.com/fernandoabolafio/dcrdex/blob/fcb7b12cfa53f3f8c2c23b78c6f419a9cde4db76/client/core/core.go#L950). See [here](https://github.com/fernandoabolafio/dcrdex/blob/fcb7b12cfa53f3f8c2c23b78c6f419a9cde4db76/client/core/notification.go#L72-L76) for a note about the `Subject` field  in `Data` notifications. I would make the subject something simple like `regupdate`.

Every js `BasePage` receives every notifications [here](https://github.com/fernandoabolafio/dcrdex/blob/fcb7b12cfa53f3f8c2c23b78c6f419a9cde4db76/client/core/notification.go#L72-L76). Inheriting classes can subscribe to notifications by adding a receiver as a property of the `notifiers` object. See [here](https://github.com/fernandoabolafio/dcrdex/blob/fcb7b12cfa53f3f8c2c23b78c6f419a9cde4db76/client/webserver/site/src/js/markets.js#L169-L172) for an example. 

So you'll need to subscribe to the `'fee payment'` (should shorten that to one word for consistency) notification on the `MarketsPage`, and update the UI appropriately. You'll also need the dex URL in that notification in order to fully determine whether to display the forms.

**Comment by fernandoabolafio** [comment]
@buck54321 thanks for the thoughtful explanation! I get it now. However, I would rather add the required changes you mentioned in a subsequent PR of #343 which will deal with this issue. Is that ok?
