### ISSUE TITLE
client,assets: need ability to prep outputs to fund trades

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#340]
Funding trades involves locking up coins (utxos w/ dcr and btc), which may be much larger than the trade size.  To avoid locking up excessive funds, which could go to other orders, the user should be able to prepare outputs.  Possibilities:

- The trade dialog could give the option for a "pre-trade output sizing transaction"
- The wallets could have a general output splitting function that allows:
   - Generate N outputs of M*(lotSize+fee padding) amounts.
   - Auto-split largest utxos into outputs of M*(lotSize+fee padding) amounts.

This will help free up funds for more orders, thus creating a healthier order book and a better user experience, but at the expense of an extra transaction.

**Comment by buck54321** [comment]
After the split transaction, they would have to wait an additional `FundConf` before actually placing an order.

**Comment by chappjc** [comment]
Right, so an option for the trade dialog could be a poor user experience, especially if the market has changed by the time the split tx completes.

**Comment by chappjc** [comment]
Now that `FundConf` is gone, this is in progress.  @buck54321 is working on wallet configuration to allow the per-order prep tx to be an option.  I am getting started on the client/{asset,core} implementation changes to generate the tx to fund the order, depending on some flag that will be set by the setting that @buck54321 is addressing.  There will be some integration, but these are largely independent tasks.

I matrix chat today, we talked through all the options we could identify.  Starting here: https://matrix.to/#/!EzTSRQITaqHuFBDFhM:decred.org/$wlS1U0yNI3f0u9eeJYD-eInGid59J3I3kXLL0cpPct4?via=decred.org&via=matrix.org&via=planetdecred.org

The decision whether or not a user wants to enable the automatic per-order prep txns is based on the current network fees (looking at you BTC) and how they feel about having too much funds locked in a UTXO.  This UTXO locking does not matter much in the case of market orders or limit orders with force=immediate as these do not stay on the books -- the funds come back unlocked after the swap.  Limit orders that can stay on the books until filled at time unknown or cancelled are likely the biggest concern for locking excessive funds.

We discussed semi-automatic UTXO pre-prepping at length, but have decided to defer that.  However, this could start by providing some basic funding information to the user: for the base asset only, a table of number of lots vs. required funding amount.  This way a sophisticated user could pre-size their utxos with `sendmany` or a similar mechanism.  A more involved tool that the client could offer is to actually do the splitting in preparation for multiple orders, but this is still limited to use in with market's base asset because the market's lot size is denominated in base asset.

**Comment by chappjc** [comment]
When https://github.com/decred/dcrdex/pull/533 goes in, are you still good to tackle the prep txn bits @buck54321?  Just making sure we're still on the same page.  :)

**Comment by buck54321** [comment]
Yeah. I was planning on starting it today, but no need to rush #533. I'll build on that branch for now.

**Comment by chappjc** [comment]
Great.  I'm doing some work comms issues raised in https://github.com/decred/dcrdex/issues/554, so that shouldn't conflict much if at all.
