### ISSUE TITLE
core: update balance

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#345]
The balance is only updated when the wallet is created, connected, and unlocked. Other times it should be updated:

1. After a order is submitted. 
2. After a redemption is complete.
3. After a block notification (`tipChange`)?

The balance updates should be sent as `Data`-severity notifications too.

**Comment by itswisdomagain** [comment]
Also when `core.Login` is triggered.

I signed in from the webserver, visited the wallets page but had to unlock the wallet to get updated balance.

**Comment by buck54321** [comment]
I'm working on this.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/390, https://github.com/decred/dcrdex/pull/418, and https://github.com/decred/dcrdex/pull/454
