### ISSUE TITLE
dcrdex: server keeps processing the same block over and over again

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/dcrdex#350]
While simulating the registration flow using `simnet` and mining a few blocks, at some point the server kept showing the same log over and over again:
```
2020-05-08 17:30:53.759 [DBG] ASSET[dcr]: Run: Processing new block 7ecc63a1b90eb90854f92ee141cc332645606389a82630702c056d97643bc3a0
2020-05-08 17:30:53.759 [DBG] ASSET[dcr]: Notifying 1 dcr asset consumers of new block at height 819
```

From this point, tip changes in the `dexc` were also not captured and the client could no longer keep track of  block changes for the decred asset.

**Comment by fernandoabolafio** [comment]
Ok, so I think that happened because my `simnet` chain got stuck so it is not a dex issue.

**Comment by chappjc** [comment]
I've seen this too when the DCR simnet runs out of votes.  The harness could use tweaking to stabilize it indefinitely if possible.

**Comment by fernandoabolafio** [comment]
Yes @chappjc. That's exactly the issue I faced. So let's keep this open then.

@matheusd pointed me to [this script](https://github.com/matheusd/simnet-tmuxes/blob/master/decred/two-wallets.tmux) which we can use as a reference. In summary, it all comes down to having one wallet with ticket buyer and voting enabled.

**Comment by chappjc** [comment]
Tracking this issue in https://github.com/decred/dcrdex/issues/413.  Despite having a harness setup with a ticket buyer with voting enabled, it eventually fails.  I believe it's an issue with only specifying 5 tickets per block because the wallet now denies ticket buying just before stake diff retargeting.
