### ISSUE TITLE
wallet config - replace file paths with file text content

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrdex#371]
Beginning in #352, assets define an array of relevant configuration options that a user may supply values for when adding a wallet for that asset.

Where a wallet config option expects a file path e.g. [`rpccert` option in dcr's config](https://github.com/decred/dcrdex/blob/cb02a994829a911f29f20ce225876b716d5ec074/client/asset/dcr/config.go#L43-L45), instead of requesting for a file path, frontends should allow users select a file from their device, read the selected file's text content client-side and submit the text content rather than the file path.

Can refer to [the pattern here](https://github.com/decred/dcrdex/blob/cb02a994829a911f29f20ce225876b716d5ec074/client/cmd/dexcctl/main.go#L153-L157) for replacing file path arguments with the file's text contents in the dexcctl rpc client.

Similarly, [see here ](https://github.com/decred/dcrdex/blob/cb02a994829a911f29f20ce225876b716d5ec074/client/webserver/site/src/js/register.js#L135-L144)for a pattern of webserver frontend reading file text contents client-side before submitting to the backend api.

**Comment by ukane-philemon** [comment]
Closed?

**Comment by ukane-philemon** [comment]
@chappjc, It seems we can close this.
