### ISSUE TITLE
core: drop scheme from DEX ID

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#374]
In **core**, the DEX is currently identified by it's URL. While the URL is plenty unique, the scheme is superfluous. 

The user should be able to input any address that includes the host name and port, when applicable. So

`https://localhost:5758`
`localhost:5758`
`localhost:5758/any/path`

should all parse to `localhost:5758` before being stored or used internally. 

Similarly

`thatonedex.com`
`https://thatonedex.com`
`https://thatonedex.com/any/path`

should both parse to `thatonedex.com`. 

#### Related conversations
https://github.com/decred/dcrdex/issues/225#issuecomment-629370594
https://github.com/decred/dcrdex/pull/330#discussion_r425879377
https://github.com/decred/dcrdex/pull/328#discussion_r425218790

Also, from https://github.com/decred/dcrdex/pull/352#discussion_r425850882, the shorthand notation `:5758` could parse to `localhost:5758`.

**Comment by chappjc** [comment]
Boy, I complain about this a lot. :stuck_out_tongue_winking_eye:

**Comment by JoeGruffins** [comment]
Working on this as it concerns another pr of mine. Hope that's ok.
