### ISSUE TITLE
core: need targeted updates to (*Core).user object

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#379]
The `Core` keeps a cached `User` struct, which is basically an application state that is populated whenever the user is logged in. The `Core.user` is only updated when `refreshUser` is called, and the `dexConnection`'s `marketMap` must also be updated when changes are made using `refreshMarkets`. This is a pretty unsophisticated way of handling updates to the cached `User`, since it recreates every `Match`, `Order`, `Market`, and `Exchange`.

This is not actually a bug, but the pattern is prone to errors because it relies on the programmer to call the required function(s) every time an update is made to basically anything. A couple of possible corrective actions.

1. Catch the `OrderNote`, `FeePaymentNote`, etc. in `(*Core).notify` and only update the appropriate `Exchange.Markets` entry.
2. A separate method for wallet updates, which do not affect the `User.Exchanges` map.

These are just suggestions, and there may be better ways to handle this.

**Comment by chappjc** [comment]
I had just made a duplicate issue (#904) because I forgot about this one.  I'll just reiterate the issue from a different angle here:

```
In `client/core.Core` there a numerous calls to `refreshUser`, and most of these calls are required only to update one small piece of the information that `refreshUser` updates.  e.g.  If `WalletState` for a certain `xcWallet` changes, there's no reason to update all of the other assets, orders, exchanges, etc.  This is particularly problematic because there are many mutexes locked by `refreshUser` and it's callers, which can easily lead to deadlock and/or contorted patterns to avoid deadlock.

In cases where `refreshUser` really is the best option, not a more targeted mutator method, each `refreshUser` call site should be documented with the reasoning.  If `refreshUser` is used for convenience regardless, the call site should document why exactly it is being called (what just changed that requires updating?).
```

**Comment by buck54321** [comment]
[See this comment too](https://github.com/decred/dcrdex/pull/805#discussion_r519236529) for a possible solution. Since every update to the `User` should involve a notification, we could hook into the notification loop to apply these targeted updates, as is done with `updateCoreMatch`.

**Comment by chappjc** [comment]
Ah, yes, call the targeted update method from the notify loop. That might be a good solution, although I've not felt it out carefully.  @amassarwi  Maybe see if this approach make sense for calling the updateUserWalletState method as you've done in https://github.com/decred/dcrdex/pull/902/commits/7b6232acfdea9d7fb3d2059664bf65b96c101b70?  I'm not sure if it would simplify it or make it less error prone, but worth trying it it out.

**Comment by buck54321** [comment]
It's actually a little racy, since we don't copy the `user` when e.g. `(*Core).User` is called, so that'll need to be fixed too. Instead of pre-emptively generating a cached `*User` (like is done in `refreshUser`), we should be regenerating the `*User` on-demand, still with caching but smarter with versioning of some kind.

**Comment by chappjc** [comment]
Ah yeah the User accessor is trouble isn't it.  There might be some optimization with caching, but it's looking like a deep copy will need to be made each call.
