### ISSUE TITLE
core: read out trade history in a portable format

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#382]
The **db** package allows reading out orders and matches. It would be useful to format the info in CSV for importing into another program, e.g. spreadsheet. For the GUI, a history view could be provided for filtering and viewing the data, and a download button for exporting to CSV. Probably want an export method on the RPC server as well.

**Comment by chappjc** [comment]
Assigned to @skynet0590

**Comment by martonp** [comment]
I'll pick this up.
