### ISSUE TITLE
multiple fee payment attempts?

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrdex#391]
I've noticed multiple fee payment notifications on the webserver on a couple occasions.
One `notifyfee` request succeeds and a success notification is displayed, the other notifications are errors of the following nature:
`Error encountered while paying fees to <addr>: notify fee result error: rpc error: 27: 'notifyfee' send for paid account`.

Doesn't affect usability, the account is g2g because of the successful fee notification, regardless of the other failed notifs.

**Comment by chappjc** [comment]
Dup of https://github.com/decred/dcrdex/issues/552, and resolved by https://github.com/decred/dcrdex/pull/860
