### ISSUE TITLE
app: need to be able to add additional DEXes

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#393]
The registration view is intended to walk the user through the registration process, including adding their first DEX server. But they also need to be able to add additional DEX servers. For a first pass, maybe just a form on the settings view, which right now is pretty much empty.

**Comment by song50119** [comment]
@buck54321, can I pick this up? Thank!

**Comment by amassarwi** [comment]
@chappjc resolved issue, can be closed.
