### ISSUE TITLE
cannot logout with active orders when there are no active orders

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#397]
Make two trades, have them completely settle:

![image](https://user-images.githubusercontent.com/9373513/82574023-2479c000-9b4c-11ea-9b5b-32d793b1fea9.png)

(note "excecuted" typo is fixed in https://github.com/decred/dcrdex/pull/399)

Click logout:

![image](https://user-images.githubusercontent.com/9373513/82574110-3e1b0780-9b4c-11ea-94eb-94a87918d6b9.png)

Restarting dexc, logging back in, and trying again lets you logout.

@song50119

**Comment by song50119** [comment]
Okay

**Comment by song50119** [comment]
Can we just refresh all dexc before logout?
