### ISSUE TITLE
client/comms: server not listening when client connection is attempted

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#407]
After merge of PR  , I occasionally get errors in CI and on my local machine at https://github.com/decred/dcrdex/blob/master/client/comms/wsconn_test.go#L227

`TestWsConn: wsconn_test.go:227: failed to get ErrCertRequired for no cert connection`

I supplemented the error and it seems that the cause is the server not yet listening when the connection attempt is made:

```
 $   go test -v -short -race -count 1 -tags pgonline ./client/comms/...
=== RUN   TestWsConn
2020-05-25 11:15:59.368 [INF] Debug: Generating TLS certificates...
2020-05-25 11:15:59.446 [INF] Debug: Done generating TLS certificates
    TestWsConn: wsconn_test.go:227: failed to get ErrCertRequired for no cert connection, got dial tcp 127.0.0.1:6060: connect: connection refused
http: Server closed
--- FAIL: TestWsConn (0.11s)
FAIL
FAIL	decred.org/dcrdex/client/comms	0.122s
FAIL
```

This is because the server is started in a goroutine, and a connection attempt is made immediately after.  This demonstrates how we should never assume the code inside a goroutine is run immediately:

https://github.com/decred/dcrdex/blob/1bc5777289db4d612521e18b7ddfd3c30b6d51fa/client/comms/wsconn_test.go#L197-L203 

We need to wait for ListenAndServer to actually start listening.

**Comment by chappjc** [comment]
@itswisdomagain Can you take this?  I feel like just a sleep is all we can do unless we relate `ListenAndServeTLS` with its component operations, the hard way, with a channel close after the listener is up.  But please to investigate.

@dajohi When you get a chance, can you add @itswisdomagain to the decred org so he can be assigned to issues?  Thanks!

**Comment by itswisdomagain** [comment]
On it!
