### ISSUE TITLE
client/asset: change handling is insufficient

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#409]
The `isDEXChange` function is meant to allow swap change outputs to be used as inputs without `FundConf`, as per [the spec](https://github.com/decred/dcrdex/blob/master/spec/fundamentals.mediawiki#asset-variables), but the function does not distinguish between DEXes. So a fresh change output from one DEX might be passed as a funding coin for a different DEX, which would likely result in the order being rejected. Right now, the exchange wallets don't really know what a DEX is, just a `dex.Asset`, which is insufficient to solve the issue. I'd like to avoid having to pass a DEX ID (e.g. host name) to the wallets for all functions that use `spendableUTXOs`, but I don't see a clean way around it.

**Comment by chappjc** [comment]
This issue is now moot since FundConf has been removed in https://github.com/decred/dcrdex/pull/499 (code) and https://github.com/decred/dcrdex/pull/498 (spec).
