### ISSUE TITLE
core/db: use plain host in db package -> connectDEX -> dexAccount

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#412]
A bug that got in with #386. The `dexAccount` is still being passed the URL as part of the `*db.AccountInfo`, but it should be host. The address is being parsed to remove the protocol in `(*Core).Register`, but the raw URL is still being saved to the database and used in `connectDEX`. This culminates as a front end bug at https://github.com/decred/dcrdex/blob/767718de5b382e5f00f570428e0a124892dbeee9/client/webserver/site/src/js/app.js#L260.

**Comment by chappjc** [comment]
Yeah, that stands out

```go
dc, err := c.connectDEX(&db.AccountInfo{
		URL:  form.URL,
```

That's on me, but thanks for picking up the resolution.

**Comment by chappjc** [comment]
All resolved?

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/420
