### ISSUE TITLE
advertise/enforce minimum rpc versions for asset backends

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrdex#424]
The readme does not currently mention a minimum rpc version for asset backends and this may lead to unexpected runtime errors.

One potential site for error is accurately identifying `txNotFound` errors returned from dcr backends. `client/asset/dcr` and `server/asset/dcr` expect such errors to be prefixed with `-5` but some dcrd versions return a different error code e.g. `-4`.

If a tx lookup error is **NOT** accurately identified as `txNotFound`, both client and server assume the tx is invalid instead of re-attempting to lookup the tx a brief moment later. This would lead to failing audit checks on swap and redeem txs, for example, which in turn leads to match revocation.

**Sample swap audit failure on client side**
`[ERR] CORE: processAudit - order 2268247..., match db66b925... - nil gettxout result`

**Sample redeem tx check error on server side**
`[WRN] SWAP: Redemption error encountered for match ---, actor --- using coin ID --- to satisfy contract at ---: GetRawTransactionVerbose for txid <txid>: -4: No information available about transaction`

The code comment below suggests enforcing rpc versions but a temporary measure could be just mention the required versions in readme setup steps
https://github.com/decred/dcrdex/blob/68fa5f47e6da2a82acefe941a6b551f59548b8cb/server/asset/dcr/dcr.go#L819-L823

**Comment by chappjc** [comment]
Bump.  The minimum dcrwallet RPC server version is now 8.2.0, and that's an important one.

**Comment by chappjc** [comment]
Taking this now unless someone else has started.
