### ISSUE TITLE
app: DEX connection notifications are spammy during registration.

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#428]
Especially during registration, when a connection is made and closed to retrieve the registration fee. 

A partial solution would be to supress the `ConnectEventFunc` call when the client is shutting down cleanly, but my instinct is to not use the notification tray at all, and just rely on the disconnected icon and maybe a poke notification, and only send an error notification when the connection status prevents action. 

Another partial solution is to ignore those notifications during the registration process.

**Comment by JoeGruffins** [comment]
I would like to add to this that any time a user shuts down the app they get the warning:
`2020-06-08 12:16:27.787 [WRN] CORE: notify: |WARNING| (conn) DEX disconnected - DEX at 127.0.0.1:7232 has disconnected`
which in this case is intended, so warning does not seem correct here.
