### ISSUE TITLE
build commit hash into web assets and go binary, compare

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#429]
A common support/debugging interaction will likely involve "did you rebuild your site assets?", so we could head this off by embedding the git commit hash in the webpack build and putting a shortened hash somewhere discrete but always visible, such a the bottom/footer area.

npm run build could execute `git rev-parse --short HEAD` to get a shortened 8-digit version of the hash, which could somehow be embedded in the web pages.  After we have a tag, we can use an approach like `git describe --abbrev=8 --long'` to get something like `v0.0.1-85-g8d9738fe`.

We might also want to apply a similar operation with go builds e.g.
`go build -ldflags "-X 'main.version=$(git describe --tags)' -X 'main.commit=$(git rev-parse --short HEAD)' -X 'main.date=$(date)'"`

**Comment by buck54321** [comment]
I'll take care of this.

**Comment by chappjc** [comment]
@itswisdomagain The frontend parts now include the commit hash, yes, but I think the last piece of this is building it into dexc also, and ideally comparing the two hashes at runtime and warning if they are not equal... or even showing the dexc-embedded hash on the settings page next to the webpack-embedded hash.

**Comment by ukane-philemon** [comment]
@chappjc, is this still an issue?

**Comment by chappjc** [comment]
Let's see what happens when embedding (`go:embed`) is done in https://github.com/decred/dcrdex/pull/1710

Even with embedding though, it can be embedded with the wrong site data.  But at least with the packages distributed to end-users there would no longer be a risk of the user accidentally using the wrong site files on their own machines.

For devs it's a different story, but less important.

But about embedding the commit into the Go binary, we now get that automatically on Go 1.18 and later because of your work (thanks!). https://github.com/decred/dcrdex/blob/master/dex/version/version_buildinfo.go
So that would leave comparing that at runtime to what's embedded in the frontend.

I guess that's still worth a look, but it sounds like how we'd do that comparison would be with the embedded
