### ISSUE TITLE
stalled dcrdex shutdown

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrdex#431]
If dcrd is shut down before dcrdex, dcrdex shutdown stalls at `Auth manager shutdown.`

**Comment by JoeGruffins** [comment]
Stalls forever, or just takes a while? I thought this was solved by https://github.com/decred/dcrdex/pull/325

**Comment by JoeGruffins** [comment]
duplicate of https://github.com/decred/dcrdex/issues/321
