### ISSUE TITLE
client: Persistent DEX ID

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#433]
Currently an account isn't linked to a DEX, but to a DEX's address, which may change. I think each DEX needs a more unique, permanent identifier. This should be a value decided by the DEX and communicated to the client upon `getfee` and `registration`. It should be the same value for all clients. It should also include a timestamped signature so that one DEX cannot impersonate another DEX. This way, a client can associate their account with a DEX, regardless of the DEX's location in cyberspace.

**Comment by JoeGruffins** [comment]
@chappjc has pointed out that this value should be the DEXPubKey that is already stored in each account.

@behindtext has pointed out that in the future, servers will run in a server-mesh. That should also be taken into account.

**Comment by chappjc** [comment]
I believe this is resolved by https://github.com/decred/dcrdex/pull/1015, in that it uses bytes of the dex pub key in the HD derivation path.  Is there more to this issue @buck54321 that was not addressed there?

**Comment by ukane-philemon** [comment]
Closed?

**Comment by JoeGruffins** [comment]
The address/host is still part of the account and saved in the db. I suppose this issue is solved, but there needs to be a way to change the address a dex points too, and the certificate, I think? Maybe this is better thought out in the context of "mesh" and bonds, as one account would have several addresses then? Closing anyhow. Will open a new one related to this when/if appropriate.
