### ISSUE TITLE
notify client of penalty / account status change

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#444]
This requires code and spec updates.

When the client is penalized/suspended, a notification should be sent to the client with details.

- reason
- additional details e.g. cancellation threshold value, inaction on match ID X, etc.
- duration (reinstate time or indefinite)
- message (e.g. state connected to complete swaps or risk further penalty or loss of reg fee!)

ref: https://github.com/decred/dcrdex/pull/406#discussion_r434612017

**Comment by JoeGruffins** [comment]
I will take this on if that's alright.

**Comment by chappjc** [comment]
Sure, let's start with a spec update proposal.

**Comment by JoeGruffins** [comment]
Currently there are no time limits set for bans. Are they all permanent? How does everyone feel about giving account a new field, `strikes`. As long as an account has less than three/five? strikes, the ban is impermanent. Breaking a rule gives the account a strike, and a temporary ban for x amount of time, maybe based on the number of strikes. On the third rule breakage, the ban is permanent. I also think it would be good if strikes had a lifetime. Maybe a couple weeks, although that complicates the needed fields a bit more.

And as for notifications, do you think we should require acknowledgement? Many penalizations will happen because the client was shut down, so notifying right when the rule is broken will probably not be seen. Maybe just notify when connected, but don't worry about a response. I believe auth already has this functioning due to a recent pr.

**Comment by chappjc** [comment]
> Currently there are no time limits set for bans. Are they all permanent? How does everyone feel about giving account a new field, `strikes`. As long as an account has less than three/five? strikes, the ban is impermanent. Breaking a rule gives the account a strike, and a temporary ban for x amount of time, maybe based on the number of strikes. On the third rule breakage, the ban is permanent. I also think it would be good if strikes had a lifetime. Maybe a couple weeks, although that complicates the needed fields a bit more. However, adding strikes would obfuscate a client's rule breaking history, which might be useful to keep, as only the last broken rule can currently be saved.

I'm sure we need a concept of strikes as closing an account for a single inaction violation is almost certainly too harsh.

However, I think we should punt on permanent vs temporary now because there will need to be a mechanism to lift an account's suspension after the temporary ban period.  As far as the notification goes, I'm OK with having a field indicating the end of the ban, where initially we just set a time say 100 years out or similar indicating it is permanent.

I also agree that strikes should expire after a period of legit use by the user, but I think we should punt on that too.

This all means we are going to be relying on manual unban actions in the beginning, but we should just get this notification in place now.

> There could be a separate `ban` table keyed by incremental ids that stores time, userID, and broken rule, and we could extrapolate everything we need by doing lookups on that table on demand.

Tracking these events is a challenge too, and we should ensure that each action is accompanied with a log entry.  A more structured record of the events in a table is a possibility we can explore as well, but it's not as critical I think.  Beyond the current account state, grievances can be addressed via the logs if needed.  That's horrible as a solution, but in terms of first steps it will do.  I'm open to exploring a `conduct` table to record all actions including strikes.

> And as for notifications, do you think we should require acknowledgement? Many penalizations will happen because the client was shut down, so notifying right when the rule is broken will probably not be seen. Maybe just notify when connected, but don't worry about a response. I believe auth already has this functioning due to a recent pr.

We can use SendWhenConnected with a longish connect timeout.  However, if the user connects a year later it is reasonable that they should be able to determine what rule was broken so it would be good to include the violated rule and even some details in the `'connect'` response.

So, first things first.  Let's get a notification going with the fields we think will be needed if we get all of the above done.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/537 (spec) and https://github.com/decred/dcrdex/pull/649 (impl)
