### ISSUE TITLE
dexc: prevent shutdown with booked orders and active matches

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#445]
Similar to how logout is prevented when there are booked orders or active matches, CTRL+C (and maybe some select other signals) should not cause dexc or any subsystems from shutting down.

This will involve formalizing the os signal handling similar to how it is done with dcrdex's signal.go, but with coordination with client/core.

Since killing dexc with active stuff will be necessary in some cases, particularly during development, there could be a special signal or perhaps secretly allowing a certain key sequence.

**Comment by song50119** [comment]
Can I pick this up?
