### ISSUE TITLE
server/comms/test: noresponse send error

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#450]
Go CI 1.13 test failure.

log:
```
 ok  	decred.org/dcrdex/server/coinlock	1.788s
--- FAIL: TestOnline (0.92s)
    comms_test.go:708: noresponse send error: write tcp 127.0.0.1:44728->127.0.0.1:33797: write: connection reset by peer
FAIL
FAIL	decred.org/dcrdex/server/comms	1.203s
ok  	decred.org/dcrdex/server/db	1.746s
```

@chappjc comment:
> It looks like the pingPeriod might be too fast or the pongWait too short vs pingPeriod in comms_test.go for the CI machines. 90 ms is a terribly fast ping period so I wouldn't be surprised if these pathetic CI machines just freeze for longer than that for no apparent reason. Otherwise I don't know why the conn write would have gotten connection reset by peer there.

If memory serves correctly, all of these sleep/wait related issues happen in 1.13. No hard evidence that this is causal, just an observation.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/524
