### ISSUE TITLE
client/asset: incorrect locked balance calculation

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrdex#453]
I've only noticed this with dcr wallets but the bug may apply to other assets.

The current locked balance calculation uses the `listlockunspent` rpc command which, unlike suggested by the name, returns all locked outputs regardless of whether they've been spent or not.

To ensure that spent outputs are not included in the calculation, it's important to always call `gettxout` for each output reported by `listlockunspent` but this is not currently always done in code:
https://github.com/decred/dcrdex/blob/048ee403851c283d9756b0f4ecae1b9836b112c6/client/asset/dcr/dcr.go#L1262-L1279

If an output returned by `listlockunspent` is found in the `fundingCoins` cache, it is assumed to be unspent (which isn't always so) and it's value added to the locked balance total. This results in locked balance reports sometimes exceeding the actual sum of locked **unspent** outputs.

Also worth noting that the issue may be averted if locked coins are returned when orders are canceled or executed. Uncertain if this is done for executed orders, but cancelling an order does not return the locked coins.

**Comment by itswisdomagain** [comment]
Update:
`gettxout` may return non-nil result for a spent output if the spending tx is in mempool.

The most reliable solution will be to "unlock" outputs after they are spent or when orders are canceled.

dcrwallet should ideally handle the first part but doesn't currently do so. Pending when a fix is implemented in dcrwallet and maybe even then, client should still unlock coins after spending them to be safe and consistent.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/548
