### ISSUE TITLE
testing: need load testing

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#457]
@itswisdomgain is laying the groundwork for this in #402 and #432. We'll need to start putting both client and server under load. 

1. I would expect that we'll want to make some changes to our simnet harness. Minimally, additional harness scripts to do things like sending coin around or even creating new wallets. 
2. We should simulate latency between harness nodes somehow.
3. Do some reorgs. We already have the scripts written though. 
4. Simulate clients acting maliciously but within rules, e.g. waiting until the last moment to send responses. 

I would suggest this testing bot to be a separate package under **dex/testing**. After #432 in in, we can look at how we can share code or otherwise combine efforts.

**Comment by buck54321** [comment]
I'm going to work on this.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/717, and I suggest we track the reorg testing cases in the other existing issue.
