### ISSUE TITLE
core,dcr: ignoring output from listlockunspent that wasn't found with gettxout

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#471]
I see these message all the time now:

> [DBG] CORE[dcr]: ignoring output from listlockunspent that wasn't found with gettxout. cf6b0cd817cbcf98d88c6368af379beaa8ec80105239c4b17f1fe57025e5fd72:1

**Comment by itswisdomagain** [comment]
This should be resolved by https://github.com/decred/dcrwallet/pull/1753.

**Comment by chappjc** [comment]
Actually I think it's introduced by that.  I've been on master built
yesterday before testing.

**Comment by itswisdomagain** [comment]
> Actually I think it's introduced by that. I've been on master built yesterday before testing.

Hmm. That's unexpected. The only reason we should be seeing those log messages is if `listlockunspent` returned an output that was already spent, hence not found by `gettxout`. Will run some tests to check.

**Comment by itswisdomagain** [comment]
I don't seem to have that issue any longer. I even commented out the following part of the `dcr.lockedAtoms` method which might prevent the log from showing up:
https://github.com/decred/dcrdex/blob/a39e1e95e2ba09cdfc08b469466bcb9a24ad4aa5/client/asset/dcr/dcr.go#L1273-L1277

I was having that issue when running simnet tests on #432 which led me to create #453 and document the following in the test code:
https://github.com/decred/dcrdex/blob/a91fbd262fc2cb25ca970cb66c08e07327b02a30/client/core/trade_simnet_test.go#L295-L300

I removed the sleep and ran the tests, no incorrect balance report and no `ignoring output` log.

**Comment by chappjc** [comment]
Hmm, I guess I was mistaken.  I'll recheck and close the issue.  Thanks for verifying!

**Comment by chappjc** [comment]
Still happens as of today.  Place 9 buy orders, then 0 sell orders, let them settle.  The DCR backend shows these messages.  Wait a few minutes and placing another DCR sell order that locks DCR and the same bunch of messages show up for the same outputs.
