### ISSUE TITLE
core: check server signatures in audit, redemption, and revoke_match requests

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#478]
These signatures were just added in #470, but they're not being checked client-side yet.

**Comment by ukane-philemon** [comment]
@buck54321, any other issue here? This was handled in [7565aa](https://github.com/decred/dcrdex/commit/7565aa09f25e948c9e54cc519632488b7ed023dc), right?

**Comment by ukane-philemon** [comment]
@chappjc, closing?
