### ISSUE TITLE
coinID: Reverse printed txid hex.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#480]
Txid are reversed when printed for all currently supported coins. The tx hash portion of coinID is not reversed when printed. This can be difficult to reason about when debugging. For example, recently there was an error in the client that printed out as:
```
020-06-11 19:15:23.015 [ERR] CORE: Error getting confirmations for 69256461677233ac018df056207a2e1154a7e6faff0d64f97402f046bcd643c000000000: -5: no information for transaction
```

While dcrwallet shows:
```
2020-06-11 19:15:23.013 [INF] WLLT: Inserting unconfirmed transaction c043d6bc46f00274f9640dfffae6a754112e7a2056f08d01ac33726761642569
```

I propose that the tx hash/txid portion of the coinID be reversed when printing for coins that reverse the txid when printing. That is, just adjusting the stringer `String()` methods.

Maybe even have coinID print out as `txid(reversed):output index(minus leading zeros)` divided by a colon, which would be much easier to read for human eyes. For applicable coins, of course.

**Comment by buck54321** [comment]
We've go a function in the asset package for that.

https://github.com/decred/dcrdex/blob/00ea246066936f1b8da7e6f9d6f6802022d3e89d/client/asset/driver.go#L49

**Comment by chappjc** [comment]
There's also a cli app to help decode logged coinIDs: https://github.com/decred/dcrdex/tree/master/server/cmd/dexcoin

I acknowledge that it's quite inconvenient to have to do this, but in the interest of supporting assets that encode their transactions and coins in different ways, using a simple byte slice with asset-specific decoding was all we could come up with.
