### ISSUE TITLE
Matching Engine

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#5]
We need an order matching engine. Given an order book and an epoch queue, the engine should generate matches and handle cancellations. This is a low-level DEX component that will be used by the order book manager, so no considerations for client notification or other higher-level DEX functions should be made. 

This work will involve the creation of an order type and an epoch queue type. The order type will be widely shared among higher-level DEX modules. A market's epoch queue will be shared with <s>an order book manager</s> the [market manager](https://github.com/decred/dcrdex/issues/11), which will be responsible for building epoch queues and sending them to the matching engine along with the order book (standing orders).

Keep in mind that there may be interest in independent verification of order matching, so there will eventually need to be some clean exported types/interfaces.  

Relevant specification sections:

- https://github.com/decred/dcrdex#Epochbased_Order_Matching
- https://github.com/decred/dcrdex#Client_Order_Management

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/15
