### ISSUE TITLE
server: use smart bitcoin transaction fee, change FeeRate to MaxFeeRate

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#502]
To handle BTC fee swings without overpaying consistently with a high configured FeeRate or under-funding orders with a low FeeRate, smart fees should be used:

- On the server,
  - specify a `"maxfeerate"` instead of `"feerate"` in the `'config'` response, which dictates the largest possible network fee that should be accounted for when locking outputs/coins to fund orders.
  - Use `estimatesmartfee 1 "CONSERVATIVE"` to get the optimal fee rate *at swap and redeem time*
  - provide the fee to the clients in the match request
- On the client,
  - Fund orders with the maxfeerate
  - create swap transactions with the rate from the match request
  - create redeem txns with...?

Related: https://github.com/decred/dcrdex/issues/501

**Comment by buck54321** [comment]
> Use estimatesmartfee 1 "CONSERVATIVE" to get the optimal fee rate at swap and redeem time

I think the server should specify the fee rate in the `Match`.

**Comment by chappjc** [comment]
Yeah, that's waaay less error prone

**Comment by chappjc** [comment]
Well, there redeem rate may be different by the time swapconf had passed, so we might consider providing this fee rate in another message, or let the client so do it.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/505
