### ISSUE TITLE
client/core: 'revoke_match' request from the server needs a response

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#509]
`client/core.handleRevokeMatchMsg` handles `'revoke_match'` requests, but it presently treats them as notifications and does not respond.

The server is expecting a `msgjson.Acknowledgement`, although presently `(*Swapper).processAck` only logs the response.

We should either change `revoke_match` to a notification, or make the client treat it as a request and respond.

**Comment by itswisdomagain** [comment]
Resolved in #475. https://github.com/decred/dcrdex/pull/475#issuecomment-651413276

**Comment by chappjc** [comment]
revoke_match is now a notification with https://github.com/decred/dcrdex/pull/725
