### ISSUE TITLE
app: hide time-in-force checkbox for market orders

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#514]
Time-in-force only applies to limit orders, but the checkbox is not being hidden when the market order tab is selected. 

![image](https://user-images.githubusercontent.com/6109680/86248347-62b6c600-bb73-11ea-86f5-40dd1116bf80.png)

Good first issue

**Comment by thi4go** [comment]
Would like to tacke this :+1:

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/560
