### ISSUE TITLE
spec: proposal to facilitate dex server account reinstatement using account proof

### ISSUE THREAD

**Issue by kevinstl** [decred/dcrdex#515]
In the event that a client account is not found on the dex server a dex client has the information necessary to reinstate their own account with AccountProof. It proves that the DEX server accepted the account's fee payment.

```
type AccountProof struct {
	Host  string
	Stamp uint64
	Sig   []byte
}
```

In the event DEX signing key has changed, reinstatement using AccountProof will not be possible.

This spec change was triggered by work towards: https://github.com/decred/dcrdex/issues/249

Functioning code, that will probably require further fleshing out has been completed here: https://github.com/decred/dcrdex/pull/504

This change will also need to be noted in the spec.

**Comment by chappjc** [comment]
It's a logical way to use the signature to prove that the fee was previously paid.

The main use cases are if the server wiped or lost their account tables but their signing key is the same.  In the wild it's perhaps unlikely to need except for catastrophic server DB failure without a backup.  In testing it would be much more helpful as when testnet/simnet server gets wiped but the signing key is the same, this would spare you the pain of re-registering.

Of course a different solution is needed for issue #249, but this could certainly follow that.
