### ISSUE TITLE
client: verify dex config matches known dex config

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#523]
Each time the client connects to a dex that it has already stored in its DB, it should verify that the config response matches what it thinks it knows about that dex server's config.  This is a precursor to market reconfiguration.

**Comment by dnldd** [comment]
Will be taking this on. Should verifying dex configs only apply for the reconnect path? Also verifying config would involve matching host urls and identical markets right?

**Comment by ukane-philemon** [comment]
@chappjc, is this still required? if yes, if the config does not match is there anything important the client should do?

**Comment by chappjc** [comment]
I think we've already got this covered by appropriate actions in `(*dexConnection)..refreshServerConfig`.

**Comment by ukane-philemon** [comment]
Okay, seems this issue can close?
