### ISSUE TITLE
multi: Enable client/server API version checking.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#530]
I think this is not currently enabled because of the current development status, but at some point the client and server must check for ability to communicate before attempting to communicate. The places where this will happen are in the `connect` route.

For the client that is currently here where the client version is set:
https://github.com/decred/dcrdex/blob/4d807f2876734b91ac090fa8a76bf4be2778f90b/client/core/core.go#L1834-L1841

And where the server should check at some point:
https://github.com/decred/dcrdex/blob/4d807f2876734b91ac090fa8a76bf4be2778f90b/server/auth/auth.go#L697-L705

**Comment by chappjc** [comment]
We should get all necessary versioning established in 0.2 so that server will be providing the version and hopefully all clients will be looking for the version by the time we start making breaking changes in 0.3/1.0 that will bump the version.

Decisions to make:
- versioning granularity (comms/api, individual assets, etc.)
- who does checking? client sending `APIVersion` to server is good so server can already recognize "legacy" clients, but it would probably be more natural to advertise it's versions to the clients instead.

**Comment by buck54321** [comment]
I'm thinking add an integer version number as a package constant in **server/dex**, and then send it in the `msgjson.ConfigResult`. Client doesn't even need to read it yet, but it'll be ready when we are.

Asset backend versioning is a different issue (#950), and as far as further granularity, I'm really hoping a single integer will be enough for our purposes. As far as clients are concerned, there is only an opaque API defined in the spec, and one way I've seen API's versioned is by using a single integer and appending it to the actual path. Here are some examples from the APIs used in dcrdata.

`api.coinbase.com/v2`
`api.coindesk.com/v1`
`api.binance.com/api/v1`
`bittrex.com/api/v1.1`

And I'll note that the Bittrex API we're using is quite outdated, and their current API endpoint is `api.bittrex.com/v3`.

So in this model, we would have `exampledex.org/ws/v1` for our websocket connection. We would potentially support more than one version simultaneously to aid in transitions.

**Comment by chappjc** [comment]
> We would potentially support more than one version simultaneously to aid in transitions

This is why I haven't even suggested the path approach, but I acknowledge its utility for clients.  I believe it's likely to open a can of worms.  Say we redefine `msgjson.Register` (or whatever), now we're talking about the dcrdex server importing multiple versions of the msgjson package/module to support both api versions, which is doable but not fun.  Then there's mounting handlers for the same request routes but for different websocket versions, similar situation.

It may be the right solution, but I just want to weight the server's burden against the benefit for heterogeneous client versions.

I tend to prefer to make things backward compatible as long as possible, but that is only possible for so long.

**Comment by JoeGruffins** [comment]
I'll pick this up if noone is actively working on it.

**Comment by chappjc** [comment]
Great, thanks, @JoeGruffins.  Although I had the config response in mind instead of connect.  Specific reasons for connect?

**Comment by JoeGruffins** [comment]
Config sounds fine. Having the server advertise is also probably right. It has been a while since I made this issue, let me do a little bit of research and post back here.

**Comment by JoeGruffins** [comment]
The linked prs give the server a single version that it worries about. It doesn't expose that as ../v1 and expects the client to look in the config to figure out if it can communicate with this DEX.

If a DEX client wants to trade on that server, they may need to upgrade their client. If a client wants to trade at DEXes of varying API levels, they will need to handle those different instances appropriately.

This does not allow for supporting multiple client versions server side when updating. This does however allow for the client to support multiple server APIs, but I would think we would only support the last one or two, as servers that don't update should be left behind. So the update flow would consist of the server spamming users to update their client before they update. Then the server can update, and clients who complied are ready to continue using that DEX with the new API.

**Comment by chappjc** [comment]
Perfect, @JoeGruffins.  That's almost exactly how I see this working.

**Comment by chappjc** [comment]
Reopening until we give each asset a version.  See https://github.com/decred/dcrdex/pull/1047#issuecomment-821226030
