### ISSUE TITLE
client/web: "Your Orders" rows uneven height.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#539]
At some point rows lose their fixed height and grow/shrink depending on the length of the time field. This causes descending rows to move up and down and is disorienting. It seems to be a combination of having a few rows and having an order revoked that triggers it. I will update this header when sure.

![brokenmist](https://user-images.githubusercontent.com/34998433/86991780-e5c2c680-c1da-11ea-9cac-a67e12ad760b.png)

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/560
