### ISSUE TITLE
LTC backend build error

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#57]
Likely realted to switching to go 1.13.

```
go: github.com/ltcsuite/ltcd@v0.0.0-20190519120615-e27ee083f08f requires
	github.com/ltcsuite/ltcutil@v0.0.0-20190507082654-23cdfa9fcc3d: invalid pseudo-version: does not match version-control timestamp (2019-05-07T13:33:22Z)
```

**Comment by chappjc** [comment]
We ran into this with a few imports in dcrdata.  ltcutil used the wrong timestamp there.  Need a replace for that pointing to 20190507133322-...

**Comment by chappjc** [comment]
This seems to do it:

    github.com/ltcsuite/ltcutil v0.0.0-20190507082654-23cdfa9fcc3d => github.com/ltcsuite/ltcutil v0.0.0-20190507133322-23cdfa9fcc3d

Go 1.13 got way more particular about the pseudo versions.  Tips at https://tip.golang.org/doc/go1.13#version-validation

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/59
