### ISSUE TITLE
markets page randomly spins

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#583]
Joe reported this months ago, and I've been hitting it regularly for several weeks now:

![image](https://user-images.githubusercontent.com/9373513/89317150-9d17f500-d642-11ea-99d1-a25c1c922a32.png)

Eventually it loads all of a sudden.  Refresh doesn't help.  It seems to be random when this happens.

**Comment by JoeGruffins** [comment]
This happened to me briefly today, but it was the first time in a long while. Was this on testnet or simnet? I ask because I have been almost exclusively on simnet recently, which is all that has changed for me, as I was using testnet in the beginning.

**Comment by chappjc** [comment]
Unfortunately still can happen:

![image](https://user-images.githubusercontent.com/9373513/91100565-0fb93680-e62b-11ea-9b94-c3113c90e2d1.png)

**Comment by chappjc** [comment]
The repro for this is to have a dcrdex page opened in the browser, shutdown dexc, wait a couple minutes.  In this time, firefox's connect attempts take increasingly longer to fail, eventually reaching minutes of delay between starting a `new windows.WebSocket(uri)` and failing and setting a timeout for the next connect event.  Further, it seems to completely hose all browser windows and is hard to eliminate, with closing the browser window making the request being inadequate to stop this pathological browser behavior.  It is entirely frontend-related, as the dexc process does not even receive a connect request from the frontend when it hangs like this.

**Comment by buck54321** [comment]
Confirmed repro for connection timing. Seems to eventually max out at 50 seconds between `new window.Websocket` and the `onclose` even, making for a 1 minute cycle. Also confirmed to not be an issue on Chrome.

For the spinner, do I remember you saying that it will eventually load?

**Comment by chappjc** [comment]
I think it does eventually load, but I feel like sometimes this tool longer than that 50 seconds.  Anyway, hopefully https://github.com/decred/dcrdex/pull/664 doesn't create new problems.

**Comment by chappjc** [comment]
Reopening.  Seems to still happen, although the issue must be different now.  When it does spin, it's also accompanied by a browser prompt about scripts slowing down the page (wait, stop, debug).

**Comment by chappjc** [comment]
@kevinstl All yours!

**Comment by chappjc** [comment]
Still happens all the time with Firefox.  Don't know how to fix

**Comment by ukane-philemon** [comment]
> Still happens all the time with Firefox. Don't know how to fix

@chappjc, is this `random spin` still happening? how to reproduce?
