### ISSUE TITLE
retire orders where the preimage request failed

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#597]
If a client submits an order, but fails to provide the preimage when epoch processing takes place, the order never leaves "epoch" status.  For sure in client/Core, the order hangs around, not getting retired.  There may be changes needed on the server as well... needs investigation.

**Comment by buck54321** [comment]
[Here's where we should hook into whatever action is needed](https://github.com/decred/dcrdex/blob/6b1ab166f9bcc64a2fd397e9de2e0e988f9cddbe/client/core/trade.go#L236-L237). Do we just need to clear the `(*trackedTrade).cancel` field? I'm certain there's also some work to be done for the GUI, but that should be straight-forward.

**Comment by chappjc** [comment]
I think we may be talking about different issues.  I'm thinking about any kind of trade order where the client quits after submitting the order, but before the preimage requests comes.  So when dexc restarts it loads the order from it's DB as epoch status, thus active.

**Comment by chappjc** [comment]
Some hacking on it here: https://github.com/decred/dcrdex/commit/9bc9349bac9a68dec8d2c2a5c520ccfb7ed27970#diff-ca928c370ec8b724badec3db0dbd7bc4R592-R610

Part of the problem with trying to retire epoch status orders client-side is that the client doesn't even have a flag to say if it had responded to a preimage request or not.  So we risk removing orders that are in epoch status but **did** respond with a preimage, but simply fail to receive either a match or nomatch message.  If a nomatch was simply missed, and the order may actually be booked.  If there was a match, it's likely the order was revoked along with the match, but even that is not certain.

I think `Core` needs to be able to query for user _orders_ in addition to the active matches to know for sure if the order is (1) revoked, (2) booked, or (3) actually still in epoch status.

It seems that there's no way to tell if an order is in that state between preimage response and match/nomatch message back from the server, which would at least address (3) partly.

**Comment by buck54321** [comment]
Yeah. I wasn't reading very closely, I guess. I'll open a different issue for handling missed cancel orders. 

I don't have a quick solution for these state syncing edge cases. I do think we've been dancing around a simple order status route for a while now, and we could also use a way to synchronize the current epoch on startup, I think.

**Comment by itswisdomagain** [comment]
Similar to what you have here: [9bc9349#diff-ca928c370ec8b724badec3db0dbd7bc4R592-R610](https://github.com/decred/dcrdex/commit/9bc9349bac9a68dec8d2c2a5c520ccfb7ed27970#diff-ca928c370ec8b724badec3db0dbd7bc4R592-R610), here's a combination of events that would permit retiring the order safely:

- Client knows no matches for the order 
- `connect` does not report any active matches for the order. Either...
  - the order was never matched (missed preimage request or nomatch request), or
  - the order received 1+ matches that are now revoked
- The order will not receive further matches and can be safely retired, if
  - the order is a market order or tif-immediate limit order and the order's epoch has passed
    - ✅ the order should be considered Revoked if preimage request was not sent
    - ☑️ If preimage was sent, the order may be Executed (with no matches) or Revoked (with 1 or more Revoked matches due to the client's inaction), regardless the order can be retired.
- ❓If the order is a standing limit order, it may be Booked or Revoked. Will require an `order_status` route to determine the current status. I can't seem to find where now, but I think @buck54321 had mentioned a need for an `order_status` route.

**Comment by itswisdomagain** [comment]
This also affects orders that are revoked unbeknownst to the client. Even when subsequent DEX connections return no matches for the order, the order will continue to be treated as Booked and will not be retired.

**Comment by itswisdomagain** [comment]
An alternative to an `order_status` route is having the DEX return order IDs and statuses for the client's Epoch and Booked orders.

Any Epoch or Booked orders in the client's record that is not found in the ActiveOrders list returned by `connect` should be retired if `connect` also returned no active matches for the order.

- If the client previously recorded the order as Booked, set status to Revoked.
- If the client previously recorded the order as Epoch, and
  - the order's preimage was not sent, set order status to Revoked.
  - preimage was sent and the order is a standing limit order, set status to Revoked.
  - preimage was sent but the order is NOT a standing limit order, set status to Executed.

Orders for which active matches are reported on connect, will likely get their statuses appropriately set in `tracker.negotiate`
- Market orders and tif-immediate orders will be set to Executed.
- Partially filled standing limit orders will be set to Booked (if also found in the ActiveOrders list returned by `connect`) or set to Revoked (if not found in the ActiveOrders list).
- Completely filled standing limit orders will be set to Executed.

**Comment by chappjc** [comment]
Being resolved by https://github.com/decred/dcrdex/pull/677
