### ISSUE TITLE
consider removing ClientTime from order structure

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#626]
The ClientTime field of an order is set by the client and the only validation that the server performs is to ensure that it is within 10 seconds of the time on the server when it stamps the order.

Issues:
- This places a possibly unreasonable constraint on the clients
- The value of the stamp itself is not valuable
- the 10 second deviation was arbitrary anyway.
- it's extra data

Can we eliminate either the ClientTime field or the 10 second deviation presently permitted by the server?

**Comment by ukane-philemon** [comment]
This was somehow addressed in #641?
