### ISSUE TITLE
client/core: silence the not yet swappable/redeemable messages based on confs already checked

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#629]
e.g. The following message should only print if the tip for the asset has changed:

[DBG] CORE: Match 39e8fde08e55a8ff0ff670089a74f3f148cde396c4c0fae009a604284de419a1 not yet swappable: current confs = 0, required confs = 1

It keeps printing each tick.  There are good architectural reasons, but we should fix this.  Assigning myself.

**Comment by chappjc** [comment]
Reopening to track the refactoring of tick and tipChange

**Comment by itswisdomagain** [comment]
For context: https://github.com/decred/dcrdex/pull/630#pullrequestreview-474116249

> we should move the isSwappable and other confirmations-dependent checks to on tip change. Unless it is possible for core to miss a tip change, it's pointless continuously checking tx confirmations every tick.

**Comment by buck54321** [comment]
To be clear, we are running `tick` on `tipChange`, https://github.com/decred/dcrdex/blob/38443f3237e34682e45a950de68f4d69a9bff52b/client/core/core.go#L3342. 

We're also running `tick` every 1/3 broadcast timeout, which is safety net and should not be necessary. We can talk about removing that once everything else is working, but let's not fiddle with it yet.

`tick` itself might be better as a `Core` method. I don't see a need for too much refactoring beyond that, but maybe @chappjc had something in mind.

**Comment by chappjc** [comment]
Being resolved in match_status work.
