### ISSUE TITLE
client/core: do not unlock outpoints on shutdown

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#631]
On dexc/Core shutdown, we should definitely not unlock outpoints that were not locked by dexc/Core, and arguably we should not unlock any that are still connected to active orders.

**Comment by itswisdomagain** [comment]
I should add this to #648.

**Comment by chappjc** [comment]
My thinking on this now is that we should not unlock any coins on shutdown, esp the ones that are connected to active orders.

The problem is especially clear with the dcr harness where ticket buying happens constantly.  Shutdown dexc with active funded orders, and the funding coins aren't found next start if you've been mining the harness and buying tickets.

**Comment by itswisdomagain** [comment]
I agree with that thinking; can't have wallets spending coins locked for orders while dexc is shut down.

This makes it all the more important to get coin unlocking right, to prevent cases where coins remain "forever" locked for orders that will no longer utilize those coins.

Such orders (that have no further use for locked coins) include:
- New orders that did not make it to the DEX, e.g. if sending the request or validating the server's response fails.
- Executed, canceled or revoked orders that have sent all required swaps, including unmatched or partially-matched market and tif-immediate limit orders. Coins for such orders should ideally be unlocked when
  - the last set of swaps are sent for such orders, or
  - the last match (that would have required sending a swap) is revoked, or
  - the order is canceled or revoked with no swap-pending match.

Coins will remain needlessly locked if a client is unaware that
- a match has been revoked (e.g. client missed the `revoke_match` request)
- an order has been revoked (there's no `revoke_order` request yet)
- an order has been canceled (is this possible?)

Such coins will/should be unlocked when the client (re-)connects the DEX and "notices" the revoked/canceled orders and/or revoked matches.
