### ISSUE TITLE
Any timeline to freeze the code?

### ISSUE THREAD

**Issue by sjtusmartboy** [decred/dcrdex#667]
I'm asking this because the time is money since many other DEXs are pushing really hard to launch the project so that they will win in fight for the currency flow. The first will eat flesh, the second eat soup, but the last eat nothing. Also I've noticed that we have been making the DCRDEX project for over a year, so maybe we could accelerate it just a little bit. Thanks !

**Comment by chappjc** [comment]
It has already reached MVP goals.  The product is presently in an intensive testing phase.  For non-dev questions like this please ask in https://chat.decred.org
