### ISSUE TITLE
proposal: less gameable deterministic order matching algo

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#67]
As defined by the current spec ([Pseudorandom Order Matching](https://github.com/decred/dcrdex/blob/master/spec/README.mediawiki#Pseudorandom_Order_Matching)), order matching begins by shuffling the epoch queue in a deterministic manner by seeding a Fisher-Yates shuffle with the hash of the concatenated order hashes.

![seed](https://raw.githubusercontent.com/decred/dcrdex/master/spec/images/seed-eq.png)

There are some concerns about this:
- Part what affects the order ID (e.g. _order1_, etc) are the client and server time stamps.
- (independent, and more importantly) The server(s) and all the clients know what the epoch order would be if it were to close with its current orders.

The change proposed (by @behindtext) to the epoch shuffling algorithm will eliminate the above concerns, but not without a complexity trade-off:
1. Each submitted order will include a commitment. This can be the hash of a random number known only to the client submitting the order.
2. At the close of the epoch, each client will be required to submit the value to which they committed.  EDIT:  The close of the epoch should be marked by a special server broadcast message containing the epoch's order IDs and commitments.  The clients must not submit their preimages prior to receiving and validating this server-signed message.
3. The seed is based on the hash of the concatenation of the commitment preimages.

With the above shuffling algorithm, it is impossible for the others to collude against you (as a client) as they would need to know your commitment value.

Issues:
1. If a client does not respond with their value?  End of queue or fail their order?
2. If no clients respond with their value?  Invalidate all orders?
3. (the obvious one) Order matching is delayed by X seconds until clients have provided their commitment value.  Is the delay acceptable?  Is the complexity acceptable?

**Comment by chappjc** [comment]
In Matrix chat with @buck54321, it was discussed how to put this into practice to prevent the server from inserting an order at the end of epoch to get a desirable shuffle.  Below are some notes from the discussion.

Up until the commitment preimages are sent in by the clients at the end of the epoch, the server is unable to determine the order, thus preventing meaningful manipulation of the matching.  If the server changes the commitment (e.g. preimage hash) then everyone will know as long as the orders get broadcast on submit (or inserted into an immutable public log, more on that later).

Since the server won't know what preimage is favorable until they get all the clients' preimages, a way to prevent the server from tampering with the order queue after receiving the preimages from the clients would be to include in the signed preimage request a list of the orders' IDs and their commitments in the just-closed epoch.  If the matching ends up including an order that wasn't in that request, the server cheated.  Further, in a server mesh other honest servers won't be able to replicate the cheating server(s) order matching.

Regarding the server omitting orders, that is not solved by this proposed client commitment scheme.  Further discussions in Matrix with @jrick point to an immutable public log, i.e. https://research.swtch.com/tlog.  However, requiring the server to immediately broadcast all received orders will expose the omission, and provide proof of the omission in the form of the server-signed new order message.

**Comment by buck54321** [comment]
I think that this is the way to go. While we can't stop the server from omitting orders, they can't do it silently. 

I offer a couple of additions to the procedure outlined above.

1. The preimage request will originate from the server, and the client will have on the order of a few seconds to respond. 

2. Included with the preimage request will be a checksum hash of the concatenated lexicographically-sorted commitments. Any validator who was online for the full epoch can compare this checksum to the commitments reported (as streaming notifications) by the server. The preimages will be broadcast together after collection. 

More decentralization via server mesh will enable further improvements, but this solution fills some big gaps.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/145
