### ISSUE TITLE
funds locked in contract output need to be in locked balance

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#672]
When a client authors a swap txn, the contract output value should go into that asset's "locked" balance.  If the contract is refunded, it goes back into spendable; if it is redeemed by the counter party, they will author their own redeem that increases the other asset's spendable or immature balance -- i.e. the actual swap.

**Comment by itswisdomagain** [comment]
In addition to incrementing the locked balance when swaps are authored, the locked balance should also be updated when coins are unlocked mid-trade or on order retirement.

**Comment by itswisdomagain** [comment]
Here's an implementation idea:

- Add a `trackedTrade.amountLockedBySwaps(assetID)` method that sums the amount sent for swaps sent from the specified wallet, where the client has neither refunded the swap nor has the client redeemed the counter-swap.

- Call the method for all trades in the `Core.walletBalances` method, adding the returned values to the locked balance returned by the wallet:
```
c.connMtx.RLock()
defer c.connMtx.RUnlock()
bal, err := wallet.Balance()
if err != nil {
	return nil, err
}
for _, dc := range c.conns {
	dc.tradeMtx.RLock()
	for _, tracker := range dc.trades {
		bal.Locked += tracker.amountLockedBySwaps(wallet.AssetID) // or bal.SwapLocked?
	}
	dc.tradeMtx.RUnlock()
}
dbBal := &db.Balance{
	Balance: *bal,
	Stamp:   time.Now(),
}
wallet.setBalance(dbBal)
```

As long as all trades for all DEXes are loaded and in the correct states/statuses, swap-locked amounts will reflect in the locked balance reported by Core.

**Comment by chappjc** [comment]
Seems like a reasonable approach, @itswisdomagain.  I think `unspentContractAmounts` might be more expressive than `amountLockedBySwaps` though.
