### ISSUE TITLE
split tx only works when server is on same node as client

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#675]
A remote testnet server will return with an "error retrieving coin ID" error because the client submits the order specifying a coin that takes time to propagate on the network.  `gettxout` doesn't see it server-side.

Note that this is a general issue with txns propagating, but we don't see it with normal orders that are funded by utxos that existed long before placing the order.  This is a race that the asset network generally looses.

The solution might be a coin waiter with a very short timeout of say 5 seconds, because any longer and the client's request timeout will kick in while waiting for the server to respond.  A simpler solution might be to just wait a bit after broadcasting the split tx to actually submit the new order to the DEX server.

**Comment by buck54321** [comment]
> any longer and the client's request timeout will kick in while waiting for the server to respond

Request timeout is adjustable, and should be >= latency limits. Solution 1 has my vote.

**Comment by itswisdomagain** [comment]
How about both?
- Wait a bit after broadcasting before submitting order to DEX
- Increase client request timeout a bit to allow server account for latency when trying to locate funding coins

**Comment by itswisdomagain** [comment]
Btw, the client gets an error that looks like
```
new order request with DEX server <addr> failed: rpc error: error code 36: error retrieving coin ID <coin id hex string>
```

**Comment by chappjc** [comment]
I'm just about done with this and I realized that I never assigned it.  Hopefully no one else has work on this.
