### ISSUE TITLE
reconnecting to wallet must sync wallet lock state with Core's state

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#676]
When the wallet, say bitcoind`, restarts while dexc is running, dexc does not attempt to check the wallet's lock state against Core's.  The reconnect hook needs to (1) change the UI wallet lock state to match the wallet, and (2) trigger wallet unlock if Core expects it to be.

Number 2 may be tricky though since unlocking the wallet requires the app password.

A related issue is that active swaps will fail in an unrecoverable manner presently with a locked wallet:

> [ERR] CORE: route 'redemption' request handler error: dex-test.ssgen.io:7232 tick: {redeemMatches - order 1e488039f3b9b33c4f467ddd9374d3016402991ccc15919 f0fb5b014719932b2 - {rawrequest error: -13: Error: **Please enter the wallet passphrase with walletpassphrase first**.}}

In the above failure: `asset.Wallet.Redeem` returned that error.  The asset backend should return a special error type for Core to recognize this and not kill the swap, instead prompting for a password.

**Comment by chappjc** [comment]
Immediate resolution is caching wallet passphrases to automatically unlock wallets that are unexpectedly locked.  A prompt would not provide sufficient time for most active swaps.

**Comment by itswisdomagain** [comment]
This should be resolved by #817?
