### ISSUE TITLE
app: reset password and change password features

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrdex#678]
- Forgot password -> Reset password feature. Reset password requests should probably be authorized somehow, perhaps by providing a recovery phrase that the user can back up on dexc setup. Should likely require user to re-provide wallet passwords.

- Change password feature for logged in users. Should not require re-supplying wallet passwords.

**Comment by chappjc** [comment]
@amassarwi is gonna start with the change password feature.  I'm not sure how well defined the "forgot password" features is at this point.
