### ISSUE TITLE
core: Add IsRegistered

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdex#682]
```func IsRegistered(host string) bool { }```

**Comment by chappjc** [comment]
If you are really after fee payment status, which is a step beyond registration, I think you'll want to use `(c *Core) Exchanges()`, which has a FeePending field for each exchange.  If the fee payment has been broadcasted, FeePending will indicate if the account is paid or not.

**Comment by buck54321** [comment]
Can close, @dajohi?

**Comment by dajohi** [comment]
yes
