### ISSUE TITLE
new match ack dialog should also prevent maker swap until BOTH acks

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#686]
One consideration for the new dialog concept being used to improve the current match/ack request/response is to ensure the ack is actually recorded by the server before maker sends the `'init'` request<s>, but a bigger concern is the maker doing `'init'` and the taker not even acking the match request.</s>

EDIT:  I acknowledge having both parties ack first is not a big deal because taker did just respond with a preimage and they could decide not to act even if they do ack the match request.  However, I still think we are facing the issue of server not being ready for init unless it has recorded the maker's match ack.  This however can be addressed with some architectural changes.  Slosing the issue in light of the distinction.

The above change requires the dialog concept described in https://github.com/decred/dcrdex/pull/526, and in handling the dialog server-side, only sending the final OK message in the dialog to both parties when *both* have acked.

**Comment by buck54321** [comment]
Maybe, but the taker just signaled their presence by submitting their preimage. We can spend all day confirming that the counter-party is ready before every action, but we can't stop a malicious actor from being an ass when it matters. Can you provide some additional motivation or a problem that this fixes?

**Comment by chappjc** [comment]
> the counter-party is ready before every action

Two things:
- first is not to ensure the counter-party is ready for action, but that the server is ready.  If the server hasn't recorded the maker's match ack signature yet, it's not ready to handle the maker's 'init' that gets sent immediately following the match ack.
- second is to save the maker the pain of waiting to refund their contract when they didn't even need to broadcast it in the first place since the taker didn't ack the match request.
