### ISSUE TITLE
capability of server request with a deadline

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#697]
The `RequestWhenConnected` server `AuthManager` method provides the ability to send requests when the user logs back if they are not around at the time. However, the use of two timeouts is counter-intuitive and does not provide an easy way to limit the maximum time allowed for both connect and response once the request is sent.  Presently there is:
- response timeout, which defines how long the client has to process and respond to the request _once it is sent_, and
- connect timeout, which defines how long the request may remain as "pending" and unsent, waiting for the user to return.
The response timeout does not start until the user connects and the request is actually sent.

In practice, what we usually need is a single deadline that expires the request regardless of whether it was sent or not.  In most cases this is the last time at which it makes sense to even allow a response.  This would be more intuitive in most cases, such as when we know an inaction/revocation would make the response obsolete.  e.g. https://github.com/decred/dcrdex/pull/680#discussion_r491022709

**Comment by buck54321** [comment]
Likely resolved by #699.
