### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#7]
We need to handle persistent data. A solution will likely utilize a relational database, though some data might be better handled with a key-value database. The primary data to be stored is order data and account information. Orders for storage will come in the form of the order type used in the order book manager / matching engine, so there is some overlap with #5.

**Comment by al-maisan** [comment]
Why not use `cockroachdb` (+ `gorm`) as politeia does?

**Comment by chappjc** [comment]
> Why not use `cockroachdb` (+ `gorm`) as politeia does?

The first choice here is the actual database to support.  Or more specifically, which wire protocol.  CockroachDB and PostgreSQL have the same wire protocol, and mostly share the same query syntax.

The other choice is ORM vs. writing the queries.  I personally prefer not to use an ORM as I see it as unnecessary code.  Also, writing the queries is not only easier for me, but it gives you full control over what gets executed on the DB server.  The two best choices for a postgresql driver are  github.com/lib/pq and https://github.com/jackc/pgx.  Note that github.com/jinzhu/gorm used github.com/lib/pq to support the postgresql dialect.

Going back to CockroachDB, this should not be the required server for a few reasons.  The first is their unfavorable approach to licensing, which in practice boils down to abandoning a permissive license in favor of a business license that requires payment.  Another big reason is that CockroachDB performance is seriously lacking, especially compared to PostgreSQL.  The last is that CockroachDB is still very immature, and although that can be debated, you only have to look at their own sql feature support table at https://www.cockroachlabs.com/docs/stable/sql-feature-support.html and review the github issues, which reflect the growing pains of a young project.  That is not to say that CockroachDB isn't a great product!  It's just not my choice at the moment.  On the other hand, crdb is great at redundancy and ease of clustering.

An even higher level decision is RDMS vs KV/NoSQL.  However, the Archivist (this persistent storage issue) must have an interface that gives no hints as to what DB backend is to used.  That is to say, I'd like if the backend could be selected at runtime via a config file setting.  The consumers of the Archivist shouldn't need to know which one is running, just that it implements the required interface.

**Comment by chappjc** [comment]
Some possibilities for backends (now or in the future):
- PostgreSQL via lib/pq or jackc/pgx
- A graph database: [dgraph](https://github.com/dgraph-io/dgraph) via [dgo](https://github.com/dgraph-io/dgo)
- A NoSQL DB: [RethinkDB](https://github.com/rethinkdb/rethinkdb) (back from the dead) via [rethinkdb-go](https://github.com/rethinkdb/rethinkdb-go)

**Comment by chappjc** [comment]
I think the high level decisions were addressed by https://github.com/decred/dcrdex/pull/47 and other subsequent PRs.  The DB driver system and the drivers themselves will continue to evolve to meet the needs of the DEX (e.g. https://github.com/decred/dcrdex/issues/112), but I think this issue is resolved.
