### ISSUE TITLE
app/browser: while registration fee is pending, /markets takes you to /register

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#701]
Getting forwarded to the /register page when your registration fee is paid, just pending, is incorrect.

**Comment by buck54321** [comment]
I'm not able to reproduce on Chrome, Firefox, or Brave. With a fee pending, I'm taken to /markets, and the proper messaging is displayed.

<img src="https://user-images.githubusercontent.com/6109680/94038288-e0155f80-fd8b-11ea-8364-4a2aca23c367.png" width="350">

**Comment by chappjc** [comment]
I can't reproduce either.  Hmm.  I thought it might have had to do with restarting dexc while fee was pending, but that doesn't do it either.  Closing.
