### ISSUE TITLE
client: Persistent Storage

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#71]
Compared to the server's persistent storage needs (#7, #47), the client is not as constrained in terms of performance requirements, so pretty much anything is on the table here. It may be worth looking at `dcrwallet`'s `bbolt`-based database, which I think has no external dependencies.

**Comment by dnldd** [comment]
Yeah, bbolt would be ideal for this. I'll share an outline of the buckets and other details I think need to be persisted for further discussion soon.

**Comment by chappjc** [comment]
Agreed that bbolt is a good choice here, although for the record I wouldn't object to badger either.

**Comment by buck54321** [comment]
I'll work on this.

**Comment by chappjc** [comment]
Nice.  You got it.

**Comment by buck54321** [comment]
Closed by #99
