### ISSUE TITLE
limiting order quantities

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#712]
The running swap successes count introduced in https://github.com/decred/dcrdex/pull/700, if not the combined score itself, will form the basis for user order quantity limits.  This could mean scaling the following limits for a user:
- max single order size
- total unsettled order quantity (booked + settling in active swaps)

So when a user submits an order for X amount of the base asset, it must be less than (unsettled limit) - (booked amount) - (settling amount).

This amount (unsettled limit) should be derived from the user's recent history of completed and failed swaps and their amounts.  e.g. The user successfully settled 20 lots and failed to swap 3 lots. Although, the nature of the failed swaps is important, as the scoring in PR #700 makes clear, so there should be some weighting for swap failures that inconvenienced the counterparty. This may be as simple as weighting the settled/failed amounts by the associated badness score.

These are of greatest important for taker orders as not settling forces the maker to lock up their funds for 20 hrs in the initiator contract. As maker the potential for abuse is mitigated because failure of maker to broadcast swap causes no funds to lock in contracts, and failure to redeem the taker's contract also means that the maker's own funds are locked for 20 hrs just to lock the taker's for 8 hr.

_Originally posted by @chappjc in https://github.com/decred/dcrdex/pull/700#issuecomment-701850611_

**Comment by buck54321** [comment]
> This amount (unsettled limit) should be derived from the user's recent history of completed and failed swaps and their amounts. e.g. The user successfully settled 20 lots and failed to swap 3 lots. Although, the nature of the failed swaps is important, as the scoring in PR #700 makes clear, so there should be some weighting for swap failures that inconvenienced the counterparty. This may be as simple as weighting the settled/failed amounts by the associated badness score.

We're already applying the weighting to the score, so we should just normalize the score to (0, 1) and apply it to linearly `unsettled limit` to get the user's limit.

e.g.

```
MaxLots = 1000
scoreRange := MaxBanScore - MinBanScore
shiftedScore := banScore - MinBanScore
normalizedScore = 1 - (float64(shiftedScore) / float64(scoreRange))
userMaxLots = int(normalized * float64(MaxLots))
```

**Comment by chappjc** [comment]
I missed your comment on this @buck54321.  Will consider that and how it compares with the concept in PR https://github.com/decred/dcrdex/pull/750

**Comment by chappjc** [comment]
I think I like the simplicity of scaling an absolute lot size limit with a normalized score.  May try that if time permits
