### ISSUE TITLE
client: account private key import/export

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#722]
Backing up dexc.db is the only way presently to backup a DEX account.  We should allow a user to export and import the private key for a DEX account.

Related, a seed mnemonic could be used, but that is a bigger change, and breaking: https://github.com/decred/dcrdex/issues/434

**Comment by kevinstl** [comment]
For the export we can provide a new endpoint in webserver.go:

```
r.Get("/keys", s.keys)
```

That endpoint will respond with a json file for download with the keys included:

```
[
   {
      "host": "dex.decred.org",
      "accountID": "hexstringhereadsfadf",
      "privKey": "hexstringhereadsfadf",
      "pubKey": "eifoiwfjoskldfjlfjfvlkldjksfkjsfdjknhheyrnn"
   }
]
```

**Comment by kevinstl** [comment]
Per @chappjc the /keys endpoint will both be behind the auth middleware and require the app pass.
