### ISSUE TITLE
dexc: view only support

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdex#726]
It would be nice if dexc could be "watch only" --  watch trade activity without needing wallets.

**Comment by buck54321** [comment]
I was just wanting this this morning. The server supports order book subscriptions without accounts, so this shouldn't be too hard.

**Comment by sumiflow** [comment]
IMO, I think it would be nice to require as little info and then show the order book.  You might even skip setting up an app password until the first wallet has been added.  Perhaps you let the user choose a dex server address and then the order book shows with options to add decred and other wallets.

**Comment by amassarwi** [comment]
would like to add that

**Comment by vctt94** [comment]
Is anyone currently working on this?
