### ISSUE TITLE
write a script to package release

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#730]
I'm guessing we'll need to do something like...

1. Build **dexc**
1. Build **dexcctl**
1. Compile web assets
1. Probably some other stuff too
1. Copy files and compress

**Comment by chappjc** [comment]
In matrix, we noted the following required directory structure:

```
$  tree -L 3
.
├── dexc
├── dexcctl
└── site
    ├── dist
    │   ├── entry.js
    │   ├── entry.js.map
    │   └── style.css
    └── src
        ├── font
        ├── html
        └── img

6 directories, 5 files
```

With the following procedure to prep the minimal "site" folder:

```
rm -rf .babelrc .eslint* node_modules package* .stylelint* webpack src/css src/index.js src/js
```

Alternatively, zipping up the required bits, with 7za as an example:

```
7za a -mx=9 site.zip site/dist site/src/font site/src/html site/src/img
```

**Comment by chappjc** [comment]
I have a really dumb bash script now, and I started hacking a clone of github.com/decred/release, but that's not ready

**Comment by chappjc** [comment]
Resolved by dcrinstall support, but I also have a script in a branch on my repo that I use occasionally: https://github.com/chappjc/dcrdex/blob/pkg1/pkg.sh
