### ISSUE TITLE
testing harness btc path issues

### ISSUE THREAD

**Issue by devwarrior-cool** [decred/dcrdex#742]
recently 3 days ago decrdex/dex/testing/btc/harness.sh
 was split into 2 scripts from 1.    harness.sh & base-harness.sh

Running from ~/dcrdex   as detailed in the wiki

$ ./dex/testing/btc/harness.sh

first issue is that  ./base-harness cannot be found from harness.sh

so changed that script to use full path on my machine 

2nd Issue:

EXCEPTION: St13runtime_error       
Invalid combination of -regtest, -testnet and -chain. Can use at most one.       
bitcoin in AppInitRPC()       

thanks

**Comment by devwarrior-cool** [comment]
2nd issue above was my mistake. Have bitcoin.conf in .bitcoin containing

testnet=1

So now the Tmux script is running.

**Comment by itswisdomagain** [comment]
First issue is resolved if you cd to the btc test dir before running the harness
`cd ./dex/testing/btc && ./harness.sh`

But I agree some changes can be made to enable running the harness using a longer path.

**Comment by devwarrior-cool** [comment]
Yup .. I can workaround.
The BTC timeouts are quite nasty as they depend your machine capability especially for the node start ups. Again I can workaround.
The path in the harness script is now documented here .. so I think we can go ahead close this one. Thanks
