### ISSUE TITLE
ui: need a visible notification when an order is revoked

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#752]
We currently send out a `Data` notification to force a status update in the "my orders" table. That is sent from `(*trackedTrade).revoke`. That can't be a `ErrorLevel` or `WarningLevel` notification, because `revoke` is used from two places with different severity. So the caller will need to send the notification instead. the `"revoke"`-subject notification itself can be removed as long as we are consistent about the caller notifying.

**Comment by chappjc** [comment]
@kevinstl is taking this

**Comment by kevinstl** [comment]
> That can't be a `ErrorLevel` or `WarningLevel` notification, because `revoke` is used from two places with different severity.

I see two places where revoke is initiated, handleRevokeOrderMsg() and handleTradeSuspensionMsg().

I'm assuming:

handleRevokeOrderMsg() is WarningLevel
handleTradeSuspensionMsg() is ErrorLevel

Is that correct?

**Comment by buck54321** [comment]
I was actually thinking the opposite. Maybe someone else can weigh in.

**Comment by JoeGruffins** [comment]
I think trade suspension error level would depend on whether or not the user was informed beforehand. If expected, warning. An unexpected suspension would be an error in my opinion.
