### ISSUE TITLE
Paginate the specification

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#76]
The specification could benefit from some pagination. Could we keep a table of contents and a DEX overview where the spec is, but break off some of the more technical sections to their own mediawiki files? The "chapters", each with its own file, could roughly follow the current table of contents.

1. Communication Protocols
2. Exchange Fundamentals
3. Account Management & Community Conduct
4. Data API (including order book subscriptions)
5. Order Management
6. Exchange Administration

The specification is bound to grow in size. I think this would provide some sanity to the information.

**Comment by JoeGruffins** [comment]
I'll take this secretarial work if that's alright.

**Comment by buck54321** [comment]
I've got a couple spec PRs open, so one of us would potentially have to work through some messy rebases, but I'm okay with it if you are. Please share your anticipated chapter structure here before getting too far. You can start with the list above, but it may have room for improvement. Don't forget to consider changes made in the open PRs.

**Comment by JoeGruffins** [comment]
I came up with the list

    Abstract
    Communication Protocols
    Distributed Exchange Design Fundamentals
    Distributed Exchange Administration
    Client Accounts
    Client Order Management
    Data API
    Atomic Settlement
    Community Conduct
