### ISSUE TITLE
Native SegWit (bech32) BTC addresses

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdex#766]
Would bech32 addresses not further reduce tx sizes for deposits?

**Comment by chappjc** [comment]
I'm seeing a bc1 address for BTC when I click deposit.  Is it showing you a legacy or p2sh instead?

**Comment by jzbz** [comment]
Legacy address, fresh wallet, only set up to use DEX, no other txs.

**Comment by buck54321** [comment]
If you had an existing client database that you didn't wipe, the address was stashed in the DB. Been meaning to add a button to generate a new address.

**Comment by buck54321** [comment]
Resolved in #769
