### ISSUE TITLE
app: order details page shows incorrect filled amount for market buy

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#775]
testnet example:

![image](https://user-images.githubusercontent.com/9373513/96922172-1d493c00-1475-11eb-81a6-8337e273c519.png)

800% is wrong, but it's because it was a 2.5 BTC market buy.

The maker's rate that was matched is 0.1 btc/dcr, so 2.5 btc covered just one 20 DCR lot.

**Comment by chappjc** [comment]
Bump.  This was reported again today

**Comment by chappjc** [comment]
A related quirk with market buys is that if you have _multiple matches_ the filled% does not always add up to 100 as expected.  I think this is observable when the different matches are at different rates.

**Comment by martonp** [comment]
I'll take a look.
