### ISSUE TITLE
server: characterize poor client connectivity and notify client

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#778]
When the server observes unexpected websocket errors (e.g. i/o timeouts every ~ping interval), server could mark the anomaly in an IP-keyed map, and when that IP has many anomalies the server could send a notification that the client could display to the user to check their connectivity.

It has already been observed that a user's connectivity can be degraded in such a way that messages sent from server->client succeed, but the client apparently cannot respond.  This can be due to any number of things, from client's firewall to poor upstream connectivity (e.g. sat).

**Comment by ukane-philemon** [comment]
@chappjc this can close now, right?
