### ISSUE TITLE
server/market: allow cancel orders while market is suspended

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#792]
This will require an alternate order processing path because a market is suspended by draining the epoch processing pipeline and actually letting Run return. (Resume starts Run again). The simplest way to allow cancel orders is simply to process them directly with no epoch shuffling and matching.  Whether or not preimages should still be requested in this context is not clear, but they would serve no purpose except perhaps consistent book keeping.

**Comment by martonp** [comment]
I'll work on this one.
