### ISSUE TITLE
server/swap: restore swap state from DB only

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#793]
This is much more doable now for a number of reasons including the dropped requirement for acknowledgements.  Coin waiters can be restarted as described in the swap state comments, and probably audit/redemption requests can be resent if no ack is recorded even if it was really sent and just didn't get a response from client before being interrupted at shutdown. Some care to ensure client is ok with possibly redundant messages is warranted, but this no longer seems too daunting.

**Comment by buck54321** [comment]
Closed by #856.
