### ISSUE TITLE
server: block download timeout consideration for broadcast timeout

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#795]
Bitcoind can get stuck with a bad sync node and it won't timeout on the block it's trying to download for 10 minutes.

https://github.com/bitcoin/bitcoin/pull/5608
https://github.com/bitcoin/bitcoin/commit/a3a7317
https://github.com/bitcoin/bitcoin/issues/12291

Despite being BTC-specific, we should consider this in the default broadcast timeout setting.

**Comment by buck54321** [comment]
Resolved in #815
