### ISSUE TITLE
overshoot swap fee to be safe

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#809]
...a certain percent over the `estimatesmartfee` result seems like a great idea given how easy it is to get buried by other txns where blocks are taking too long.  I was thinking more like 150% though, so it would indicate 450 for 300 e.g. and that would have been more than sufficient throughout this latest congestion.

_Originally posted by @chappjc in https://github.com/decred/dcrdex/pull/785#discussion_r515636419_

**Comment by buck54321** [comment]
Resolved by #864?
