### ISSUE TITLE
app: tx rejection when withdrawing dcr - payment of 0 is dust

### ISSUE THREAD

**Issue by karamble** [decred/dcrdex#812]
just saw this the first time. when trying to withdraw/empty out the trading account trough the app dcrd gives an error:
`withdraw error: sendrawtx error: -4: wallet.PublishTransaction(...)
is not standard: transaction output 1: payment of 0 is dust, raw tx:`

**Comment by chappjc** [comment]
Withdraw does seem to have a logic issue with dust sometimes.  Apparently affects dcrd, maybe btc too.

**Comment by chappjc** [comment]
Apparently just DCR since BTC's sendtoaddress has a subtract option we use that dcrwallet lacks, necessitating a custom txn.  I will look into this tonight.
