### ISSUE TITLE
Specify PRNG

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#82]
In order for the client to be able to independently verify matching, they need to be able to produce the same series of random numbers based on a given seed. This means that we must use the same exact random number generator. Right now, the generator used is the default from Go's `math/rand`, which is only described as [`algorithm by DP Mitchell and JA Reeds`](https://golang.org/src/math/rand/rng.go). Googling gives [some indication of the source](https://grokbase.com/t/gg/golang-nuts/137fejwsem/go-nuts-math-rand-package-underlying-algorithm), but it's not clear how common this implementation is. If Mitchell/Reeds is uncommon, but there is some more common algorithm we could use, we should.

**Comment by buck54321** [comment]
As an alternative to using a random number generator, we could generate the random series using a hash like Blake-256 that we know the client will have. For example, [in `shuffleQueue`](https://github.com/decred/dcrdex/blob/fc0c0d42a745e18c59df22553451fc886e63f2f5/server/matcher/match.go#L421), 

```
var seedHash [32]byte
inHash := hashCat
randRange := func(i int) int {
    seedHash = HashFunc(inHash)
    inHash = seedHash[:]
    seed := int64(binary.LittleEndian.Uint64(seedHash[:8]))
    return int(seed % int64(i))
}
for i := range queue {
    j := randRange(qLen-i) + i
    queue[i], queue[j] = queue[j], queue[i]
}
```

**Comment by chappjc** [comment]
I'm not too comfortable with making a series using a hash like Blake256, but maybe.

I think we should specify the uniform random number generator instead.  However, I think mt19937 is more common than Mitchel and Reeds.

Another thing to note is that changing math/rand for Go 2 is under discussion: https://github.com/golang/go/issues/21835

**Comment by jrick** [comment]
https://godoc.org/decred.org/cspp/chacha20prng

**Comment by buck54321** [comment]
mt19937 seems to be the way to go. It's standard library in most languages. ChaCha20 also seems to have wide availability from third-party sources. @jrick was there something particularly compelling about ChaCha20 that we should consider?

**Comment by jrick** [comment]
It's cryptographically secure (if you need it) and well defined.

**Comment by buck54321** [comment]
We're using Blake256 to generate the seed, so I think MT19937 is sufficient. Language support is the priority, IMO, and MT19937 has the widest standard library support.

**Comment by buck54321** [comment]
Recommend picking up this issue in the work for order commitments, since both will affect order ID and shuffle order.

**Comment by chappjc** [comment]
Assigning myself for the implementation part.  I'll make a mt19936 package that satisfies [`math.Source` and `math.Source64`](**url**).

**Comment by chappjc** [comment]
The code was updated in https://github.com/decred/dcrdex/commit/3955943ae9f54b00c8d5fca5527ca3b5b2813e45, but the spec still needs an update.
