### ISSUE TITLE
zero qty orders in chart and orders

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#835]
Leaving the markets page open for a long while, returning to this:

![image](https://user-images.githubusercontent.com/9373513/98888603-e788e900-245d-11eb-9dc0-b57bf07aab5d.png)

F5:

![image](https://user-images.githubusercontent.com/9373513/98888612-ebb50680-245d-11eb-8e97-04b4894e3977.png)

Both the depth chart and the orders lists have indicate something strange with the order feed.

**v0.1.1 release**

_Originally posted by @chappjc in https://github.com/decred/dcrdex/issues/824#issuecomment-725791277_

**Comment by chappjc** [comment]
The symptom seems to be zero qty sell orders building up in the list

![image](https://user-images.githubusercontent.com/9373513/99543435-c9008180-2978-11eb-8216-313fd3918b42.png)

and the depth chart getting a zero quantity level on the buy side.

**Comment by amassarwi** [comment]
will be working on that after my current task.

**Comment by chappjc** [comment]
Got it while testing LTC-DCR

![image](https://user-images.githubusercontent.com/9373513/172652852-b822ae1d-e4f4-4dc2-92d0-346cbf298f03.png)

But only on the depth chart, not the tables.

**Comment by chappjc** [comment]
Sort of resolved by https://github.com/decred/dcrdex/pull/1543
