### ISSUE TITLE
Market page will not display in Safari on mac OS

### ISSUE THREAD

**Issue by ewbjan** [decred/dcrdex#839]
Followed the setup guide instructions all the way to paying the 1 dcr fee.  Market page shows progress indicator and never updates to show buy and sell orders.  Also wallet page options do not work in Safari (all links are greyed out).

**Comment by chappjc** [comment]
Will test on Epiphany as the closes browser I have access to, but we do have some MacOS users.  It sounds a bit like there might be a problem with the location of the "site" folder though.  Three questions:

1. how did you install?  from one of the supplied archives or manually built from the git repository?
2. when dexc starts, what does it say in the logs regarding the location of the "site" folder?
3. In Safari, can you look for error messages in the browser console?  https://appuals.com/open-browser-console/

**Comment by ewbjan** [comment]
Installed from the latest archive (downloaded, changed to executable and
then ran it from command line).

Tried both versions 0.1.0 and 0.1.1 of dexc.
after desc starts, it shows:

Looking for site in /Users/[username]/decred/site

2020-11-17 20:36:50.924 [INF] WEB: Located "site" folder at
/Users/[username]/decred/site

Safari console shows the below errors:

Refused to connect to ws://127.0.0.1:5758/ws because it does not appear in
the connect-src directive of the Content Security Policy.
Unhandled Promise Rejection: SecurityError: The operation is insecure.
followed by (screenshot of additional info)
[image: Screen Shot 2020-11-17 at 2.33.01 PM.png]

**Comment by chappjc** [comment]
Is the browser opened to "http://127.0.0.1:5758/"?  The Content Security Policy error saying that "ws://127.0.0.1:5758/ws" is not allowed by the `connect-src` directive indicates that it somehow differs from how the brower is addressing the page?

The screenshot didn't seem to make it in the comment.

**Comment by chappjc** [comment]
OK, I've reproduced in Epiphany.

![image](https://user-images.githubusercontent.com/9373513/99450412-5e066a80-28e6-11eb-834f-a6449795d0b5.png)

![image](https://user-images.githubusercontent.com/9373513/99450431-6494e200-28e6-11eb-97fe-bddad66f2574.png)

Thanks for the report.  We'll git this fixed right away.

**Comment by chappjc** [comment]
Resolved in PR https://github.com/decred/dcrdex/pull/840.

Unfortunately, I don't see a way for the user to workaround the issue with Safari setting, so this will need to land in the next patch release.
