### ISSUE TITLE
use decred's rpcclient for BTC with all requests going through RawRequest

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#841]
btcsuite's rpcclient does not support request cancellation, so we might consider using decred's rpcclient/v6 and have all requests use RawRequest.

_Originally posted by @chappjc in https://github.com/decred/dcrdex/pull/838#discussion_r526242776_

**Comment by amassarwi** [comment]
will do

**Comment by chappjc** [comment]
Only concern I'm having about the plan is we might make things harder on ourselves if/when we want to start using cfilters with bitcoind.  i.e. https://github.com/btcsuite/btcd/blob/c3ece697dab966a9b8854facead71755d226eead/rpcclient/chain.go#L1235
But it doesn't look horrible - just keep using btcsuite's wire and btcjson packages, I believe.  So not that we should stop this work, just putting that out there in case @buck54321 or @itswisdomagain have thoughts about this.

As an aside, I'm glad to see btcsuite "waking up" in the last several months, around May 2020 I guess. https://github.com/btcsuite/btcd/commits/master/rpcclient For a while I was a bit disheartened that without active maintainers it had stagnated, but I'm happy to see @jcvernaleo and friends keeping things moving.

**Comment by buck54321** [comment]
#938 resolved this for the client, but the server still needs to be done. @amassarwi?

**Comment by amassarwi** [comment]
Oh right. will do the server part next of course.
