### ISSUE TITLE
windows javascript mime type error

### ISSUE THREAD

**Issue by sumiflow** [decred/dcrdex#843]
After running dexc.exe and browsing to the login page, I see an error in the browser console that says:
"Refused to execute script from 'http://127.0.0.1:5758/js/entry.js?v=nntTxf' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled."
The javascript file is not missing.  It does exist at the URL but this error does not allow you to log in since the 'submit' button does not work.
This was using v1.6.0-rc3 on a fresh install of Windows 10 and Chrome browser.  I can work around this issue by modifying the Windows registry HKLM\SOFTWARE\Classes\.js Conent Type value from text/plain to application/javascript, restarting dexc, and  clearing browser cache but of course this is not ideal.

**Comment by chappjc** [comment]
We did address this with 0.1.1 (https://github.com/decred/dcrdex/pull/770), so I'm wondering if your running from the old subfolder dcrinstall created with 0.1.0.  dcrinstall makes these subfolders that are like backups, but the stuff to run is in the root of the "decred" folder.  Can you verify the dexc version with `dexc.exe -V` or looking for a version log entry?

**Comment by chappjc** [comment]
Yeah, I verified the "nntTxf" part of the url you showed was from the initial release. 

v0.1.0

https://github.com/decred/dcrdex/blob/122dcb3f90fd1a944d460c215e741244db4ff5f1/client/webserver/site/src/html/bodybuilder.tmpl#L88

v0.1.2

https://github.com/decred/dcrdex/blob/c3d9e80602e9cad8cc7ebc80e2d7e96a2257d3ab/client/webserver/site/src/html/bodybuilder.tmpl#L88

We should consider ways to improve dcrinstall w.r.t. these "backup" folders"

**Comment by sumiflow** [comment]
I just ran dexc.exe -V
dexc version 0.1.2+release (Go version go1.15.5 windows/amd64)

**Comment by sumiflow** [comment]
Ah yes you nailed it.  I didn't realize I had two version of dexc.exe installed.  I was running the one from the wrong directory.  The new one seems fine.
