### ISSUE TITLE
client: unintentional dexauth cookie invalidation

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#845]
Because cookies are not port specific, if you have two instances of dexc running (e.g. mainnet and simnet) and open browser and login to both, one of those will lose the valid cookie because the dex auth cookie applies to any page at the given domain **regardless of port**.  To prevent this, we might consider putting another identifier in the cookie name, such as "dexauth_{portnumber}" or "dexauth_simnet" but that complicates the auth middleware.  Perhaps a better option is to bind to different loopback Ip addresses as suggested in https://github.com/decred/dcrdex/issues/845#issuecomment-730571250.

A related issue seems to be that calling (*Core).Login twice as would be done if having to login again can break the internal wallet lock state.

**Comment by chappjc** [comment]
Another mitigation to the issue of cookie clashes and invalidation is to have the default host for different networks to vary.

For example:
- mainnet: 127.0.0.1
- testnet: 127.0.0.2
- simnet: 127.0.0.3

This would prevent the authdex cookie from being used for multiple dexc backends listening on different ports.

**Comment by amassarwi** [comment]
On it
