### ISSUE TITLE
[sec] Default to encrypted wire communication

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrdex#854]
While playing around with the dex I enabled it to listen on an external reachable IP address via `--webaddr`. I then connect a remote browser to the dex. To my dismay, I noticed that the communication was NOT encrypted. We cannot rely on users to notice the stupid padlock icon on their browser and we cannot default to non-encrypted wire communication.

Since there are legit use cases for `--webaddr` I'd like to suggest that a flag is added to disable encryption. We can add `--notls=1` to explicitly disable encryption.

Defaulting to unencrypted communication over a wire is in my opinion insanity. If we are to provide a footgun then at least we must add a safety.

Alternatively, I'd prefer to remove `--webaddr` over having it default to unencrypted. We could document `ssh -L` to explain how to tunnel the application safely.

**Comment by marcopeereboom** [comment]
Firefox:
![image](https://user-images.githubusercontent.com/4366787/100160539-62e29580-2e75-11eb-9534-c08d1cc020bd.png)

Chrome:
![image](https://user-images.githubusercontent.com/4366787/100160576-7988ec80-2e75-11eb-9a9f-c8e4fc044b54.png)

It is not really obvious from the icons on the major browsers if a connection is secure.

**Comment by chappjc** [comment]
The `webaddr` option cannot be removed because it needs to be used to change port, and can be used to switch to alternative loopback addrsses too (127.0.0.3).

However, I'm in favor of making it harder to do something stupid with `webaddr`.

First we need to even support http.  https://github.com/decred/dcrdex/issues/853.  This is not available presently because the default is localhost and our stance is that anyone who changes the listen address can setup their network how they like it.

**Comment by chappjc** [comment]
> Firefox:
> ![image](https://user-images.githubusercontent.com/4366787/100160539-62e29580-2e75-11eb-9534-c08d1cc020bd.png)
> 
> Chrome:
> ![image](https://user-images.githubusercontent.com/4366787/100160576-7988ec80-2e75-11eb-9a9f-c8e4fc044b54.png)
> 
> It is not really obvious from the icons on the major browsers if a connection is secure.

Those are both screenshots of when it **is secure** listening on a loopback.  Here's a non-loopback address without https:

Firefox

![image](https://user-images.githubusercontent.com/9373513/100160694-b05f0280-2e75-11eb-9808-ab51be4ef2dc.png)

Chrome

![image](https://user-images.githubusercontent.com/9373513/100160712-b94fd400-2e75-11eb-8e96-ed5e6ec24b64.png)

Safari/Epiphany/webkit

![image](https://user-images.githubusercontent.com/9373513/100160760-cec4fe00-2e75-11eb-9ff7-927c47344a35.png)

**Comment by marcopeereboom** [comment]
> > Firefox:
> > ![image](https://user-images.githubusercontent.com/4366787/100160539-62e29580-2e75-11eb-9534-c08d1cc020bd.png)
> > Chrome:
> > ![image](https://user-images.githubusercontent.com/4366787/100160576-7988ec80-2e75-11eb-9a9f-c8e4fc044b54.png)
> > It is not really obvious from the icons on the major browsers if a connection is secure.
> 
> Those are both screenshots of when it **is secure** listening on a loopback. Here's a non-loopback address without https:
> 
> Firefox
> 
> ![image](https://user-images.githubusercontent.com/9373513/100160694-b05f0280-2e75-11eb-9808-ab51be4ef2dc.png)
> 
> Chrome
> 
> ![image](https://user-images.githubusercontent.com/9373513/100160712-b94fd400-2e75-11eb-8e96-ed5e6ec24b64.png)
> 
> Safari/Epiphany/webkit
> 
> ![image](https://user-images.githubusercontent.com/9373513/100160760-cec4fe00-2e75-11eb-9ff7-927c47344a35.png)

I didn't even notice the difference until you pointed it out. We can't rely on users to peruse dumb icons.

**Comment by chappjc** [comment]
I think this is a question of how many seat belts we need to give to a user.  By default it is a secure config.

A self-signed certificate and https by default is just out of the question given how browsers work in that case.

The only reasonable solution we can take is to force HTTPS if the user specifies a non-default `webaddr`

**Comment by marcopeereboom** [comment]
> I think this is a question of how many seat belts we need to give to a user. By default it is a secure config.

`localhost` is fine to use by default and unencrypted.

> A self-signed certificate and https by default is just out of the question given how browsers work in that case.

Agree, provided it is localhost only.

> The only reasonable solution we can take is to force HTTPS if the user specifies a non-default `webaddr`

I support this. I also support adding `--notls=1` for people who wish to tunnel or do other advanced settings.

Forcing HTTPS is a sane default for financial software.

**Comment by chappjc** [comment]
Thing is, there's more than one way to have encryption on the wire.  I don't know if there's an ssh tunnel or openvpn or another encrypted transport layer, and that's really the user's decision.  So while I think dexc should switch on HTTPS for non-loopback, it should be _allowed_ with a switch like `notls` as you said.

**Comment by peterzen** [comment]
> Thing is, there's more than one way to have encryption on the wire. I don't know if there's an ssh tunnel or openvpn or another encrypted transport layer, and that's really the user's decision. I also don't know if the user has an isolated LAN. So while I think dexc should switch on HTTPS for non-loopback, it should be _allowed_ with a switch like `notls` as you said.
> 
This is not a public facing service - it should listen on `127.0.0.1` with no TLS by default but please do not add the user facing complexity of having to create and set up a TLS certificate to run it on my own trusted network.

**Comment by chappjc** [comment]
Tracking in https://github.com/decred/dcrdex/issues/853
