### ISSUE TITLE
client: fee rate limit setting

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#858]
The maxFeeRate config item from the server describes the maximum possible fee rate that could be required at match time for swap txns, however the client software should have a user-configurable limit on what max fee rates are acceptable here.

**Comment by amassarwi** [comment]
Looking into it

**Comment by chappjc** [comment]
Assigning @amassarwi .  Example of adding a wallet config option: https://github.com/decred/dcrdex/commit/27ae3168023dad32c30fd13e61832ef23fc298a9

**Comment by buck54321** [comment]
After some matrix chat, I wanted to doc my opinion on this issue. I don't personally think there should be a wallet setting for a fee rate limit. We just need to better inform the client at order time what their risk is, and it sounds like we need to record the max fee rate at order time as part of match validation, to ensure the match rate is not greater than expected. 

I think this is best handled by displaying on the order confirmation dialog 1) the maximum fees that might be assessed, and later 2) the estimated fees based on current network conditions (`estimatesmartfee`).

**Comment by chappjc** [comment]
I'll reiterate my point of view that the stance of better informing the client at order time is not really applicable to dexcctl or Go consumers, and even if they do check the config response for the current maxFeeRate right before submitting **every** order, which is poor UX, it's not guaranteed that when you submit the order that that will be the same maxFeeRate.  Even the maxFeeRate shown in the GUI dialog starts to become out-of-date as soon as it is shown.  The only ways to prevent submitting an order for an intolerable fee rate are (1) specify the acceptable max with the order submission form, or (2) have a setting that is checked just before order submission.  I think (2) is very simple, and it has been explicitly requested.  The default can be such that there is no limit unless it is specified.

The issue of recording the max fee rate at order time for use at match time is a separate but legit issue that needs to be addresses separate from this possible setting.

**Comment by buck54321** [comment]
So we really dug into this on matrix yesterday, but failed to come to a conclusion. I don't want to dwell any longer, so let's just move forward with #874. 

@amassarwi If you're gonna set a default value, take a look at the values used for `sendrawtransaction` (that'll lead to `maxRelayFeeMultiplier`). For Decred, it's something like 1e5 sats/byte. The issue with a default is that either 1) it'll be low enough that the server will eventually go over it, denying orders for every use who never changed any settings (people love that), or 2) the default has to be high enough that the the dex operator would never hit it, in which case, what's the point. So using network constants is a good approach here, I think.

**Comment by amassarwi** [comment]
Sounds good to me, let me try summarize what we have discussed:

- Asset specific user wallet settings
- Need to check on order placement and for that will need to add feeRateLimit field to `xcWallet` type
- Recheck on match time and cancel if maxFeeRate increased ? need to store the agreed value locally for that ?

What about user changing value after placing an order ? should we cleanup orders then ?

**Comment by amassarwi** [comment]
cc: ^ @buck54321 @chappjc

**Comment by chappjc** [comment]
> What about user changing value after placing an order ? should we cleanup orders then ?

Not an issue if the maxFeeRate known at order *placement* time is stored with order meta data as that will be checked at match time (user's limit need not checked at match time, only at time of order placement).

**Comment by chappjc** [comment]
@buck54321's comment:

> the default has to be high enough that the the dex operator would never hit it, in which case, what's the point. So using network constants is a good approach here, I think

I think the point is that it could be opt-in.  But the default value from the sendrawtransaction "high fee" definition is appropriate as we really should have it avoid committing to fees that would exceed what they are even *able* to use.

Unrelated, a suggestion for the setting and its tooltip:
- "Highest acceptable fee rate"
- (i) "This is the highest network fee rate you are willing to pay on swap transactions.  If you set this too low, you may not be able to place orders with servers that allow for higher swap rates as network conditions demand"

**Comment by amassarwi** [comment]
@chappjc 

> Too late to cancel at match time. At match time client just needs to check that the prescribed fee rate is <= the recorded maxFeeRate at placement time. Doing this involves a new core order field and updated boltdb encodings... and upgrade handling (sorry this is getting more advanced)

hehe no worries, the best way to master a codebase is be diving into it. I'll try break it down and do one step at a time.

So I will need to add  the feeRateLimit to https://github.com/decred/dcrdex/blob/5099d69f8a7dbf7d372385a1d534a9656ea04211/client/asset/interface.go#L266 & https://github.com/decred/dcrdex/blob/master/client/core/types.go#L264 to use store and then check it against prescribed fee rate.

**Comment by amassarwi** [comment]
@chappjc  This was resolved with #874 & #898 - issue can be closed.
