### ISSUE TITLE
client: allow paying higher swap fee rate than server specified rate

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#859]
The client could pay a higher fee rate on the swap txns if they like, as long as they don't consume so much in fees that they cannot fund the order.

**Comment by amassarwi** [comment]
can do

**Comment by martonp** [comment]
@amassarwi, are you still working on this? I would like to do it if you're not.

**Comment by amassarwi** [comment]
haven't started, feel free to pick it up.
