### ISSUE TITLE
client: ability and UI for bumping chained swaps with CPFP

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#862]
The author of a swap should be able to attempt to accelerate mining of a chain of swaps they authored by spending the change output (if there is one) in a txn with a high enough fee rate to incentivize the parent (swap) txns to be mined too.

This can be done by spending the change, sending to a new output that client then replaces as the funding coin if there is an active partially filled order requiring the coins.  The new output will need to be large enough to cover remaining swaps at maxFeeRate.

There should also be a UI control in the order's details page for any match with: (1) an unmined swap txn and (2) unspent change.

**Comment by martonp** [comment]
I'm interested in working on this one. The way I understand it is the only way a user will be able to accelerate a tx is if it has unspent change and there are currently orders waiting to be matched. Maybe we could also allow just sending the change to another address controlled by the user in the case where there are no more partially filled orders.

**Comment by chappjc** [comment]
Thanks @martonp.
It's even better if the change is not locked for the rest of the order, as long as it's not locked for a new order that is.

**Comment by martonp** [comment]
> It's even better if the change is not locked for the rest of the order, as long as it's not locked for a new order that is.

I'm not sure what you mean.

**Comment by chappjc** [comment]
> Maybe we could also allow just sending the change to another address controlled by the user in the case where there are no more partially filled orders.

Was referring to this.  If you mean change from the last swap of an unbooked order (completely filled, cancelled, or immediate force and partially filled) where the order is no longer holding the change locked, but we want to accelerate any active matches from that order, we can definitely try to bump that change.
 
Did I misinterpret "no more partially filled orders"?

The other case is where the change is still locked by the partially filled and still booked order.

**Comment by martonp** [comment]
Ah yes that's right, that's what I meant. Everything is clear.

**Comment by JoeGruffins** [comment]
Closed by #1555 or are there more coins we can do this with?

**Comment by chappjc** [comment]
If we wanna have "speed up" (and replacement txns) with ETH, that should be a separate issue.
Ultimately we should, even if just to tolerate users manually doing a speed up in an unmanaged wallet like they shouldn't.
