### ISSUE TITLE
Version bump leads to broken dcrinstall download from website

### ISSUE THREAD

**Issue by karamble** [decred/dcrdex#866]
dex.decred.org links their downloads to dcrinstall -dcrdex

After a version bump the download links need to be bumped, otherwise users aren't able to install dcrdex due to following error message:

![Auswahl_001](https://user-images.githubusercontent.com/25404928/100933046-a9bf3380-34e4-11eb-887c-8c79c2a7c182.png)

**Comment by chappjc** [comment]
@dajohi Would you please transfer this issue to https://github.com/decred/dexweb?  @jholdstock  FYI

**Comment by jholdstock** [comment]
PR is done, just await a redeployment from dhill
