### ISSUE TITLE
Mention where to get binaries in release notes

### ISSUE THREAD

**Issue by xaur** [decred/dcrdex#873]
I expect that some people reading [release notes](https://github.com/decred/dcrdex/releases/tag/v0.1.3) will be confused about where to get release notes. Adding a link to proper [decred-binaries](https://github.com/decred/decred-binaries/releases/tag/v1.6.0-rc4) release would help.

**Comment by ukane-philemon** [comment]
@chappjc, resolved by #1050, right?

**Comment by chappjc** [comment]
Yeah, although I have a backlog clearly. :)
