### ISSUE TITLE
BTC deposit address not in dex wallet

### ISSUE THREAD

**Issue by peterzen** [decred/dcrdex#879]
I sent a BTC deposit to the address shown in the GUI, but it didn't end up in the configured `dex` wallet.

```
# grep Deposit mainnet/logs/dexc.log
./mainnet/logs/dexc.log:2020-12-09 16:02:06.376 [INF] CORE: Loaded btc wallet configuration. Deposit address = bc1deadbeef....
```

Verifying whether the deposit address from `dexc` belongs to the `dex` wallet:
```
# bitcoin-cli -conf=/home/bitcoin/.bitcoin/bitcoin.conf getaddressinfo bc1deadbeef....
{
  "address": "bc1deadbeef....",
  "ismine": false,
  "solvable": false,
  "iswatchonly": false,
  "isscript": false,
  "iswitness": true,
  "ischange": false,
}
```

Confirming that it's the `dex` wallet that's open:

```
# bitcoin-cli -conf=/home/bitcoin/.bitcoin/bitcoin.conf getwalletinfo
{
  "walletname": "dex",
  "walletversion": 169900,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 12,
  "keypoololdest": 1606075542,
  "keypoolsize": 10000,
  "hdseedid": "xxxxxxx",
  "keypoolsize_hd_internal": 10000,
  "unlocked_until": 0,
  "paytxfee": 0.00000000,
  "private_keys_enabled": true,
  "avoid_reuse": false,
  "scanning": false
}
```

Any clues what might be the issue here?  The wallet was working correctly, a BTC withdrawal worked correctly yesterday. `bitcoind` is caught up to the tip as evidenced in `dexc.log`.

**Comment by chappjc** [comment]
Are there other walletnames in `listwallets` and `listwalletdir`, and are you certain that the `"dex"` walletname is configured in the dexc GUI?

**Comment by peterzen** [comment]
I verified the above and reconstructed the timeline:

1. New bitcoind instance & default wallet created, initial sync completed. 
`wallet=dex` not present in `bitcoin.conf` at this point.
2. Added BTC wallet in `dcrdex`, configured rpc, verified the wallet connection
3. `bitcoin-cli createwallet dex`, `bitcoin-cli -rpcwallet=dex encryptwallet`
4. Changed BTC wallet in `dcrdex` to `dex` wallet, added `wallet=dex` to `bitcoin.conf`
5. Shredded `wallet.dat` so that `bitcoind` throws an error in case the default wallet would get opened instead of `dex` due to conf error <-- (this was a BTC 0.1 mistake)
6. Over a period of several weeks, executed several trades, did BTC withdrawals, but no BTC deposit
7. `dexc` kept the deposit address obtained in (2) across restarts and BTC wallet reconfigurations, causing a BTC deposit to go to the black hole of the original default wallet
8. Subsequently generated new deposit address do verifiably belong to the `dex` wallet, as expected.

So as I understand, the caching of the deposit address is slightly too aggressive.  While the above steps don't strictly follow the documentation (as in, I first connected to the default wallet and then changed it), `dexc` should invalidate the deposit address upon configuration changes.

Also, I would recommend adding a `getaddressinfo <last known BTC deposit address>` call upon startup and obtaining a new address in case `ismine == false`

**Comment by chappjc** [comment]
Ok, so in chat I think we discovered what happened, and apparently it was always using `dex` wallet name (always hitting the `btc-wallet:8332/wallet/dex` endpoint), but the bitcoin wallet recreated (deleted and made new encrypted), but since dexc saw everything as the same (wallet name and RPC auth details, it didn't know to validate the deposit address.

Some actions we can take:
- on dexc startup, validate teh current address (e.g. getaddress info > ismine must be true)
- When the GUI brings up the deposit address, always validate it first (with same mehanism as above).
- Although it was not a problem in this instance, document and warn bitcoin core users about encrypting a wallet (it makes a new HD seed and all the old keys are inaccessible except by dumpwallet! can you believe it?)

**Comment by amassarwi** [comment]
Would like to implement the suggested solution.

**Comment by chappjc** [comment]
I think the most needed change is the ismine check and subsequent generation of a new deposit address when false.  If there are other obvious and simple improvements to either GUI or documentation, that's fair game but less important.
