### ISSUE TITLE
client/asset/dcr: contracts try to refund too soon

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#897]
The contract expiry logic indicates a contract is refundable too soon, resulting in ~50 minutes of refund attempts with "not finalized" transaction errors until eventually network consensus permits the refund.

**Comment by JoeGruffins** [comment]
If this is still a problem, I will work on it.

**Comment by chappjc** [comment]
Hasn't been reported, but I'm sure it is still an issue.  Thanks.

**Comment by JoeGruffins** [comment]
Any more info on this? Is it only a problem with bitcoin? It certainly looks like `wallet.LocktimeExpired` is doing the same check with the same data as btcd. Perhaps core is slightly different?

**Comment by chappjc** [comment]
It actually only seems to be a problem with *Decred*, or at least only observed that way.

If the trail goes cold, one thing to consider is that the locktimes for both contracts reference the same reference time.  That is maker/initiator contract is 20 hrs expiry from match/creation, but taker/participant's contract is 8 hrs from that same time instead of 8 hrs from creation.  I'm not sure if this is a factor in the refund attempt timing, but it's also something I'm open to revising in general as it means the taker/participant contract never actually has 8 hrs to get mined.

**Comment by JoeGruffins** [comment]
Ah, even the title says dcr.

**Comment by JoeGruffins** [comment]
So, maybe if we checked vs the on-chain blocktime like btc, problem solved?

**Comment by JoeGruffins** [comment]
It seems dcrd is using the same median time as btc internally, but I don't think that is exposed in an rpc. We could get it added to getblock probably, and calculate it ourselves in the meantime.

So... I suppose this means that all locktimes for btc and dcr are off by about an hour(ish), as the median time is always behind real time?

**Comment by JoeGruffins** [comment]
> but it's also something I'm open to revising in general as it means the taker/participant contract never actually has 8 hrs to get mined, often much much less.

Can be a separate issue?

**Comment by chappjc** [comment]
> > but it's also something I'm open to revising in general as it means the taker/participant contract never actually has 8 hrs to get mined, often much much less.
> 
> Can be a separate issue?

Yah, separate issue.  Clearly unrelated, but still something up for discussion.
