### ISSUE TITLE
Swap Executor

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#9]
A swap executor is needed to coordinate the atomic swaps as described in [Atomic Settlement](https://github.com/decred/dcrdex#atomic-settlement) between one or more clients whose orders have been matched by the [Order Matcher](https://github.com/decred/dcrdex/issues/5).

The swap executor will interface with:
1. The asset backends, for txn monitoring (receive broadcast ntfns and track confirmations) and validation (sufficient UTXO value, correct contract amount, etc.).
2. The communications hub, to: (a) inform clients of the match, (b) receive swap transaction details from the clients, (c) send swap transactions to the clients.  **Alternatively, the market manager can handle comms for these events, which would be notified to the market, who owns the swapper.**
3. <s>The order matcher, from which it will receive the matched order, including amounts and account public keys.</s> The market manager will relay the matches to the swap executor.
4. The market manager, which controls the swap executor by instantiating executors and receiving swap outcomes from the executor.

**Comment by buck54321** [comment]
I'll start on this one.

**Comment by chappjc** [comment]
Some thoughts from Matrix chat:

>I've been thinking we should design the swap coordinator so that it can be used in a very simple test CLI app to veryify all the swap bits work.
Ideally the swap coordinator could be tested without the market manager.
It would just be great if the swap coordinator could be used without too much effort outside of the dex server and even outside of a market manager.
> It would probably be similar ot a minimal test harness, but maybe with more concrete types of course since it would need to be processing real orders.
But without all the `testing` junk.  I'm thinking a basic cli for absolutely minimal coordination (lots of manual steps with the wallet, etc.) of mainnet/simnet/testnet swaps
> Part of the thinking is to ensure that we make the swap coord. into a package that can be reused in other applications with reasonable ease
Say perhaps we even decide that the swaps can be handed off from the dex server to a separate microservice.  Or someone wanted to build a pretty CLI for doing swaps between their buddies without using a DEX.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/39
