### ISSUE TITLE
audit use of refreshUser, and devise methods to set/update piecemeal

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#904]
In `client/core.Core` there a numerous calls to `refreshUser`, and most of these calls are required only to update one small piece of the information that `refreshUser` updates.  e.g.  If `WalletState` for a certain `xcWallet` changes, there's no reason to update all of the other assets, orders, exchanges, etc.  This is particularly problematic because there are many mutexes locked by `refreshUser` and it's callers, which can easily lead to deadlock and/or contorted patterns to avoid deadlock.

In cases where `refreshUser` really is the best option, not a more targeted mutator method, each `refreshUser` call site should be documented with the reasoning.  If `refreshUser` is used for convenience regardless, the call site should document why exactly it is being called (what just changed that requires updating?).

**Comment by buck54321** [comment]
See also #379

**Comment by chappjc** [comment]
Ah yeah, this will be pretty much a dup then.  Let me just drop a comment to bump the issue.
