### ISSUE TITLE
backends: Add Ethereum.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#939]
### Ethereum support is coming to the dex.

This issue is intended to get the ball rolling and should be closed by adding eth backends for the server and client. This issue does not include atomic swaps, only basic communication abilities in an attempt to keep pr's smaller.

### Client

I propose using [geth](https://github.com/ethereum/go-ethereum) because it has active development and is written in golang.

### Networks

A simnet setup script will have a separate issue.

There are four [testnets](https://ethereum.org/en/developers/docs/networks/).  After looking into them, I propose using [Gorli](https://goerli.net/) for three reasons. 
 1. It is supported by geth with just the `--goerli` flag so setup is easy.
 2. It seems to be stable. 
 3. The faucet, while requiring captcha, works.

**Comment by chappjc** [comment]
@JoeGruffins Thanks for feeling this out.  I was also settled on geth, but I hadn't gotten to the bottom of the four different testnets.  However, I had already made a note of Ropsten being the best target given its description as "A proof-of-work testnet. This means it's the best like-for-like representation of Ethereum." vs the other PoA networks.  I'm actually kinda surprised you can choose the consensus algorithm on testnet and development networks, so perhaps this is considered a minor detail in ethereum?

**Comment by JoeGruffins** [comment]
I read a bit of this https://gitter.im/ethereum/ropsten and decided it looks like a headache. You need to beg for eth because faucets don't work:
```
 bold
@AboldUSER
Jan 15 08:28
Is there something going on with the Ropsten network today? I have tried to queue or receive ETH from 4 different faucets but non seem to be working today for me
```
and apparently the chain gets actively attacked at times or simply has no miners and stops moving: 
```
0xlegos
@0xlegos
Oct 30 2020 21:30
Since yesterday, the ropsten network has been paralyzed. Has anyone attacked the test network? Can they get any benefits?
```

**Comment by JoeGruffins** [comment]
geth has these flags, so robstein is still easy to setup:
```
  --goerli                            Görli network: pre-configured proof-of-authority test network
  --rinkeby                           Rinkeby network: pre-configured proof-of-authority test network
  --yolov2                            YOLOv2 network: pre-configured proof-of-authority shortlived test network.
  --ropsten                           Ropsten network: pre-configured proof-of-work test network
```
I will start it up and see what it's like.

**Comment by chappjc** [comment]
It was way easier for geth to connect to peers on goerli than ropsten (`--testnet`), so yeah, perhaps that's just where it's at for eth testneters.  I suppose dex doesn't need to worry about the testnet concensus algo as long as it makes new blocks and nothing else of significance changes like transaction or contract structure, and it doesn't seem to.

I got all sync'd up in a couple minutes with `./geth --nousb --http --ws --goerli --syncmode "light"` and was playing around in a separate console with `./geth --goerli attach`.

**Comment by JoeGruffins** [comment]
Starting on this.
