### ISSUE TITLE
testing: Ethereum simnet harness.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#940]
Add an harness that sets up an eth [development network](https://ethereum.org/en/developers/docs/development-networks/). If possible I would like to avoid large dependencies, but am not sure what is needed yet. I will update this issue. I think this should happen first as far as eth support so we can test.

Edit: It looks like everything we need is contained in the go-ethereum repo, so there shouldn't be any other dependencies.

**Comment by JoeGruffins** [comment]
Working on this.

**Comment by JoeGruffins** [comment]
Srry slow. Will get this done tomorrow.

**Comment by chappjc** [comment]
Don't even worry.  I'm still just doing research and experimentation with the eth ecosystem and existing code.
