### ISSUE TITLE
ui: down DEX server leads to register dialog sequence

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#943]
If you have dexc configured with a registered DEX account at some server, that is the only configured DEX account, and then startup cannot connect for any reason, the UI enters into the add-a-dex path.

![image](https://user-images.githubusercontent.com/9373513/105740778-22e47100-5eff-11eb-845f-2bff59fa523f.png)

![image](https://user-images.githubusercontent.com/9373513/105740957-5cb57780-5eff-11eb-85bd-9a0775ce0d10.png)

But really it's because the already-configured dex couldn't connect. e.g.:

```
[ERR] CORE: error connecting to DEX 127.0.0.1:17273: dial tcp 127.0.0.1:17273: connect: connection refused
[INF] CORE: Successfully connected to 0 out of 1 DEX servers
```

Preferably the UI should say there was a connection failure and not prompt you to re-register (which wouldn't work even if you wanted to pay again because the DEX is actually unreachable in this situation).

**Comment by vctt94** [comment]
Looking into it
