### ISSUE TITLE
harnesses: force bash with shebang or make posix compatible

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#951]
The decision is between:

 1. Make all the scripts specify bash in their shebang (`#!/usr/bin/env bash`) and freely use bashisms.
 2. Stick with `#!/bin/sh` and ensure the scripts are always POSIX-compatible.

Door number 1 makes people use bash of course, but we don't have to consider other shells in making changes.
Door number 2 restricts us a bit more and perhaps creates a testing burden.  Do we test every harness change on multiple shells or with a POSIX only mode (`bash --posix`)?

Vote or comment.

**Comment by chappjc** [comment]
Bash.

**Comment by chappjc** [comment]
POSIX.

**Comment by amassarwi** [comment]
As I'm having hard time maintaining the bash changes in my git stash in order to run harness scripts I would like to 
fix this in a coming PR.
