### ISSUE TITLE
ui: Market buy/sell button has no text.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#963]
A market order's buy/sell button shows nothing after opening the webpage. You must first make a limit but or sell for it to be viewable.
Steps to reproduce:
1. Start client.
2. Open webpage.
3. Make a market buy or sell.

![nolabel](https://user-images.githubusercontent.com/34998433/106716744-23d57b00-6642-11eb-9d49-a7904d1ac7fd.png)
`Build ID: 945cb4a`

**Comment by amassarwi** [comment]
on it
