### ISSUE TITLE
ui: Market trade does not change labels from sell <-> buy.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#964]
When on the `Market Order` tab, changing to buy or sell has no effect on the sell/buy confirmation's header and button. To change, you must go to the limit order tab and click that button.
Steps to reproduce:
1. Start client.
2. Go to `Market Order` tab.
3. Attempt to buy or sell with the tab you did not start on.
![notselling](https://user-images.githubusercontent.com/34998433/106717432-12d93980-6643-11eb-8da3-abb0b658ebf6.png)
`Build ID: 945cb4a`

**Comment by amassarwi** [comment]
on it
