### ISSUE TITLE
ensure new wallet can process existing orders when connecting

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#968]
When doing ReconfigureWallet, we should verify that the new wallet can settle any existing swaps, and since we don't support changing funding coins yet, any active orders.

> Should really check if this is the same wallet and user has active trades. If both are yes error, can't use a different wallet with active trades.
> 
> We have the old wallet's deposit address, so maybe a simple `isMine` method on wallets would be good enough?
> 
> Also, after checking we will know if we should disconnect here or not.

_Originally posted by @JoeGruffins in https://github.com/decred/dcrdex/pull/928#discussion_r571744313_

**Comment by JoeGruffins** [comment]
Probably obvious, but should have read *not* the same wallet and has active trades.

**Comment by JoeGruffins** [comment]
I will do this.
