### ISSUE TITLE
server/asset: blockCache grows forever.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#976]
All current assets have a `blockCache` which is an in-memory map that grows forever.

https://github.com/decred/dcrdex/blob/master/server/asset/btc/cache.go

At some point this will cause an out of memory error. At the very least the map should be pruned periodically. However, I believe the better answer is to store the `blockCache` on disk in the database.

**Comment by JoeGruffins** [comment]
Actually, not sure which is better, map or db. I guess it depends on how much cache we actually need and how often it is accessed.

**Comment by chappjc** [comment]
I don't think there's a need for a DB for this if the fallback is just and RPC to the node.

**Comment by buck54321** [comment]
All things considered, each `cachedBlock` accounts for about 85 bytes. You could load the entire Bitcoin and Decred blockchains in ~ 100 MB, and the clients will of course only have a small portion of that. Pruning would be good, but it's not a big problem as it is.

**Comment by JoeGruffins** [comment]
Does not seem to be a problem. Closing.
