### ISSUE TITLE
client/webserver: apiShutdown and /api/shutdown

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#993]
Shutdown of dexc will currently involves ctlr+c/sigint and potentially a console-based prompt if there are active orders, however for Decrediton or another process to govern dexc (without exposing the console for this purpose), it is necessary to have a way to command the shutdown and to override the active orders check.  I propose an `/api/shutdown` endpoint and an `apiShutdown` function.

Response:

```{
    "ok": bool,
    "msg": string (optional)
}
```

With a basic/empty request payload, the handler would check for active orders, and then begin Core shutdown via context cancellation.  In this case, the response might be `{"ok": true}`.

If there were active orders, the response might be `{"ok": false, "msg": "6 active orders"}`

Then the user could deal with those orders, or force a shutdown:

Request:

```json
{
    "force": bool (optional)
}
```

**Comment by amassarwi** [comment]
I can add that
