### ISSUE TITLE
UI: schedulePreOrder maxLoaded is not a function

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#998]
![image](https://user-images.githubusercontent.com/9373513/109736725-69765c80-7b8a-11eb-8613-f4287601130f.png)

Hit randomly.  Usually don't see this, as evidenced by the successful /api/maxbuy calls prior to this error.

It seems easy to hit it by clicking around on the depth chart.

It's also quite surprising that the maxbuy endpoint takes `1300ms`.

**Comment by chappjc** [comment]
Another thing that is strange and probably not good is that it hits the maxbuy endpoint immediately after (concurrently?) with the trade endpoint.

2021/03/02 19:10:10 "POST http://127.0.0.3:5758/api/trade HTTP/1.1" from 127.0.0.1:58090 - 200 792B in 121.904094ms
2021/03/02 19:10:12 "POST http://127.0.0.3:5758/api/maxbuy HTTP/1.1" from 127.0.0.1:58344 - 200 239B in 1.25403875s

**Comment by chappjc** [comment]
Bump for whoever.

**Comment by buck54321** [comment]
> Another thing that is strange and probably not good is that it hits the maxbuy endpoint immediately after (concurrently?) with the trade endpoint.
> 
> 2021/03/02 19:10:10 "POST http://127.0.0.3:5758/api/trade HTTP/1.1" from 127.0.0.1:58090 - 200 792B in 121.904094ms
> 2021/03/02 19:10:12 "POST http://127.0.0.3:5758/api/maxbuy HTTP/1.1" from 127.0.0.1:58344 - 200 239B in 1.25403875s

This makes sense, because the wallet balance changes -> balance notification -> update displayed buy limit
